### ISSUE TITLE
Better grpc install

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#1]
A less hacky way to install an electron compatible grpc would be good.

If the grpc branch we are using hits master there we might be able to avoid the issue all together which would be ideal.  Will have to keep an eye on that.

**Comment by gozart1** [comment]
`npm run dev` seems to run fine.
But I'm getting this error in the electron console,
```
ELECTRON_ASAR.js:173
Uncaught Error: dlopen(/Users/gozart/code/decrediton/app/node_modules/grpc/src/node/extension_binary/grpc_node.node, 1): Symbol not found: _GENERAL_NAME_free
  Referenced from: /Users/gozart/code/decrediton/app/node_modules/grpc/src/node/extension_binary/grpc_node.node
  Expected in: flat namespace
 in /Users/gozart/code/decrediton/app/node_modules/grpc/src/node/extension_binary/grpc_node.node
```
Anyone familiar with this error?

**Comment by jcvernaleo** [comment]
@gozart1 I just rebuilt from scratch on osx (10.11) and it worked fine.  I did update the build instructions to require a newer version of node since 6.5.0 no longer works for us so you might want to start over from there.  Did you build grpc the way the README says?

**Comment by jcvernaleo** [comment]
Also, to update this issue. the grpc branch we were waiting for did hit master so the build is simplified, but until there is a new release, we do still need to manually build grpc (but that is very easy on any platform other than windows).

**Comment by alexlyp** [comment]
Closed with recent commit
