### ISSUE TITLE
1.1.2 - Stakey doesn't go away after "script not redeemable" error

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1001]
> Error: The script is not redeemable by the wallet. This probably means you are trying to use a stakepool account that is already associated with another wallet. If you have previously used a voting account, please create a new account and try again. Otherwise, please set up a new stakepool account for this wallet.

If this error is displayed after importing a stakepool API key, Stakey appears and does not go away. Decrediton must be restarted before the Purchase Tickets tab is usable again

**Comment by jholdstock** [comment]
The same thing also happens if you get the private passphrase wrong

**Comment by matheusd** [comment]
Need to dispatch `IMPORTSCRIPT_FAILED` either in `importScriptAttempt()` irrespective of the presence of `cb` or on `setStakepoolInformation()`, on the error callback passed to the importScriptAttempt function call. 

I'm just uncertain if there are further implications on dispatching that (I believe not, but maybe @alexlyp can chime in on that).

**Comment by alexlyp** [comment]
Yah going to be looking at this first thing today.
