### ISSUE TITLE
Votes history page sorts randomly

### ISSUE THREAD

**Issue by taoteh1221** [decred/decrediton#1003]
Looks like the new votes history page in v1.1.2 randomly displays voted tickets, so there is no sort by date or what have you. Not sure if this is a bug, but figured I'd note it here for you.

**Comment by matheusd** [comment]
It's a small display bug: all tickets (independent of type) are sorted by their purchase date, but the votes/revocations show the date/time of the vote/revoke tx on the ticket card.

Will fix to present the correctly sorted view.
