### ISSUE TITLE
clear memory for sensitive data.

### ISSUE THREAD

**Issue by dajohi** [decred/decrediton#101]

**Comment by matheusd** [comment]
After a quick code audit, as of https://github.com/decred/decrediton/commit/e0aecbd13103e3b03fe270533277d6913c09da95 and after the PRs for passphrase modal refactoring, current status of passphrase information in decrediton is the following.

All passphrase requests, except **Message Signing** (which should be refactored) and **Wallet Creation** (which is a sensitive operation anyway) now use a modal that store the passphrase only while it is open. So after closing (either accepting or canceling) the modal and the request is completed, the passphrase is no longer stored within the wallet.

For reference, the following grpc calls request a password (either the private/public wallet or the rpc password):

```
// control
rpc NextAccount (NextAccountRequest) returns (NextAccountResponse);
rpc ImportPrivateKey (ImportPrivateKeyRequest) returns (ImportPrivateKeyResponse);
rpc ImportScript(ImportScriptRequest) returns (ImportScriptResponse);
rpc SignTransaction (SignTransactionRequest) returns (SignTransactionResponse);
rpc PurchaseTickets(PurchaseTicketsRequest) returns (PurchaseTicketsResponse);
rpc RevokeTickets(RevokeTicketsRequest) returns (RevokeTicketsResponse);
rpc SignMessage (SignMessageRequest) returns (SignMessageResponse);

// control (not used)
rpc ChangePassphrase (ChangePassphraseRequest) returns (ChangePassphraseResponse);
rpc CreateSignature (CreateSignatureRequest) returns (CreateSignatureResponse);

// wallet loader
rpc StartConsensusRpc (StartConsensusRpcRequest) returns (StartConsensusRpcResponse);
rpc CreateWallet (CreateWalletRequest) returns (CreateWalletResponse);
rpc OpenWallet (OpenWalletRequest) returns (OpenWalletResponse);
rpc DiscoverAddresses (DiscoverAddressesRequest) returns (DiscoverAddressesResponse);

// ticket buyer
rpc StartAutoBuyer (StartAutoBuyerRequest) returns (StartAutoBuyerResponse);
```
