### ISSUE TITLE
Validate 0.7.0 release

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#102]
Basic testing of the release build needs to be done on supported OSes

- [x] OSX x64
- [x] Linux x64

Testing more than one Linux disto is a good idea so please mention distro or version you tested in comments.

- [x] Confirm wallet seeds: Create New Seed, receive funds, send funds then recreate with dcrwallet and make sure they are the same.

**Comment by jrick** [comment]
Linux 10? :)

**Comment by jcvernaleo** [comment]
Grrrr.  I copied and pasted from another issue to get the pretty checkboxes.

**Comment by jcvernaleo** [comment]
I'm mostly going to test on osx but in quick tests the linux build at least runs on Ubuntu14.04, 16.04, 16.10, Fedora23, and Debian (not sure what version I tested, but recent-ish).

**Comment by jcvernaleo** [comment]
macOS seems to work with the package (with the one thing that is documented in the README that you must use open rather than click if you want dcrd to auto launch).

**Comment by alexlyp** [comment]
Validated on debian from decrediton to dcrwallet back to decrediton on testnet.  Validating on mainnet now...

**Comment by alexlyp** [comment]
Confirmed on mainnet as well

**Comment by alexlyp** [comment]
All set.
