### ISSUE TITLE
Updated to v1.1.3 - Missing existing API keys for staking, missing stake pool from dropdown

### ISSUE THREAD

**Issue by younanjo** [decred/decrediton#1026]
Hi guys,

Just updated to v1.13 and when going into `Tickets` tab, it's as if i'm setting Decrediton staking from scratch so it's asking me for API key of stake pool. Additionally `stakepool.dcrstats.com` is missing from `Stake pool` dropdown! What's going on?

**Comment by matheusd** [comment]
Stakepool data is downloaded from here: https://api.decred.org/?c=gsd

And `stakepool.dcrstats.com` is listed, so I don't know what could cause it to temporarily disappear, but if it did disappear when you were starting up decrediton then it would cause the behaviour you're seeing (losing your existing key and going back to an unconfigured state).

Try to restart decrediton, see if it shows up on the list and reimport the stakepool api and it should be correct.

**Comment by matheusd** [comment]
For discussion with the devs: current behaviour of stakepool listing is to remove anything not returned by the remote api. Maybe we should modify it to preserve local stakepools entered, even if they are not returned?

Downside is that users may be left with an outdated list when stakepools get removed.

**Comment by younanjo** [comment]
@matheusd restarting the wallet did the trick.  `stakepool.dcrstats.com` is now in the dropdown. thanks. This can be closed.

**Comment by matheusd** [comment]
I'll leave it open for a few more days so we can discuss the above change and prevent this happening again, but glad to know it was fixed.
