### ISSUE TITLE
Add indicator of node connection to peers

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1030]
We're receiving a few support requests from people on spotty internet connections unable to perform functions (eg: purchasing a ticket or sending a transaction) or downloading block nodes. We need to add an indicator (visible both on the getstarted pages and on the main UI) for when peers are unreachable. This may or may not need work on dcrd/dcrwallet.

**Comment by matheusd** [comment]
Dcrd has `getconnectioncount`/`getpeerinfo` rpc calls that can be used to collect the number of connected nodes of that dcrd instance, but dcrwallet currently doesn't expose that to decrediton. 

Alternatives:

1. Manually call that (like we call `getblockcount' on main.development)
2. Add a `getnetworkinfo` (or something) call on dcrwallet that requests the info from the node and passes it back
3. Add rpc connection directly to the node.

Alternative 1 is easiest, doesn't require modifying dcrd/dcrwallet but doesn't allow for notifications when connection is lost and is the worst option performance-wise (needs to start a dcrctl process each time we wanna check).

Alternative 2 implies work on dcrwallet but potentially allows notification and is possibly future-proof when we get SPV.

Alternative 3 implies work only on decrediton but is another connection/api to keep track of.

**Comment by alexlyp** [comment]
I believe @jrick and @davecgh have actively discussed solving this down below in dcrd/dcrwallet.  When they land on a fix, we can then figure out a way to communicate with decrediton.

I'm mostly reticent about adding any further dcrctl calls as this will be need to be ripped out once we start to make decrediton ready for SPV (only comms with dcrwallet).

**Comment by jholdstock** [comment]
I believe this can be closed as of #2685
