### ISSUE TITLE
Ticket Transaction Filter + Recent Transactions Bug

### ISSUE THREAD

**Issue by jiecut42** [decred/decrediton#1034]
Okay, I love the transaction filter, and I like that the filters are persistent. One problem though is the interaction with the recent transactions. (Also I think this bug was in 1.1.2 also).

So the problem is that if you set a transaction filter in Transactions > History, (i.e regular, votes, tickets ...) Then you click on a transaction in Overview > Recent Transactions. If you click on a transaction that fulfilled the filter, all would be fine, and can click back and you go to recent transactions. But if you click a transaction in Overview > Recent Transactions to view the details, that doesn't fulfill the filter on the other page, all you get a white screen.

So, proper behavior should be that the the Transactions > History filter should work and be persistent. But it shouldn't affect which transaction details are viewable in Overview.

**Comment by matheusd** [comment]
Thank you for the detailed bug report and reproduction steps!

Just sent a fix for this. It should be included in the next release.
