### ISSUE TITLE
Installation fails on Mac

### ISSUE THREAD

**Issue by vanjan** [decred/decrediton#1036]
Hi, I'm using macOS High Sierra (10.13.2) and try to install decreditation 1.1.3.

Upon opening the dmg I get a new device showing up in Finder's sidebar called "decreditation 1.1.3" but the image on my Desktop says "Exodus 1.41.0" and when I click on it, I get the following error: 

> “decrediton 1.1.3” can’t be opened because the original item can’t be found.

I've tried with v1.1.2 and got the same issue.

**Comment by jpz** [comment]
This is not a software issue.  This is a basic user issue of not knowing how to use OSX.  

See: https://www.youtube.com/watch?v=7BrtaOfQVXQ

**Comment by vanjan** [comment]
> This is not a software issue. This is an issue learning how to install software on OSX.

You can keep stupid comments to yourself. 

So it ‘works for you’ — happy days. Doesn’t help me.

**Comment by jpz** [comment]
Right, but in your comment you said you clicked on Exodus.  You do realise Exodus is a completely separate cryptocurrency wallet, right?  Trying to install "decreditation" (there is decrediton, not decreditation btw) by clicking "exodus" it is just bizarre.  

You should be opening the DMG from your downloads folder on the bottom right of your MacOS menu bar, or else from your web browser, and then interacting with the macOS Finder window which pops up - you should not be interacting with the desktop.

The Exodus thing is what strikes me however.  Imagine I was wanting to install Ruby, and I downloaded a Ruby DMG, and then I saw an icon which said "PHP" on my desktop, and I clicked it, and then I said raised a Github issue in the Ruby project about how clicking PHP didn't install Ruby.  It's kind of the same category.

**Comment by vanjan** [comment]
> Right, but in your comment you said you clicked on Exodus. You do realise Exodus is a completely separate cryptocurrency wallet, right?

That is precisely why I thought something was wrong with the decredition disk image. The mounted image on my Desktop had Decred icon but was called Exodus. Is decredition a fork of Exodus? Maybe the process of making the dmg is forked from Exodus? 

Anyway, your comment made my try again after a good old reboot and it worked. It is bizarre tho.

**Comment by jpz** [comment]
This is Exodus - it's a completely different piece of software.  https://www.exodus.io/releases/

Have you downloaded it and forgotten you did so?

**Comment by matheusd** [comment]
Closing as the user reported it's already solved.
