### ISSUE TITLE
Incorrect Mouse Cursor Type When Hover over Buttons in Ticket View

### ISSUE THREAD

**Issue by StabbarN** [decred/decrediton#1038]
Same as #436 but in the ticket view. The cursor type is incorrect on MacOS when hovering the text. Tested on MacOS High Sierra.

See mouse cursor over "Revoked":
![hover](https://user-images.githubusercontent.com/921390/34455111-64146618-ed78-11e7-8217-d58c3b0e4cc8.jpg)

**Comment by matheusd** [comment]
Closed via #1098
