### ISSUE TITLE
Improve styling of View Logs on Help Page

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1041]
Currently the view logs area is bare bones, it could use some basic styling: 

- More explicit button press to expand to see current logs
- Defined areas for each log type

**Comment by linnutee** [comment]
Can anyone drop a screenshot of the current state?

**Comment by matheusd** [comment]
A few notes:
- The logs can be viewed from the main app and the startup stage, so they may have slightly different colors.
- Not yet implemented but must be made room for: decrediton logs (basically another log file, along with the dcrd/dcrwallet logs available)
- Not yet implemented but must be made room for: a checkbox/toggle/button/whatever to enable autoupdate/autoscroll of the logs

![screenshot_2018-01-10_08-41-50](https://user-images.githubusercontent.com/1752493/34769150-2882a2d0-f5e4-11e7-9ea9-c24ba3e15613.png)
![screenshot_2018-01-10_08-42-00](https://user-images.githubusercontent.com/1752493/34769151-28a50672-f5e4-11e7-8fff-f6db29a65c72.png)
![screenshot_2018-01-10_08-42-10](https://user-images.githubusercontent.com/1752493/34769152-28c3b9a0-f5e4-11e7-961f-02e5234f3e14.png)
![screenshot_2018-01-10_08-43-20](https://user-images.githubusercontent.com/1752493/34769153-28e4ffb6-f5e4-11e7-9fc7-9f44f678890d.png)
![screenshot_2018-01-10_08-43-24](https://user-images.githubusercontent.com/1752493/34769154-2904f0dc-f5e4-11e7-9578-30ebffa11d58.png)
![screenshot_2018-01-10_08-43-28](https://user-images.githubusercontent.com/1752493/34769155-29291714-f5e4-11e7-853d-e51d3665933c.png)
![screenshot_2018-01-10_08-43-34](https://user-images.githubusercontent.com/1752493/34769156-2948cae6-f5e4-11e7-8084-db22e91f6ed3.png)

**Comment by alexlyp** [comment]
Completed in recent design PRs
