### ISSUE TITLE
When decrediton is veritcally expanded it's impossible to scroll down on transactions

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1044]
It just shows "Loading more transactions" but seems to be no way to force it to load more.

Definitely a bit of a corner case, but worth trying to fix somehow.

**Comment by matheusd** [comment]
What do you mean "vertically expanded"? Full screen? Or with a height > the number of transactions loaded per page?

**Comment by alexlyp** [comment]
When the height is > number of transactions loaded.

**Comment by alexlyp** [comment]
So after doing some testing, it come down to triggering ANY scroll down.  So if you resize it to just barely show a y-scroll then mouse-wheel down it'll show more, but won't when the y-scroll is still hidden.
