### ISSUE TITLE
Improve Validate Address form in Security Center

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1045]
Here are some improvements I'd like to see to the form:
- Basic improved styling.
- Add an info modal like that Verify/SignMessages have.
- When an address is found to be owned, show all of the other information returned in the validateAddressResponse ( https://github.com/decred/decrediton/blob/master/app/middleware/api.proto#L815-L840 ) 

If owned, show transactions that are related to that address (debit/credit).  Showing of the transactions will require work on a filtering service of sorts that will allow us to find transactions based on searched addresses.  This will require #1046

**Comment by matheusd** [comment]
I'd also change the passphrase input to use the passphrase modal for consistency.

**Comment by alexlyp** [comment]
Do you mean the passphrase input for the sign message form?  Definitely agree there.  Was going to refactor that stuff today.

**Comment by matheusd** [comment]
Yes, exactly.

**Comment by vctt94** [comment]
this has been done
