### ISSUE TITLE
Add transaction filtering by address

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1046]
Add a "search" bar at the top of the Transactions/History page that will let people see all transactions related to a particular address (either in debit or credit).  This will most likely require changes to the GetTransaction call to dcrwallet.  Feel free to drop a proposed change here before embarking on a large set of changes.

**Comment by cipherzzz** [comment]
@alexlyp - I can take a look this week... I'll give a some proposed changes to the **dcrwallet.GetTransaction** call and options for a search bar

**Comment by cipherzzz** [comment]
@matheusd @alexlyp - I am looking at the decrediton Transactions => History screen. Let me know if this is the one you are referring to. 

The 'sort by' button is really a 'filter' button and I would like to repurpose that to show a modal filter that we can add criteria to over time. For instance, have a search input and various other criteria for filtering the transactions. We can include the sort by in this view as well or have it as a root button next to the 'sort by' modal. Here is a mockup...

![screen shot 2018-02-13 at 8 51 10 am](https://user-images.githubusercontent.com/33289322/36153077-1c20e7d2-109b-11e8-9018-173f4010f808.png)
