### ISSUE TITLE
Update to use react-router 4

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1047]
Here's a pretty decent rundown of things that need to happen to migrate from 3.2.0 to 4:
https://codeburst.io/react-router-v4-unofficial-migration-guide-5a370b8905a

**Comment by alexlyp** [comment]
@Jascha-Sundaresan do you have any time to give this a try?  We're looking to upgrade in conjunction with the new launcher redesign which introduces in layout styles.

**Comment by Jascha-Sundaresan** [comment]
I'll take a look at it this evening.

**Comment by Jascha-Sundaresan** [comment]
so it looks like it'll be a bigger undertaking than a few months ago. We added a few extra nested routes.

React router 4 introduces dynamic routing, so we're no longer passing in a route object.

instead, a switch for the various routes happens at any point in the component heirarchy.

The nested routes will live in the actual components that render them now, so the one PR will touch a number of different files.

I don't have the time to take on an undertaking of this size at this point. I'll be available to answer questions for anybody who takes this on between now and the 14th, but I won't for a few weeks after that.
