### ISSUE TITLE
View logs on GetStarted stage

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1049]
We should be able to view the logs not only after the wallet is loaded on the help screen, but also on the GetStarted pages (during daemon blockchain sync, wallet header download, etc) as that may be useful to debug initialization problems.

**Comment by alexlyp** [comment]
Agree, thoughts on design/layout to show these?

**Comment by matheusd** [comment]
Well, the actual component (page/pane/whatever)  that shows the log should be the same. To access it, maybe the same as the settings during startup (a button that shows the page).

**Comment by alexlyp** [comment]
Ya, maybe similar to the App Settings page reveal that you addded.
