### ISSUE TITLE
View Decrediton Logs

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1050]
Besides the dcrd/dcrwallet logs, we should also be able to see Decrediton logs on production as that may help diagnose problems.

**Comment by alexlyp** [comment]
Yah I was going to add that once we have tackled a first pass of #1042

**Comment by alexlyp** [comment]
I need to figure out how to add a custom transport to the winston logger that appends to a var that can be updated like the dcrdLog and dcrwalletLog.  Then should be ready to go as well.

**Comment by vctt94** [comment]
Can I get this one?
