### ISSUE TITLE
Operation not permitted error in Windows 10

### ISSUE THREAD

**Issue by QcMrHyde** [decred/decrediton#1056]
![decreditionerror](https://user-images.githubusercontent.com/6273472/34620955-44c9b0e6-f215-11e7-96e9-8cf2c9ca4eee.png)

I've installed Decrediton on two PC with Windows on it, one installed without problems the other gives me this error even if I'm in administrator mode. I have no idea why.

**Comment by alexlyp** [comment]
What version are you using?  I believe this was fixed in the recent patch release v1.1.3

**Comment by QcMrHyde** [comment]
You are right! I'm one of those morons who post issues without having the latest version I guess lol. I'm gonna hide behind the fact that you release patches really fast. Good job!

...I'm retesting it on my PC that had problems with it, I'll confirm and close the issue when Decrediton will open but it has been "preparing background process" for almost an hour now. Maybe this could be another issue, feedback for the smaller steps happening behind those bigger operations.

**Comment by QcMrHyde** [comment]
I don't seem to have the error anymore but the process always stays stuck at "preparing background process". I'll try to setup my machine to help you debug it, because it's probably due to some setting on that specific PC.

I'll close the issue and re-open it if I find anything.
