### ISSUE TITLE
Decredition JavaScript Error 

### ISSUE THREAD

**Issue by danielpazos** [decred/decrediton#1057]
Hi guys, i'll be really succint here. I've been getting this same problem whenever I try to launch Decredition on Windows 64bit. Anyone can help with a solution?

Appreciate the help in advance. Thank you.
<img width="845" alt="decred" src="https://user-images.githubusercontent.com/35192709/34649527-cb4fefa6-f38f-11e7-85b0-2691acd22b37.png">

**Comment by jolan** [comment]
This should be fixed in the latest version (1.1.3).  Please upgrade:

https://decred.org/downloads/#decrediton

**Comment by danielpazos** [comment]
Thanks a lot!


Em 7 de jan de 2018 11:35, "jolan" <notifications@github.com> escreveu:
