### ISSUE TITLE
Visual Design: implement Overview mockup

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1062]
![overview update](https://user-images.githubusercontent.com/17774057/34694605-545d4cbc-f4d0-11e7-9f01-eb171df618da.png)

Preview (slides 1-4): https://xd.adobe.com/view/456f480c-efaa-4837-a702-e22f19a73163/
Specs: https://xd.adobe.com/view/456f480c-efaa-4837-a702-e22f19a73163/screen/6158b027-61c3-41a0-9511-d9561f0b2b96/Overview-Specs

As this is a complete overhaul of the Overview, I've broken up the implementation into two parts. This one is for the view and it's layout itself and second one contains the specific charts.

**Comment by vctt94** [comment]
Good job linnutee, it looks beatiful! I can work on this. I will start with the overview layout.

**Comment by alexlyp** [comment]
OK vctt94 I'll assign this to you.  I'd say to begin fill out the full spec EXCEPT for the graphing portion in the upper right as a first pass.  

So you should be able to make the changes to Current Total Balance, Available, and Locked as well as shrinking the recent transactions.  

The ticket activity area will require some extra rigging too, so may be worth leaving that for a future PR as well.

**Comment by vctt94** [comment]
I did what you said. I will also create tabs for the graphs, and I believe the PR will be good to merge so it won't get too big.

**Comment by vctt94** [comment]
My PR is good for reviewing now https://github.com/decred/decrediton/pull/1069. I could not make the active tab work properly. I need to investigate why, but I believe it is because of some relative or absolute position on the tabbed component.
