### ISSUE TITLE
Hitting f5 at overview page seems to shut down decrediton sometimes

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1065]
Sometimes when hitting f5 at overview page it shuts down decrediton, but sometimes it does not. Not really sure of the cause.

**Comment by alexlyp** [comment]
Can you explain what you're seeing? I'm seeing a clean reload when I enter f5 while in dev mode.  Any steps to reproduce?

**Comment by vctt94** [comment]
I am not sure. I've seen this message: `Error: Endpoint read failed`, but not really sure if it is related. I will keep investigating. Not sure if it happens in other pages too.

**Comment by alexlyp** [comment]
Yah that error is related to a grpc stream that hasn't been properly closed.  I'll be trying to find that.

**Comment by alexlyp** [comment]
I believe this issue has been resolved.  Closing.
