### ISSUE TITLE
Version info displayed inside Decrediton Wallet

### ISSUE THREAD

**Issue by karamble** [decred/decrediton#1071]
Would be nice to have the version info anywhere in the GUI

maybe just on top of the help-page

**Comment by jolan** [comment]
I would put it in the title of the window too.

**Comment by alexlyp** [comment]
Hrm @matheusd thoughts about ways we could pass the app version info into app.html to change the title?

**Comment by matheusd** [comment]
No need to pass it to the html. Just remove the `<title>` tag and set it up from the electron `BrowserWindow` function.
