### ISSUE TITLE
can't find anyway to import Web wallet backup to decrediton

### ISSUE THREAD

**Issue by bibondz** [decred/decrediton#1079]
I have Web wallet and back up to xxxxx.json
How to add wallet to GUI Wallet(Windows)

**Comment by alexlyp** [comment]
The seed is not in the backup json.  You must enter that 33 word seed from webwallet into decrediton.

**Comment by bibondz** [comment]
I've try but not work
It create new one not a same i want
I propose to add json document import.
To be easy to use.
