### ISSUE TITLE
Ticket Purchase just not Occurring

### ISSUE THREAD

**Issue by chadi77** [decred/decrediton#1084]
Whenever I attempt to purchase a ticket I successfully input everything, click the Purchase button, input the correct passphrase, get the "Successfully imported new script tickets" message, and Stakey just sits on the screen dancing and will not go away. No tickets show as purchased, no transactions appear on my transactions page (although a loading mor transactions animation appears but never goes away), and I never see any evidence of a ticket anywhere. I have attempted this several time over a few weeks with no success. I have to close Decrediton in order to be able to view the Purchase Tickets page and no transactions from my ticket purchase attempts appear. Rescanning doesn't do anything either. I have attempted to review the wallet logs but I am unable to to determine anything from them (because I am unsure how to read them.) I don;t know if this is an issue with Decrediton or with how I initially set it up.

Let me know what you may need me to do to help you figure out what is going on.

Thanks!

**Comment by matheusd** [comment]
Which version of Decrediton are you running? There was a bug on 1.1.2, fixed on 1.1.3 that lead to that problem on some situations, so make sure you've upgraded (check the version on the Help -> About main menu).

**Comment by chadi77** [comment]
I am currently on Decrediton 1.1.3, dcrd 1.1.2+release. and dcrwallet 1.1.2+release.

**Comment by matheusd** [comment]
Ok, please try the following:

- Close Decrediton. Open it again.
- Main Menu -> "Advanced" -> "Toggle Developer Tools"
- Try the ticket purchase

See if there are any error messages there.

Second check:

- Main Menu -> "Advanced" -> "Show wallet log files"
- Open `dcrwallet.log`. Look from the bottom up (last lines) see if there are any messages marked as `[ERR]`, specially after a line starting with `GRPC: Unary Method /walletrpc.WalletService/PurchaseTickets invoked ...`

**Comment by chadi77** [comment]
OK yeah seeing a multitude of errors in Developer Tools. 
dcrwallet.log does not contain anything with "PurchaseTickets".

Errors from Developer Tools:
> Uncaught AssertionError: Assertion failed  bundle.js:14

* goog.asserts.DEFAULT_ERROR_HANDLER | @ | bundle.js:14

* goog.asserts.doAssertFailure_ | @ | bundle.js:14

* goog.asserts.assert | @ | bundle.js:14

* jspb.BinaryEncoder.writeSignedVarint64 | @ | bundle.js:14

* jspb.BinaryWriter.writeSignedVarint64_ | @ | bundle.js:14

* jspb.BinaryWriter.writeInt64 | @ | bundle.js:14

* proto.walletrpc.PurchaseTicketsRequest.serializeBinaryToWriter | @ | bundle.js:1

* proto.walletrpc.PurchaseTicketsRequest.serializeBinary | @ | bundle.js:1

* mt | @ | bundle.js:14

* Client.makeUnaryRequest | @ | C:\Users\[redacted]\AppData\Local\Programs\decrediton\resources\app.asar\node_modules\grpc\src\node\src\client.js:515

* apply | @ | C:\Users\[redacted]\AppData\Local\Programs\decrediton\resources\app.asar\node_modules\lodash\lodash.js:499

* wrapper | @ | C:\Users\[redacted]\AppData\Local\Programs\decrediton\resources\app.asar\node_modules\lodash\lodash.js:5356

* (anonymous function) | @ | bundle.js:1

* (anonymous function) | @ | bundle.js:19

* dispatch | @ | bundle.js:14

* (anonymous function) | @ | bundle.js:1

* (anonymous function) | @ | bundle.js:1

* (anonymous function) | @ | bundle.js:19

* dispatch | @ | bundle.js:14

* (anonymous function) | @ | bundle.js:1

* (anonymous function) | @ | bundle.js:19

* dispatch | @ | bundle.js:14

* (anonymous function) | @ | bundle.js:1

* (anonymous function) | @ | C:\Users\[redacted]\AppData\Local\Programs\decrediton\resources\app.asar\node_modules\grpc\src\node\src\clients.js:559

**Comment by chadi77** [comment]
I'm assuming by "advanced seetings" you are referring to the Settings icon for Purchase Tickets. If that is the case then everything looks fine to me:

Account: The Balance

Number of Tickets: 1
Stake Pool: "The stakepool"

Ticket Fee: 0.001 DCR/KB   Tx Fee: 0.001 DCR/KB   Expiry: 16 blocks

Ticket Address: Populated
Pool Address: Populated
Pool Fees: Populated

**Comment by matheusd** [comment]
By the provided logs, the error seems to be on parameters used by the purchase ticket method, but since you mentioned all fields are populated, it's hard to know what exactly is causing it.

Next things you can try:

- Remove the stakepool from your configured list, and re-add it (make sure you have api key/login details to the stakepool before doing this)
- Re-create the wallet from seed (backup your wallet.db file as a precaution before doing this)
