### ISSUE TITLE
Identify corrupted blockchain and offer methods/instructions to fix

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1093]
We have users on a semi-weekly basis with what end up being blockchain db corruptions.  We should give them an easy way to fix (click button to delete directory and restart dcrd) or at least provide instructions on how they can fix themselves.

**Comment by xaur** [comment]
What are the reasons for corruptions? Hardware faults or are users doing something wrong?

**Comment by alexlyp** [comment]
From what we've seen it's typically hardware faults or unexpected hard shutdowns (power outage during a db write or something).

**Comment by alexlyp** [comment]
Completed in #1392
