### ISSUE TITLE
Use correct timezone for transaction date/time

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1099]
Eg: [this testnet tx](https://testnet.dcrdata.org/explorer/tx/44466fda195cf91b3931c83c1ad418a995125c235d201e837318f922bf74e569) happened at  (UTC) 2017-10-16 18:56:27 but is shown on my running decrediton instance as "3:56:27 PM", when the correct time (due daylight savings being effective on this date at my current locale) is 4:56:27 PM. 

So we need a better way of detecting/selecting the user timezone and/or a better way to convert from the int timestamp to a string date/time.

**Comment by cipherzzz** [comment]
I can take this - @matheusd Any design thoughts?

**Comment by matheusd** [comment]
Not really. We might need a setting to say which tz to display the info in (either local or UTC) or default to always display in local tz, but take care of localized display formats.

**Comment by shweini** [comment]
@cipherzzz working on this? or should i work on it?

**Comment by cipherzzz** [comment]
Go for it! I'm not working on Decred right now

**Comment by shweini** [comment]
alright. thanks
