### ISSUE TITLE
Icon on Linux

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#110]
There is no icon in the Linux build.

**Comment by jcvernaleo** [comment]
After going through this more, I don't actually see an icon option for linux (and I notice the slack app doesn't have an icon in this place either) so I think we can't actually do this.  There are some other places for icons needed for the .deb packaging #199 but that is a separate issue so I'm closing this as somewhere between redundant and not possible.

**Comment by jolan** [comment]
I looked at this awhile back and setting the icon property on BrowserWindow to a path works:

https://github.com/decred/decrediton/compare/master...jolan:jolan_icon

I wasn't able to figure out the webpack stuff to make it work in !dev mode though.

**Comment by jcvernaleo** [comment]
Guess that means I'll reopen this guy and assign it to you for future since you actually made some progress.  I was working at it from the electron builder angle rather than that way.
As for webpack, that is nothing but confusing.  I don't know if I blame the docs or the package itself.

**Comment by jolan** [comment]
I noticed that [electron-packager](https://github.com/electron-userland/electron-packager) seems to support Linux icons somehow so if we decide to change the packaging over to that, then this might be trivial.

**Comment by jcvernaleo** [comment]
I think there was some reason we builder was better but I'm not sure.  Either way something we should look at later.
