### ISSUE TITLE
Feature Request: "Terminal Mode" for executing dcrctl --wallet commands

### ISSUE THREAD

**Issue by mverrilli** [decred/decrediton#1108]
It would be convenient to have a terminal mode for more advanced usage built into the UI that executes dcrctl with the correct parameters.

**Comment by jrick** [comment]
decrediton doesn't run dcrwallet with the json-rpc server enabled at all for security reasons.  Any other application, especially those running as the same user, would be capable of calling an API to drain the entire wallet the moment it is unlocked.

**Comment by alexlyp** [comment]
As jrick explained, due to security concerns we won't be adding this feature request.
