### ISSUE TITLE
DECREDITON wallet sending to wrong address

### ISSUE THREAD

**Issue by WKw23ks** [decred/decrediton#1118]
I need help. I've sent 3 transactions from my decrediton wallet that have been lost in cyber space. When I see the address it has been sent to, it is different from the one that I allocated.

**Comment by matheusd** [comment]
You're sending to yourself? When you see the transaction details inside Decrediton, does the address/account match what you expect? Where are you comparing the address (blockchain explorer)?

**Comment by WKw23ks** [comment]
DsRgfTTcmiZGQ8eW4Da9x6mjxVa6V7wUfKX

Dsopc7QwQbeM1FNko6EWtLxK84DYEfzL9x8


The transaction was supposed to go to the top address, and it somehow went to the bottom... I have no idea what that address is and where it came from..? I was sending it from decrediton wallet - to cryptopia exchange. I've written to cryptopia but they have not responded....

**Comment by alexlyp** [comment]
https://explorer.dcrdata.org/tx/2e1a317c9783a975da4165494a3548f6a9f5ccd3513c81baccb1b46cd1e38924

The top address is your destination address, the bottom address is a change address generated by your wallet.

**Comment by WKw23ks** [comment]
The transaction happened yesterday and has not shown up. there is no record of it on the exchange...?

**Comment by alexlyp** [comment]
I believe some of the exchanges are still experiencing wallet issues that should be resolved shortly.  But from everything I see there was a successful transaction to DsRgfTTcmiZGQ8eW4Da9x6mjxVa6V7wUfKX for 19 DCR.
