### ISSUE TITLE
Design Implementation: Launcher Loader

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1123]
Visual Design and specs: https://xd.adobe.com/spec/a12ebccf-c8e9-416e-9a23-71a9d4615f69/

The new decrediton launchers loader comes in two different forms. In the `Launcher Overview` the default large loader is displayed. When the user is in any other view (Settings, Tour, Wallet Creation Feedback or Logs) a smaller loader is displayed in the bottom of the viewport. 

Will follow up with some animation examples to refine this further.  

See [launcher-master](https://xd.adobe.com/spec/ab537a4e-2902-4260-99f1-85c3992f9a73/) more for reference or hit me up on slack.

**Comment by StabbarN** [comment]
Looking awesome! 

I'd enjoy reading the onboarding docs (#1120) while the blockchain is loading. Education while waiting is a super good opportunity. Perhaps the onboarding could be squezeed above the loader? It's merely a suggestion, you know what's best :)

**Comment by linnutee** [comment]
The onboarding ones are far too large, but otherwise thinking about adding a rotation of smaller tips to show during loading in the future.
