### ISSUE TITLE
Cleanup/Refactor main.development.js

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1137]
This file has become quite large and bloated.  We should split out functionality into reasonable modules.

Short list of potential modules:
- Config (already exists, but could use clean up)
- Logging (already exists)
- dcrd/wallet launching/shutdown
- Ipc handling
- electron window/menutemplate creation

If you would like to work on this issue please submit a PR per module so review can proceed quickly.

**Comment by vctt94** [comment]
I can work on this issue

**Comment by alexlyp** [comment]
Cool, give me a run down of how you're going to organize things, then I'll give an OK on that before you get going on the major refactor

**Comment by vctt94** [comment]
Okay, I'll read the code and get back with an approach. One thing I think would be good is a directory, so all files don't stay on the app folder. Something like MainDev, what do you think?

**Comment by vctt94** [comment]
I liked how you divided modules, I'll follow as you said, and if I think some change is necessary on the way, I come back to you. I'll start with config and we can see how it goes. 

I am thinking we can have a file for paths as well. There are some paths being created on the config file and some on the main.development.
