### ISSUE TITLE
Refactor layout/routing in preparation for new launcher design

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1138]
As suggested by @matheusd:

> The onboarding "stories" (with a left-side sidebar-like illustration) and the main actions (which don't use a sidebar). Along with the main view, we should now have 3 general layout styles. Probably wanna do those as individual containers, refactoring the App container to be the top-level with just the i18n init stuff, and then different root routes for the different layouts

So these 3 layout styles would be something like:
- StoryView
- MainSideBarView (currently what is mostly App.js container)
- MainNoSideBarView

The StoryView and MainNoSiderBarView layouts should be able to be easily generated from #1120 and #1121, respectively.  

Routes can then be redone in the following fashion:
 App -> Layout -> Page -> Tabs (if necessary)

**Comment by matheusd** [comment]
I don't know if there's anything that could be done to ease the migration to react-router 4 (#1047) while doing this, but whoever ends up making this refactor should at least keep this future change in mind.

**Comment by alexlyp** [comment]
Yah I was actually thinking the same thing last night.

**Comment by alexlyp** [comment]
After discussing with @matheusd, I will proceed with the react-route 4 upgrade prior to embarking on this routing refactor.

**Comment by matheusd** [comment]
Fixed in the various recent refactorings.
