### ISSUE TITLE
Design Implementation: Launcher, Advanced Daemon

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1142]
Visual Design and Specs: https://xd.adobe.com/spec/a3027efd-f104-4dde-b977-48323d3c865d/

Advanced Daemon should be disabled by default, but can be activated from Settings. 
In case both Adv. Daemon and Display Wallets are activated, the wallets are displayed below it (slide 4)
`Skip` hides Adv. Daemon and shows Launch Wallet button again. 
When Adv. Daemon is active, `Launch Decrediton Automatically …` needs to be in a disabled state.

See [launcher-master](https://xd.adobe.com/spec/ab537a4e-2902-4260-99f1-85c3992f9a73/) more for reference or hit me up on slack.

**Comment by alexlyp** [comment]
Completed
