### ISSUE TITLE
Create an account on testnet - 502 Bad Gateway

### ISSUE THREAD

**Issue by katian** [decred/decrediton#1143]
Hi, i'm trying to create an account on https://teststakepool.decred.org/ but it show me an "502 Bad Gateway" error.

I have modified ~/.conf/decredition/config.json with "network" : "testnet"

Ubuntu 17.10

**Comment by matheusd** [comment]
Thanks for the heads up, but this isn't a Decrediton issue (it's an issue with that particular stakepool).

Someone should be looking into this shortly.
