### ISSUE TITLE
Chart Legends on Start Page Is Lower Case

### ISSUE THREAD

**Issue by StabbarN** [decred/decrediton#1155]
Imo, it looks weird with legends starting with a lower case. Legends on all tabs; Balance, Ticket and Transactions.

<img width="426" alt="legend" src="https://user-images.githubusercontent.com/921390/35882395-57c64384-0b84-11e8-9f4e-f73ecb18e77d.png">

**Comment by linnutee** [comment]
Referring this to #1063
The charts are partially implemented atm, legends shouldn't be displayed there at all

**Comment by StabbarN** [comment]
Ok, great, closing this issue then.
