### ISSUE TITLE
Tab Title In Plural (Ticket -> Tickets)

### ISSUE THREAD

**Issue by StabbarN** [decred/decrediton#1156]
Set the title on the second tab to be in plural, that is, "Tickets", not "Ticket" because "Transactions" is in plural.
<img width="426" alt="legend" src="https://user-images.githubusercontent.com/921390/35882557-e3d53df8-0b84-11e8-977f-3e7739564dd8.png">

**Comment by cipherzzz** [comment]
This is already resolved @matheusd @alexlyp 
![image](https://user-images.githubusercontent.com/33289322/36400253-c5472144-159d-11e8-9d7f-606407561c57.png)
