### ISSUE TITLE
Move constants to wallet/constants.js

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1164]
There are all sorts of constants (maturity heights, block time interval, etc) spread throughout the code. Ideally, we should store all such constants and calculations inside the `wallet/constants.js` file, which follows the dcrd convention of one param object per network.

**Comment by Jujhar** [comment]
This seems to be done, with maturity heights, block time interval added:
https://github.com/decred/decrediton/blob/master/app/wallet/constants.js

There are some variables in statistics actions such as MaturityBlocks, MaxMaturity,  BlocksPerDay,  ExpirationDays, DayBuckets that could be added here if it makes sense, besides those is there anything else missing in that file I could add?

**Comment by matheusd** [comment]
The stuff in statistics is derived from what is in the chainParams, so it's not super necessary to move them to the constants file, but I guess it's not too problematic to do it.

Last time I looked there were only one or two places left using magic numbers, but they may have been handled already in various refactorings.

**Comment by Jujhar** [comment]
If I do add it it will look something like this:

```
// Constants copied from dcrd/chaincfg/params.go

const DevTicketMaturity = 16;
const DevCoinbaseMaturity = 16;

// For statistics
const DevTicketExpiry = 6144, // 6*TicketPoolSize
const DevTargetTimePerBlock = 2 * 60, // in seconds

export const TestNetParams = {
  TicketMaturity:          DevTicketMaturity,
  TicketExpiry:            DevTicketExpiry,
  CoinbaseMaturity:        DevCoinbaseMaturity,
  SStxChangeMaturity:      1,
  GenesisTimestamp:        1489550400,
  TargetTimePerBlock:      DevTargetTimePerBlock,

  // For statistics
  MaturityBlocks:          Math.max(DevCoinbaseMaturity, DevTicketMaturity),
  MaxMaturity:             Math.max(DevCoinbaseMaturity, DevCoinbaseMaturity),
  BlocksPerDay:            (60 * 60 * 24) / DevTargetTimePerBlock,
  ExpirationDays:          Math.ceil((DevTicketExpiry + devTicketMaturity) / BlocksPerDay),
  DayBuckets:              Array(ExpirationDays + 1).fill(0),

  // no way to know which one the wallet is using right now, so we record both
  // types for the moment.
  LegacyHDCoinType: 11,
  HDCoinType: 1,

  WorkDiffWindowSize: 144,
};

const MainTicketMaturity = 256;
const MainCoinbaseMaturity = 256;

// For statistics
const MainTicketExpiry = 40960, // 5*TicketPoolSize
const MainTargetTimePerBlock = 5 * 60, // in seconds

export const MainNetParams = {
  TicketMaturity:          MainTicketMaturity,
  TicketExpiry:            MainTicketExpiry,
  CoinbaseMaturity:        MainCoinbaseMaturity,
  SStxChangeMaturity:      1,
  GenesisTimestamp:        1454954400,
  TargetTimePerBlock:      MainTargetTimePerBlock,

  // For statistics
  MaturityBlocks:          Math.max(MainCoinbaseMaturity, MainTicketMaturity),
  MaxMaturity:             Math.max(MainCoinbaseMaturity, MainCoinbaseMaturity),
  BlocksPerDay:            (60 * 60 * 24) / MainTargetTimePerBlock,
  ExpirationDays :         Math.ceil((MainTicketExpiry + MainTicketMaturity) / BlocksPerDay),
  DayBuckets:              Array(ExpirationDays + 1).fill(0),

  // no way to know which one the wallet is using right now, so we record both
  // types for the moment.
  LegacyHDCoinType: 20,
  HDCoinType: 42,

  WorkDiffWindowSize: 144,
};

```

Kinda seems clunky but it does make statistics action only use DayBuckets eliminating the other two related constants which are used to just calculate that. I personally prefer the older way as it is more high cohesion as all the statistics code in one place.

**Comment by matheusd** [comment]
Yeah, adding these separate vars doesn't look great.

**Comment by Jujhar** [comment]
We should close this.
