### ISSUE TITLE
Enforce spacing in eslint file

### ISSUE THREAD

**Issue by cipherzzz** [decred/decrediton#1181]
We currently have random spacing with braces, brackets, etc. Need to enforce this in the eslint specs.

Examples:
**ClientActions.getStakeInfoAttempt**
- Notice how the 'OR' operation has no spaces, but the !== does. We need consistent spacing around operations
`...
      const reloadTickets = getStakeInfoResponse
        ? checkedFields.reduce((a, v) => a||getStakeInfoResponse[v]() !== resp[v](), false)
        : false;
...`

**ClientActions.getWalletServiceSuccess**
`...
      dispatch({ walletService, type: GETWALLETSERVICE_SUCCESS });
...`
**ClientActions.getStartupWalletInfo**
`...
      dispatch({type: GETSTARTUPWALLETINFO_ATTEMPT});
...`
- Notice how the dispatch {} has inconsistent spacing. We need consistent spacing around braces

**Comment by cipherzzz** [comment]
Adding the following to the eslintrc file gives us 1670 related errors
```
"object-curly-spacing": ["error", "always"],
"array-bracket-spacing": ["error", "always"],
```
The opposite gives us 3184 errors
```
    "object-curly-spacing": ["error", "never"],
    "array-bracket-spacing": ["error", "never"],
```

So, it seems that there are twice as many adding the space than not. I can --fix them, but is this too big of a change? @matheusd @alexlyp

**Comment by alexlyp** [comment]
Let's enforce the rules just to get it over with.  I'll submit a PR momentarily.
