### ISSUE TITLE
Motion Design Fix: Don't move scrollbar during transitions

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1189]
<img width="756" alt="screen shot 2018-02-21 at 18 28 37" src="https://user-images.githubusercontent.com/17774057/36492134-0eaf59f8-1735-11e8-856f-817ffeb72e5a.png">

Currently the scrollbar changes position with the rest of the view during a transition. 
When a subpage transition takes place, scrollbar needs to remain in place.

**Comment by matheusd** [comment]
Following is the dynamic behavior of the scrollbar we get by moving it from each individual tab into the parent container (disregard scrollbar styling). It doesn't really look terribly good as well. What do you think should happen eg: when moving from a page without scrollbar to one with scrollbar (and vice-versa)?

![dynamic-scrollbars mp4](https://user-images.githubusercontent.com/1752493/37290470-1479ae50-25eb-11e8-8a43-8d9976e84b3c.gif)

**Comment by linnutee** [comment]
Perhaps a time-out / fade-out of the scroll bar would solve it. By default is hidden, triggers and fades in again when scrolling, pressing up-down arrow or hovering on it. If not used for 1.3 sec, fades out again.
