### ISSUE TITLE
mach_kernel via decrediton

### ISSUE THREAD

**Issue by ivorpad** [decred/decrediton#1199]
What is this? I deleted Decrediton from my Mac and this is still appearing in LittleSnitch. How do I stop it?

<img width="1168" alt="screen shot 2018-02-24 at 14 32 03" src="https://user-images.githubusercontent.com/52452/36633700-5789a290-1970-11e8-8b7b-ad2ec0de097c.png">

<img width="354" alt="screen shot 2018-02-24 at 14 32 24" src="https://user-images.githubusercontent.com/52452/36633693-4b7ab43a-1970-11e8-9ce3-f301b048fcfd.png">

**Comment by alexlyp** [comment]
https://discussions.apple.com/thread/4965707

Looks like you may not have removed the decrediton application appropriately.

**Comment by ivorpad** [comment]
@alexlyp I uninstalled the app with AppCleaner. What's the proper way to uninstall it?

**Comment by alexlyp** [comment]
Make sure all of these are gone:
/Applications/decrediton.app
~/Library/Application Support/decrediton
~/Library/Application Support/Dcrd

**Comment by jrick** [comment]
9108 is the network port.  dcrd must still be running.
