### ISSUE TITLE
ReactTimeout error while on GetStarted screen

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1207]
`Uncaught TypeError: Cannot read property 'apply' of undefined at Object.<anonymous> (reactTimeout.js:11)`

Not sure the cause exactly, but I believe it's due to the ReactTimeout not being configured correctly.

**Comment by matheusd** [comment]
Do you have reproduction steps? Haven't been able to trigger this.

**Comment by alexlyp** [comment]
Looks like this issue has been resolved from the recent updates.
