### ISSUE TITLE
One of my transactions   can't be  confirmed  for more two days.  

### ISSUE THREAD

**Issue by better2018** [decred/decrediton#1209]
One of my transactions   can't be  confirmed  for more two days.  
The transaction  is  0.000621DCR.
Now I can't buy ticket.  When I buy it,the web said:
"Error: Unable to purchase tickets: failed to send split transaction: -1: Rejected transaction 407bcadb155f09c976cf929d0f8b2a958967e2876c6145fe6e7d44876dcd8b1c: orphan transaction 407bcadb155f09c976cf929d0f8b2a958967e2876c6145fe6e7d44876dcd8b1c references outputs of unknown or fully-spent transaction 53b0259ececf70ed1a221b3641d52a4db0ef7899dd2920043362244e3b5141a9"

Please help me out!!  Thank you!

**Comment by matheusd** [comment]
You can rebroadcast any pending transactions by opening its details, copying the raw (hex) transaction then posting on https://explorer.dcrdata.org/decodetx

You should also try rescanning.

**Comment by better2018** [comment]
@matheusd Thank you for answer me. Now I try it,then  it  sent tx:  " Error: -1: Rejected transaction 53b0259ececf70ed1a221b3641d52a4db0ef7899dd2920043362244e3b5141a9: already have transaction 53b0259ececf70ed1a221b3641d52a4db0ef7899dd2920043362244e3b5141a9"

**Comment by alexlyp** [comment]
Looks like it was just mined: https://explorer.dcrdata.org/tx/53b0259ececf70ed1a221b3641d52a4db0ef7899dd2920043362244e3b5141a9

**Comment by better2018** [comment]
@matheusd @alexlyp the  transaction has been confirmed.Thanks!
