### ISSUE TITLE
Create new account dialog - Incorrect button layout

### ISSUE THREAD

**Issue by peterzen** [decred/decrediton#1217]
Confirm/Cancel buttons layout incorrect - Confirm should be on the right

![image](https://user-images.githubusercontent.com/5878500/36985331-436e1a74-2097-11e8-996e-51b3b336b430.png)

**Comment by alexlyp** [comment]
We're going to keep the ordering, but this will be updated use InvisibleButton for the cancel instead of SlateGray

**Comment by alexlyp** [comment]
And the Cancel will be directly next to the Confirm not floated to the right

**Comment by peterzen** [comment]
Right, the Cancel should be next to Confirm, the ordering is correct indeed

**Comment by alexlyp** [comment]
Though I am thinking that maybe both buttons should be on the right with Cancel first then Confirm. Thoughts?

**Comment by peterzen** [comment]
Yes, that is the UI best practice is to keep the buttons flushed to the right.

On another note, the Cancel button is recommended to be placed to the left of the Confirm/OK button, it feels more natural that way.

https://material.io/guidelines/components/buttons.html#buttons-persistent-footer-buttons

**Comment by alexlyp** [comment]
Kk PR in a sec

**Comment by peterzen** [comment]
https://material.io/guidelines/components/dialogs.html#dialogs-confirmation-dialogs
