### ISSUE TITLE
Cancel button missing on 'Add new wallet' dialog

### ISSUE THREAD

**Issue by peterzen** [decred/decrediton#1220]
There's no way to go back one step - needs a Cancel button:

![image](https://user-images.githubusercontent.com/5878500/36987176-0605af76-209c-11e8-9d5f-517ee1a608fa.png)

**Comment by alexlyp** [comment]
It's on the right.  Do you mean after someone completes this form?

**Comment by peterzen** [comment]
Oh indeed, my bad - the inspect sidebar hid it.  Closing this, sorry
