### ISSUE TITLE
Use Radio Buttons Instead of Toggle When Only Two Options?

### ISSUE THREAD

**Issue by StabbarN** [decred/decrediton#1223]
Is Mainnet chosen because it's pressed down or is Testnet chosen because it's standing out?

<img width="603" alt="toggle" src="https://user-images.githubusercontent.com/921390/36990601-7ff9b896-20a5-11e8-91dd-26edc4b4defb.png">

In my opinion toggle buttons are great when there is at least three options or when it's an on or off state.
I'd prefer two radio buttons instead of the toggle.

I mentioned this in the Slack #dev channel and two other guys agreed that a toggle with only two options are confusing.

@linnutee What do you think about changing it to radio buttons instead of a toggle? Or something else where the selection is more clear?

**Comment by linnutee** [comment]
Yup – this is included in a earlier step now: https://xd.adobe.com/spec/ab537a4e-2902-4260-99f1-85c3992f9a73/#screen/ffe8f614-aad4-4ee1-a8c9-8dbb4e6da261/Create%20Wallet%202

**Comment by alexlyp** [comment]
This is no longer an issue.
