### ISSUE TITLE
Transfer

### ISSUE THREAD

**Issue by mtham1** [decred/decrediton#1232]
I sent a deposit to Poloniex yesterday and it still has not shown up.  How long should this take?
mthambyte@gmail.com

**Comment by alexlyp** [comment]
Do you have a confirmed transaction id?  Can you see your transaction on explorer.dcrdata.org ?

**Comment by mtham1** [comment]
Transaction:

91878219998a005c04ce735e5d6f66b3e440292ac254b6f4d4765dfd7fb87b9e

**Comment by alexlyp** [comment]
https://explorer.dcrdata.org/tx/91878219998a005c04ce735e5d6f66b3e440292ac254b6f4d4765dfd7fb87b9e

It's been sent and confirmed.  If it's still showing pending on Poloniex I'd contact their customer service to resolve the issue.
