### ISSUE TITLE
Detect and instruct on "references outputs of orphan transaction"

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1247]
Version 1.2.0 will have a rebroadcast button which along with the rescan action should solve most of these problems. But if we keep getting support requests for this, we might wanna add a specific check to detect and show instructions on how to solve it.

![orphan-tx-error](https://user-images.githubusercontent.com/1752493/37458326-7f99174a-2823-11e8-885d-b222c920ae47.jpg)

**Comment by alexlyp** [comment]
Yah I think that's a great idea.  Definitely the most common support question I've been getting as of late.

**Comment by ZeroASIC** [comment]
We're on v1.3.1.  Did this get fixed?  If not then how do I reproduce it?

**Comment by alexlyp** [comment]
The issue still happens.  And it will continue to happen without some major changes underneath.

And we haven't yet added the error + instructions.  

To reproduce you can try to buy tickets twice in a very short period of time. And exit decrediton before they are mined.  That could do it.  But you probably need to use a remote/advanced dcrd that isnt' connected to the network.  A few ways to wedge it.  Hit me up on matrix and I can walk you through the process if you want to try.

**Comment by ZeroASIC** [comment]
I think that teststakepool.decred.org is still having email issues.  When I try to reset my password I get this error. `Unable to send password reset email`

**Comment by alexlyp** [comment]
Yah we need to update to use another email provider for teststakepool, sounds like you can use https://test-dcrpool.dittrex.com in the meantime.

**Comment by vctt94** [comment]
I believe with the rebroadcast button this has been solved
