### ISSUE TITLE
Loading Bar, Headline and Logs Overlaps

### ISSUE THREAD

**Issue by StabbarN** [decred/decrediton#1260]
See
![loading bar and logs overlap 2](https://user-images.githubusercontent.com/921390/37555710-10b0f92c-29ec-11e8-89de-eeb98fdfaa99.png)

To recreate you have to choose/create a wallet so that both dcrwallet and dcrd logs can be expanded.

"Logs" view should be wrapped in a div or similar so they don't crash into the header at the top or loading text at the bottom when scrolling.

**Comment by matheusd** [comment]
At what stage are you accessing the page that shows the broken title? I'l trying to check this on latest master but I don't see the overlapping title.

**Comment by StabbarN** [comment]
1. Remove blockchain files
2. Start decrediton
3. Choose a wallet
4. Open logs
5. Expand both drcd and dcrwallet
