### ISSUE TITLE
Alternative seed entry/confirmation methods?

### ISSUE THREAD

**Issue by obxium** [decred/decrediton#1263]
Not sure how helpful this idea will be, but some discussion occurred in the [Telegram channel](https://t.me/Decred) about the UX for entering/confirming seed words. Here was my initial observation as a new user of decrediton remarking on another new user's similar observation of being frustrated by having to type the words for confirmation:

> I think this person shared my same initial bewilderment around the challenging UX of forced typing in the wallet UI. From a new user perspective, it feels much like certain organizations' websites which block pasting passwords. It is a bit cumbersome, might present accessibility challenges(?), does not play nice with password managers and I wonder if it exposes the seed to keyloggers...

To which Isaac helpfully added:

> I think the “no cut and paste” is intended to support the best practice of writing down by hand and never storing the information electronically.  There is a much higher chance of seeds being stolen from a file on PC or in cloud than a hand written paper in your safe or other secure location.  I’m not sure of that, just my guess.  I agree with your sentiment however.

and my response:

> I thought that could be the case and it definitely makes sense to enforce that best practice for sure. It's a challenging UX problem and I think the team has probably made the best decision here with respect to the storage of the seeds.
and Noah further commented:

> Yeah, if I remember correctly it is a security thing
> If you'd like to propose alternatives you are welcome to create an issue: https://github.com/decred/decrediton/issues

Hopefully this adds some color to the request.

Other wallets I have personally used provide the option to either enter the seed words _word-at-a-time_ style as decrediton does, or _also as open open text field_ which can typically allow for pasting.

The request here would be to consider also allowing other means to confirm the wallet seed phrase in decrediton as this seems like a fair tradeoff between the intended use of seed phrases (written down/stored in an offline mode) and the security practices which favor tools for managing pass-phrases/passwords and pasting in versus typing in.

This way, perhaps decrediton can match the previously mentioned seed confirmation modes from other wallets and provide a familiar UX for the user's preferred seed management style.

Some pros and cons of each method which might also help in thinking about this:

#### word at a time style

Pros:

1. Can help to ensure that the seed phrase words are copied down properly
2. Helps to not lose your place when typing the seed phrase

Cons:

1. Can be challenging to get the phrases correct when manually typing
2. The challenges presented by typing a large number of random words can become frustrating for new users especially if they're accustomed to alternate methods in other wallets
3. Some users could have concerns with manually typing things either due to accessibility or other issues

#### pasting into a form

Pros:

1. Accurate and quick
2. Some defense against keylogging (though perhaps susceptible to clipboard exfiltration?)
3. Could potentially be helpful to people of different abilities
4. Other wallets offer this as an option

Cons:

1. Doesn't fit the intended use case of manually writing the seed phrase down
2. Ultimately not as secure as writing the seed phrase down

Thanks for the great project and keep up the fine work!

**Comment by matheusd** [comment]
The new version to be released (1.2.0) has a new seed input method. It will allow you to copy a new seed into the clipboard (after a warning and confirmation) and will only require you to verify about 10 (random) words of the seed.

You will also have the option of pasting **existing** seeds (with a simple ctrl+v).

**Comment by obxium** [comment]
Awesome, that sounds like a great feature!

**Comment by obxium** [comment]
The 1.2.0 subset of seed words approach is great and a fantastic compromise on the UX. Well done!
