### ISSUE TITLE
Security Page hot reload does not seem to work

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1276]
If changes are done at any tab of Security Page, they do not take place when refreshing decrediton. It is needed to restart decrediton which is annoying when editing those pages.

**Comment by alexlyp** [comment]
Can you explain this?  AFAIK hot reloading doesn't work anywhere

**Comment by matheusd** [comment]
Don't know if it's the same thing I get, but I occasionally webpack's auto rebuild stops working for some pages (usually the purchase tickets for me). I haven't been able to track down what exactly causes this, but usually restarting the machine works. I think this *might* be an issue with inotify or something.

**Comment by vctt94** [comment]
Yes @matheusd, I believe it is the same issue. I restarted my computer and now seems to work again. 

@alexlyp what I mean by hot reloading is refreshing the page and changes actually being made, how it works now. For changes to take place I needed to close decrediton and open it again.
