### ISSUE TITLE
Add an empty state for Statistics page as well

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1277]
We should hide the graphs on the statistics page until there is information to graph.

Also looks like the graphs aren't playing nicely with the expanding/reducing sidebar

**Comment by linnutee** [comment]
Preview: https://xd.adobe.com/view/865086b6-3db6-4273-bc22-779c0b15be85/
Specs: https://xd.adobe.com/spec/dd59ab80-f45d-4d38-86f2-a1c48f8ee464/

Icon: [stats-disabled.svg.zip](https://github.com/decred/decrediton/files/1844516/stats-disabled.svg.zip)
