### ISSUE TITLE
User was able to get into main UI prior to sync

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1295]
Unknown what may have caused this, but I'm guessing that they had a bad response for current block count so it didn't force a check and let them through.

This led to some odd issues when in the full app with rescan etc.  

Not sure on the potential solutions, but we should brainstorm

**Comment by matheusd** [comment]
Maybe the new grpc endpoint `BestBlock` could return (along with the hash/height the wallet has synchronized so far) the height the wallet is **trying** to sync to?

**Comment by jrick** [comment]
Oh, this is just the grpc call to the wallet?

In that case forget what I said.  The wallet would remain stuck at whatever last block it last exited with and then attach more once dcrd finishes creating cfilters, wallet connects, and catches up.

The semantics of BestBlock aren't going to change.  It is the best block that the wallet currently knows about and has processed up through.
