### ISSUE TITLE
Shutdown on Ubuntu 16.04 does not close dcrd and dcrwallet processes

### ISSUE THREAD

**Issue by karamble** [decred/decrediton#1299]
After i have closed decrediton i am not able to restart it, because daemons are allready running.

I have to `killall dcrd` and `killall dcrwallet` 

But after that the warning window still appears that a client is running in background.

Have to `killall decrediton` manually in order to fix it.

**Comment by matheusd** [comment]
No lock files. Is this on 1.1.3 or 1.2.0-rc1?

**Comment by karamble** [comment]
1.2.0-rc1

have to manually `killall decrediton`

**Comment by matheusd** [comment]
Did you have a previous install of the CLI there or was it a completely new install?

We just merged a fix for a situation where not having a previous dcrd.conf caused that, so that might be it.

**Comment by karamble** [comment]
I have a previous installation and the 1st launch of it was flawless, detected my mainnet wallet

**Comment by matheusd** [comment]
Right. Could you please check your ~/.dcrd dir and see if there's a `dcrd.conf` file created there?

**Comment by alexlyp** [comment]
@karamble are you still having this issue?

**Comment by alexlyp** [comment]
Closing due to age and no other reports of issues.
