### ISSUE TITLE
[charts] User requested that we try and use the system date format

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1308]
Not sure if it's possible, but a user requested that instead of defaulting to DD/MM/YYYY on graphs we attempt to determine what the system preference is and use that instead (if MM/DD/YYYY, for example).

**Comment by matheusd** [comment]
The localization of the date is actually working as if you notice, using the pt/br language for the app correctly uses the DD/MM/YYYY format, while using english it uses the MM/DD/YYYY format (see below screenshots).

![english](https://user-images.githubusercontent.com/1752493/38929181-e46a55b6-42e1-11e8-8bee-b03de291d64e.png)
![portuguese](https://user-images.githubusercontent.com/1752493/38929182-e491ab8e-42e1-11e8-8d77-00c7ebd83ed1.png)

User reported as using osX with australian locale.

The easier way to support this is to introduce a en/AU locale (english language, australian locale).

The more flexible way is to introduce a separate config option for time formatting that the user can customize (and that we'd default to the system settings if that can be grabbed during the node init).

I'll take a quick look at option one, as that is faster, easier and arguably more correct.

**Comment by alexlyp** [comment]
Nice, thanks for the quick rundown of the issue at hand.
