### ISSUE TITLE
[tickets] Properly updating agendas for their current state

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1316]
Currently, dcrwallet does not know the state of a running agenda.  It is simply using a dcrd dependency that pulls in the params that includes the running agenda information.  Due to this it is not able to provide decrediton with any basic information about whether an agenda is still currently voting or locked-in or activated/finished. 

Ideally, dcrwallet should be able to determine this information (which would then be easily provided to decrediton), but after extensive conversations with @davecgh and @jrick this is a very difficult issue to solve and would require significant protocol changes.  

So until that ideal fix is implemented, I would like to discuss our various options to solve this in decrediton.  

1) We just update the agendas to finished/locked-in etc when we release a new version (currently implemented this way, but yuck).
2) Implement a call to dcrwebapi that returns the current state of any agendas and the current/past results of the vote.
3) Implement an rpc call to dcrd that checks a given vote version for agendas and is able to determine status of the vote (but not easily be able to determine past vote results).

I'm leaning toward option 2, since we could also reuse that api call in various other places.  Let me know if you have any strong feelings one way our another.

**Comment by vctt94** [comment]
I believe 2 is achievable without much trouble, as we are already doing some external API requests and we already have proxy configuration for it.

We could also use some other implementation in case proxies are deactivated, but I think starting with 2 would be good.

**Comment by matheusd** [comment]
Agree for the moment on 2, though obviously this should be ideally from dcrwallet (considering the fact that with spv we'll only ever get stuff from it).

**Comment by oregonisaac** [comment]
I believe this error, reported on Telegram as "unclear" is due to the same issue.  It would be helpful if this error/notification was user readable to indicate the agenda state (as not yet active in this case)

![image](https://user-images.githubusercontent.com/4402603/54340789-5cef4700-45f5-11e9-9d08-c3ce27ad77e6.png)
