### ISSUE TITLE
Allow for graceful window resizing across various size groups

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#133]
Similar to bootstrap xs, sm, md, lg col grouping.  When width degrades past certain px range then re-render to accommodate new size

**Comment by alexlyp** [comment]
With the incoming refactor in #528 and the reintroduction of .css we should be able to accomodate 3 different media groups, tiny, medium and extra large.

**Comment by alexlyp** [comment]
@matheusd has done an initial pass for this issue, but we will still keep it open until we have done proper styling for the various sizes.

**Comment by vctt94** [comment]
This is being worked with responsive views
