### ISSUE TITLE
[config] Extraneous incomplete wallet created on first load of v1.2.0

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1330]
![screen shot 2018-04-26 at 20 26 14](https://user-images.githubusercontent.com/4388501/39325170-8386423a-495f-11e8-8041-6c57e6785e75.png)

Will try to gather more info and post here to determine what's going on

**Comment by teknico** [comment]
Same thing happened to me on upgrade. A `/home/USERNAME/.config/decrediton/wallets/mainnet/config.json` file was created, containing just `{}`. I deleted it and the spurious wallet disappeared.

**Comment by alexlyp** [comment]
Resolved in #1335
