### ISSUE TITLE
My Ticket - Detail Windows Missing Header

### ISSUE THREAD

**Issue by oregonisaac** [decred/decrediton#1332]
When navigating in My Tickets information in v1.2.0 and selecting a subsection (such as Live Tickets in the example image) there is no header information to let you know which screen you are in.  For example, if the attached screen said "Live Tickets" above the four tickets listed.  The mind likes the little confirmations that the mouse did what we think it did.
![example - live tickets screen](https://user-images.githubusercontent.com/4402603/39342948-2eb74fda-498f-11e8-8641-243894270f96.png)

**Comment by linnutee** [comment]
Fair point. I'll be addressing this soon and testing out a few approaches. Been intentionally avoiding building up repetitions in the past, but do see this being a minor usability issue since the amount of subpages has grown.
