### ISSUE TITLE
Initial Startup v1.2.0 - Recommend End User Instructive Message

### ISSUE THREAD

**Issue by oregonisaac** [decred/decrediton#1333]
Suggestion from Telegram user base that during the initial startup (RPC Daemon message time) a more user-friendly and user instructive message appear such as "Converting to High Speed Database, this may take a while the first time, please do not quit or shut down your PC"

**Comment by matheusd** [comment]
We don't have feedback from what dcrd is doing except from the log, which is fragile to parse to interpret and show a more specific message.

But I think it would be helpful to show the latest log line (for dcrd and dcrwallet) on the loading screen.
