### ISSUE TITLE
0 Balance Displayed in Account Overview

### ISSUE THREAD

**Issue by oregonisaac** [decred/decrediton#1334]
MacOS
Restored from seed into fresh 1.2.0 install
Was in 1.1.2 last

Everything displayed correctly, bought a few tickets, wallet left open for about 20 minutes, display of Account Overview changed to 0DCR from 42.2DCR...still correct balance shown in the default wallet and stake wallet (imported) when clicking in the bottom left, total balance also shows 0 in the bottom left
![zero balance](https://user-images.githubusercontent.com/4402603/39343900-38b64fe0-4994-11e8-8cf4-0f0cf1a1b789.png)

**Comment by matheusd** [comment]
After restarting decrediton, does the balance show correctly?

**Comment by nbenci** [comment]
Same thing here, 1.2.0, macOS. After rescan, total balance remains on 0 ( default & imported are showing correct balances ). 

After decrediton restart, total balance is shown correctly.
