### ISSUE TITLE
Wrong translation of labels pt_BR in the Overview tab

### ISSUE THREAD

**Issue by rramires** [decred/decrediton#1338]
![txt](https://user-images.githubusercontent.com/14129483/39368129-27beac02-4a0f-11e8-8713-74a2522b2b0e.jpg)

**Comment by matheusd** [comment]
grrrr, sorry for that. Will fix it.

**Comment by matheusd** [comment]
Let me know if you find any more translation problems.

**Comment by rramires** [comment]
Ok, thanks!
