### ISSUE TITLE
[launcher] Allow for middle-click seed paste from primary selection cache

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1342]
Currently middle-clicking in the Restore wallet from seed does nothing on Mac/Linux.  It would be preferable to be able to paste the previously selected text by middle clicking. 

After doing some research/testing, it is simple enough to capture the middle-click event from onMouseUp/Down but it does not seem like it's possible to get the Primary Selection value.  

I believe this value should be accessible somehow, since middle-clicking in other fields does properly paste as expected.

**Comment by vctt94** [comment]
I can work on this issue, but is there any reason for we do not use `crtl+v` for pasting? I believe it would be confusing pasting with middle-click.

**Comment by alexlyp** [comment]
We do use ctrl-v for pasting, but i'd like to support middle clicking for Linux/Mac users as well.
