### ISSUE TITLE
DB upgrade on initial use of Version 1.2

### ISSUE THREAD

**Issue by flintknap** [decred/decrediton#1347]
Recommend revising the message during the DB upgrade or adding an onscreen visual cue that the DB upgrade is occurring.  Repeated slack comments have demonstrated people are concerned there is a technical issue, but they (I) just needed a bit more patience.

**Comment by matheusd** [comment]
Done via #1340 
1.2.1 will show the last log line of the daemons on the stage where migrations happen.
