### ISSUE TITLE
Better handle fatal errors in dcrd/dcrwallet

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1354]
Currently, errors starting dcrd just show an alert message "dcrd closed due to an error".

We can improve that by sending the user to a specific page that shows the log, contact options and maybe a FAQ.

**Comment by alexlyp** [comment]
Our first pass implementation of this is complete.  We should discuss with @linutee about ways to implement a help/suggestion system that offers more of a robust solution set for the user.
