### ISSUE TITLE
Balance shows 0

### ISSUE THREAD

**Issue by vanjan** [decred/decrediton#1358]
<img width="278" alt="screen shot 2018-05-04 at 08 06 39" src="https://user-images.githubusercontent.com/130294/39614781-bcea62f4-4f72-11e8-8b3b-94aef058434c.png">

Initially the balance display is fine. At some point it switches to zero. Might be related to voting, as that changes balances, but I haven't noticed when exactly the error happens.

**Comment by matheusd** [comment]
This was fixed via #1336 in version 1.2.1. Please upgrade and see if it corrects the problem.
