### ISSUE TITLE
Confusing splashscreen for restoring keys

### ISSUE THREAD

**Issue by lte13** [decred/decrediton#1369]
If you do a fresh install of Decredition and want to restore your keys it is a bit confusing because you need to click "create new wallet" and then get a choice between creating a new wallet or restoring from a seed.

Suggestion: Have two buttons, create new wallet and restore from seed, and skip the step after "create new wallet".

**Comment by matheusd** [comment]
Thinking long term, I believe we'll still need a two step process as we'll have *many* options for creating/importing wallets:

- Create a wallet with a new seed
- Import an existing seed
- Import a masterpubkey for a watch only wallet
- Use a trezor hardware wallet
- Use a ledger hardware wallet
- ...?

But I agree we can improve the copy/UX of the process.

**Comment by linnutee** [comment]
Good notice. Regarding the current flow: the setup view displaying `Create New Wallet` and `Restore Wallets` should be only accessed after completing the onboarding. 

When navigating from the Launcher Overview, should send user directly to the selected setup choice. 

Quick flow diagram below: 

<img width="1403" alt="screen shot 2018-05-11 at 20 22 00" src="https://user-images.githubusercontent.com/17774057/39937695-30de34f6-5559-11e8-9fc2-36801e25aeda.png">

**Comment by lte13** [comment]
@linnutee Looks good, pretty much how I imagined it. 
@matheusd Maybe have 1) create wallet 2) import seed 3) import wallet? 

With descriptions like:

1) Create wallet - Create a new wallet with a new generated seed.
2) Import seed - Create a wallet from mnemonic seed.
3) Import wallet - Maybe just call it "import wallet" if its just from Trezor/Ledger. If you want to use a masterpubkey to import a watch-only wallet or other functions, then maybe change it to "more", "other choices", "more alternatives" or add another button number 4) called "more alternatives"?
