### ISSUE TITLE
[Adavanced mode] If dcrd lost peer when decrediton is syncing, it does not sync. 

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1377]
When on advanced mode, if try to connect on a remote daemon and dcrd lost its peers, decrediton stay as `Establishing RPC connection` even after dcrd connects to another peer.

**Comment by alexlyp** [comment]
Not sure I follow this, you mean dcrd doesn't sync?

**Comment by vctt94** [comment]
Dcrd connects to a new peer. Decrediton otherwise, does not sync and stay at launch screen showing `Establishing RPC connection`

**Comment by alexlyp** [comment]
I've still not been able to reproduce this issue, can you provide any other information about how to replicate?

**Comment by vctt94** [comment]
I can not reproduce this issue with the new startup. I will close this issue.
