### ISSUE TITLE
Implement updated Wallet Cards design

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1383]
Specs: https://xd.adobe.com/spec/ff91a336-c60d-4ad0-90c3-91780cf9082d/
Preview: https://xd.adobe.com/view/33dbd420-7478-48bc-9a36-6cfb4a230496/

Breakdown: 
- When the blockchain is still loading, the `Launch Now →` isn't displayed.
- When blockchain finishes loading, `Launch Now →`fades in (e.g. 130ms transition / quart type easing) 
- After fading in, the arrow (→) should begin an animated loop of doing a slight nudge/bounce to the right. 
(Example value: 130ms to change pos. in X +8px; 80ms return to original position w/ minimal bounce; 340 ms break; repeat). 
This should overall be something subtle like this, but is needed to have as a reminder where to launch a wallet from. 
- Clicking on the new `Edit Wallet` button displays the `Remove Wallet` and `Change Network` icons on all wallet cards as well `Cancel Changes`only on cards that are currently hovered over. Also changes Edit Wallet to a `Cancel` icon (also cancelling editing).
- Remove and Change Network open confirmation modals. 
- `Last Accessed` is only displayed on the currently selected wallet and when hovering on other wallets. 
- Also check Card States (https://xd.adobe.com/spec/ff91a336-c60d-4ad0-90c3-91780cf9082d/#screen/a7906e1f-2c29-423f-8f29-ca0c59ec8923/Card%20States) for updating the hovers a bit, currently not selected wallets have a blue outline when hover, should be grey. 

![dcr_launcher_animation](https://user-images.githubusercontent.com/17774057/39937218-b41ef7a8-5557-11e8-938c-203482e2cbad.gif)

Nb! Edit icon is currently a placeholder, will follow-up soon with another issue to several icons as a group.

**Comment by alexlyp** [comment]
Not sure I follow the change network buttons, why/how would you change a wallet to a different network?

**Comment by alexlyp** [comment]
What about connecting to a remote daemon (advanced daemon settings) ?

Currently, the user needs to select the wallet before reaching that form.
