### ISSUE TITLE
Immature stake generation incorrectly classified as available in overview.

### ISSUE THREAD

**Issue by dnldd** [decred/decrediton#1386]
Noticed the overview graph and bar tooltip currently show immature stake generation as available right after a ticket votes.  
<img width="72" alt="immature-stakegen" src="https://user-images.githubusercontent.com/1281030/39991564-84bf1d62-575f-11e8-88f9-06189ac1c261.png">

The funds locked by the ticket transitioned from `locked` to `available` immediately my ticket voted. The account page shows the correct output.

<img width="341" alt="actual-account-details" src="https://user-images.githubusercontent.com/1281030/39991911-98a8041e-5760-11e8-909e-230abfaf1b82.png">

I'm using Decrediton 1.2.1

**Comment by matheusd** [comment]
We've removed the immature balance from that initial screen. The immature amounts are currently (on latest master) appearing in the "tickets" charts (example on testnet):

![image](https://user-images.githubusercontent.com/1752493/40010934-a20b4ff4-577c-11e8-9570-6f2347f9081d.png)

@linnutee maybe we should drop the "immature" balance from here, as it is double counting the ticket purchases?

The underlying data source should be fixed to account for the immature stake generation though.
