### ISSUE TITLE
Visual fix: Overview – Recent Tx and Tickets layouts

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1394]
Specs: https://xd.adobe.com/spec/618ab30b-a553-4f7e-926c-f1aa4cd394b8/
Preview: https://xd.adobe.com/view/5c2f092d-3262-46cb-8e7c-3834fa9a9673/

These smaller transaction and ticket row layouts are a bit broken. Rough pointers:
- Recent TX rows should have the icon and amount optically centred to the card; date and time aligned to the fonts baseline of amount.
- For Pending tx, the Pending text (showed instead of date) should keep the same padding with the right edge, but only change position to left to consider the size of "…"
- The triangle at the right end of cards can be removed. 
- The ticket cards display the changes of ticket's states and should show the appropriate status as it's `Title`. E.g. "Purchased" "Live" "Voted" "Revoked" "Missed". 
- Tickets: Small icons should be updated, included in attachment. 
- Tickets: Row alignment otherwise the same as Transactions.

[Recent Items - Icons.zip](https://github.com/decred/decrediton/files/2005365/Recent.Items.-.Icons.zip)

**Comment by alexlyp** [comment]
Hmmm is that stake reward icon correct?  Looks like a little face or something.

**Comment by alexlyp** [comment]
Also, what's the difference between Live and Purchased?

**Comment by linnutee** [comment]
Yep, treasure chest motif.

**Comment by alexlyp** [comment]
Can you guys make some tweaks to that icon?  I've polled a few people in the office and it reads as a smiley face rather than a treasure chest.  Thanks
