### ISSUE TITLE
White screen in Tickets -> Stakepool settings after url is deleted

### ISSUE THREAD

**Issue by nbenci** [decred/decrediton#1401]
Decrediton 1.2.1
maOS 10.13.2

To replicate:

1. Navigate to Tickets
2. Click on Stakepool settings button ( above 'Manually import a redeem script' button )
3. Click on Stakepool management button ( Lifebelt icon )
4. Click on 'Add Stakepool'
5. Click on stakepool URLs dropdown to get blinking cursor inside of that field 
6. Press delete key on Mac
7. White screen will appear, Decrediton restart is required to gain back its functionality.

**Comment by alexlyp** [comment]
Nice catch, I'll patch it. Thanks
