### ISSUE TITLE
Improve copy on 'Learn the Basics' pages

### ISSUE THREAD

**Issue by heyvj** [decred/decrediton#1402]
When starting Decrediton for the first time and also if you click on "Learn the Basics" anytime afterwards, you are taken through a series of pages/slides with the following titles:

What is the Decred Blockchain?
What is a Wallet?
Key to Your Wallet
Staking and Governance
Safety Tips

The copy (text) under each of these slides does not read as if written by a native English speaker - some sentences are clunky and unnatural and so could be made much clearer.

I am willing to put some time into re-writing this provided this is an important enough issue and that these slides will remain an important aspect of Decredition for a significant duration of time to come. 

If the feedback in the next few days is that yes this is the case, I will make a start on redoing copy. Please let me know what you think.

**Comment by RichardRed0x** [comment]
If the slides will be used long-term, this looks like a good project. I would contribute.

**Comment by alexlyp** [comment]
I'm kinda meh about re-writing the whole thing, but I'm open to suggestions on wording fixes.  Can you provide some examples of improvements?

**Comment by linnutee** [comment]
The onboarding slides are getting short animations made based on the topics. These are half-way done. The whole thing shouldn't be re-written, but rather simplified or shortened where it makes sense. Also should keep in mind that the key points of each slide would be still clear and concentrated. 

Slide no 2 and 3, need to be merged into a single slide about Wallets in general. 

Not completely sure which version is currently live, so i'll include two recent updates I've got. 

First is a contribution by Dustin. Second pdf of Decred booklet, in which I included parts of the onboarding copy (e.g. Introduction page). I find that one to be one of the more refined copy bits so far as there was a lot of good input from the #writers-room 

[Decrediton Copy track changes - Mar 17, Dustin.pdf](https://github.com/decred/decrediton/files/2018457/Decrediton.Copy.track.changes.-.Mar.17.Dustin.pdf)

[dcr - booklet preview - DO NOT PRINT THIS FILE.pdf](https://github.com/decred/decrediton/files/2018454/dcr.-.booklet.preview.-.DO.NOT.PRINT.THIS.FILE.pdf)

**Comment by heyvj** [comment]
@alexlyp just a few examples of grammatical errors below. The clunkiness of the language could also be vastly improved.

"Wallet is the tool for interacting with the blockchain and using the currency. It can be used to send and receive Decred funds, and acts as a personal ledger of transactions.

Decrediton Wallet can also be used for participating in staking (PoS) and project governance by time-locking your funds in return for tickets."
> Should be "The Wallet" / "The Decrediton Wallet" in each case.

"Funds can be time-locked in return for tickets on the network. Tickets are chosen at random to vote on the validity of blocks. By average a ticket gets voted in 28 days" 
> Should be "On average..." rather than by

"Staking encourages long term investment in Decred by giving the stakeholders decision-making power in projects governance as well rewarding them for participation."
> Should be "by giving stakeholders decision-making power in **the** project's governance"

**Comment by heyvj** [comment]
@linnutee Thanks for that. Dustin's contributions fixed the grammatical errors I have highlighted in my reply to ay-p but it also introduces new typos and errors!

The copy in the booklet seems fine althought it doesn't cover some things - e.g. Wallets - which the onboarding covers.

So with all this taken into account, is there a structure to the onboarding flow you want me to follow? 

Ideally I'd like to approach this from the ground up and re-think the structure of the onboarding flow and work with you and kyle to get videos that fit with the structure we decide to go with. 
How far are you and kyle with the videos - is this a sensible way to proceed?

**Comment by linnutee** [comment]
Ground up approach isn't feasible as we're quite far with the animations and those two will need to be in sync. The main change in structure for animations was combination of no. 2 and 3 into a single slide about Wallets. Any copy improvements should account for that and in general be done in an iterative way focus on simplifing and refining the slides + concentrating better on the main points. 

Structure points:
**1) What is Decreds Blockchain**
- What’s blockchain in general, simple explanation
- How does it work, what is it’s functions 
- Touch point and introduce what's different about DCR here – the hybrid PoS/PoW, and what is it for

2) What is a Wallet
- How are they generated (living in blockchain)
- Importance of seed keys 
- About being a tool to interact with blockchain in x,y,z ways

3) Staking and Governance
- Follow-up on PoS (from first slide)
- How it works in general (seeing potential in this being simplified still) 
- What’s the different (three) different “voting” functions  
- What’s the governance about, why is it important
- Tie together; reason/motivation for participation

4) Security Tips
- See storyboard

[dcr - onboarding animations - storyboard drafts.pdf]
[dcr - onboarding animations - wip previews.zip](https://github.com/decred/decrediton/files/2023922/dcr.-.onboarding.animations.-.wip.previews.zip)

**Comment by vctt94** [comment]
fixed
