### ISSUE TITLE
[Restore Seed] Restore seed button is overlapped by seed words

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1407]
The restore wallet buttons for switching between words and hex is overlapped by the place for writting the seed words.

**Comment by alexlyp** [comment]
Can you provide a screenshot please?

**Comment by vctt94** [comment]
![restoreseedbug](https://user-images.githubusercontent.com/15069783/40316024-5c61f878-5cf3-11e8-9d24-75ec9df30e5b.png)

I will fix it on my pr for #1342

**Comment by linnutee** [comment]
Specs here if needed: https://xd.adobe.com/spec/f3d26fc1-dbc2-4a3a-9870-c0ac2ae59a8a/#screen/a4437426-f531-4ea2-9e92-0fd1f015fe61/Restore%20Wallet%201
