### ISSUE TITLE
Visuals Fix: Statistics subpage layouts

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1409]
Specs: https://xd.adobe.com/spec/97657dd4-1305-45b3-4d09-2d99868d9404-e154/
Preview: https://xd.adobe.com/view/91442776-3228-430a-4adc-5d2abee0fa30-e775/

The scope of this issue is only the Statistics subpage general layout, how the 3rd level navigation between different stats is handled and the icons. I will make another issue specifically for charts designs. 

Also @alexlyp, thoughts on Stakepool stats (what currently lives under Purchase Tickets), moving it under Statistics subpage? 

<img width="803" alt="screen shot 2018-05-21 at 22 28 12" src="https://user-images.githubusercontent.com/17774057/40325974-5c9a9c0c-5d46-11e8-85ed-7923f993dff6.png">

Icons: [decrediton - statistics icons - 210518.zip](https://github.com/decred/decrediton/files/2023808/decrediton.-.statistics.icons.-.210518.zip)

**Comment by alexlyp** [comment]
Yah I'm okay with that, it's a bit odd where it currently is

**Comment by alexlyp** [comment]
@linnutee where should the stake info data go in the statistics subpage?  The first graph you have listed there is for stakepool data, not an individual wallets information.

**Comment by alexlyp** [comment]
Also, i'm not sure that a pie chart really makes sense for the stakepool data.  Typically you'll see huge portions for voted, live and immature, then tiny slivers for missed, expired etc.
