### ISSUE TITLE
[Launcher] Suggest delete blockchain when resource is unavailable 

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1414]
When starting decrediton on non advanced mode, with an instance of dcrd running, it will suggest for delete the blockchain data for fixing the problem.

![decreditonsuggestsolutionbug](https://user-images.githubusercontent.com/15069783/40435766-c83ee318-5e87-11e8-87e3-bc393d860fd5.png)

it should not.

**Comment by alexlyp** [comment]
Fix this in a separate PR please.  Typically, it's best to keep PRs more focused.  1 issue per.
