### ISSUE TITLE
Fix Buffer() deprecated node 10 warnings

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1421]
Biggest offender (in line count) is the generated grpc code.

There are some libraries also using this code, so it will be quite a job to track down each one, open issues upstream, wait for them to be fixed, merged and released then update the dependency.

As a start, we should list the offending libraries here to track down exactly each one with a problem.

**Comment by alexlyp** [comment]
Thanks for opening this issue.  Hopefully most libs will be making the updates soon.

**Comment by matheusd** [comment]
See https://github.com/grpc/grpc-node/issues/670 for grpc.

**Comment by vctt94** [comment]
fixed
