### ISSUE TITLE
Color Fix: #091440

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1423]
In part of consistency update, dcr color palette was updated. Most common inconsistency seems around the darkest blue/black, which should be only #091440 everywhere. 

Replace all instances of `#000000`, `#0C1E3E`, `#152337``#09182D`, `#08172E` with `#091440 `. 

If there's any other really dark blues or almost black color values in use, can post here for review (value and screenshot where). Overall `#091440` should be the darkest color used with the next value being `#3D5873`

**Comment by alexlyp** [comment]
So this change is fine, but on your recent Spec sheets you were still using `#0C1E3E` throughout.  
https://xd.adobe.com/spec/97657dd4-1305-45b3-4d09-2d99868d9404-e154/

**Comment by alexlyp** [comment]
I'll start finding and replacing all

**Comment by linnutee** [comment]
Yeah can ignore that, i'll make a notice of it if occurs in the specs. In process of clearing out the master files, unfortunately there's no proper global colors feature in xd, so got a good load of manual grinding to do :E  

I'll be exporting another set of icons as well to get it cleared.

**Comment by alexlyp** [comment]
Awesome thanks.
