### ISSUE TITLE
Error: Unable to purchase tickets- message box disappears too quickly to read

### ISSUE THREAD

**Issue by jesiki** [decred/decrediton#1428]
When trying to purchase a ticket, I get the error message stating "unable to purchase tickets." The message box has a lot of text but does not stay up long enough for me to read it all. It disappears after roughly three seconds. I'd like it to stay up longer.

**Comment by Jasminrice** [comment]
I think I have been having the same issue 
The message I get is 
Unable to purchase tickets : failed to send split transaction:-1
Rejected transaction 
Then tx ID
Orphan transaction 
Same tx ID
references outputs of unknown fully spent transaction 
Different tx ID 
Any help would be appreciated
