### ISSUE TITLE
Visual Design Implementation: Charts

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1437]
Preview: https://xd.adobe.com/view/d0fc4838-3ecc-43ac-7af2-0a2057f37189-a6cd/
Specs: https://xd.adobe.com/spec/2945c19e-ed9d-4d5a-5ee1-37fc3fae3078-5f74/

Collected the new charts designs for Statistics subpage. 

**Stakepool** – horizontal meter-bar chart, displaying to comparisons on each bar. 
Visual design contains 100 strokes, each representing 1%. Coloring of the strokes should be evened to the closest full number.

**ROI** – linechart, displaying the change of ROI % horizontally and months vertically. The line endings should be defined w/ circles at the end of the chart area, so the lines wouldn't be cut off at the edges. 

**Vote Time** – scatterplot, vertically counting for days till voted, horizontally months. Ideally this should draw trendlines that represent average vote times by a timeframe, or how possible in the chart framework (if drawing through each circle, can be straight lines that end up connecting them; if drawn over the chart, should be curved lines, i'll design an example then).

**Ticket Activity** Horizontal barcharts and heatmap. Heatmap being similar to gh contribution counter. Should mark down every ticket related activity, 1st (light) blue = 1x, 2nd blue = 2x, 3rd blue = 3x, 4th (darkest) blue = 4x+ actions per day.

**Comment by vctt94** [comment]
I will work on the ticket activity chart

**Comment by alexlyp** [comment]
Awesome, make sure to review any Visual Design issues to see if there have been updates since this one is quite old.

**Comment by vctt94** [comment]
sure, will do. As this part is not yet implemented, I think it did not change, but I'll double check with the new responsive views @MariaPleshkova is adding.

**Comment by linnutee** [comment]
Nice, just mentioning no updates regarding this. Should be fairly easy top-down re-arrangement regarding responsive views and likely not require any adaptations.
