### ISSUE TITLE
Prompt for possible API key on wallet restore.

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#1442]
To avoid potential balance issues and the associated freak-outs it would be handy to prompt the user to input the API key from their stakepool if they have one during the wallet restore process.
E.g., "If you are staking Decred please enter the API key provided by your stakepool so your balance is displayed correctly."

**Comment by xaur** [comment]
Multiple API keys. Great idea.

Perhaps also worth prompting for redeem scripts on wallet restore in dcrwallet?

**Comment by jholdstock** [comment]
Love this idea @jzbz. I had a mini freak-out myself the first time this happened to me!

**Comment by matheusd** [comment]
Already implemented via #1410.
