### ISSUE TITLE
Potentially misleading text on Welcome page

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1443]
![chain-downloading](https://user-images.githubusercontent.com/6762864/40886269-8ac352c8-672c-11e8-8c8a-697108856426.png)

This page is shown to all users when Decrediton is first opened, regardless of whether they wish to create a new wallet or if they wish to restore a wallet from seed. The text which says "New Wallet Name" and button "Create New Wallet" may give the impression that restoring from seed is not possible.

Suggestion:
- Update text `New Wallet Name` to `Wallet Name`
- Update button `Create New Wallet` to `Continue`

**Comment by linnutee** [comment]
Not sure if this might be updated already, but leaving the flow chart for reference. 
Figured the Wallet name would be in each generation view (create or restore) with the passwords and such. 

If the name needs to be entered beforehand, i'll need to make another view to cover the name entry for this first time as well update the overview flow as suggested. 

<img width="1754" alt="screen shot 2018-06-03 at 19 57 13" src="https://user-images.githubusercontent.com/17774057/40889043-a68fc1ee-6768-11e8-8880-41995cacb0af.png">

**Comment by alexlyp** [comment]
Yah I need to have wallet name screen previous to the create new/restore screens.  Basically it causes a huge headache in the background if we do a different flow for the wallet name.
