### ISSUE TITLE
-r is not a valid option

### ISSUE THREAD

**Issue by hunjixin** [decred/decrediton#1465]
error bellow occurs after run command ‘yarn start dev’

···

decrediton@1.2.1 start-hot D:\project\decrediton
cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development
-r is not a valid option!
-r is not a valid option!
./app/main.development is not a valid option!
-r is not a valid option!
-r is not a valid option!
./app/main.development is not a valid option!
-r is not a valid option!
-r is not a valid option!
···

**Comment by alexlyp** [comment]
not an error
