### ISSUE TITLE
Visual Fix: Seed Key entry (!)

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1477]
Preview: https://xd.adobe.com/view/c2a7081a-6d95-4986-7db4-f20c589da54f-b496/
Specs: https://xd.adobe.com/spec/813e0369-b7fa-45d1-61d1-75504c4d29fa-f70f/

There's a couple visual issues around the seed key entry.

<img width="1301" alt="screen shot 2018-06-15 at 19 22 34" src="https://user-images.githubusercontent.com/17774057/41479419-c11f09ce-70d3-11e8-9b94-a94e925b1a3c.png">

1 Most critical is the amount of rows and columns, which currently is changing in the views and isn't correctly displayed. 

Seed keys should always display in **5 columns and 7 rows**. This way the 33 words are housed in the optimal manner as well copy-to-seed key can be fit next to them. Should be all the both Restore and Create Wallet, Confirming seed key listings. 

2 The spacing between the fields and seed keys should be updated to match the visual design, currently there's quite big amounts of space in between.

3 Confirm Password entry renamed to: `Repeat Private Password` infield: `Confirm Password Entry`

4 Remove pre-triggered warning from password entry 

5 Change color #ff0000 in seed entry boxes to the defined colours 

**Nb!** Do not use color #0C1E3E anywhere, only #091440.

**Comment by alexlyp** [comment]
Can you clarify where you are seeing #ff0000 in seed entry boxes?  not seeing that one
