### ISSUE TITLE
.mp4 file update: Motion Blur enhancement fix to scene 1

### ISSUE THREAD

**Issue by kyleFirethought** [decred/decrediton#1488]
https://github.com/matheusd/decred-weekly-builds/releases/tag/v20180514165803

After reviewing the onboarding video content for all scenes have been updated with a few cosmetic enhancements, noteably light motion blur. **This effects all scenes 1-4**

There is also a slight issue with scene 1 not looping correctly,  this has been fixed in the most recent version available in the shared directory: https://drive.google.com/drive/folders/18lHNfTnKJbSfBVzKx0X127fU_103JKpb?usp=sharing

Other than that no other issues seen in the Dev Build.  Tested: Manjaro KDE Edition (17.1.10)

**Comment by matheusd** [comment]
Yeah, @heyvj was working on the copy for the animation slides, so I was waiting for that before going for another round of updates. Will close this one along with #1483 and #1402

**Comment by kyleFirethought** [comment]
Nice one, thanks for the update @matheusd!

**Comment by heyvj** [comment]
Hey @matheusd the updated copy is here: https://github.com/decred/decrediton/issues/1483
