### ISSUE TITLE
Visual Design: Implement Installer

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1497]
Addressed the visual design for Installer. Use the native Mac OS application icon. Posting the updated Decreditons icon in a follow-up issue. 

Preview: https://xd.adobe.com/view/044a39e3-1256-4779-41e9-9362e821dbb8-727b/
Specs: https://xd.adobe.com/spec/19ff2338-2d69-4c01-5dd3-0b104d4b846e-6fce/

[decreditonInstallerArrow.svg.zip](https://github.com/decred/decrediton/files/2138847/decreditonInstallerArrow.svg.zip)

**Comment by Jujhar** [comment]
Does this still need to be done?

**Comment by alexlyp** [comment]
believe it has been completed.  closing

**Comment by alexlyp** [comment]
Well no, the arrow has not been implemented.   Go ahead @Jujhar  if you think you know how.

**Comment by Jujhar** [comment]
OK

**Comment by vctt94** [comment]
Is this still an issue?

**Comment by linnutee** [comment]
Yep

**Comment by vctt94** [comment]
Closing as #2169 was merged
