### ISSUE TITLE
Visual Design: Fields and Dropdowns fixes and updates

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1504]
Specs: https://xd.adobe.com/spec/1c4345df-59aa-4dca-595d-0f82e91ecbaa-6a72/
Preview: https://xd.adobe.com/view/ac103d86-9c42-4bd4-6feb-cd0660c8ddc7-da21/

Alright, this has been a lower priority item in my list for a while. Since the overhaul back in November, some of the fields are partial or slightly off. 

Fixes: 
- Input B with double-sized DCR amounts should be implemented and added to Send view. 
- Some of the default states info copy has an wrong color value #767676 
- Dropdown fields and dropdown context menus have mixed up the round edges. All of the field dropdowns should have square edges and context menus (e.g. filters in history) with rounded edge and a triangular pointer near the button. 
- Use of Inactive and Filled fields may be slightly confusing. I'm not sure whether there is even a need for Disabled field right now, as for Sending a transaction and Purchase Tickets settings could simply used Filled fields? @ay-p thoughts? 

Updates: 
- Updated the color values for some states to improve contrast for the info bits and get things more consistent in general. 
- Removed all Semi-Bold and Bold type styles and use of Inconsolata. 
- Added a missing checkmark for context menus. 
- Changed shadow colour to #091440 through-out. 

[checkMarkContextMenu.svg.zip](https://github.com/decred/decrediton/files/2142637/checkMarkContextMenu.svg.zip)

<img width="1131" alt="screen shot 2018-06-27 at 22 22 15" src="https://user-images.githubusercontent.com/17774057/41995378-2fafd578-7a5a-11e8-9317-f8bc42b6e63d.png">

**Comment by alexlyp** [comment]
I'm going to open another issue that will handle the Input B implementation.  It'll be kinda involved to get correct since there will need to be active value checking like Balance currently does to separate into various sizes/colors while the user is entering data.

**Comment by xaur** [comment]
On the pic, do amounts in parens denote negative amounts?

**Comment by alexlyp** [comment]
No they don't, and I suppose that's an issue for us to handle.  

Thoughts @linnutee?   I think we could just remove the parenthesis and the same information would be given without any loss of design.
