### ISSUE TITLE
Visual Design: Grouped minor fixes

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1508]
I've grouped a number of minor fixes together in this single issue. These are through-out Decrediton and Launcher. 

Preview: https://xd.adobe.com/view/da6fa83c-ddaa-4fab-77aa-3812ccf6395f-ac5e/
Specs: https://xd.adobe.com/spec/65fd055f-6015-4ba7-6230-b6dd27cdc020-13cc/

1. In Overview, the tabs Balance - Transactions - Tickets. 
Update both colours of selected text and its border to #3D5873, as well the hover state. 

2. In Tickets/Governance view, the radio button style seems to have gone missing. 

3. Security Center tab has a 1 pixel error in the middle and uses a dated tab styling. Should be opposite as the metaphor is more like a switch there, which ties the active part together with the white content box. I'll update this on dcrweb also. 

4. Settings/Privacy checkbox's checkmarks are off from optical centre. Infotext is with italic. 

5. Gap limit has some issues with the typographic styling. While in most instances I try to root aligning the numerations and bullet points outside of the text field for better optics, in this instance i've left them inside the normal copy area due to the small amount of space. May be the cause of the odd rendering. So the text should be laid out in two uniform paragraphs there. Also Warning is without bold and with orange colour. 

6. Logs and System Logs in launcher are repeating. May be due to interference with logs placed in Settings?

7. Settings/Tutorials would look better with shorter rows, same as used in Overview. If they are shorter, we can create a better layout with two columns once more items get added.

**Comment by alexlyp** [comment]
Can you show me a screen shot of the missing radio buttons?  I see them fine on my end.
