### ISSUE TITLE
GetTransactionsAttempt is causing slowness on large wallet

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#151]
as reported by @jcvernaleo:

When using a large wallet, when any calls to getTransactionsAttempt occur the wallet gets noticeable slow.  Should be fixed when pagination is added, but we may need to audit the data structure for transactions and see if there are any simple fixes

**Comment by jcvernaleo** [comment]
Are this and #197 dupes?  I kind of think so (in which case we could close this one since the other has more info).

**Comment by alexlyp** [comment]
doh yah oops.  i'll close this one
