### ISSUE TITLE
[inputs] Implement amount design as specified in the docs

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1511]
Specs: https://xd.adobe.com/spec/1c4345df-59aa-4dca-595d-0f82e91ecbaa-6a72/

The Input B specifications need to be implemented for the send page amount input (and possibly other places as well.)  

This is a bit more than just a styling change due to needing to parse and change the input actively while the user is entering in the information.  And I'm not 100% that it can be done.  I'm not aware of a way to split apart portions of an input to which some will get differing styling.

**Comment by Jujhar** [comment]
Started working on this.

**Comment by alexlyp** [comment]
OK, let me know if you have any questions.

**Comment by alexlyp** [comment]
Just to confirm it should look like this for input amounts (on send page):
(sending 0.12345678)
0.12 would be large then 345678 would appear at the lower font size

**Comment by Jujhar** [comment]
OK great
