### ISSUE TITLE
Visual Design: Update Accounts view

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1519]
Specs: https://xd.adobe.com/spec/f8dd8a32-a806-4a3c-62e8-31be79ab97f2-8eec/
Preview: https://xd.adobe.com/view/7ef5a74f-c73b-491d-7375-f4c1f45a6706-08c4/

In relation to #1518 applied a few updates to the Accounts view, as that's been changed over time. 

- Removed inconsolata
- Color color consistency and contrast updates 
- Re-aligned the Balances and Properties accordingly to the card 
- Updated Rename and Hide account buttons
- Added a background layer to the opened panel. 
- Immature Stake Generation renamed to Immature Stake Gen. shorthand to fit bette.r 

Ps! Still reminding, no use of #0C1E3E, only #091440

**Comment by alexlyp** [comment]
Not sure what you're referring to with the #0C1E3E, there are no more references to that color in the code anymore.  Only from icons that have yet to be updated.

**Comment by alexlyp** [comment]
Do you have the new rename and hide icons? I only have those in blue currently.  Thanks!

**Comment by linnutee** [comment]
Adding just incase, did save them out but forgot to attach: 

[decrediton - icons - 300618.zip](https://github.com/decred/decrediton/files/2160922/decrediton.-.icons.-.300618.zip)

**Comment by alexlyp** [comment]
Do you have a spec for the "rename" accounts form that appears after the button is clicked?

**Comment by alexlyp** [comment]
@linnutee do you have the eye open icon as well, there was only hideWhite in the above zip. thanks!

**Comment by linnutee** [comment]
Added to zip: [eyeOpenWhite.svg.zip](https://github.com/decred/decrediton/files/2167626/eyeOpenWhite.svg.zip)


<img width="329" alt="screen shot 2018-07-05 at 20 39 21" src="https://user-images.githubusercontent.com/17774057/42338746-87d2fd9a-8093-11e8-9c8c-eccc74fd8b5e.png">
