### ISSUE TITLE
Add close wallet action

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1551]
Add an action (maybe in the main sidebar?) to close the current wallet, return to the wallet selection screen and allow the user to open or create a different wallet.

This might be slightly tricky as we need to close the dcrwallet process and all connections, and all the UI code assumes that once the wallet is loaded it won't change.

Might wanna hold off implementing this only after spv hits, since this will further change things.

**Comment by alexlyp** [comment]
Ah very cool.  Yah I've been thinking we should do something like this.  

And agree we should avoid this til after 1.3.0 hits so we can settle some of the lingering issues with SPV and any other regressions that have come along with basic wallet operation.
