### ISSUE TITLE
Hi, trying to figure out why my ticket still hasnt voted after 1m18days!!!

### ISSUE THREAD

**Issue by daveberns** [decred/decrediton#1553]
Simply trying to figure out if this was due to something i did (user error)?

Or whether it was bad luck?

Any insight into what determines the length of time that a live ticket is chosen to vote would be very helpful!

Sorry for posting this on github..... =)

Thanks!!

**Comment by matheusd** [comment]
This is totally normal. 

You can see details about the ticket's lifecycle (including maximum possible voting time) here: https://docs.decred.org/mining/proof-of-stake/#ticket-lifecycle
