### ISSUE TITLE
can not Compile on win7

### ISSUE THREAD

**Issue by zhaoyulong1** [decred/decrediton#1562]
![r vfo8e 21sr2r7aigq mbo](https://user-images.githubusercontent.com/13092764/43378056-ec6d95be-93f6-11e8-927b-eb7a85099e80.png)

**Comment by zhaoyulong1** [comment]
when run 
    npm run package

**Comment by alexlyp** [comment]
you should try with `yarn package`

**Comment by matheusd** [comment]
Seems he's trying to compile on a win32 vs win64. Are the builds working on win32 (I've only trying in 64).

**Comment by zhaoyulong1** [comment]
win32

**Comment by zhaoyulong1** [comment]
but my computer is x64 win7,why it's  show win 32

**Comment by zhaoyulong1** [comment]
i an in the China, ofen show 443 when       grpc-tools

**Comment by zhaoyulong1** [comment]
who can give me a good package?  thanks

**Comment by alexlyp** [comment]
package for what?

it works fine to be built if you use yarn.  follow the directions on the readme.
