### ISSUE TITLE
Visual Enhancement: Overview page

### ISSUE THREAD

**Issue by denyszayets** [decred/decrediton#1586]
I'd recommend changing this color to something a bit darker. It's barely visible on the white background. Perhaps into what we use for the date.
https://d.pr/i/3TIWCU

**Comment by linnutee** [comment]
This is already addressed in #1582.
If checking for design issues, best to reference the XD master files – whether the case matches up with the release or not. Recent ones are posted to /dcrdesign repo.

**Comment by denyszayets** [comment]
good, thanks
