### ISSUE TITLE
Something is off with changepasswordDefault.svg

### ISSUE THREAD

**Issue by StabbarN** [decred/decrediton#1590]
A white overlay appears on button "Update Private Passphrase", see screenshot below
<img width="1132" alt="changepassworddefault" src="https://user-images.githubusercontent.com/921390/44113643-099c5fb2-a009-11e8-8d03-a885b1b39e0e.png">

It's a bit random but takes less than a minute to reproduce. Just move around the mouse cursor and click on random places (for example checking and unchecking "Network information").

It seems that the file `app/style/icons/changepasswordDefault.svg` is errornous because when replacing `background: @change-password-default-icon no-repeat center;`
with `background: #00f no-repeat center;` I cannot reproduce it.

**Comment by matheusd** [comment]
Which OS are you using? I wasn't able to reproduce this in either linux or windows.

**Comment by StabbarN** [comment]
MacOS 10.13.6. It occurs in both dev mode and 1.3 release candidate.

**Comment by StabbarN** [comment]
I can't reproduce it anymore. Closing this issue until further notice.
