### ISSUE TITLE
Too Low Contrast in History of Transactions View When No Transactions

### ISSUE THREAD

**Issue by StabbarN** [decred/decrediton#1591]
I can barely see the text "No transactions found".
See 
<img width="1146" alt="poor contrast" src="https://user-images.githubusercontent.com/921390/44114397-5493cc38-a00b-11e8-8c15-5aaa8329a82d.png">

**Comment by cosmicvs** [comment]
Which scripting languages are you making use of

**Comment by Jujhar** [comment]
I can tackle this.

**Comment by alexlyp** [comment]
Duplicate of issue #1582
