### ISSUE TITLE
Tickets:My Tickets "Immature" not updating

### ISSUE THREAD

**Issue by hermanlim** [decred/decrediton#1598]
As per item 9 on https://docs.decred.org/mining/proof-of-stake/ tickets that have voted become immature for 256 blocks prior to release. 

The My Tickets pane in decrediton 1.3.0 RC (not running SPV mode)does not seem to show this. Rescanning had no effect.

**Comment by matheusd** [comment]
Yeah, that's how it currently works: the wallet reports immature tickets but not immature votes.
