### ISSUE TITLE
SPV Mode "Purchase Ticket" display error

### ISSUE THREAD

**Issue by gravityz3r0** [decred/decrediton#1599]
Decrediton 1.3.0 RC1
In SPV mode:

1. In "Purchase Ticket" option, the following stats are showing zero : 
Own Mempool Tickets:0 
Immature Tickets:0 
Live Tickets:0
All Mempool Tickets:0
Missed Tickets:0
Pool Size:0
Expired Tickets:0

Only Voted Tickets, Revoked Tickets & Total Rewards shows correctly.

2. However, all statistic shown in "My Tickets" tab is correct.
3. Re-importing script and re-scanning the chain does not fix this problem.
4. Everything in non-SPV mode shows correctly.

**Comment by matheusd** [comment]
Yeah, most of that information is currently unavailable in spv mode. Maybe we should not show it instead of showing 0?

**Comment by rramires** [comment]
Maybe the pool can provide via API when in SPV mode. Good or bad idea?

**Comment by alexlyp** [comment]
Well the pool doesn't provide stat infomation per user, only their own stats.

**Comment by rramires** [comment]
I thought about the existing information in the logged area:
![pool](https://user-images.githubusercontent.com/14129483/46554210-faf81c00-c8b5-11e8-8479-b52661e7806a.jpg)
I imagined creating a method by passing some parameter, such as voting address, or other thing to return this.
Whenever enter this screen, or some operation, like ticket purchase, call the method again.

**Comment by alexlyp** [comment]
It's not possible for a variety for reasons.  But mostly it's not possible currently to distinguish stake info by certain voting addresses.
