### ISSUE TITLE
New account shows balance as NaN

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1611]
After creating an account, it balances shows as NaN on the sidebar.

![bug](https://user-images.githubusercontent.com/15069783/44490337-81250f80-a634-11e8-9d6a-c7544619b6c1.png)

**Comment by codemaestro64** [comment]
Seems a call for balances returns an empty total that is then divided by 1000000. That causes the NaN error. 

possible fixes 
1. if total is empty, set to zero. this makes sense as newly created accounts will have a zero total

2. solve this at grpc level

**Comment by shweini** [comment]
Seems a call for balances returns an empty total that is then divided by 1000000. That causes the NaN error. 

possible fixes 
1. if total is empty, set to zero. this makes sense as newly created accounts will have a zero total

2. solve this at grpc level
