### ISSUE TITLE
Motion Design: Implement loader microanimations

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1612]
A small and pleasant improvement to the loader. Instead of the current two loading pieces, we're concentrating all of the loading items into the loading bar area. 

The post-blockchain loading tasks (Establishing RPC connection, Discovering Addresses, Scanning Blocks for Transactions etc) received individual microanimations that should be played one after another when the specific process is happening. Each tasks icon and copy are displayed inside the loader. Only state that has a static icon is during the time when the blockchain has been loaded but the wallet has not been launched yet. 

Regarding implementation, performance tests should be run whether gif/png sequence works the best here or json animations with the following library: https://github.com/airbnb/lottie-web 

Assets: [decrediton - loaders - microanimations.zip](https://github.com/decred/decrediton/files/2315129/decrediton.-.loaders.-.microanimations.zip)

Preview: 
<img width="1387" alt="screen shot 2018-08-23 at 18 28 37" src="https://user-images.githubusercontent.com/17774057/44535350-720c9300-a702-11e8-9cb0-3cf7806d622e.png">
![44208229-c094bd00-a157-11e8-8bb8-75ab75f2cb86](https://user-images.githubusercontent.com/17774057/44535383-88b2ea00-a702-11e8-9493-0a9017c4444a.gif)
<img width="1161" alt="screen shot 2018-08-23 at 18 17 48" src="https://user-images.githubusercontent.com/17774057/44535355-75078380-a702-11e8-9506-e25049e7b463.png">

Thanks to @kyleFirethought for the motion work.

**Comment by alexlyp** [comment]
Animations look great!

I've attempted to implement lottie through a helper package: https://github.com/chenqingspring/react-lottie  
Seems to work well enough, but unfortunately lottie uses an eval(), which trips our current ban on eval usage.  Apparently, lottie_light.js doesn't make sure of eval, but only allows svg renders (which we use) and "expressions".  I'm not clear on what they mean by an expression, or how to force usage of the lottie_light with react-lottie.  I'm going to leave this issue open to further discuss lottie.  But for now I'll be completing this issue using the provided fallbacks.

**Comment by kyleFirethought** [comment]
[decrediton.-.loaders.-.microanimations.zip](https://github.com/decred/decrediton/files/2326084/decrediton.-.loaders.-.microanimations.zip)
Awesome! Understandable eval = evil (AE's JSON parser uses eval and it is a tremendous ballache to work with).  As it's clearer that the fallbacks will probably be used in the next revision I've attached (within the GIF folder) a 2nd version of GIFs without the alpha channel and instead the solid #cccccc background.  This should provide on par performance with the PNG without the size overheads and anti-aliasing issues associated with GIF.  The obvious downside to this is that the GIFs labelled "no_alpha" can only be used with the corresponding #cccccc background. If you have any requests or issues fire over a message and I'll get you a fix over promptly.  Re: Expressions this refers to After Effects's expression system and Lotties support for this to influence objects in the renderer... Some of the animated pieces included rely on this in a basic capacity ie: loopOut(); and any parenting links transform.position[0.0.0];

**Comment by linnutee** [comment]
Currently got it planned with all smaller animations to make them optimized for exporting to both json/lottie and image sequence or gif. This @2x .png sequence is probably most optimal for icon microanimations, json/lottie may be bit overkill.  

Though I do think it would be relevant to further investigate about eval case https://github.com/chenqingspring/react-lottie/issues? If there's any possibility to use the json ones for bit more complex animations would be far superior result to img seqs/gifs.
