### ISSUE TITLE
Update Decrediton text to use Voting terms instead of "Mining" wrt PoS

### ISSUE THREAD

**Issue by RichardRed0x** [decred/decrediton#1615]
So far I have only seen words that obviously need replacing in the Learn the basics pages.

Here's some suggested wordings. There are other minor improvements (some typos, some subjective) in these suggested texts. Might be easier to review these suggestions as a PR?

p1: Decred uses an innovative hybrid of proof-of-work (PoW) mining and proof-of-stake (PoS) voting for validating the transactions, keeping the network secure and making decisions on the consensus rules.
In return for participation, miners (PoW) and voters (PoS) are rewarded with newly generated Decred tokens.

P2:  The Decrediton Wallet can also be used for participating in voting (PoS) and project governance by time-locking your funds in return for tickets. 

P4 left:
Participation in voting (PoS) requires only existing Decred funds. (Unlike Proof-of-Work (PoW) mining that requires computing resources and electricity).
Funds can be time-locked in return for tickets on the network. Tickets are chosen at random to vote on the validity of blocks. By average a ticket gets voted in 28 days(possible maximum time period is 142 days). A successful vote returns the stakeholder a part of the Block Reward plus the original cost of the ticket. In case of not being called to vote(0.5% probability), the original cost of the ticket is safely returned to the user without the reward.

P4 right:
Changes are inevitable for all digital currencies, whether deciding on development matters or resolving unexpected problems. Decred’s innovative governance system is built into the blockchain. This allows for seamless adaption while keeping the existing blockchain ecosystem safe and un-forked. The same tickets are also used as voting power when deciding on consensus changes.
Staking encourages long term investment in Decred by giving the stakeholders decision-making power in the project's governance as well rewarding them for participation.

**Comment by RichardRed0x** [comment]
Stake Pool on the Tickets page should become "Voting Service Provider".
Ticket Lifecycle page in help refers to Staking, should be Voting

**Comment by linnutee** [comment]
Not sure how this came up, but in case there's a wider agreement to change the proof-of-stake terms, then this needs be done in a  coordinated manner through-out all instances in the more important platforms(not only Decrediton) and with some accompanying communications giving notice of it. Otherwise one at a time can cause a lot of confusion, as staking is rather deeply rooted, through use of Stakey and such. 

Atm there's bigger design updates in the pipeline for stakepools theme, so that's definitely an important other end to cover.

**Comment by RichardRed0x** [comment]
Based on reddit and slack discussions, it seemed like there was broad agreement for this change in terms. However, if there is any doubt we should perhaps wait and put it to a vote on Politeia.
This PR about decrediton go along with a similar language change on docs.decred.org.
Maybe we should make a list of other places where language would need to be updated?
Decred.org is a fairly major one.

**Comment by s-ben** [comment]
Per will of the Stakey (approved [Politeia proposal](https://proposals.decred.org/proposals/522652954ea7998f3fca95b9c4ca8907820eb785877dcf7fba92307131818c75)), we shall change the words we use to refer to:

- Proof of Stake "mining" to "voting"
- "Stakepools" to "Voting Service Providers" (VSPs)

As stated in the proposal, ideally we want to change terminology in numerous places, including Decrediton and dcrdocs, among others, at around the same time. Just thought I'd get the ball rolling here again. Would it be difficult to get a PR for this in the next minor release?

**Comment by alexlyp** [comment]
Nope I can totally kick off a PR whenever you guys want me too.  Pretty simple change

**Comment by s-ben** [comment]
@alexlyp , if you can get a PR locked and loaded, that would be great. My plan: I'm reaching out to the other repos that still need to implement this change (dcrweb, dcrdata, stakepools). My idea is to get the change ready to go in as many PRs as possible before flipping the switch, to avoid confusion from using different terms different places.

**Comment by jholdstock** [comment]
Unexpected consequence of updating terminology "Stakepool" to "Voting Service Provider". The logo we use for Stakepool in many places is an inflatable pool ring: https://docs.decred.org/img/dcr-icons/Pool.svg
This logo doesn't make much sense with the new name VSP
