### ISSUE TITLE
[Overview] Duplicated information at stake transactions

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1622]
On the overview stake transactions, there are some duplicated information about tickets, because they were supposed to show as purchased and voted, but when a ticket is voted, both transactions show as voted.

Image Showing the same information twice: 
![decreditonbuggy](https://user-images.githubusercontent.com/15069783/44747129-c0df7180-aae2-11e8-8c61-7422d78251aa.jpg)

**Comment by linnutee** [comment]
Adding a few broader UX points around tickets as whole. 

**History / My Tickets**
At the moment the tickets are shown as duplicates in both Transactions/History tab and Tickets/My Tickets view. The design idea behind My Tickets was to only display the tickets there and that way clear out the History view and reserve it only for Sent/Received and Ticket Fee Transactions. Also referring to this old issue here: https://github.com/decred/decrediton/issues/950

<img width="1779" alt="screen shot 2018-09-05 at 18 41 09" src="https://user-images.githubusercontent.com/17774057/45105085-30d1a580-b13c-11e8-9d86-1ab75d492820.png">

**Overview – Recent Staking Activity**
Unlike the My Tickets view, Recent Staking activity was intended to only display the changes in Ticket States e.g. switching from live to voted. Not sure if it does that, noticed also the terms and icons don't add up there. 

**Current state name and icon**
I think it would be logical and help to clear things out if in all instances the tickets only display the current given state and it's relevant icon. In addition to that, can look into visualizing the ticket lifecycle view as a schematic within the details view.
