### ISSUE TITLE
[Selectors] Refactor isWatchingOnly and isWatchOnly

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1626]
On the selectors there are these two methods which one is used when creating a watching only wallet and the other when opening a watching only wallet. We can refactor these two so they have the same name using the method `or` from the fp. 

also, we can discuss about having a standardized method naming to the selectors and refactor all of them so we can improve readability.

**Comment by alexlyp** [comment]
Thanks for opening this issue.  

I'm totally in favor of a standardized method for naming.  It's gotten pretty messy (mostly my fault).
