### ISSUE TITLE
Ticket icon/status in transaction inconsistent in master

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1630]
Seems that #1600 introduced a small change in the status/icon of ticket transactions, which makes them now display as "voted", so effectively when scrolling through the transaction history I cannot figure out what is actually a ticket purchase tx and a vote tx.

IMO show this is way is wrong, since the transaction history is supposed to show the status of each individual transaction, not of whole ticket/vote chains. Showing a "live" status is also not technically correct, since an old ticket might have been expired/missed/etc.

I think we need to show ticket purchases as actual purchases, independently if the ticket was eventually voted or not.

@linnutee @alexlyp thoughts?

![screenshot_2018-09-03_16-46-56](https://user-images.githubusercontent.com/1752493/45000383-c8978e00-af9a-11e8-8c92-e38563029310.png)

**Comment by vctt94** [comment]
This is duplicated from #1622.

But I agree with you about showing as purchased ticket.

**Comment by matheusd** [comment]
bargh.. sorry about the dupe :)
