### ISSUE TITLE
Confusing error message after successful operation

### ISSUE THREAD

**Issue by psmithson** [decred/decrediton#1638]
Right after I buy a ticket, I get a red message "Insufficient spendable account balance to purchase tickets" message. I also get a little green message at the same time below saying the transaction was successful. But the green one disappears very fast and only the red message remains, confusing me.

### So as a user, my experience is that I click buy, and immediately a message appears saying I have insufficient funds, and in fact the purchase succeeded.

What actually happened is that I had enough balance for only 1 ticket, the ticket was bought, the UI was refreshed and then Decrediton thinks I don't have enough DCR to buy another ticket. It happens so fast it seems the transaction failed. Here is a screenshot below.

So maybe you can update the "From" combobox with a zero non-valid item called "Select Account" or "Pick Account" or simply "Select", and when a transaction is successful, the combobox should default back to the zero item, so that the red message does not appear after a successful transaction.

![confusing](https://user-images.githubusercontent.com/1484015/45122382-425d8200-b129-11e8-872d-753fe85f83d8.JPG)

Thanks, I hope that was clear. I'm sure many people got confused the first time with that too.

**Comment by matheusd** [comment]
Thanks again for another report. This one is totally fixable.

**Comment by psmithson** [comment]
Perfect @matheusd ! I believe in DCR so I will keep sending any UI issues I may find and help the project in any way I can.

Thanks and good luck : D

**Comment by noahpierau** [comment]
Forwarded this issue to the #design channel as well

**Comment by matheusd** [comment]
This is how it's currently appearing in 1.3.0

![screenshot_2018-09-06_08-38-22](https://user-images.githubusercontent.com/1752493/45155440-61075b80-b1b1-11e8-8a72-cdcb2797e052.png)

**Comment by linnutee** [comment]
Afaik all the pre-triggered warnings got ironed out with the last release https://github.com/decred/decrediton/issues/1424. If there's any found still can be ironed out in the same manner as above.

**Comment by alexlyp** [comment]
Closing this as this is no longer being shown as an error and instead just a field warning as shown in the screenshot above.
