### ISSUE TITLE
Display a 'Last Updated' field for Politeia proposals

### ISSUE THREAD

**Issue by lukebp** [decred/decrediton#1639]
Once a proposal has been made public, the author is still able to edit the proposal up until the voting period starts so that they can incorporate feedback from the community.  We don't want somebody to vote on proposal that they read a week ago, but was actually changed the day before.  Displaying some type of "Last Updated" field would help the user know if they need to take another look at the proposal before casting their votes.

**Comment by matheusd** [comment]
Given that we only have a single timestamp information coming from Politeia (last updated timestamp) this is what we can show for the moment:

![image](https://user-images.githubusercontent.com/1752493/45168920-d172a480-b1d2-11e8-9e8c-7b020e42bd37.png)

**Comment by lukebp** [comment]
I think that's fine.  The combination of the version number and the last updated timestamp give the user a good idea if they need to look at the proposal again.
