### ISSUE TITLE
[non-advanced] when start decrediton ticket information is not retrieved

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1642]
When starting decrediton in non advanced mode, the ticket information does not seem to retrieve.

![ticketbug](https://user-images.githubusercontent.com/15069783/45380692-aa084700-b5d9-11e8-8e22-3b975b524535.png)

**Comment by vctt94** [comment]
I made some tests and the ticket information seems fine. Closing this issue

**Comment by alexlyp** [comment]
thanks!
