### ISSUE TITLE
Disable "About Decrediton" modal duplicate

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1651]
<img width="1015" alt="screen shot 2018-09-14 at 23 36 36" src="https://user-images.githubusercontent.com/17774057/45573994-10f65c00-b877-11e8-896d-8949415cbd4f.png">

When opening "About Decrediton" from the op system navbar, it should display the same modal instead of the system default one.

**Comment by alexlyp** [comment]
Hrm OK I'll look into this one, hopefully it's just a setting for mac builds or something.

**Comment by linnutee** [comment]
Should be, I've checked some mac apps – e.g. telegram, spotify got it the same way. And in Skype the same action opens a view within a Settings modal even.

**Comment by alexlyp** [comment]
This may be relevant to solving this issue: https://github.com/electron-userland/electron-builder/issues/2468#issuecomment-428641768
