### ISSUE TITLE
Daemon Error [ERR] DCRD: Unable to start server on [:9108]

### ISSUE THREAD

**Issue by greenman57** [decred/decrediton#1659]
Installed Decrediton for the first time and getting this error when opening. Tried reopening after Delete and Shutdown and got the same error message. Help?

![error](https://user-images.githubusercontent.com/35261504/45930210-0567fc80-bf2b-11e8-9a86-06f580f6930a.JPG)

**Comment by matheusd** [comment]
Fixed via chat (some background app was blocking port 9108).

If you're not the same person as the chat, please reopen the issue.
