### ISSUE TITLE
Wallet Hangs on "Discovering addresses..."

### ISSUE THREAD

**Issue by rymurph20** [decred/decrediton#1660]
After trying on every release from v1.0.0 upwards, I can't get my wallet seed to regenerate my wallet due to Decrediton hanging on 'Discovering addresses'. When restoring my wallet, everything works fine until I get to the screen where Decrediton wants me to 'Scan for existing addresses'.

I enter my passphrase and the application looks like it's running as I see 'Discovering addresses...' but nothing ever happens. I've left it for ~48hours before it brings my machine to a crawl and I have to reboot.

Any ideas? If not, is there any way I can skip this step and go straight to my wallet?

OS: Windows 10
Decrediton version: 1.3.0

**Comment by matheusd** [comment]
Could you please look at the daemon and wallet logs and see if there are any error messages there?

You should see a link to the logs page at the upper right corner in decrediton.

**Comment by alexlyp** [comment]
@rymurph20 any more information you can provide?

**Comment by alexlyp** [comment]
Please try again in v1.3.1

**Comment by rymurph20** [comment]
Sorry for the late response, but this was fixed in v1.3.1

Thanks!

**Comment by iobond** [comment]
it happends on 1.4.0 now

![image](https://user-images.githubusercontent.com/11798579/79058252-6b58c980-7c20-11ea-8102-f0ace6c14281.png)

**Comment by matheusd** [comment]
v1.4.0 has been forked off the network. Please update to 1.5.1.
