### ISSUE TITLE
Save button on settings tab does not reset

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1666]
Steps to recreate:
- Change the value of the "Network information" checkbox
- Save button becomes enabled
- Change the "Network information" checkbox back to its original value

Expected result:
- Save button should become disabled, as there are no new settings to save

Actual result:
- Save button stays enabled.

**Note:** The save button resets as expected if this test is performed with a different setting, eg. "Displayed Units"

**Comment by alexlyp** [comment]
Yah I'm currently updating the settings page to allow for SPV/Network changing.  I'll be fixing this while I'm in there.
