### ISSUE TITLE
[export] Misaligned search button

### ISSUE THREAD

**Issue by dnldd** [decred/decrediton#1669]
The log page is currently showing an incorrect version. I'd suggest using a single version var for all pages, should make version updates easier.
<img width="1144" alt="log_incorrect_version" src="https://user-images.githubusercontent.com/1281030/46157847-2783b680-c26c-11e8-9564-07389669f0aa.png">

Insufficient balance prompt for ticket purchases overflow the bounds of the widget.
<img width="772" alt="tickets_msg_overflow" src="https://user-images.githubusercontent.com/1281030/46158636-d248a480-c26d-11e8-948c-478410838616.png">
 

Alignment and icon size are off for the search icon on the export page.
<img width="479" alt="txns_search_icon" src="https://user-images.githubusercontent.com/1281030/46158337-2ef78f80-c26d-11e8-9124-cd2eb6f536a0.png">

**Comment by alexlyp** [comment]
Hrm I can't seem to replicate the v1.1.2 issue.  How did you reach that page?

**Comment by alexlyp** [comment]
I always see "Logs" at the top of that page.  I only see that text on the release notes page.

**Comment by dnldd** [comment]
> Hrm I can't seem to replicate the v1.1.2 issue. How did you reach that page?

I used the `Logs` link on decrediton's main page.
<img width="1118" alt="logs_link" src="https://user-images.githubusercontent.com/1281030/46162936-450b4d00-c279-11e8-93df-c830642fbb53.png">

**Comment by alexlyp** [comment]
Hrm there must be something really wacky going on with mac build, let me try it out and see if i can replicate.  Same with your issue that you opened about the charts.  no clue how to replicate that.  looks fine for me.

**Comment by alexlyp** [comment]
Ah just figured out what's going on.  Something goofy with language and language selection.  It's using an old set of translations.  So that just needs to be updated and should update to the current master template.  @matheusd can you update that?

**Comment by alexlyp** [comment]
@dnldd can you confirm everything looks OK if you switch to English (US) ?

**Comment by dnldd** [comment]
> can you confirm everything looks OK if you switch to English (US) ?

Can confirm switching to English(US) solves it.

**Comment by alexlyp** [comment]
Updated to reflect the remaining issue here about the misaligned search button
