### ISSUE TITLE
v1.3.0 - Cannot remove partially setup wallets

### ISSUE THREAD

**Issue by morrisonbrett** [decred/decrediton#1675]
Tested on Windows 10 Insider Preview

Steps to repro:
* Create a New Wallet OR Restore Existing Wallet
* Cancel
* Try and Remove

See attached videos. I **was** able to remove after exiting Decrediton and re-launching.

https://1drv.ms/v/s!AktSiyBbVlbrgZiCQ_pFIz4Y3cHl3N0
https://1drv.ms/v/s!AktSiyBbVlbrgZiCRJ0WPyRosRqgGU8

**Comment by matheusd** [comment]
Thanks for the report. This is a known issue (#1653) and we have some work towards fixing it already.
