### ISSUE TITLE
Linux 1.3.0 javascript error when using the passphrase

### ISSUE THREAD

**Issue by mberionni** [decred/decrediton#1680]
I'm getting the following error, in the linux decrediton wallet, version 1.3.0, when trying to update the passhprase or simply entering the passphrase in order to connect to a pool:

TypeError: Cannot read property 'PRIVATE' of undefined

**Comment by matheusd** [comment]
Changing the private passphrase is indeed broken in 1.3.0, but I don't have any issues with adding stakepools.

What exact process do you mean by "in order to connect to a pool"?

**Comment by mberionni** [comment]
After adding the pool key, in order to confirm you have to insert
passphrase, hence the same error.
