### ISSUE TITLE
Allow watch only wallets to construct transactions

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1682]
Maybe this could be done by changing the send button in the send page to a "construct" button that just shows the most recently constructed tx.

This would allow decrediton to produce a tx that could be saved and moved to a separate computer for signing.

**Comment by alexlyp** [comment]
Ya, I think that's a great idea.  And with the way you suggested it should be totally possible and easy to implement.

**Comment by vctt94** [comment]
I'd like to take this one

**Comment by alexlyp** [comment]
Great go for it!
