### ISSUE TITLE
“decrediton.app” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by fulldecent** [decred/decrediton#1691]
> “decrediton.app” can’t be opened because it is from an unidentified developer.

> Your security preferences allow installation of only apps from the App Store and identified developers.

> Safari downloaded this file today at 1:35 PM.

![screen shot 2018-10-05 at 1 42 31 pm](https://user-images.githubusercontent.com/382183/46551044-b1530580-c8a4-11e8-9582-b13cf18f5510.png)

**Comment by fulldecent** [comment]
Currently, there is no secure binary for decredition.

Please release secure and signed binaries on the GitHub releases for this repository.

**Comment by alexlyp** [comment]
Yup, we're planning on doing this at some point.  But problem is Apple making us jump through all sorts of hoops to get certified.  It will be done.  

I wouldn't call the binaries "unsecure" though.  You can verify the binaries are the ones we have built.

**Comment by fulldecent** [comment]
Thank you for following up.

I can see that the official place to get binaries is at: https://github.com/decred/decred-binaries/releases

This is better than the http://decred.org homepage because if you click that link you see a bunch of redirects and it downloads from amazon.

**Comment by alexlyp** [comment]
It's the exact same link being used in both places.  Maybe github uses AWS hosting or something.  But either way we provide instructions to verify these binaries:
ttps://github.com/decred/decred-binaries#verifying-binaries

**Comment by fulldecent** [comment]
Awesome. Ok, I have good binaries. So the only issue is proving that to macOS once Apple accepts your application.

**Comment by alexlyp** [comment]
Closing.  Duplicate of #922
