### ISSUE TITLE
Passphrase retry within passphrase modal

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1693]
When the user enters an incorrect passphrase whilst purchasing tickets, the passphrase modal automatically closes and the user is returned back to the tickets tab. Another mouse action is then required to reopen the modal and retry the passphrase.

It might be nice if the modal did not close, but instead it simply displayed an error and blanked the text input so the passphrase can be quickly retried.

**Comment by alexlyp** [comment]
I'm going to give this a go, but it may be quite the endeavor in terms of the we way handle passphrase submission attempts etc.  But I'm hoping it'll be a simple change.
