### ISSUE TITLE
Error shown if passphrase reset is attempted with wrong passphrase

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1694]
**Steps to recreate:**
- Open the settings tab
- Click "Update Private Passphrase"
- Enter an incorrect value for current passphrase, and two matching values for the new passphrase.
- Continue

**Expected result**
- A meaningful error informing the user their passphrase was incorrect

**Actual result:**
- An error saying: `TypeError: Cannot read property 'PRIVATE' of undefined`

**Comment by Jujhar** [comment]
I can attempt to fix

**Comment by alexlyp** [comment]
Sure go ahead

**Comment by Jujhar** [comment]
Fixed
