### ISSUE TITLE
Rename private passphrase

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1695]
The dcrwallet binary has concepts of "private passphrase" and "public passphrase". These are are different things used for different purposes.

Decrediton abstracts this away, and simplifies things so the common user is only aware of a the private passphrase. Does it make sense for Decrediton to simply call this a "passphrase", and not a "private passphrase"?

**Comment by alexlyp** [comment]
I'm down for discussing this further.

Issue I see is that there is still a possibility of user's hitting the "public" passphrase with decrediton (if they created it with dcrwallet then manually moved it over).  This is an extremely rare and probably unsupported case.

We can probably just change them all to "password".

**Comment by matheusd** [comment]
Personally I'm indifferent on which way to use. I like "passphrase", but maybe it's just because I'm already used to it. 

As @alexlyp , users hitting the public passphrase page know what they are doing, given the only way they could have that is if they manually imported a dcrwallet file.
