### ISSUE TITLE
New notifications design

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#1696]
Preview: https://xd.adobe.com/view/08fd9288-7f3e-4b53-48e2-e4c247bedd50-7ecc/
Specs: https://xd.adobe.com/spec/d6c21559-32f1-4c07-5abb-40bc3f7125fc-a0f3/

Change old error/success messages and notifications for larger actions/events to new ones.

**Comment by alexlyp** [comment]
Can you supply the new icons for the Error and Success as well?

**Comment by MariaPleshkova** [comment]
@alexlyp sure

[icons.zip](https://github.com/decred/decrediton/files/2467867/icons.zip)

**Comment by MariaPleshkova** [comment]
@alexlyp I updated the links in this issue to new ones (added a progress bar to error notification and showed hover effect for this notification)

And this is the icon itself: 
[Progress bar.zip](https://github.com/decred/decrediton/files/2472720/Progress.bar.zip)

**Comment by alexlyp** [comment]
Reopened issue to complete the suggested notification progress.  As well as discuss the way in which the stacking of notifications should occur.
