### ISSUE TITLE
[launcher]  Add SPV enabling launch page

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1713]
Once we decide that SPV should be enabled by default for decrediton, we should create a page that asks existing users if they would like to change over.  This would consist of YES/NO buttons and a short explanation of the pros and cons of using SPV.   

This page should be shown similarly to how the language select or wallet instructions page are shown.  All users are shown it if "spv_page: true" or something like that.  And once the user makes their decision the page will never be seen again ie "spv_page: false"

**Comment by linnutee** [comment]
Should this be added to the Settings for later changes also?

**Comment by alexlyp** [comment]
It already has been added to the Settings page
