### ISSUE TITLE
macOS Mojave - Error: Failed to connect before the deadline

### ISSUE THREAD

**Issue by vladstan** [decred/decrediton#1746]
Everything went well in the last couple of days, but today I got this error when I tried to open the wallet. Error: Failed to connect before the deadline

<img width="1073" alt="image 2018-10-28 at 02 35 57" src="https://user-images.githubusercontent.com/4694319/47610966-6323c300-da5a-11e8-9bbe-1b66cc001236.png">

I also upgraded to v1.3.1 but it's the same.

**Comment by alexlyp** [comment]
I've never seen this error reported.  Can you check your logs for any errors?  There should be a logs button in the upper right corner.

**Comment by vladstan** [comment]
The thing is I can't reproduce the error anymore and I opened the app a couple of times. Let's close this for now, and if will appear again I will also save the logs. What do you think?

**Comment by alexlyp** [comment]
Yah please do, we've had some lingering reports of issues on various macOS versions.  The more information I can gather about it, the better.

**Comment by vladstan** [comment]
Ok I will. Thank you!
