### ISSUE TITLE
[launcher] Use newly implemented getblockchaininfo for progress

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1753]
Now we can use the new dcrd rpc command for "getblockchaininfo" to get the "verificationprogress" to report back how far along the user is for syncing the blockchain.

This will remove the need to check blockchain height from dcrdata and will be able to consistently display the progress for normal (non-SPV) dcrd syncing.

**Comment by matheusd** [comment]
One thing I thought about some time ago: why do we use dcrctl to check on the dcrd height? Couldn't we connect directly to it via its rpc interface and check through that (and avoid polling)?

**Comment by vctt94** [comment]
I believe that would be possible @matheusd , but right now we use `ipcMain` to do dcrctl commands. Are you suggesting to open a new rpc connection with dcrd?

**Comment by matheusd** [comment]
Yes

**Comment by alexlyp** [comment]
Yes, totally.  Let's open a new issue to discuss how that impl would work.
