### ISSUE TITLE
Grouped minor design fixes - 1.3.1

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1756]
Preview: https://xd.adobe.com/view/5c2f092d-3262-46cb-8e7c-3834fa9a9673/

1. Launcher / Privacy Options - Duplicate of logo

2. Launcher / Privacy Options / Customize - Duplicate logo and  text alignment issues
This page has an undesigned layout, for a quick fix the "close and accept" buttons can be also aligned with the checkboxes. To be addressed separately later on.

3. Settings - Timezone title alignment issue

4. Launcher - Wallet Cards alignment issues  

5. Launcher logs - Double scroll bar

6. TX data - Spacing issue, header content issue

Also reminding again, if anyone can pick up this issue: https://github.com/decred/decrediton/issues/1499, Decred logos within Decrediton and the launcher need updating still. Thanks.

**Comment by alexlyp** [comment]
I've addressed the dupe logos in my Spv Default PR.  

3 has already been addressed.

**Comment by alexlyp** [comment]
1 and 2 are done.
