### ISSUE TITLE
Visual Design: Consensus Changes tweaks

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1758]
Few small tweaks to bring the page up to date in relation to Proposals subpage. 

Preview: https://xd.adobe.com/view/9d23147b-2188-4330-5560-af2cab5ddf70-eb12/
Specs: https://xd.adobe.com/spec/47db64cf-3899-4483-4c5d-66dcce31cd6e-31ea/

- Add background grey levels to content areas (note these are different than in Proposals view). 
- Update title and copy:
```
Consensus Changes
Consensus changes refer to the on-chain governance aspect of Decred. This means deciding whether to adopt changes to the consensus rules of the network. Participation in voting requires (PoS) tickets. 
``` 
- Add info icon - at the moment opening link to https://docs.decred.org/getting-started/user-guides/agenda-voting/ (later on new tutorial once designed). 

- Add button "Voting Dashboard" linking to http://voting.decred.org

Nb! Navigation icons will be addressed in a separate issue soon.

**Comment by alexlyp** [comment]
So I noticed that the stakepool selection is gone.  Can you explain the updated UX for that?  Should the vote choices be sent to all pools that the user may have set up?

**Comment by linnutee** [comment]
Ah right. Did not add the commentary to this – actually the idea was to display the Voting Dashboard link/button only when the user has not setup any stakepools yet. 

In case the user is participating in staking, should still display the same stakepools dropdown there I recon.
