### ISSUE TITLE
[launcher] Add links to docs.decred.org about SPV

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1768]
I believe there is a more long-form explanation of SPV in the works for docs. When that is available we should link to it directly in the header of the SPV Choice page.

**Comment by jholdstock** [comment]
I added decred/dcrdocs#676 for this

**Comment by alexlyp** [comment]
awesome thanks!

**Comment by jholdstock** [comment]
decred/dcrdocs#676 is done, SPV docs available here: https://docs.decred.org/wallets/spv/

**Comment by alexlyp** [comment]
Great I'll add the link
