### ISSUE TITLE
[1.3.1] Dont reset stakepool choice if API key is incorrect

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1773]
Steps to recreate:
- Create a new wallet
- Open the tickets tab
- Select a stakepool which is not the default already selected
- Enter an invalid API key (any old string)
- Press continue
- Enter valid passphrase 
- Press continue

Expected result:
- Error is shown 
- Stakepool choice is remembered

Actual result:
- Error is shown 
- Stakepool choice is reset back to the default

Note: This same behaviour is also observed if the API key is correct, but the passphrase is wrong

**Comment by alexlyp** [comment]
Thanks for the report.   Shouldn't be too bad to fix
