### ISSUE TITLE
[1.3.1] Auto ticket buyer shows orange floating "Attention"

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1774]
Open the tickets tab after adding a stakepool API key, and try to enable the auto-ticket buyer. The passphrase modal is displayed, along with a strange floating orange message saying "Attention!"

![sta](https://user-images.githubusercontent.com/6762864/47965433-374aa380-e03f-11e8-8c77-3bbe0378c258.png)

**Comment by alexlyp** [comment]
Good spot, I've addressed this in the Ticketbuyer V2 PR that will be in soon.
