### ISSUE TITLE
system error adding a stake pool - 1.3.1 on linux

### ISSUE THREAD

**Issue by mberionni** [decred/decrediton#1781]
Hi,
I'm running decrediton 1.3.1 on linux.
In the "Tickets --> Purchase" section, when trying to add a new stakepool, after inserting the API key and the passphrase I get the following error:

"system error - unable to process wallet commands" 

As a result I'm unable to buy tickets.

**Comment by alexlyp** [comment]
which stakepool are you trying to add?  i believe that's an error from the stakepool itself

**Comment by mberionni** [comment]
https://decred.raqamiya.net/

**Comment by alexlyp** [comment]
We're investigating an issue with stakepools now.  Will leave this issue open until we have that issue resolved.

**Comment by alexlyp** [comment]
Ok I believe they should have resolved the issue now.  Please let me know here if you are still having issues.  thanks.

**Comment by mberionni** [comment]
still having the same error...

**Comment by alexlyp** [comment]
Ok then I suggest you get in touch with the admins at https://decred.raqamiya.net/

There is no issue on the decrediton side.

**Comment by daw731** [comment]
I'm having this issue as well - can you give some insight into what the cause of the problem was?

**Comment by mloop1** [comment]
Using a different pool worked for me
