### ISSUE TITLE
Auto dark theme

### ISSUE THREAD

**Issue by vanjan** [decred/decrediton#1784]
This is a feature request. 

The UI should have another, dark, theme. By default, the UI should change theme in accordance to the OS, eg macOS Mojave dark mode.

**Comment by matheusd** [comment]
It's in the works. Don't know if it's possible to detect the current OS theme via electron (I'm going to guess: no) but we'll try and research that.

**Comment by vanjan** [comment]
This looks promising: https://stackoverflow.com/questions/25207077/how-to-detect-if-os-x-is-in-dark-mode#25214873

**Comment by laszlolm** [comment]
I'm gonna start on this issue since Electron now supports getting dark mode natively:
```
const {systemPreferences} = require('electron')
console.log(systemPreferences.isDarkMode())
```
