### ISSUE TITLE
[1.3.1] Erroneous newline when copy/pasting address

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1791]
Observed on Ubuntu 16.04 using Decrediton 1.3.1

**Steps to recreate**
1. Open the transactions panel
2. Open the Receive tab
3. Double click on the displayed address to select it. Copy
4. Paste into a text editor

**Expected:**
Only the address is pasted

**Actual:**
The address is pasted, but it is prefixed with a newline character.

**Comment by vctt94** [comment]
I can fix that
