### ISSUE TITLE
[Governance] Cache information from governance page

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1796]
When clicking on the governance tab, decrediton starts downloading proposals from politeia, but if the component gets unmounted, when clicking on the governance tab, it will download the information again. We should cache it.

I believe we can use redux or electron sessions for doing that, what do you guys think?

**Comment by matheusd** [comment]
Weird, I'm not seeing this behavior. How are you reproducing this?

**Comment by vctt94** [comment]
If you go to governance, download proposals, then go to another tab, spend a while, and then go back, it will re-download proposals

**Comment by alexlyp** [comment]
Yah it's not about the unmounting.  There's a 5 min timer that is checked at the top of the index.js in Governance/Proposals.

I'm open for a new way to load/update the Politeia information after the initial fetch.  Maybe a different indicator signifying that it's updating?

**Comment by matheusd** [comment]
Ideally, politeia should return an http 304 status (and no body) if the proposal hasn't changed in any way, which should cause the browser to fetch the data from cache. If we wanted to get fancy, we there might be a way to extract that the 304 happened and not regenerate the data for prop, reusing whatever we already have in the state.

Don't know if this is currently handled by the politeia api though.
