### ISSUE TITLE
Implement type representing DCR amounts

### ISSUE THREAD

**Issue by szpasztor** [decred/decrediton#1804]
Long-term and major undertaking. Follow up on https://github.com/decred/decrediton/issues/1780

**Comment by alexlyp** [comment]
Can you explain a bit more what you're thinking here?

**Comment by matheusd** [comment]
Just to reiterate: the app generally (and the wallet definitely) only uses atom amounts for internal representation. It only really uses dcr amounts for input and display.

The idea of having a dcr amount type (similar to dcrutil.Amount) is to have some protection against wrong usage (eg: simply willy nilly multiplying dcr amounts without taking care of the potential floating point errors).
