### ISSUE TITLE
[macOS] Non-existent menu referenced on invalid RCP menu

### ISSUE THREAD

**Issue by szpasztor** [decred/decrediton#1805]
There's no help menu on macOS, so the last sentence shouldn't be shown. 
![image](https://user-images.githubusercontent.com/8398290/48634671-63164380-e9c6-11e8-9feb-675f09af7bab.png)

**Comment by alexlyp** [comment]
Ah good catch, you can update the text to reference the Help page having access to the About screen.

**Comment by szpasztor** [comment]
Is the about modal supposed to show the current version of executables? It certainly doesn't show it for me. If that's the case, the message might not be helpful on any platform.

**Comment by alexlyp** [comment]
Yah looks like you're correct.  So just remove the last message about "See ..."  This issue will only be caused by those that are actively deving/building from source.
