### ISSUE TITLE
This script is not redeemable by this wallet

### ISSUE THREAD

**Issue by ammmmb** [decred/decrediton#1817]
This happens when I add stakepool API token to my wallet. I use Decrediton 1.3.1 with a restored wallet from the seed. And the balance is incorrect.

Farther, I also tried to restore the wallet in the command line wallet, the balance is still incorrect that some funds are missing after I imported the script and did a wallet rescan.

**Comment by hypernoob** [comment]
https://github.com/decred/decrediton/blob/master/app/i18n/docs/en/InfoModals/ScriptNotRedeemable.md

> If you receive an error about the script not being redeemable when attempting to add your stakepool, you can try the following:
> 
> Each stakepool account you create can only be associated with 1 wallet. If you have previously created this stakepool account with a different wallet (different seed), then you must create a new account.
> 
> If you had previously used a ‘voting account’, for your ticket purchases, please go to the Accounts page and create a new account. This may now allow you to successfully import your script for your stakepool.

**Comment by ammmmb** [comment]
My wallet (the same seed) is only associated with this stakepool.
I don't really understand the meaning of "voting account". If I recall correctly, there are some previous tickets, and I used them to vote in Politelia. But I didn't buy new tickets in that wallet. 

After I reinstalled my OS and restored the wallet, this issue occurs. Furthermore, I have tried to create a new account (in wallet accounts), but it didin't help.

**Comment by ammmmb** [comment]
Both CLI wallet and decrediton don't work. :(

I tried to decode the script and validate the address, it shows `isvalid: true`.

**Comment by matheusd** [comment]
Right, the important bit is whether `isMine` is true or false, which indicates whether that address is from your wallet.

**Comment by alexlyp** [comment]
Try this:

Open decrediton and go to settings.  Change gaplimit to 100, close decrediton and restart.  Then click the rescan button in the lower left corner.  Then attempt to add your api key again.  If this doesn't work try the same process with 1000.

**Comment by ammmmb** [comment]
It workes when I delete the hole wallet and reinstalled decrediton. Thanks. :+1:
