### ISSUE TITLE
[overview] Days label overrides the pending div

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#1848]
Here is an image: 

![bug](https://user-images.githubusercontent.com/15069783/49309455-70e9bf80-f4c2-11e8-9bcd-2577639f045c.png)

**Comment by alexlyp** [comment]
Weird, shouldn't be seeing a pending on a vote.

**Comment by vctt94** [comment]
This wallet is pretty weird. I made a backup with its file, to upgrade to db 12 when testing https://github.com/decred/dcrwallet/pull/1330

and after copying it back to decrediton's wallet directory, it is acting weird since then. Not sure why, yet.

**Comment by vctt94** [comment]
well it is probably due to trying to use the older version of the db, using the matheus's PR it looks okay. I will close this issue as we are not going to have a pending vote.
