### ISSUE TITLE
my decredition has no "export" tab under transactions

### ISSUE THREAD

**Issue by ezeboog** [decred/decrediton#1850]
trying to gather decredition transactions for tax purposes. Can anyone provide info/or link to an explanation for this. Under "Decred Documentation" it shows/explains an "export" function under transactions for a .csv file. However, my decredition does not show this export tab.

**Comment by degeri** [comment]
Some Using user was older version: (1.1.3)

https://www.reddit.com/r/decred/comments/a2eelq/help_export_decredition_transactions

Would you mind closing this issue ?
