### ISSUE TITLE
indicating confusion of ticket status: status  "purchased" means what?

### ISSUE THREAD

**Issue by zhiduochen** [decred/decrediton#1863]
ticket status is in confusion
lived tickets shall be indicated in "live", but some lived tickets is indicating "purchased". 
Is it correct or not?
![141961543896086_ pic](https://user-images.githubusercontent.com/22485302/49418530-89592300-f7bd-11e8-994d-e12f83a76e5e.jpg)

**Comment by zhiduochen** [comment]
purchased means voted?

**Comment by matheusd** [comment]
We had a couple of issues in determining status of single tickets, so we had inconsistent status displays.

Now that https://github.com/decred/dcrwallet/pull/1318 is in, I'll try to rework this.
