### ISSUE TITLE
Fix and improve the tab "my tickets"

### ISSUE THREAD

**Issue by juarezbatistaneto** [decred/decrediton#1866]
The tab tickets / my tickets has a bug: it does not properly present the voted tickets (this bug happened in “staking activity” as soon as it opened the wallet). I also have a suggestion: using the “voted” filter, appear on how many days the ticket was voted, as in the main screen of the wallet.

main tab (showing correctly): https://imgur.com/a/P21Uxpt

tab not showing voted tickets correctly (and how many days was voted): https://imgur.com/a/UYHpr1r

**Comment by matheusd** [comment]
Adding the days to vote label is a fine thing.

I'm slightly confused by the "not showing correctly" thing. It seems the ticket _is_ listed as voted (notice the icon is the same on the two screens).

Do note that the "My Tickets" tab shows status _per ticket_, so a given ticket will only appear once there, and sorted in the order of ticket purchases (tickets purchased more recently are shown first, even if you have more recent votes) vs on recent stake activity box in the overview page, where it's shown sorted in _transaction order_ (votes that happened more recently are shown first).

We're trying to work out some improvements to these pages.

**Comment by juarezbatistaneto** [comment]
I think it makes more sense to display the latest votes first. I think the logic of the "overview / staking activity" tab makes a lot of sense. When I click on "see all", the logic changes and loses some function. I just can't find the information on how many tickets were voted in the month, for example. I already had x tickets voted this month, however, in my tickets / voted only 1/3 of this appears.

**Comment by rramires** [comment]
I've been noticing this... In my wallet on the tickets tab, does not show the last voted:
![incorrect](https://user-images.githubusercontent.com/14129483/49553677-07ade600-f8e0-11e8-9968-c478bbf18f66.jpg)
But they appear correctly in the transactions tab, filtering by voted:
![correct](https://user-images.githubusercontent.com/14129483/49553718-362bc100-f8e0-11e8-9980-c196a2a3b844.jpg)

**Comment by rramires** [comment]
I've been noticing this... In my wallet on the tickets tab, does not show the last voted:
![incorrect](https://user-images.githubusercontent.com/14129483/49553858-d1249b00-f8e0-11e8-8ff2-88888a5f4aec.jpg)
But they appear correctly in the transactions tab, filtering by voted:
![correct](https://user-images.githubusercontent.com/14129483/49553863-d84ba900-f8e0-11e8-9133-c40e29d5f873.jpg)
