### ISSUE TITLE
[launcher] Notify users of long wait for upgrade from <1.3 

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#1880]
Due to the dcrd reindexing that has been included in 1.4.0 users upgrading from 1.3 will encounter a long wait until dcrd is prepared for usage.  

We should capture specific lines in the logs that will let us know that they are currently reindexing.  This isn't ideal, but unfortunately since the dcrd's rpc client isn't available until after the upgrade is complete.

**Comment by jholdstock** [comment]
I've just run the db migration for dcrd 1.3.0 to the current master (a0816cf). No issues but it took ~40 minutes using a decent spec laptop + SSD. CPU running at near max for the whole time.

log: https://pastebin.com/w0Spdnht

**Comment by matheusd** [comment]
That's generally what was reported in the migration PR (~40 minutes).
