### ISSUE TITLE
[1.4.0-rc] Whitescreen freeze when cancelling out of wallet setup

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1886]
**Steps to recreate:**
- Clean decrediton install
- Press "Create a New Wallet"
- Enter a name and press continue
- Wait for the seed to be displayed. Close the window
- Reopen Decrediton
- Wallet should be displayed as "Incomplete setup". Click "Launch Wallet"
- Seed is displayed again. Press Cancel

**Actual result:**
- White screen and Decrediton becomes unusable.

**Expected result:**
- User returned to the wallet selection page.

**Comment by matheusd** [comment]
Hmm, can't reproduce using these steps on latest master. Can you check whether this is still happening?

Also, are you running on spv or regular (rpc) mode?

**Comment by jholdstock** [comment]
Can also reproduce with dcrd, dcrwallet and decrediton on `release-v1.4` branches

**Comment by matheusd** [comment]
Thanks for the additional info! 

The important bit to reproduce the issue was not having any other wallets created (ie, this was the very first wallet of a new install).
