### ISSUE TITLE
[1.4.0-rc] "Reveal" extended pub key does not reveal whole pub key

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1911]
On the Accounts tab, clicking the button to reveal the extended public key only actually reveals the first half of the pubkey and not the whole thing. The copy to clipboard button works, and that does copy the whole key, but a user may not want their pubkey in their clipboad.

**Comment by matheusd** [comment]
Changed the design to show the full xpub, but I think it's unlikely someone is going to hand-write the whole thing.

If pushing the xpub to the clipboard is an issue, we could add a SaveToFile button as an alternative action.

**Comment by alexlyp** [comment]
OK just merged @matheusd's styling fix. 

And yah not sure what the correct answer is here tbh.  I agree with matheusd that it is unlikely that a user will copy a pubkey by hand, but I suppose it's possible.

**Comment by jholdstock** [comment]
I just tested this and it looks good to me, I'm going to close the issue. Agreed that writing by hand will rarely/never happen, but I just found it strange to have a button saying "Reveal" when it doesn't actually reveal the whole thing :)
