### ISSUE TITLE
[1.4.0-rc] Alignment on the Settings tab

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#1912]
The descriptions of various options in the settings tab do not line up nicely. 

![222](https://user-images.githubusercontent.com/6762864/50055031-4db94400-0141-11e9-8df3-a3ccdfa4c3d1.png)

**Comment by jholdstock** [comment]
I'm not going to have time to pick this up for a little while so I've closed my PR on this and somebody else can take it on.

**Comment by vctt94** [comment]
Closing this one as it has been fixed
