### ISSUE TITLE
[1.4.0-rc] SPV sync stage should have wallet logs 

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1921]
I got into an error state when loading an spv wallet and did not have access to wallet logs, so we should enable this.

**Comment by alexlyp** [comment]
Good catch, weird didn't realize it wasn't there.

**Comment by alexlyp** [comment]
Hrm when you say wallet logs, do you mean dcrwallet or decrediton logs?   

I currently see the dcrwallet logs appearing as expected after you select a wallet to load.  I will be adding decrediton logs to be seen all the time.

**Comment by matheusd** [comment]
Here are a couple of stages where the top right "logs" link ins't displayed. My actual failure was on the first one:

![image](https://user-images.githubusercontent.com/1752493/50174776-3796b980-02e2-11e9-8228-b23194d541a2.png)

![image](https://user-images.githubusercontent.com/1752493/50174796-41b8b800-02e2-11e9-9359-146052012143.png)

**Comment by alexlyp** [comment]
Oh very strange.  And this was just after you clicked "launch wallet" ?

**Comment by matheusd** [comment]
Yes. Seems that in some stages the log link shows up, but not on others.

If you happen to enter the log page when the link is first visible, then you can remain there, but you can't get to that page from the above states.

**Comment by alexlyp** [comment]
Yah good point.  I'll take a look at streamlining this today.
