### ISSUE TITLE
Alert when closing wallet/shutting down that ticket buyer is running

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#1923]
While we alert that the wallet needs to remain open when turning on the ticket buyer, it's been suggested in chat that we should also alert when closing the wallet or shutting down the app that the ticket buyer will be closed and no tickets will be further purchased.

We could also possible add warnings when going into/out of suspend mode or on app shutdown.

https://github.com/electron/electron/blob/master/docs/api/power-monitor.md

**Comment by szpasztor** [comment]
I'll take this.

**Comment by szpasztor** [comment]
Taking this.
