### ISSUE TITLE
[config] Allow CLI config option setting - macOS

### ISSUE THREAD

**Issue by szpasztor** [decred/decrediton#1938]
Implement https://github.com/decred/decrediton/issues/1646 on macOS

**Comment by matheusd** [comment]
Why would this need a separate issue specifically for macOS? Wouldn't providing CLI args work across all platforms?

**Comment by szpasztor** [comment]
Since the app is bundled as .dmg, there's no "decrediton" executable by default, creating it is OS specific.

**Comment by szpasztor** [comment]
Did a bit more research and creating/linking the executable shouldn't need significant extra code, closing this.
