### ISSUE TITLE
Visual Design: Receive view

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1943]
Preview: https://xd.adobe.com/view/81c6e4d1-9033-42a6-574b-fffc62106367-f7f7/
Specs: https://xd.adobe.com/spec/f89751ab-7634-4720-5336-2872e46247ac-8ea6/

Similarily removed the Accounts reference icon. 
Seems in last release, the blue background behind address has been lost, should be added again. 

@alexlyp @matheusd @davecgh – been thinking of potential UX improvements for this view. Two features in mind are: 
1) allowing the users to view previously generated addresses or spin through the possible addresses
2) provide some kind of data feedback on which addresses have been used (maybe in simple and obfuscated way e.g. marking an address with sent or received action). 

Reason being is giving more convenient feedback on the matter. For example the user could see right away whether an address has already been used or not instead of going to the blockexplorer to double check. Not sure if these have been considered, but would like to hear the opinions regarding any security implications and technical limitations.

**Comment by vctt94** [comment]
I think that showing used addresses would be a good improvement, but wouldn't that be better in transactions's history? This way we can show used addresses, how much received for a specific address, how much spent. 

Maybe all this information at this page would be too much information, although it is a very clean page. What do you think?

**Comment by linnutee** [comment]
If there's no security concerns about this, i'll produce a quick prototype to see what would work.

Agree that both pages would be relevant for these features, would lean towards receive as that simply has the space available to cover those as another section in the layout, whereas in History view would likely need to re-organise the structure more. 

I'll do initial tries in the Receive view and explore also some hybrid options between the two views.

**Comment by vctt94** [comment]
Any updates on this?

**Comment by linnutee** [comment]
I'll follow up on this one.

**Comment by linnutee** [comment]
Closing this issue as I've discussed the points suggested above quite some time ago and it turned out there's quite some security concerns and possibility of these leading to bad practices. 

I'll however make another issue to cover a few other items which i've got listed down for improving the receive view.
