### ISSUE TITLE
Visual Design: Staking and Add stakepool

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1944]
Preview: https://xd.adobe.com/view/fd838cbb-8653-4313-6599-4a642bceec2c-8bb2/
Specs: https://xd.adobe.com/spec/b81ed559-a7e2-423e-7ae6-56ded3c85b33-ce2f/

- For add stakepool, think it might be a bug as the "manually import a redeem script for tickets" should not be displayed there: 
![](https://user-images.githubusercontent.com/17774057/50377613-24108900-0629-11e9-982a-c0a9ac4512fa.png)
- Included a view when "add a new stakepool" is opened from the stakepools settings, displays a cancel button next to continue then. 
- On purchase tickets view, repositioned the info icon to the top to improve the layout. This way the Ticket stats and buyer cards can be brought much closer together. 
- Removed the account icon reference (next to field) as elsewhere. 
- Created a new design pattern for add/reduce ticket amount, as the old one was not as convenient. 

[decrediton - plus and minusWhite.zip](https://github.com/decred/decrediton/files/2705448/decrediton.-.plus.and.minusWhite.zip)

**Comment by matheusd** [comment]
We need _a_ import script button somewhere when the wallet does _not_ have any stakepool APIs imported.

This is due to the import script being an alternative to directly contacting the stakepool and useful for stuff other than just ticket buying (eg: multisig transactions, which we don't currently support in decrediton but probably should add at some point).

**Comment by vctt94** [comment]
Any update on this?

**Comment by linnutee** [comment]
@vctt94 slight update on this one, realized the specs on the last one seemed to be bugged around the alignment, fixed that + replaced the icon for import script. Since importing script is likely secondary interaction compared to the API key use, I think its fine to be kept where it is right now. 

Note that i've aligned the import script icon -1px on X in comparison to the text block (Create account...) above in order to optically account for the icons bounding box. 

Prev/Specs: https://xd.adobe.com/view/92bb5119-6df0-4a45-448a-44c33ac00f65-e48a/
Icon/states: [decrediton - import script icons.zip](https://github.com/decred/decrediton/files/4402420/decrediton.-.import.script.icons.zip)

**Comment by vctt94** [comment]
Thanks for the update linnutee
