### ISSUE TITLE
Responsive views: Overview

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1946]
Responsive views master issue: https://github.com/decred/decrediton/issues/1820 

Preview: https://xd.adobe.com/view/f803fd3f-cbb2-412d-7b9c-b3878e8bcb5d-8e32/
Specs: https://xd.adobe.com/spec/3893e71c-63bc-41b8-77f3-6f7aa0ed6e6f-4ea2/

Starting this with the overview. All following issues will be posted in a similar format, that include these three key views. In i've not covered a specific state of a view that needs more insight, please remind me. 

Briefly the overview needs no adapation in 768px size, as the rows can simply scale down in width and the graph can be re-positioned slightly. 

In 375px mobile view however will need to replace the graph selector with a smaller variant of it, where instead of textual labels are icons. The textual graph data is positioned below the graph; and instead of 14 dates, the graph should display only 12. This way the size of it can remain the same. 

Also the navigation in the mobile view should obviously be on the bottom of the viewport and always visible above the content (just mentioning if the example is confusing).
[decrediton - graph selector icons.zip](https://github.com/decred/decrediton/files/2705383/decrediton.-.graph.selector.icons.zip)

**Comment by jholdstock** [comment]
I notice the page here says "24 active tickets"

Should this not be "24 live tickets"?

**Comment by linnutee** [comment]
"Active" here is meant as an umbrella term, as the charts display a combination of both immature and live tickets.
