### ISSUE TITLE
Responsive views: Transactions/Send

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1947]
Responsive views master issue: https://github.com/decred/decrediton/issues/1820 

Preview: https://xd.adobe.com/view/0302e86a-8ac1-4c5c-5863-6dd8e2e64323-7533/
Specs: https://xd.adobe.com/spec/102ceee8-2aa4-4575-7b7d-a64f61f56457-661d/

Changes needed to the send view are covered in a previous issue. In 768px tablet size, the content card can be scaled down in width while reducing the spacing between total amount sent and the amount. Field sizes are retained the same. 

In mobile 375px, the details part is repositioned; its content is also slightly repositioned. Field titles (from: to: amount:) font sizes reduced.

**Comment by vctt94** [comment]
I have a question about this design.

When having multiple addresses, this view looks as the following right now:

![image](https://user-images.githubusercontent.com/15069783/59376032-be729f00-8d25-11e9-9d9f-55cb12a1e1c9.png)

How does this view should look when having multiple addresses after the redesign?

**Comment by linnutee** [comment]
Basing this off the previous issue on the design update: https://xd.adobe.com/view/3fe77764-ecd0-41c7-7e5e-5a6487e983ef-49d6/

So the simplest way should be:
- if another address/amount is added, send max is disabled (or even hidden altogether for smaller viewport) 
- plus icon moves down to the new to/amount section
- previous one shows a remove X

Quick mockup: https://xd.adobe.com/view/60537fa6-6df1-4b84-4774-7b940553357f-1662/
Specs: https://xd.adobe.com/spec/443b5c03-ec60-4bab-71f5-65d36fc1c410-320a/
