### ISSUE TITLE
Responsive views: Transactions/Receive

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1948]
Responsive views master issue: https://github.com/decred/decrediton/issues/1820 

Preview: https://xd.adobe.com/view/8cca62bc-8b80-46ae-47ca-dd1ce305614e-fafb/
Specs: https://xd.adobe.com/spec/251e94bc-3c1a-429a-6934-0d650f398f11-532f/

Tablet 768px largely the same as desktop view, content card scaled in width, while elements retain size and position. 

For mobile: elements repositioned in top down manner; field title font size reduced; address font size reduced; QR code size increased

**Comment by bgptr** [comment]
I'm working on this.
