### ISSUE TITLE
Responsive views: Transactions/History

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1949]
Responsive views master issue: https://github.com/decred/decrediton/issues/1820 

Preview: https://xd.adobe.com/view/4aadd355-8691-4b7c-6cde-c8b39f5d9380-3c9c/
Specs: https://xd.adobe.com/spec/b814d6c2-0f4d-4b53-59c1-a71d8f3ff077-ce25/

Tablet largely same again, scaling the width of rows. 

For mobile use same pattern as in overview (with rows containing less amount of information). `Filter by address ` is scaled in width in order to align with the layout better.

Also referring to updates posted in: https://github.com/decred/decrediton/issues/1942

**Comment by vctt94** [comment]
Is this history tab supposed to show only tx not related with tickets?
