### ISSUE TITLE
Responsive views: Transactions/Export

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1950]
Responsive views master issue: https://github.com/decred/decrediton/issues/1820 

Preview: https://xd.adobe.com/view/14802504-08ac-4a86-4876-28cac7fd21eb-62b1/
Specs: https://xd.adobe.com/spec/bfc3b6e6-e641-46cb-56db-594a5de9852b-c9f2/

Desktop and tablet largely the same, mobile repositioning the description part in top down manner.

**Comment by bgptr** [comment]
I'm working on this.
