### ISSUE TITLE
Responsive views: Transaction Details

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1951]
Responsive views master issue: https://github.com/decred/decrediton/issues/1820 

Preview: https://xd.adobe.com/view/ffa08ee0-45e5-4daf-5fb5-3c51de25efd3-8991/
Specs: https://xd.adobe.com/spec/68180e46-60bf-4ad8-709e-9ad15191f137-1e29/

In tablet only scaling down the spacing. 

In mobile i've kept all the element sizes the same as much as possible. 
Top header area (with white background): in case there are more detail items, these should stack in a row and increase the header area height) 
Secondary header area (light grey): only change is rebroadcast icon being centrally aligned for consistency. 
Content area: I/O details are stacked top down and the arrow is also facing down accordingly. 
Raw transaction element is scaled down in width; repositioned slightly under the element title and copy to clipboard icon is also slightly repositioned.

**Comment by bgptr** [comment]
I'm working on it.
