### ISSUE TITLE
Responsive views: Purchase Tickets

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1956]
Responsive views master issue: https://github.com/decred/decrediton/issues/1820 

Preview: https://xd.adobe.com/view/a00f9e86-6e82-420a-4026-26be4cdc5b7b-d63e/
Specs: https://xd.adobe.com/spec/da214bb6-7903-40e0-7f51-15fa9b643578-ac10/

Few tweaks addressed in: https://github.com/decred/decrediton/issues/1945. Otherwise field titles type sizes reduced in mobile, elements repositioned down-town.

**Comment by vctt94** [comment]
Did the auto purchase ticket move to another place?

**Comment by linnutee** [comment]
Hrmm nope. Just seems to have gone missing on the design. However do keep it as it is.

**Comment by linnutee** [comment]
I'll open another issue for a small alignment fix regarding that on the next week. Seems to have gotten a bit broken over time.
