### ISSUE TITLE
GetTransactions on huge wallets causes run away memory usage

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#197]
When dealing with very large wallets, decrediton is failing when trying to process all of the transactions returned from the getTransactions rpc request.  

Garbage collection should be freeing these but currently it is not.

**Comment by jcvernaleo** [comment]
Just to give a sense of what large means, one of my wallets from the start of testnet (so txes from almost the first block up until a month or so ago) is the one with a problem.

**Comment by alexlyp** [comment]
https://github.com/reactjs/redux/issues/768

This issue's discussion seems to point to a possibly incorrect usage of Array() in state.  ImmutableMap or some over data structure appears to be the solution.   ie previous state is not copied on successive data pushes

**Comment by alexlyp** [comment]
I was able to grind electron with 100K+ dummy GETTRANSACTIONS_PROGRESS actions.  So that can as our benchmark towards solving it.

**Comment by alexlyp** [comment]
This has been resolved, but we will be implementing Immutable.js during the #528 refactor.

After that audit issues like this will never remain.
