### ISSUE TITLE
[refactor] Remove duplicate spvMode selector

### ISSUE THREAD

**Issue by szpasztor** [decred/decrediton#1974]
The [spvMode](https://github.com/decred/decrediton/blob/8c6cec3c5692ae4a19518a1dcb4209b3e6a3eb38/app/selectors.js#L664) and [isSpv](https://github.com/decred/decrediton/blob/8c6cec3c5692ae4a19518a1dcb4209b3e6a3eb38/app/selectors.js#L183) selectors query the same thing.

**Comment by vctt94** [comment]
We do not have 2 selectors anymore, but the config file (spvMode) and isSPV selector still have different names, and because of that I am not closing this issue. 

If you guys are okay with that, feel free to close it.
