### ISSUE TITLE
[launcher] Misaligned wallet components

### ISSUE THREAD

**Issue by szpasztor** [decred/decrediton#1977]
Some window sizes cause the app to display weird layouts, eg.: 

- 900x855 px
![image](https://user-images.githubusercontent.com/8398290/51046115-88d65800-15c5-11e9-9a8d-04ad03b72b54.png)

- 1140x855 px
![image](https://user-images.githubusercontent.com/8398290/51046170-ae636180-15c5-11e9-9b64-a4e56aba2ae8.png)

**Comment by vctt94** [comment]
Closing this one
