### ISSUE TITLE
The "Restore Existing wallet" prompt Unfriendly

### ISSUE THREAD

**Issue by 0x5826** [decred/decrediton#1980]
I tested "Restore Existing wallet"under decrediton 1.4.0 rc2.

- When I type the first word, The Decrediton prompt "**Error: 3 INVALID_ARGUMENT: walletseed.DecodeUserInput: invalid encoding: encoding/hex: invalid byte: U+0072 'r'**"

- When I type the second word, The Decrediton prompt "**Error: 3 INVALID_ARGUMENT: walletseed.DecodeUserInput: invalid encoding:: pgpwordlist.DecodeMnemonics: word absurd is not valid at position 1, check for missing words**"

I think those notices will make people misunderstand, Could we optimize it?

**Comment by vctt94** [comment]
I can fix that. 

Would `Word not valid at this position`, be better?

**Comment by 0x5826** [comment]
nice！

VcTT <notifications@github.com>于2019年1月15日 周二下午8:46写道：
