### ISSUE TITLE
Wording on Fatal error screen

### ISSUE THREAD

**Issue by peterzen** [decred/decrediton#1992]
* "Suggested action to resolve *the* error"
* Rockchat -> *Rocketchat*
* Maybe add a link to https://www.decred.org/community/
* The "Please note" box seems misaligned 
![image](https://user-images.githubusercontent.com/5878500/51378305-4654d400-1b0d-11e9-9583-c80af75a8631.png)

**Comment by s-ben** [comment]
Is this issue still in play? Thinking of tweeting it out on the [Good First Issues (GFI) twitter](https://twitter.com/dcrgoodfirst) feed.

**Comment by vctt94** [comment]
Yeah, this still an issue. But @peterzen may be right and it does take some effort to get there.

So I'll fix it
