### ISSUE TITLE
Visual Design: Settings View

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1995]
Preview: https://xd.adobe.com/view/751d0061-ad52-45a0-75c8-7776e95a6e97-032c/
Specs: https://xd.adobe.com/spec/45d7a71d-b6df-4b65-70bb-8bf5afbedf6e-33e6/
Icons: [decrediton - settings icons - 190119.zip](https://github.com/decred/decrediton/files/2775876/decrediton.-.settings.icons.-.190119.zip)

Minor visual design updates for better housing of the content + other smaller improvements.

1) As the initial layout was designed around very few items, the current alignment has reached its capacity for optimal use. I've re-designed the layout slightly to have two more distinct columns which can be populated further. This was also needed for the responsive views follow-up. 

2) Small fix: Close Wallet button styling should be updated. Consistent with secondary button style. 

3) Gap limit: has a broken icon, replace with new included in zip. 

4) Toggle Theme: changed to dropdown, section title: `UI theme` content: `Tonality: Light / Dark` (ps. I would recommend having this hidden/disabled for a full release and aim for an designed version for 1.5.0)

**Comment by szpasztor** [comment]
I'll take this. 

@linnutee Is there any reason behind the 1179x915 size in the spec vs 1178x790 (default for the app)?

**Comment by linnutee** [comment]
Good notice, i'll get that fixed for the future specs. 

The default desktop sized layouts have historically been 1180 px width in the designs. However I see i've got some odd artboards as 1179 px come to play at an unknown time. Probably due to some mistake or export bug.

Not sure about the 1178 px within app. As it's a 1 or 2 px difference and only affects the right side safe area – can be just kept as it is for now imo.

<img width="979" alt="screenshot 2019-02-15 at 20 03 49" src="https://user-images.githubusercontent.com/17774057/52875415-f2b1c680-315c-11e9-9c0e-3f6b462473b0.png">

**Comment by vctt94** [comment]
Closing because it is outdated. Newest issue:  #2253
