### ISSUE TITLE
Global colors fix: change all #00000 to #091440

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1997]
Some of the views (including field titles) still contain #00000, that should be globally changed to #091440

In relation to https://github.com/decred/decrediton/issues/1423

<img width="935" alt="screenshot 2019-01-21 at 18 44 51" src="https://user-images.githubusercontent.com/17774057/51487808-a9b06180-1dac-11e9-9f63-783eab594469.png">

**Comment by vctt94** [comment]
This has been addressed
