### ISSUE TITLE
Responsive views: Security Center

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#1999]
Responsive views master issue: #1820

Preview: https://xd.adobe.com/view/baa71cfa-6f11-49b2-4ba5-1a99dba89992-cc96/
Specs: https://xd.adobe.com/spec/a37df407-906c-4090-6413-341e8ac42892-d54c/

No significant adaptations/changes on scaling. Sign and Verify message tab changes on smallest viewport from fixed/left alignment to center alignment.

**Comment by bgptr** [comment]
I'm working on this.
