### ISSUE TITLE
Responsive views: Settings

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#2000]
Responsive views master issue: #1820

Preview: https://xd.adobe.com/view/2770aadf-642c-4936-6347-efd97b56a16d-5141/
Specs: https://xd.adobe.com/spec/d57694d8-4994-422e-5205-fdffd34564a4-a347/

Two content columns are stacked in top-down manner when scaling to smallest view.

**Comment by bgptr** [comment]
I'm working on it.
