### ISSUE TITLE
Last line of each RFP is getting cut off

### ISSUE THREAD

**Issue by dre-tech** [decred/decrediton#2014]
When comparing the text of the RFP in Decrediton to the text in Politeia it looks like the last line of each RFP is not making it into Decrediton. This affects all the RFP articles in Decrediton 'Under Discussion', 'Finished Voting' etc.
![last_line](https://user-images.githubusercontent.com/47340186/52314373-f03eb800-2977-11e9-8bb2-d19a2ff10857.png)

**Comment by vctt94** [comment]
This has been addressed
