### ISSUE TITLE
Start sync during tutorial instead of after

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2016]
The current flow of the setup wizard is as follows:

- Select language 
- Privacy options 
- SPV mode 
- Decred tutorial

Synchronization is only started *after* all of these steps are completed, however I believe the user experience may be improved if it is started after the SPV mode is selected and while the tutorial is still being shown.

It is possible for a user to spend significant amount of time on the tutorial - they may want to google terminology or to make notes - and the chain sync could be running in the background during this time.

**Comment by szpasztor** [comment]
I'll take this.
