### ISSUE TITLE
[1.4.0] Inconsistent caps

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2018]
On the governance page, proposals can be filtered by "Under Discussion", "Under Vote", "Finished voting" and "Abandoned".  For consistency I suggest capitalizing the V for "Finished voting"

**Comment by way-finder** [comment]
On the tickets page in SPV mode, the "Live Tickets" is listed as "Unspent Tickets". Could we either have the title changed or a tool tip explaining the word "Unspent Tickets"
