### ISSUE TITLE
[1.4.0] Ticket info drops off the bottom of panel

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2020]
The ticket purchase info above the blue "Purchase" button is dropping off the bottom of the gray panel:

![screenshot from 2019-02-07 12-12-21](https://user-images.githubusercontent.com/6762864/52410882-b97cb500-2ad1-11e9-9cff-de0cd20462a1.png)

**Comment by linnutee** [comment]
Design reference within this issue: https://github.com/decred/decrediton/issues/1944
I'll add another view there with the Automatic Buyer included also.
