### ISSUE TITLE
Feature to delete corrupt db

### ISSUE THREAD

**Issue by xaur** [decred/decrediton#2026]
Is it possible for Decrediton to auto-detect corrupt database and take some action?

If not, at least the button to rebuild the database is needed somewhere in Settings or Maintenance (if there is such a thing, I'm not using Decrediton).

Good example of user confusion that can be avoided:

> davecgh: That's pretty clearly a corrupt db  
> LordAjax: How do I fix it?  
> LordAjax: There's no "reload database" button.

And then he needs to go and delete the file.

From [chat](https://matrix.to/#/!dhHYPTtCtvPSUfTepT:decred.org/$154948766931170jgaRT:decred.org).

**Comment by alexlyp** [comment]
This is already the case.  When a panic or unexpected exit from dcrd is observed.  The user is shown a button that will delete their dcrd data directory and then they are told to restart decrediton.

**Comment by xaur** [comment]
Great! I assume the user in that chat was not using the latest version where this was implemented? Closing, please reopen if needed again.

**Comment by alexlyp** [comment]
Must be.  This feature was available in 1.3.0+ i believe.  There were some bug fixes with it added in 1.4.0, if they aren't seeing that page I'd like to revisit this issue and narrow down what exactly they are seeing.
