### ISSUE TITLE
[tickets] Auto buyer is not properly shut down on wallet close 

### ISSUE THREAD

**Issue by szpasztor** [decred/decrediton#2029]
Follow-up to https://github.com/decred/decrediton/issues/1923

Reproducing:
1. Open wallet, start auto buyer
2. Settings > close wallet > confirm

At this point, the buyer still hasn't been not shut down:

![image](https://user-images.githubusercontent.com/8398290/52703929-c2610100-2f7f-11e9-81bf-1481264652a4.png)

**Comment by matheusd** [comment]
Resetting this to false needs to be added to the appropriate CLOSEWALLET_SUCCESS reducer.

**Comment by vctt94** [comment]
fixed
