### ISSUE TITLE
Estimated Fee Displayed Incorrectly on Send Screen

### ISSUE THREAD

**Issue by oregonisaac** [decred/decrediton#2031]
User reported issue, when sending a transaction in v1.4.0 the total shows the correct (newly reduced) fee total, but the estimated fee is off by one decimal point.  See image below.

![image](https://user-images.githubusercontent.com/4402603/52776539-aea4b180-2ff6-11e9-9105-d0abc4cdac5b.png)

**Comment by 0x5826** [comment]
Yes, I got the same problem.

**Comment by alexlyp** [comment]
KK simple fix.

**Comment by szpasztor** [comment]
I can confirm too.
