### ISSUE TITLE
[advanced daemon] Add timeout when starting with wrong parameters

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2037]
When starting a remote daemon in advanced mode, if the parameters are wrong, decrediton will keep trying to connect without failing.

We should have a timeout after a time trying to connect and throw an error.

How to reproduce: 

- Start decrediton in advanced mode
- Choose advanced daemon 
- Add a wrong parameter, like the port

On this point, decrediton will stuck on the launching daemon page.

**Comment by matheusd** [comment]
Confirmed it's an issue.

**Comment by vctt94** [comment]
I can take this one
