### ISSUE TITLE
Show notification before opening Governance page

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2042]
![screenshot from 2019-02-20 08-10-03](https://user-images.githubusercontent.com/6762864/53076340-5cc4c580-34e7-11e9-8ed1-276b3950b019.png)

When the 4 new proposals went up on Politeia, I only received a notification in Decrediton **after** opening the Governance tab (see the red box).

The Governance tab is not something users would open every day, so this would be easy to miss. A notification **before** opening the tab, eg in the blue box, would be nice. 

I have a vague memory of this feature already existing - I'm sure I have seen a notification in that location before...

**Comment by matheusd** [comment]
The notification on the main menu should only appear if there are new proposals in the voting stage (as requested in the original issue: https://github.com/decred/decrediton/issues/1832)

**Comment by jholdstock** [comment]
@linnutee as you wrote the initial spec, what do you think about my suggestion above?
