### ISSUE TITLE
[governance] standardize with [politeia-public proposals]

### ISSUE THREAD

**Issue by ghost** [decred/decrediton#2047]
For Decrediton / macOS / 1.4.0 / SPV mode 
- “Under Discussion” (currently 4 proposals)
- “Under Vote” (currently 3 proposals)
- “Finished voting” (currently 8 proposals)
- “Abandoned” (currently 5 proposals)

For Politeia / Public Proposals
- “all proposals” (currently 18 proposals)
- “pre-voting" (currently 4 proposals)
- “active voting” (currently 3 proposals)
- “approved” (currently 5 proposals)
- “rejected” (currently 6 proposals)
- “abandoned” (currently 5 proposals)

Note:
- Similar issue opened in politeiagui repository. https://github.com/decred/politeiagui/issues/1025
- Not all ("approved" proposals in Politeia) are showing up in ("Finished voting" Decrediton).

**Comment by vctt94** [comment]
This discussion has already been started: https://github.com/decred/decrediton/issues/2015

**Comment by find34** [comment]
Let me know if you think this issue should be deleted. I didn't catch the prior post.

**Comment by vctt94** [comment]
I do not think there is need to close this issue as this one is more descriptive then the other one, but it is good let the discussion centralized only on one place. There is this issue at politeiagui to discuss about it: https://github.com/decred/politeiagui/issues/1013
