### ISSUE TITLE
Show GUI progress for reindexing.

### ISSUE THREAD

**Issue by fulldecent** [decred/decrediton#2049]
When opening 1.4.0 for the first time, if SPV is disabled, then you will see 

> Waiting for daemon connection...

and fan spins to 100%.

But the dcrd log shows: 

> 2019-02-24 10:55:10.998 [INF] CHAN: Reindexing to height 185750 of 320218 (progress 58.01%)...

This is a long-running process that can be expected by the GUI. So the GUI should inform the user about what is happening.

**Comment by alexlyp** [comment]
There should be text to describe what is occuring, and the logline from dcrd should be shown to show that same information.
