### ISSUE TITLE
Change Decred logo to sold dark blue version in launcher

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#2050]
Replace blue-green DCR logo with solid dark blue one:
![image](https://user-images.githubusercontent.com/8841018/53323935-8bc8a600-38f0-11e9-8f75-8dcd3884c6f7.png) 
->
![image](https://user-images.githubusercontent.com/8841018/53323948-98e59500-38f0-11e9-9b65-e7275877df8a.png)

Attaching SVGs below (full logo with Decred sign is for desktop views, and just DCR symbol is for mobile views)

[Dark blue logos.zip](https://github.com/decred/decrediton/files/2899539/Dark.blue.logos.zip)

**Comment by bgptr** [comment]
Hi there! I'd like to work on this.
