### ISSUE TITLE
Responsive views: Launcher overview

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#2059]
Responsive views master issue: #1820

Previews: https://xd.adobe.com/view/4b423e19-fcf1-44dd-4705-84e02ed3ead0-3d73/
Specs: https://xd.adobe.com/spec/ce37e6a7-cba5-4ee1-5d24-19413a1ac84c-b806/

When scaling down, in tablet if there's only 1 wallet created, all of these square buttons will be in 1 row.
![image](https://user-images.githubusercontent.com/8841018/53337078-626c4200-3911-11e9-8934-f7f16bec7104.png)
But if there are at least 2 wallets created, "Create a new wallet" "Restore existing..." buttons will move down under the first two.

In mobile the size of these buttons was reduced. Launcher was moved to the bottom of the screen. "Settings" and "Logs" items were moved under the Settings icon 
![image](https://user-images.githubusercontent.com/8841018/53337695-2fc34900-3913-11e9-8af6-a811b0bb991f.png)

Also full logo was changed to DCR symbol only.

**Comment by bgptr** [comment]
I have a question. When the "Settings" and "Logs" items move under the Settings icon in mobile, what should happen on click event? Is it just a link to Settings page?

**Comment by vctt94** [comment]
Yeah, right now they are wrapped by an invisible button with an onclick event. 

I believe you can use them to show in the settings icons as well. And if you wrap them by a function, like:

```
const settingsLogsButtons = () => (
  <>
    <InvisibleButton onClick={onShowSettings}>
      <SettingsLinkMsg />
    </InvisibleButton>
    <InvisibleButton onClick={onShowLogs}>
      <LogsLinkMsg />
    </InvisibleButton>
  </>
);
```

I believe it will not be a problem to reuse them.

**Comment by bgptr** [comment]
Ok. Thanks for the quick answer. I'm on it.

**Comment by bgptr** [comment]
@MariaPleshkova, can I get your opinion on the settings icon functioning? There is a conversation already in this PR(#2189)
