### ISSUE TITLE
Responsive views: Advanced Daemon (3 states)

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#2062]
Responsive views master issue: #1820

**Advanced Daemon-1**
Previews: https://xd.adobe.com/view/138c363d-e807-445a-4792-e89cd1a9573a-65bd/
Specs: https://xd.adobe.com/spec/cb465abd-ab7f-4d52-68ab-0fffde6a4f2e-bd77/

**Advanced Daemon-2**
Previews: https://xd.adobe.com/view/888dec94-fc4e-429d-57c4-1d88c2a5a562-febc/
Specs: https://xd.adobe.com/spec/43038ac3-4620-4e56-5695-26266597aa99-3532/

**Advanced Daemon-2-2**
Previews: https://xd.adobe.com/view/ecec2634-dd52-4fe1-63c6-2a7052674245-9add/
Specs: https://xd.adobe.com/spec/53c377ad-8c18-4c34-463a-e9bb829dfe59-25f2/

When scaling down, launcher line is sticked to the bottom of the page. "Settings" and "Logs" items are moved under the Settings icon
![image](https://user-images.githubusercontent.com/8841018/53340121-3bb20980-3919-11e9-9a34-f60912bbaa6b.png)
Buttons "Start AppData Daemon","Skip" / "Connect to remote", "Skip" are moved to the bottom of the screen, but above the launcher line.
Also full logo in mobile is changed to DCR symbol only.

**Comment by vctt94** [comment]
I like it, but the remote and local forms are switched. Otherwise it looks good

**Comment by MariaPleshkova** [comment]
@vctt94 Fixed this

**Comment by vctt94** [comment]
Great! Just one suggestion, I'd prefer the remote form as the first one, as I have the feeling people use it more (at least for dev).

We can also add a last used form and bring the one used as activated

What do you think?
