### ISSUE TITLE
Scroll Issue: Governance/Proposals - Unable to reach bottom of proposal

### ISSUE THREAD

**Issue by oregonisaac** [decred/decrediton#2064]
When pulling up a proposal, unable to scroll to the end to read the last bit of the proposal.

![decrediton - unable to scroll to bottom - win10 3200x1800](https://user-images.githubusercontent.com/4402603/53372258-3cda3b00-3907-11e9-96a6-63660138f764.GIF)
![decrediton - unable to scroll to bottom - win10 3000x2000 2](https://user-images.githubusercontent.com/4402603/53372337-714df700-3907-11e9-85b0-5fc574a812cb.GIF)
![decrediton - unable to scroll to bottom - win10 3000x2000](https://user-images.githubusercontent.com/4402603/53372338-714df700-3907-11e9-8475-4cf4d5f047fd.GIF)

Reported/replicated on Windows 10 in 3000x2000 zoom2x, 3200x1800 zoom2x, 1920x1080 zoom1x and MacOS Mojave in 1080P

**Comment by vctt94** [comment]
This is being fixed at https://github.com/decred/decrediton/pull/2045
