### ISSUE TITLE
Voting preferences changes in the consensus change subsection of Governance section do not apply to all VSPs linked to wallet

### ISSUE THREAD

**Issue by 0x0K** [decred/decrediton#2074]
I observed that when I register with two VSPs (A & B added to Decrediton in that order), my voting consensus changes made in Decrediton only propagate to VSP A, but not VSP B.

Since the UI does not allow me to choose VSPs in this section, my assumption is that voting preference changes apply to all VSPs associated with the wallet.  This also is consistent with the behavior of preferences on proposals (all votes in the wallet must vote for the same option) and also makes intuitive sense.

**Comment by matheusd** [comment]
Just tested and decrediton 1.4.0 does change the voting bits for all configured VSPs at once.

However, it might be the case that a particular VSP hasn't (or hadn't) updated their dcrstakepool/wallets to the new agenda when you tried updating the voting preference, in which case it would return an error.

**Comment by vctt94** [comment]
I tested as well, and see no issues. All the VSPs were updated.

Can you confirm if is this an issue and explain how to reproduce or close it? @0x0K

**Comment by vctt94** [comment]
closing by inactivity
