### ISSUE TITLE
[discussion] Add new RPC connection to dcrd

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2082]
@matheusd Once suggested we could open a new rpc connection to dcrd so we can make some calls directly, instead of using dcrctl, as we do right now. Here it is: https://github.com/decred/decrediton/issues/1753

And discussing on matrix about adding a way to verify anchored transactions by dcrtime at decrediton, with this rpc connection it would be possible to verify it directly by the anchored file hash.

Discussion: https://matrix.to/#/!gltiHJRZiSJTzvjOEu:decred.org/$1553875230499wyjcF:decred.org?via=decred.org&via=matrix.org

So I think it would be good to have this new rpc connection

**Comment by davecgh** [comment]
I'm surprised it doesn't already have that to be honest.  It's far more reliable and efficient than shelling out to a separate utility.

**Comment by vctt94** [comment]
closing as #2088 is already merged
