### ISSUE TITLE
Dark Mode: Master Issue

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#2089]
Created this master issue used for reference to all implementation issues around the dark mode. 

Key drivers and notices: 
- Color scheme: this needs to be separately defined in order not to mix things up. The current (light) scheme's blue and grey have been chosen to only perform for light mode. However for dark mode, the blues/greys making up bulk of the UI structure are a reverse-split with adjusted contrasts and a few tweaks in order for the scheme perform up to accessibility contrast standards as well result in similar but reversed optical look/feel. 

- Listing the only key colors that overlap in both light and dark mode: `#2970FF #2DD8A3 #091440 #69D5F7 #E9F8FE #ED6D47 #FEB8A5 #41BE53 #C4ECCA #FFC84E #FFE4A7`
All dark mode colors used: https://xd.adobe.com/view/63e0674b-87d1-4a81-456c-7d3ea16e1c6a-15d1/

- Iconography: Majority of the icons received a dark mode alternative version. Following a naming convention w/ adding a camelCase Dark at end of icon names. Assuming the presently animated icons will need to be re-rendered also? @kyleFirethought?

- Components: UI components only require change of color, no form or other properties have been changed. 

- /Dcrdesign issue w/ master files https://github.com/decred/dcrdesign/issues/105 

@MariaPleshkova will be posting the individual key views for reference. These should cover all of the common components used in Decrediton. 

Additionally would request for compiling a named list of the current release front-end components (ideally with previews). We can replicate that in the master visual design files to keep better track of those and streamline any future updates. The current visual design component sheet has not seen any updates for a long time and is likely overly synced up with the real implementation. So ideally we'd end up with one for light mode and one for dark mode. Once dark mode is implemented, any updates concerning components will need to reflect in both instances.

**Comment by MariaPleshkova** [comment]
Posted in-app and launcher kew views to decred/decrediton#2122 and decred/decrediton#2123
