### ISSUE TITLE
[Export] BUG: Inconsistent balances in Daily Balance CSV

### ISSUE THREAD

**Issue by emesterhazy** [decred/decrediton#2097]
#### Issue Description
I am experiencing two issues with the daily balance CSV export:
1. The daily balances exported from v1.4.0 do not match a previous export I made from v1.3.x. For example, the v1.3.x export may report 102.321 DCR on 12/31/2018 but a subsequent export from v1.4.0 reports 100.876 DCR on 12/31/2018. I know the second balance is wrong because of the second point below.

2. The sum of the `spendable`, `immature`, and `locked` columns in the export do not equal the `total` column. For certain dates the discrepancy can be > 100 DCR.

#### Expected result
For days that have closed, the daily balance in the CSV should not change between exports. The sum of the `spendable`, `immature`, and `locked` columns should equal the `total` column.

#### Versions Affected
Experiencing this issue with Version 1.4.0. I was able to export a correct CSV from Version 1.3.2

#### Steps to reproduce
1. Be running decrediton with staking turned on
2. Export the Daily Balances CSV file from v1.4.0
    * This is sufficient to surface issue 2
3. Export the Daily Balances CSV from v1.3.x and compare to v1.4.0 export
    * Necessary to surface issue 1

**Comment by matheusd** [comment]
Was there any change in the wallet between exports, such as adding/importing VSP keys, rescanning, performing the export in wallets imported from the seed at different times, etc?

Is this a completely "regular" wallet (in that it only ever purchased tickets on decrediton using VSPs) or is there anything unusual on it (split tickets, solo voting, ran on a different computer or on a different seed import, etc)?

You used "12/31/2018" as an example date, but how far back is the actual date you noticed the change? One or two days before the export date or was it literally in 12/31/2018 (and you exported it yesterday)?

**Comment by emesterhazy** [comment]
I looked into this a bit more and firmed up the specifics in the original issue. It looks like multiple exports from the v1.4.0 wallet are consistent with each other, but do not match

**Comment by emesterhazy** [comment]
I looked into this a bit more and firmed up the specifics in the original issue. It looks like multiple exports from the v1.4.0 wallet are consistent with each other, but do not match the totals from a previous export made with v1.3.x. Previously I had said that multiple exports from 1.4.0 are not consistent with each other, but it looks like they are.

However, I believe the exports from 1.4.0 are incorrect due to the second issue I listed, which is that the columns within the CSV do not match the `total` column.

As far as the wallet, nothing unusual is happening there. The seed was imported on version 1.3.x and DCR was staked using a VSP. Later, the wallet was upgraded to 1.4.0 and staking continued.

The discrepancies I see in the CSV file go all the way back to the beginning of the wallet history, which is more than one year.

**Comment by matheusd** [comment]
Ok, thank you for the extended information. I'll take a look at this.

**Comment by emesterhazy** [comment]
Thanks! I'm contemplating downgrading the wallet back to 1.3.x in the meantime, but am concerned whether there are incompatibilities between 1.4 and 1.3 that could corrupt the wallet file. Obviously there's a backup of the wallet, but I'm trying to minimize headaches and downtime.

Would you expect any issues with downgrading from 1.4?

**Comment by matheusd** [comment]
You won't be able to downgrade, due to changes in the db structure and to the node.

At most, you could run 1.3 and re-seed, but you'll have to do this in the next few weeks only, since the 1.3.x branch will get forked off after the latest agenda is activated.

**Comment by emesterhazy** [comment]
Thanks, that's helpful information. Do you have any estimate on when a fix might be available? I need this data for a 1Q 2019 report, so I might need to run 1.3 separately and re-seed if this likely won't be resolved soon.

Appreciate the help.

**Comment by matheusd** [comment]
We have a fix already. Basically, the issue was that the "total" column was _not_ taking into account the balance changes for the last operation of the day, so on days where the last operation was (e.g.) a ticket purchase, you could get a large difference between the total column and manually summing up the columns.

You can either rely on directly summing up the columns on a spreadsheet software or compile a custom version of decrediton with the fix applied. We don't really have a timeframe for the next release yet.

**Comment by emesterhazy** [comment]
Thanks for the update. However, even when I sum the columns in the export from 1.4x there are discrepancies for some dates when compared to the previous export made under 1.3.x.

For example, the balance in the newer 1.4x file is over 200 DCR less on 12/19/2018 than in the new file (and there are many other dates like this). When summing the columns, only around 15% of the dates agree between the two files.

Do you have any thoughts on what might be causing this?

**Comment by vctt94** [comment]
I downloaded 1.3.1 version and run it as spv and it looks like the values are mismatching. 

I will take a deeper look on this issue.

If you want to do the same to compare, you can download the binary from here: https://github.com/decred/decred-binaries/releases/tag/v1.3.1

**Comment by matheusd** [comment]
> Do you have any thoughts on what might be causing this? Is it possible the last operation of the day is completely excluded from all columns?

Seems something like that, yeah. We can reproduce the problem now, seems like some transactions get offset into the next day, which ends up throwing the calculations off. We'll keep you posted once we have a fix for it.

**Comment by emesterhazy** [comment]
Thanks guys @matheusd @vctt94 . Any idea when this will appear in a release? I was using a watch-only copy of 1.3 but now I'm suck syncing at block 342913.

**Comment by matheusd** [comment]
Can't really say it authoritatively.

**Comment by emesterhazy** [comment]
Fair enough. I'd strongly recommend getting this out sooner than later since it affects everyone that has financial reporting obligations related to DCR.

Can you confirm if 1.3 should still work? It's hanging for me, and one of the previous comments mentioned that it would stop working soon.

**Comment by matheusd** [comment]
It won't work anymore, given it's been hardforked out of the network (due to the latest voting).
