### ISSUE TITLE
Balance Display incorrect/doesnt add up

### ISSUE THREAD

**Issue by Guang168** [decred/decrediton#2098]
![41555492323_ pic](https://user-images.githubusercontent.com/43533453/56276610-665c5980-6135-11e9-8053-dc718c937201.jpg)

In screen shot above, "Current Total Balance" correctly matches to "Total Balance", but "Available" + "Locked" does not add up. I use a VSP and the difference is approx amount voted but still locked in the ticket. 

Can we add another amount to reflect "Unlocked but still not available"

**Comment by zubairzia0** [comment]
If you go under accounts you can see the locked amount beside immature stake gen. IMO, to make things simple and for better UI experience, the overview page locked amount should include the immature stake gen amount as well.
