### ISSUE TITLE
Spanish Translation - "GetStarted"

### ISSUE THREAD

**Issue by Tricubeart** [decred/decrediton#2112]
TutorialPage01

# ¿Qué es la cadena de bloques de Decred?

En el corazón de Decred se encuentra una lista cada vez mayor de registros compartidos globalmente a través de un libro de contabilidad descentralizado; Esta es la cadena de bloques de Decred.

La cadena de bloques contiene todos los datos transaccionales de Decred y utiliza un innovador **Sistema de prueba de participación (PoS) / Prueba de trabajo (PoW)** para validar las transacciones y mantener la red segura.
Este sistema híbrido mitiga las debilidades que PoS y PoW tienen individualmente. Además, constituye la piedra angular para la **gobernanza inteligente** del proyecto.

La participación generalizada en **Staking (PoS)** y **Minería (PoW)** ayuda a proteger la neutralidad de la red y recompensar a los participantes con DCR recién generados en la recompensa por bloque.

TutorialPage02

# ¿Qué es una Cartera?

**La cartera es la herramienta para interactuar con la cadena de bloques y usar Decred como moneda**. Puede usarlo para enviar y recibir fondos de DCR, como un libro de contabilidad personal para registrar sus transacciones y participar en el Staking (PoS).

Las carteras son generadas de manera determinista por una clave semilla. La semilla mnemotécnica es una lista de **33 palabras** que se pueden escribir fácilmente en una hoja de papel para respaldo.

**La semilla funciona como una llave maestra** que almacena toda la información necesaria para recrear la cartera en cualquier momento, incluso si se olvida la frase de contraseña o se destruye la billetera. La misma semilla también se puede utilizar para exportar su cartera a otros clientes de cartera Decred.

**El hecho de no mantener en privado la clave semilla puede resultar en el robo de toda su cartera. Bajo ninguna circunstancia se debe revelar a otra persona**

TutorialPage03

# Staking y Gobernanza

La participación en el Staking (PoS) está abierta a todos y requiere tiempo para bloquear una parte de su DCR a cambio de tickets. El propósito de estos tickets es doble:

- En primer lugar, cumplen una función automática de votación sobre la validez de nuevos bloques.
- En segundo lugar, otorgan el derecho a participar en los procesos de toma de decisiones que determinan el futuro de Decred.

El proceso de Staking es esencialmente una lotería, donde los tickets se eligen para votar al azar. Un voto exitoso devuelve al participante el costo original del ticket y una parte de la recompensa por verificar el bloque como beneficio en el DCR recién creado.

En caso de que el voto se pierda (0.5% de probabilidad), el costo original del ticket se devuelve de manera segura sin la recompensa. El tiempo promedio de un ticket para votar es dentro de los 28 días y el máximo es de 142 días.

**El Staking fomenta la inversión a largo plazo en Decred** Los participantes reciben una voz real en la toma de decisiones y son recompensados por su participación en el Gobierno del proyecto.

TutorialPage04

# Consejos de seguridad

**Solo usted es responsable de su seguridad**. Siempre mantenga su clave semilla y contraseña seguras. Si las pierde, nadie más puede recuperarlas.

Haga una copía de seguridad de su clave semilla y contraseña. No lo almacene en su computadora, en vez de eso, escríbalo o imprímalo en una hoja de papel o guárdelo en una unidad USB.

No almacene su clave semilla en un almacenamiento en la nube o un servicio de contraseñas. Si su cuenta se ve comprometida, también pueden hacerlo sus fondos.

No ingrese su clave semilla en ningún sitio web. Nadie puede revertir, cancelar o reembolsar transacciones si su cartera ha sido comprometida.

**Cuando algo no parece correcto o usted no lo entiende, haga preguntas y haga su propia investigación. Evita tomar una decisión basada en el miedo.**

**Comment by matheusd** [comment]
Thank you for the translation, but issues are _not_ the correct way to send them if you want to do long-term contributions to the projects.

If you really want these (and eventually other) contributions to be included, you need to get familiar with git and send them as a github PR.

Please take a look at this: https://docs.decred.org/contributing/using-github/ and try to resubmit this as a PR so we can directly inlcude it as contribution.

Also I should note we generally only accept translations from people that are also contributing in other capacities for some time, so you should spend some time to get to know other members from spanish-speaking countries (preferably from wherever you are located) and interact with them o find other things you can help with.

**Comment by Tricubeart** [comment]
I get it.
I will send it again in the correct way.
and  I'm talking with Elian to expand this on the Hispanic side alright.
