### ISSUE TITLE
UI dark color scheme. In-app views

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#2122]
Master issue decred/decrediton#2089
This dark-mode blues scheme is initially only aimed for Decreditons dark mode (desktop views only) and not to be applied globally in DCR identity. There are only key views and their variants with notable differences in the .xd.
The structural elements as well most of the icons use new color scheme additions.
Although, color coded interactions and some elements keep their default colors (e.g. key blue, orange, yellow, green etc).
New color scheme and updated icon package included.

Preview: https://xd.adobe.com/view/15770d1b-f110-493f-465f-0c00fc6b6fd4-6346/
Spec: https://xd.adobe.com/spec/648bb599-05a1-4130-7e31-956a94708d0a-12ba/
Icons in SVG: [Dark mode icons_21.05.19.zip](https://github.com/decred/decrediton/files/3203366/Dark.mode.icons_21.05.19.zip)

**Comment by matheusd** [comment]
Some of the icons and text colors look a bit weird to me. The fact that the color scheme is _almost_ (but not exactly) [solarized](https://ethanschoonover.com/solarized/) is throwing me off, but that's a personal preference and if the rest of the design team is backing this up, then we'll go along with this.

Does the Adobe toolset you're currently using allow defining the color palette via css vars? We've managed to define all colors via vars (see [here](https://github.com/decred/decrediton/blob/master/app/style/Themes.less)) so if you could specify the theme colors corresponding to those that would make testing and integrating the changes super easy on our end.

In fact you can even define them on your own decrediton on runtime and test in practice if the palette is working. Hit me up on matrix if you want some instructions on trying that out.
