### ISSUE TITLE
[Governance] Improve error display when failing to fetch proposals

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2131]
When going to governance page, if decrediton fails to fetch proposals, it shows as there is no proposals available. We should show that an error happened instead, to better inform the user what happened.

![image](https://user-images.githubusercontent.com/15069783/58806602-ec9d0400-85ec-11e9-9d0b-e338f157195d.png)

**Comment by s-ben** [comment]
Hey @vctt94, is this issue still valid? Looking to [tweet out good first issues](https://twitter.com/dcrgoodfirst) and this look promising.

**Comment by vctt94** [comment]
Hey @s-ben, yeah it still an issue!

**Comment by guilhermemntt** [comment]
Fixing the issue. I'd like to collaborate, could someone assign this issue to me? Thanks!
