### ISSUE TITLE
decredition fails to start (30+ min. waited)

### ISSUE THREAD

**Issue by zallarak** [decred/decrediton#2137]
When I run `decredition`, it hangs on `Installing session intercept`

Any thoughts on how to fix this?

```
~/lib/decrediton-1.4.0$ ./decrediton --debug
2019-06-13 15:50:26.444 [INF] DCTN: Using config/data from:/home/zain/.config/decrediton
2019-06-13 15:50:26.445 [INF] DCTN: Versions: Decrediton: 1.4.0, Electron: 3.0.6, Chrome: 66.0.3359.181
2019-06-13 15:50:26.471 [ERR] DCTN: Locale  not found. Switching to locale en.
2019-06-13 15:50:26.473 [INF] DCTN: Setting up proxy null
2019-06-13 15:50:26.519 [INF] DCTN: Proxy successfully setup
2019-06-13 15:50:26.526 [INF] DCTN: Installing session intercept

```

**Comment by zallarak** [comment]
if it helps to know, i am running debian.

also, i waited for 30 minutes, and tried again.

**Comment by sammyt3812** [comment]
Close with continue on the thread plus you need to properly close the code thread as well

**Comment by zallarak** [comment]
@sammyt3812 can you clarify?

```
$ ps aux | grep decredition
zain     19988  0.0  0.0  12784   976 pts/10   S+   06:36   0:00 grep decredition
```

**Comment by sammyt3812** [comment]
Ok you have to close out a command and also have a start with option to end and collect. That way the currency can be stopped at certain amount captured sent to wallet where it can be utilized. You can also put a limit on how much is required to mine to withdraw

**Comment by zallarak** [comment]
@sammyt3812 i think you misunderstand. The app literally does not open for me.

**Comment by vctt94** [comment]
Is it hanging on the startup view? Did you update for 1.4? If not update in time in are sync out off the chain. 

To fix you need to delete your dcrd data and re-download it. Here is a similar issue: https://github.com/decred/decrediton/issues/2138

**Comment by zallarak** [comment]
@vctt94 it does not show any view. I see those logs but no UI / window opens up.

**Comment by vctt94** [comment]
I see. This log is related with `allowed_external_requests` config item, so maybe something is making it silently error. 

Can you tell us what is the value of your config item `allowed_external_requests`

The config is the config.json file, located at `~/.config/decrediton/config.json`

**Comment by zallarak** [comment]
@vctt94 pasted below:

```
{
	"theme": "theme-light",
	"daemon_start_advanced": false,
	"must_open_form": true,
	"locale": "en",
	"network": "mainnet",
	"set_language": "true",
	"ui_animations": true,
	"show_tutorial": "true",
	"show_privacy": true,
	"show_spvchoice": true,
	"allowed_external_requests": [],
	"proxy_type": null,
	"proxy_location": null,
	"remote_credentials": {
		"rpc_user": "",
		"rpc_password": "",
		"rpc_cert": "",
		"rpc_host": "",
		"rpc_port": ""
	},
	"appdata_path": "",
	"spv_mode": false,
	"spv_connect": [],
	"max_wallet_count": 3,
	"timezone": "local",
	"disable_hardware_accel": false
}
```

**Comment by alexlyp** [comment]
Is this pure debian or running as a VM under Qubes or something?

I ask since you may try and change your "disable_hardware_accel" to true

**Comment by zallarak** [comment]
@alexlyp pure debian. Settings `disable_hardware_accel` to `true` fixed it! Thank you. I wonder why that is?

**Comment by alexlyp** [comment]
Ah great.  Some goofy stuff for recent electron changes iirc.  @matheusd and I had always had issues on Qubes with that.  First time I'd heard of issues on debian not in a VM.

Glad you're up and running.  Let me know if you are able to get your wallet up and running and I'll go ahead and close this issue.

**Comment by zallarak** [comment]
I think it is safe to close, since the issue is fixed (the wallet opens!). I appreciate the help here.
