### ISSUE TITLE
windows wallet  blockchain syncing 

### ISSUE THREAD

**Issue by dish67** [decred/decrediton#2138]
it's been more than 2 hour that nothing to finish to sync  blockchain  
it alway in syncing (342913 / 353120
![decred_syncing](https://user-images.githubusercontent.com/6472167/59515538-58a12700-8e8d-11e9-9467-3f198b888f7e.png)
do you have solution !!

**Comment by vctt94** [comment]
Did you update your decrediton to 1.4? After the fork if not update in time, your blockchain data will not sync. 

So you need to delete your dcrd data and re-download it.

**Comment by dish67** [comment]
ok 
how to delete dcrd data

**Comment by dish67** [comment]
yes I update to 1.4

**Comment by dish67** [comment]
Ok I remove  C:\Users\dish67\AppData\Local\Dcrd\data\mainnet 
and restart decredition

**Comment by vctt94** [comment]
Yeah, that is the place. Tell us if it works

**Comment by dish67** [comment]
yes it working !! thanks
