### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by BigD77** [decred/decrediton#2140]

**Comment by BigD77** [comment]
API KEY Is missing. Upgraded to v1.4 and restored wallet. Shows prev Stakepool but no api key. Did not know I was to save it.?

**Comment by vctt94** [comment]
You can find your API key on the pool you are using or used. Just login in there and go to settings if I am not mistaking

**Comment by BigD77** [comment]
It wont let me in without a password and I never created one ):

**Comment by vctt94** [comment]
Try to rescue it or contact them

**Comment by BigD77** [comment]
I sent an email

**Comment by vctt94** [comment]
Okay, closing this issue

**Comment by BigD77** [comment]
Thx
