### ISSUE TITLE
Graphic Issue when Toggling SPV mode.

### ISSUE THREAD

**Issue by gravityz3r0** [decred/decrediton#2152]
Not sure if this has been raised, it's just a very minor issue concerning a graphical bug i encounter.

Decrediton 1.4.0, Windows 10.

Step to reproduce:

1. Open Decrediton in non-SPV mode. From here, you can either choose to launch wallet or not to. Both situation will lead to same result.
2. Go to Settings,
3. Toggle SPV mode (Enable),
4. Click Save. (with wallet restart if already launched)
5. Back to wallet select screen, "SPV mode activated, wallet ready to launch" is displayed in a grey box. (The correct color should be blue)

P/S - Toggling from SPV to Non-SPV via the same method does not cause the same issue.

**Comment by vctt94** [comment]
This is properly working now, so I am closing this issue.
