### ISSUE TITLE
Create Flatpak and Snap packages

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#2154]
The goal here would be two-fold:
* Enable users an easy way of installing/updating Decrediton on all major Linux distros simply with `{flatpak|snap} {install|update} decrediton` or using the built in GUI software installer their distro ships with.
* Provide redundancy in the event GitHub/AWS downloads are not accessible.

There's also the added benefit of getting Decred in front of additional eyeballs by distributing it in more channels.

Flatpak:
http://docs.flatpak.org/en/latest/electron.html
https://www.npmjs.com/package/electron-installer-flatpak

Snap:
https://docs.snapcraft.io/electron-apps
https://electronjs.org/docs/tutorial/snapcraft

**Comment by jholdstock** [comment]
What about PPA?

**Comment by jzbz** [comment]
Either Snap or Flatpack would cover all modern distros and (in the case of Snaps) not require the user to do any additional configuration.
