### ISSUE TITLE
Encrypted JSON import from web wallet

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#2161]
If we're going to deprecate the web wallet (hopefully soon) it might be nice to have the ability for people who failed to back up their seed but made an encrypted JSON backup to recover their funds easily. Apparently this isn't that uncommon.

**Comment by vctt94** [comment]
We ca have a tool similar to this website to decrypt the wallet: 

https://bitwiseshiftleft.github.io/sjcl/demo/
