### ISSUE TITLE
Excessive data download

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2166]
#### The problem
When a wallet is opened in Decrediton, proposal voting data is immediately downloaded from Politeia. This includes all vote data for all proposals, which currently represents a >40MB download every single time Decrediton opens a mainnet wallet. 

This is very wasteful, and seems to be getting worse every time voting is opened on a new proposal.

I can see that gzip compression is already being applied to the data, so I don't think we have any easy savings there. Server response time is not great, so there may be savings possible there, but for this issue lets focus on the sheer amount of data downloaded.

#### Analysis of the data

`/api/v1/proposals/{proposal_id}/votes` is called once per proposal ([example](https://proposals.decred.org/api/v1/proposals/5431da8ff4eda8cdbf8f4f2e08566ffa573464b97ef6d6bae78e749f27800d3a/votes)), downloading ~3MB each time. Each of the responses comprises:

- Tickets IDs eligible for voting (80% of total data)
- Votes cast 
	- Signatures (6.5%)
	- Ticket IDs (3.5%)
	- Tokens     (3.5%)

#### Suggestions

- The vast majority of the data, the eligible tickets, is static and known from the moment voting begins. This could be downloaded once and cached by decrediton indefinitely. Downloading it multiple times is wasteful.
- For votes which are known to be concluded, data is static and can also be cached. Only votes which are currently in progress need to be polled.
- Does decrediton even need all of this data? The vote signatures, tokens and ticket IDs for **all** votes?
- When a wallet is closed and re-opened (without closing decrediton) the data already in memory should be persisted and not re-downloaded.
- Perhaps we could defer downloading the data for historical votes which have already concluded? Does historical data really need to be downloaded immediately upon opening the wallet?

**Comment by lukebp** [comment]
Decredition needs the eligible tickets snapshot in order to check if the user has any tickets that are eligible to vote.  This data could be fetched directly from dcrwallet though so that you don't have to fetch such a large payload from the Politeia server.  You can get the vote start block height from the `VoteStatus` endpoint, a lightweight version of the `VoteResults` endpoint that is referenced above, then use it to determine the block height of the vote snapshot.

Note: there are plans to deprecate the `VoteStatus` endpoint in the future.  decred/politeia#953 adds the vote summary information that is returned by `VoteStatus` to a proposal record by default.

**Comment by lukebp** [comment]
Even if Decrediton fetches the eligible ticket snapshot locally, it will still need to request the cast votes from Politeia in order to determine if the user has any eligible tickets that have not yet voted.  I've opened an issue (decred/politeia#961) to add an eligible tickets flag to the `VoteResults` endpoint so that the client can fetch the cast votes without the eligible tickets snapshot.

**Comment by lukebp** [comment]
Looks like you can't get a ticket snapshot locally without implementing a whole bunch of stuff yourself.  Decredition should just get the eligible ticket snapshot from politeia the first time it requests the vote results and cache it.

**Comment by lukebp** [comment]
After discussing this some more we came to the conclusion that a `EligibleTickets` flag is not needed and that Decrediton only ever needs to call the `VoteResults` endpoint once per proposal.

Decrediton would fetch the eligible tickets snapshot and cache it, but after that there's no need to actually fetch the cast vote data. Decrediton can keep track of whether the user has voted manually. This might not be accurate in the case of a fresh install or possibly other edge cases, but in that scenerio the user would just try to vote again and the votes would be rejected by pi. The issue with fetching all of the cast vote data in order to see if the user has already voted is that its a very expensive call, even if the eligible ticket snapshot isn't included.

**Comment by vctt94** [comment]
So, let me see if I understand the issue correctly. Decrediton needs the eligible tickets snapshot in order to cast votes and they are too much data to download each time decrediton starts. 

So a solution would be:
 - Each time a proposal starts a vote, calls `VoteResults` once, if not called.
 - Cache it in some plain text file
 - When need to vote use the cached information.
 - After proposal finishes vote, delete cached information.

Is that correct?

**Comment by lukebp** [comment]
@vctt94 more like this:

So a solution would be:

* Each time a proposal starts a vote, calls VoteResults once, if not called.
* Cache the eligible tickets snapshot in some plain text file
* When need to vote use the cached eligible tickest snapshot to determine which of the user's tickets can vote.
* Once the user votes, mark the tickets as voted and save this information locally.  This is how Decredition will know whether the user's tickets have voted.  Previously, it would fetch the `VoteResults.CastVotes` to determine this, but this call is too expensive and should be avoided.
* After proposal finishes vote, delete cached information.

**Comment by vctt94** [comment]
Okay, so we still have a problem about this solution.

I am looking into proposals that have finished voting, and I believe that is not how to know how a decrediton user cast a vote in some proposal (it would be ideal if we could know from a proposals batch)

Right now we are getting the wallet committed tickets, looking which one is an eligible ticket and cast votes. 

With the proposed solution, we can know which proposals have been voted in the active votes, without problems, as we have the live tickets and the eligible ticket, but after deleting the cached information, we would lost this data. Also for finished proposals we would need to look into all voted tickets to know if some of them have cast votes to politeia.

I also believe keeping the eligible tickets and which votes were cast not an ideal solution.
 - it would not be a good solution for cold wallets, for example, which a user would need to change computer to sign the message 
- it would increase complexity, if every time finished vote tab loads we would need to look for votes into many eligible tickets.

**Comment by lukebp** [comment]
I'm not quite sure I understand the problem.  When a user votes using decrediton, save that data locally and use it to display their voting preference.  If they didn't vote using decrediton then their voting data would not be displayed in decredition.

> it would not be a good solution for cold wallets, for example, which a user would need to change computer to sign the message

If someone is using a cold wallet they're most likely going to be using the politeiavoter cli tool.

> I also believe keeping the eligible tickets and which votes were cast not an ideal solution.

You're not.  You're just keeping the eligible ticket snapshot while the vote is ongoing to see if the user has any eligible tickets. Once the vote ends you can get rid of it.

> it would increase complexity, if every time finished vote tab loads we would need to look for votes into many eligible tickets.

The only time you're fetching data from politeia is when you initially fetch the eligible ticket snapshot and cache it.  Nothing is needs to be fetched.  Then you delete it once the vote ends.

**Comment by vctt94** [comment]
I will try to be clearer.

Voting using the voter to cold wallet makes sense, but we support watching only wallets into decrediton and probably later having support to vote into politeia would be good. But I think we can discuss this later.

The problem with having the snapshot of eligible tickets only on the voting time, is that we also have a `finished vote` tab. Look: 

![image](https://user-images.githubusercontent.com/15069783/66395204-32a81100-e9ad-11e9-8569-ab02d3a8a734.png).

Right now there is only one way to know if the user cast a vote on some of these proposal. 

Calling `GET /V1/proposals/{token}/votes` to each proposal, get tickets which voted, look which one of them belong to the wallet and look how they voted.

The problem with this solution is this call fetches cast votes and the eligible tickets and each of these calls take up to 3s to finish. 

Response example: 
```
{
  "vote": {
    "token":"642eb2f3798090b3234d8787aaba046f1f4409436d40994643213b63cb3f41da",
    "mask":3,
    "duration":2016,
    "Options": [{
      "id":"no",
      "description":"Don't approve proposal",
      "bits":1
    },{
      "id":"yes",
      "description":"Approve proposal",
      "bits":2
    }]
  },
  "castvotes": [{
    "token":"642eb2f3798090b3234d8787aaba046f1f4409436d40994643213b63cb3f41da",
    "ticket":"91832123c3f04c0783fb51d93bffd6f641ce3e951c30a29e15fb9986f23817c0",
    "votebit":"2",
    "signature":"208e614662fd7719df82687b72578cfb1f5e54fd05287e67683397b77e1819d4ff5c2029117d1d01bfa5c4637b7661ad95319f455c264ed4b4637382ffee5d5d9e"
  },{
    "token":"642eb2f3798090b3234d8787aaba046f1f4409436d40994643213b63cb3f41da",
    "ticket":"cf3943767a35136252f69118b291b47006308e4215de41673ab118736e26605e",
    "votebit":"2",
    "signature":"1f8b3c8207fa67d91a65d8742e5026044ccebd6b4865579a1f75d6e9a40a56f9a96e091397d2ec9f8fca773c68e961b93fe380a694aceecfd8f9b972f1e4d59db9"
  }],
  "startvotereply": {
    "startblockheight":"282899",
    "startblockhash":"00000000017236b62ff1ce136328e6fb4bcd171801a281ce0a662e63cbc4c4fa",
    "endheight":"284915",
    "eligibletickets":[
      "000011e329fe0359ea1d2070d927c93971232c1118502dddf0b7f1014bf38d97",
      "0004b0f8b2883a2150749b2c8ba05652b02220e98895999fd96df790384888f9",
      "00107166c5fc5c322ecda3748a1896f4a2de6672aae25014123d2cedc83e8f42",
      "002272cf4788c3f726c30472f9c97d2ce66b997b5762ff4df6a05c4761272413"
    ]
  }
}
```

What I am proposing is to have something like `GET /V1/proposals/batch-votes` , so we can get votes cast in a proposals batch (without eligible tickets and other information) so we can know how a user has voted in finished proposals.

**Comment by lukebp** [comment]
Here's the problem with a batch-votes endpoint.  If you're fetching all of the cast vote data at once, it's going to be a lot of data.  Far more data than just the eligible ticket snapshot.  So if you're fetching this data for multiple proposals on the "Finished Voting" tab, the performance is going to be unacceptably slow.

If you're proposing an endpoint that allows you to specify specific ticket hashes that you want cast vote data for, that's a privacy issue.  We don't want an endpoint that encourages people to tell the server what tickets they control.

What I'm proposing is to only display the cast vote data on the "Finished Voting" tab for proposals where the user voted using decrediton.  So when a user votes using decrediton, you save that data locally somewhere and use it to populate the "Finished Voting" tab.  If a user voted using some other method or if they restore an existing wallet then decrediton will have no knowledge of prior cast vote data and it will not be displayed on the "Finished Voting" tab.

Another option would be to not display the cast vote data on the "Finished Voting" tab at all.  If a user wanted to look back at what votes they cast then there would be some button that they would have to click and it would fetch all of the cast vote data for that proposal, at which point decrediton can filter out the users votes.  This would prevent having to fetch the cast vote data for multiple proposals at once.
