### ISSUE TITLE
Create/restore wallet hidden if 3 wallets exist

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#2186]
If you create 3 wallets (regular or watch only) in Decrediton you will lose the ability to create more as the "create" and "restore" buttons will disappear.

For a temporary workaround you can move the directories out of /wallets/mainnet and then put them back when you are done creating additional wallets.

**Comment by matheusd** [comment]
There's also a manual `max_wallet_count` config option in the main decrediton config file that you can set to whatever limit you want. This breaks some of the layout of the starting page though, which was the initial motivation for the limit.

**Comment by vctt94** [comment]
I believe we can close this issue, as we already have a "fix" for it? 

If we see people want many wallet, we can add `max_wallet_count` to the settings page, but I believe it is fine being at the  config files for now.

**Comment by jzbz** [comment]
The problem is the fix requires the GUI user to edit a config file (or find the entry in the settings page if we add one), and first they need to figure out that's what they need to do. There should be an indicator that replaces the missing "create/restore wallet" buttons that activates this functionality and bumps the max_wallet_count automatically.

**Comment by lukebp** [comment]
Had a friend call me up after getting stuck on this.  Agree with jz that there should be some sort of UI element to help the user figure it out.

**Comment by victorgcramos** [comment]
Why can't we just kill this limit? IMO, having a button to "unlock" the new wallet buttons is kinda redundant...

**Comment by vctt94** [comment]
I think it is fine removing it. The reason we did it is to preserve the ui, but with the last changes it doesn't look that bad with multiple wallets:

![image](https://user-images.githubusercontent.com/15069783/93380751-0c822680-f836-11ea-8254-c43a7200108a.png)
