### ISSUE TITLE
[style] Dark tonality setting

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#2199]
When toggling to "Dark" tonality, there are some areas that are still showing as "light".  

Here is a brief list of one's I've spotted:
- Sidebar
- Transactions/Send - right area (with transaction details)
- Tickets/Purchase - ticket settings/details

**Comment by vctt94** [comment]
How does it show in your decrediton? Here they look dark:

![image](https://user-images.githubusercontent.com/15069783/66079183-f0f51180-e539-11e9-97c5-3d0f0604dd78.png)

**Comment by alexlyp** [comment]
Strange I'm seeing white for both.

**Comment by alexlyp** [comment]
Whoops was on an old version
