### ISSUE TITLE
Styling html and css of get started page (home + notloggedin)

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#22]
Update the current homepage for the notloggedin state for a cleaner/better looking login form that is properly centered and looks good at various widths of the app.

**Comment by jolan** [comment]
Ended up working on stakepool API. Closed by #66.

**Comment by alexlyp** [comment]
Not quite done yet, will close when those changes are merged

**Comment by alexlyp** [comment]
Initial release get started funnel completed in #89
