### ISSUE TITLE
Visual Design: Seedword Field States (Dark Mode)

### ISSUE THREAD

**Issue by hqnnes** [decred/decrediton#2210]
Preview: https://xd.adobe.com/view/a2a46f36-a3df-4e1b-535e-d1526c831bc5-d495/
Specs: https://xd.adobe.com/spec/8e7966c2-f272-40d9-496e-8fbd35c52d7a-f848/

Right now the Unfilled field state is the same as the Filled field state in the dark mode. I created additional examples to have them the same way in both modes.

**Comment by bgptr** [comment]
Hi! Could you provide me the Light Mode Specs too?
