### ISSUE TITLE
Launcher: Enable Scroll for Settings

### ISSUE THREAD

**Issue by hqnnes** [decred/decrediton#2222]
Preview: https://xd.adobe.com/view/71a9eae0-ced8-4c50-7025-58e60aa9e1e5-0798/

Scrolling is disabled in the view, which causes the save button to be left outside of the viewport. Add scrolling feature to make it accessible, similar to inside the wallet.

**Comment by vctt94** [comment]
Are you suggesting to move the button to the left? 

The reason I ask is because we use to have a right alignment idea through decrediton, here is an issue about it: https://github.com/decred/decrediton/issues/1940

**Comment by hqnnes** [comment]
No, this is only in regards the scrolling. The button should be on the right. Sorry just had dated files, will update.

**Comment by vctt94** [comment]
I noticed this is also happening at the send view button
