### ISSUE TITLE
Visual Design: Content area alignment simplification

### ISSUE THREAD

**Issue by hqnnes** [decred/decrediton#2231]
Preview: https://xd.adobe.com/view/b7bf407f-2456-4d3e-6756-9ea7ffeb3e1d-c18e/
Specs: https://xd.adobe.com/spec/3f020af3-2ef1-4319-4b14-9e1b4c96700f-4933/

So far the content area items have been aligned by type and header elements. As it seems to be difficult to be coherently applied and kept up, we’ve decided to simplify the alignment in the content area against the cards. Meaning all titles should be aligned to the left side of the card, all help icons and action buttons to the right side. This makes for uniform blocks and fewer layout variables to worry about.

This should be applied globally within the wallet, views affected:
- Overview
- Transactions: Send / Receive / Export
- Governance: Individual Proposals view
- Tickets: Add Stakepool / Purchase Tickets / My Tickets / Statistics
- Accounts
- Security Center
- Help: Sources / Tutorials / Logs

**Comment by bgptr** [comment]
I'm working on this.
