### ISSUE TITLE
Visual Design: Settings, detailed groupings and wider views examples

### ISSUE THREAD

**Issue by hqnnes** [decred/decrediton#2253]
Preview: https://xd.adobe.com/view/ce07ff55-7c3c-4cc8-7e22-b8b63a2ac769-b836/
Specs: https://xd.adobe.com/spec/c71571d1-022e-4879-5bb1-cf3859d68d87-b124/

This view can benefit in improving the grouping, which also translates better to wider and smaller views. Propose changing the content from current single single card to three key groups w/ separate cards.

Below is a breakdown of the groups – though this needs a second set of eyes to confirm whether everything makes sense?

### Connectivity

(Column 1)
- Network
 - - Network
 - - SPV
- - SPV Connect
 - - Adv. Daemon Setup

(Column 2)
- Proxy
 - - Proxy Type
 - - Proxy Location

### General

(Column 1)
- UI
 - - Tonality
 - - Language
- Misc
 - - Displayed Units
 - - Gap Limit

(Column 2)
- Timezone
 - - Local
 - - UTC

### Privacy & security
- All current items

Regarding wider views: from 1680 screen size there are 2 columns. In the 340 and 1680 screens the card contents (title etc.) have got a 15px left and 35px right padding. Other views have 40px left and right padding.
Due to visual reasons the “Privacy and Security” card content has a higher upper padding on screens 1920 and 1680.

**Comment by bgptr** [comment]
I am working on this.
