### ISSUE TITLE
Validate 0.8.0

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#226]
Basic testing of the release build needs to be done on supported OSes

- [x] OSX x64
- [x] Linux x64
X- [ ] Windows 7
X- [ ] Windows 10

Testing more than one Linux disto is a good idea so please mention distro or version you tested in comments.

- [ ] Confirm wallet seeds: Create New Seed, receive funds, send funds then recreate with dcrwallet and make sure they are the same.

If there are any other obvious things we need to add here, please add to the issue.

All this testing MUST be done on release builds which will be provided soon.

**Comment by jrick** [comment]
Win10 (with #246):

* Ugly rendering of fonts and the application does not fit in the window (http://i.imgur.com/ht1A7yc.png).
* dcrd does not close cleanly on shutdown like on other platforms (I observed clean shutdown on Linux)

Linux (Fedora 25):

* Fonts look better and the application is a bit more reasonably sized to fit well in the window it opened
* dcrd has clean shutdown
* dcrwallet DOES NOT shutdown, and was left running in the background after I closed decrediton

**Comment by jcvernaleo** [comment]
That lack of wallet shutdown on Fedora is surprissing.  I get correct shutdown on Ubuntu and macOS.

**Comment by jcvernaleo** [comment]
The visual issues on win aren't really release critical so could you open a new issue for them so @alexlyp can look at them after release?

**Comment by jrick** [comment]
Done (#247)

**Comment by jcvernaleo** [comment]
OSX looks good.  Removed windows from this since we won't release it until next time (but leaving it in the issue so I can copy and paste for next release.

**Comment by jcvernaleo** [comment]
Linux is mostly good although as @jrick found, there are some situations where wallet doesn't stop properly #252 but this primarily seems to happen on Fedora.

**Comment by alexlyp** [comment]
Confirmed mainnet seeds created in decrediton match first address in dcrwallet and vice versa. OK

**Comment by jcvernaleo** [comment]
Quick tests on osx look okay.
