### ISSUE TITLE
[1.5.0-rc1] Proposals: Links do not work

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2270]
The Spanish marketing proposal contains various links to external websites. These do not open when clicked.

**Comment by vctt94** [comment]
This is intended. 

Here you can see the part of the code: https://github.com/decred/decrediton/blob/master/app/components/views/GovernancePage/Proposals/Details/helpers.js#L94

from the code: 

```
// This changes links to never open. Debatable whether we want to
// allow proposals to link somewhere directly from decrediton.
const renderInternalProposalLink = ({ children }) => {
  return <a onClick={() => {} } href="#">{children}</a>;
};
```

Decrediton is configured to open only allowed external links, and we can not simply know where a proposal link is taking, so we do not open them. 

I believe we can have a warning informing that, but I think it is reasonable not open them.

**Comment by jholdstock** [comment]
Makes sense - I will close this issue as it is not related to 1.5.0 and is part of a longer discussion.

**Comment by davecgh** [comment]
This seems like something that should have a warning and allow the user to open it in an external browser if they choose.  I agree that it shouldn't open in the wallet, but just doing nothing is poor UX.

**Comment by jholdstock** [comment]
Agree with dave here, its quite a confusing UX to have a blue highlighted link which does nothing. I clicked on it multiple times, and checked all my active browser windows to see if a random tab had opened somewhere. For a moment I thought my system was misbehaving

**Comment by vctt94** [comment]
I agree with you guys and pushed a fix

**Comment by jholdstock** [comment]
The popup looks nice, thanks!
