### ISSUE TITLE
[1.5.0-rc1] Launcher: Sync progress 298837/0

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2273]
![Screenshot from 2019-11-08 15-24-27](https://user-images.githubusercontent.com/6762864/68487957-f847c300-023b-11ea-92fb-6d2014b70c24.png)

**Comment by jholdstock** [comment]
Its happening on the next screen too:
![Screenshot from 2019-11-08 15-26-43](https://user-images.githubusercontent.com/6762864/68488080-3513ba00-023c-11ea-966d-6e4b00d7439f.png)

**Comment by vctt94** [comment]
How to reproduce?

**Comment by jholdstock** [comment]
Open decrediton in mainnet mode. On the "Welcome to Decrediton Wallet" screen, open settings and switch to testnet. Press save.
