### ISSUE TITLE
[1.5.0-rc1] Testnet: Proposals are not being displayed

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2274]
All tabs are empty despite proposals showing on https://test-proposals.decred.org/

![Screenshot from 2019-11-08 15-39-03](https://user-images.githubusercontent.com/6762864/68488880-e9faa680-023d-11ea-8005-227fcb27164a.png)

**Comment by vctt94** [comment]
Steps to reproduce?

**Comment by jholdstock** [comment]
Open decrediton in testnet mode - click on the governance tab.

**Comment by jholdstock** [comment]
Potential cause, 403 response:

![Screenshot from 2019-11-09 10-02-20](https://user-images.githubusercontent.com/6762864/68526854-119e4d00-02d8-11ea-918e-4ab56d66b4f1.png)

**Comment by vctt94** [comment]
Weird, here it works. 

can you try disabling and then enabling to see what happens?
