### ISSUE TITLE
[1.5.0-rc1] Help: Slack link is no longer active

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2276]
Should update to https://decred.slack.com/join/shared_invite/enQtNTE4MDM1NzAzODEzLWFiYzgwN2YzYTQyNWQxOTg2NjEwNGU5YTI4YmZiNTI5Mzk2Y2E1N2QxNWEwOWVmYmYzZWY3MWNjNTJlYTgyZDQ

**Comment by vctt94** [comment]
http://slack.decred.org still seems to work

**Comment by jholdstock** [comment]
```
$ curl -I  slack.decred.org | grep Location
Location: https://join.slack.com/t/decred/shared_invite/enQtNTE4MDM1NzAzODEzLWFiYzgwN2YzYTQyNWQxOTg2NjEwNGU5YTI4YmZiNTI5Mzk2Y2E1N2QxNWEwOWVmYmYzZWY3MWNjNTJlYTgyZDQ
```

**Comment by jholdstock** [comment]
Hm... you're right, http://slack.decred.org/ is currently configured correctly and redirecting to the correct URL, however it looks like my Decrediton has a cached 301 response which is taking me to the old URL.

**Comment by vctt94** [comment]
I am not able to reproduce it.

We use `shell.openExternal` to open external links, so maybe electron has some cache we do not know of. 

Can you try deleting electron's cache to see if does it solve?

It is located at:

Windows:
C:\Users\<user>\AppData\Decrediton\Cache

Linux:
/home/<user>/.config/decrediton/Cache

OS X:
/Users/<user>/Library/Application Support/Decrediton/Cache

**Comment by jholdstock** [comment]
Looked at this further, I think this is actually a browser issue and not Decrediton. Decrediton simply opens slack.decred.org in a browser window, and the browser is the one which has a cached 301 redirect.

This is a sysadmin issue and not a decrediton issue. Closing and pursuing with @dajohi on Matrix.
