### ISSUE TITLE
[1.5.0-rc1] Decrediton can only be launched by CLI on Linux

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#2277]
Clicking on the Decrediton binary just throws an error as it's not recognized as an executable but as a "shared object".

Output of `file` for v1.5:
`decrediton: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=c30f8134c6e2c45cd03898ad082d31cf65088dba, stripped`

vs.

v1.4:
`decrediton: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, stripped`

**Comment by alexlyp** [comment]
https://github.com/electron-userland/electron-builder/issues/3950

I was able to find this issue that was filed a few months ago.  Need to look further into it, but it might not be fixed until we can update to Electron-6.  I'll keep testing.

**Comment by jholdstock** [comment]
Issue still exists in rc2

**Comment by matheusd** [comment]
This is a bug in the `file` tool misidentifying electron binaries. The relevant upstream issue is this:

https://bugs.launchpad.net/ubuntu/+source/file/+bug/1747711

Basically no way to solve it until gnu/ubuntu/electron solves it. Our only other alternative would be to ship AppImage builds which apparently aren't affected by this.

**Comment by jzbz** [comment]
It's pretty terrible UX to have to run the GUI from CLI, likely going to lead to a ton of support requests, but probably not too big of an ask for most Linux users. AppImage would actually be nice and simplify things since it's just one file.

**Comment by matheusd** [comment]
Indeed. Seems nautilus devs actually want to remove the ability to launch even legacy binaries from it:

https://bugzilla.gnome.org/show_bug.cgi?id=737849#c19

**Comment by jzbz** [comment]
Gnome perfection will be achieved when it has so few features you can't even run applications from it.

**Comment by dnldd** [comment]
A Decrediton AppImage would be sweet.
