### ISSUE TITLE
[1.5.0-rc1] No icon displayed for Decrediton in launcher on Linux

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#2278]
Decrediton just shows a transparent block instead of the appropriate logo in the launcher.

Tested on Ubuntu 19.10.

![image](https://user-images.githubusercontent.com/4731927/68501002-13f69d80-022b-11ea-9f5c-d6c7e010cb3c.png)

**Comment by rodrigondec** [comment]
@jzbz how did you generate the desktop launcher icon?

**Comment by jzbz** [comment]
@rodrigondec I didn't, I simply started it from CLI and it appeared in the launcher. It can't be pinned there, likely to do with #2277.

**Comment by rodrigondec** [comment]
On my deepin it didn't create the desktop launcher as I run the CLI. I created manually as decribed on #2318
