### ISSUE TITLE
Info modals enhancements

### ISSUE THREAD

**Issue by hqnnes** [decred/decrediton#2285]
Preview: https://xd.adobe.com/view/3b5ac3b0-4a19-48b8-5c35-847568d5ac3e-4d6b/
Specs: https://xd.adobe.com/spec/d89551ab-f5bf-4541-568b-579c129a1dfe-aea4/

As @linnutee mentioned in past discussions on implementing highlighted tooltips (https://assets.website-files.com/5c7fdbdd4e3feeee8dd96dd2/5c915cffec1487b7e4a24501_5c3f5e0666eac1955b2eb6b8_typeform-tooltips-product-tour.png), I recommend this small enhancement to the current info modals as a useful in-between step. Allowing the modals to be positioned next to explanatory copy at the same time would make the user sympathize faster between them.

- First, to make the blurred background of the informative modals clear up when the modal is clicked/active, which brings us to the second enhancement:

- Second, to make the modal movable in a bounding box (red outlined box). This modal moving works simply by dragging the modal via the drag handle. The drag handle is the modal element itself (I indicated it with orange), excluding all the elements on it (copy, buttons etc.).

- Lastly, to make clicking of the blurred area close the modal box.

Affected informative modals:
accounts
tickets-purchase
security
settings-gap limit

**Comment by bgptr** [comment]
I'm working on this.
