### ISSUE TITLE
Visual Design: Purchase Tickets/Staking Overview component improvements

### ISSUE THREAD

**Issue by hqnnes** [decred/decrediton#2303]
Preview: https://xd.adobe.com/view/8f9ea77f-844d-43c1-49bc-cb9c27a9a675-f9af/
Specs: https://xd.adobe.com/spec/0b2049ed-80d2-4978-703a-72ad6ceea744-7d11/
Icons: [decred - icons19 - colored tickets.zip](https://github.com/decred/decrediton/files/3842363/decred.-.icons19.-.colored.tickets.zip)

Made some grouping and visual improvements to provide a more comprehendible overview of the users staking activity. Also included icons to help identify the different ticket statuses.

As a sidenote/question: the current version includes an “Unspent Tickets”. Is this any different from Live tickets? If not from a users perspective, should be replaced by "Live" and the icon, or if it is different then could you provide an icon and some explanation on that.

**Comment by linnutee** [comment]
Mentioning on this one, the ticket states icons had some micro tweaks done, so these should be updated globally to those included .zip.

**Comment by guilhermemntt** [comment]
It seems to be linked with https://github.com/decred/decrediton/issues/2305, so I'll do it as well.
