### ISSUE TITLE
Visual Design: Purchase Tickets settings alignment fixes

### ISSUE THREAD

**Issue by hqnnes** [decred/decrediton#2304]
Preview: https://xd.adobe.com/view/d5cdc9bb-f0ad-41cb-7685-d3893e740367-a3fc/
Specs: https://xd.adobe.com/spec/3db5ecad-864e-4b03-5ac6-27dbcb1e57d8-4b84/

* Align and reorder the elements to match the closed and open views
* Added icons after the fields
* Change the width of “Account Name” field to 295px instead of 300px to align with the fields below

**Comment by bgptr** [comment]
I am working on this.
