### ISSUE TITLE
Linux binary release missing icon

### ISSUE THREAD

**Issue by rodrigondec** [decred/decrediton#2317]
I downloaded both version [1.14.0](https://github.com/decred/decred-binaries/releases/download/v1.4.0/decrediton-v1.4.0.tar.gz) and [1.15.0 rc1](https://github.com/decred/decred-binaries/releases/tag/v1.5.0-rc1) from [decred-binaries](https://github.com/decred/decred-binaries).

On both versions, the `tar.gz` file for linux didn't come with a `icon.png|ico|jpg` file to create a my `decrediton.desktop` entry (I got a image from a friend for that).

It would be nice if the release could come with a oficial icon on some folder.

**Comment by jholdstock** [comment]
duplicate of #2278?

**Comment by rodrigondec** [comment]
Probably 😅

Yeah. I believe pr #2290 will bundle the icon image on release.
