### ISSUE TITLE
Decrediton must be manually installed (linux)

### ISSUE THREAD

**Issue by rodrigondec** [decred/decrediton#2318]
I had to manually install the `Decrediton` release downloaded.

This include creating a soft link from the binary executable `decrediton` to `/usr/bin/decrediton` and creating the `decrediton.desktop` entry on `/usr/share/applications/` with the content 
```
[Desktop Entry]
Type=Application
Name=Decrediton
GenericName=Decred Wallet
Icon=/path/to/icon/decrediton.png
TryExec=decrediton
Exec=decrediton
Terminal=false
Categories=Internet;
StartupWMClass=decrediton
```

This setup/configuration could be made from a `install.sh` script which could be included on the `binary release`. Just to make things easier for new users.

The same way it could exist a `uninstall.sh` script which would remove those files and all binary files.

**Comment by matheusd** [comment]
It's unlikely we'll do it this way.

Experienced users can just do as you wrote here, in a distro and user-specific way that they may prefer.

For less knowledgeable linux users we could offer the AppImage distribution which is just a single executable that sets things up as needed.

**Comment by rodrigondec** [comment]
I mentioned with my friend the possibility of a `.deb` package. But the AppImage is the best way
