### ISSUE TITLE
[1.5.0-rc2] "Cast Vote" button activates without selecting a voting preference

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2329]
- Open a proposal which is active for voting
- Click on the gray area highlighted in screenshot
- Cast Vote button activates without selecting a voting preference.
![Screenshot from 2019-11-22 04-36-11](https://user-images.githubusercontent.com/6762864/69398562-a6df0f80-0ce2-11ea-9137-08ba8a95343e.png)

**Comment by noahpierau** [comment]
I reproduced this issue in the Windows release. Also, when I click the "Yes" option, the "Cast Vote" button activates but the green ball inside the green circle does not appear.
