### ISSUE TITLE
[1.5.0-rc2] Tickets tab: Weird alignment on "Not enough funds" 

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2332]
![Screenshot from 2019-11-22 04-57-57](https://user-images.githubusercontent.com/6762864/69399096-c119ed00-0ce4-11ea-8c9c-34514ab3585f.png)

The number "1" and the orange "Not enough funds" text appear to be too high. Also I'm not sure the text needs to be wrapped onto two lines?

**Comment by bgptr** [comment]
I am working on this.
