### ISSUE TITLE
[1.5.0-rc2] Launcher: Changing test/mainnet does nothing

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2335]
From the launcher, open the settings panel. Change mainnet to testnet (or vice versa). Press save. Nothing changes.

**Comment by jholdstock** [comment]
It works as expected if you change both the network setting **and** the tonality setting before hitting Save

**Comment by vctt94** [comment]
I believe we are having some problems with actions that need to reset the network. 

For now, I think it would be better we close decrediton for all this actions and better deal with them after https://github.com/decred/decrediton/tree/refactor_startup is merged.

@matheusd  @alexlyp thoughts?

**Comment by vctt94** [comment]
This is fixed at master now. So I am closing this issue
