### ISSUE TITLE
Governance Tab: Available Treasury Balance

### ISSUE THREAD

**Issue by abg3090** [decred/decrediton#2341]
I am using Decrediton - 1.5.0 rc 2 and noticed an issue in the governance tab with the available treasury balance. It says 63,610 while dcrdata is 636,106. Appears the comma and decimal point may be in the wrong spot?

![image](https://user-images.githubusercontent.com/51087063/69488034-fda33100-0e29-11ea-892d-b5dbe5462df8.png)

**Comment by vctt94** [comment]
Related https://github.com/decred/decrediton/issues/1990

It happens sporadically, so it is not simply a wrong comma place. Need to be investigated.

**Comment by matheusd** [comment]
@abg3090 which locale is your decrediton configured to use?

**Comment by abg3090** [comment]
@matheusd sorry for the delay. In settings, my locale is set to English (US). Let me know if this isn't what you are looking for.
