### ISSUE TITLE
0.00 - Transactions -> History -> Filter: Voted, Tickets, Revoked

### ISSUE THREAD

**Issue by Michae2xl** [decred/decrediton#2350]
<img width="766" alt="Captura de Tela 2019-11-27 às 16 30 15" src="https://user-images.githubusercontent.com/44928059/69761147-81b02e00-1134-11ea-810a-6d6b923b8ab9.png">
<img width="766" alt="Captura de Tela 2019-11-27 às 16 31 03" src="https://user-images.githubusercontent.com/44928059/69761148-81b02e00-1134-11ea-8bcb-5043214988fe.png">
<img width="766" alt="Captura de Tela 2019-11-27 às 16 31 25" src="https://user-images.githubusercontent.com/44928059/69761149-81b02e00-1134-11ea-80b9-884194de6c2a.png">

**Comment by alexlyp** [comment]
I'm not following, can you explain what the issue is?

**Comment by fguisso** [comment]
I'm using the 1.5.0-rc2 debian, and get the same issue.
When you access `Transacitons > History` the tickets don't get data of `Ticket Price` and `Ticket Reward`
![screeshot](https://user-images.githubusercontent.com/5755568/69968233-bd624380-14f8-11ea-9e6c-3ae5d3809142.png)

**Comment by Michae2xl** [comment]
Correct, thanks.
