### ISSUE TITLE
Add BIP-0021 support

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#2365]
Under the Transactions > Receive tab it would be good to have a place to specify an amount and have the QR code update to reflect that based on BIP-0021.

https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki

**Comment by fguisso** [comment]
I like that to Decred wallets accept URI scheme and we need this feature in `dcrwallet` too.
Something like invoices are begin here https://github.com/decred/dcrwallet/issues/1132

**Comment by bgptr** [comment]
I am working on this
