### ISSUE TITLE
[1.5.0-rc4] Politeia spinner for dark mode

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2369]
The spinner doesnt look great, we probably want something with a transparent background

![Screenshot from 2019-12-11 10-52-02](https://user-images.githubusercontent.com/6762864/70615576-91377880-1c04-11ea-960f-00b6d428c8b7.png)

**Comment by linnutee** [comment]
@kyleFirethought could you render a negative version for this also? (Didn't found one).

**Comment by kyleFirethought** [comment]
I wasn't aware of the Dark requirement here. @linnutee @jholdstock would a Lottie .json be suitable here? 

With this structure are .jsons for original, white and dark theme colour schemes, Also please assign me to this. 

Thanks,

[politeia_lottie_04_2020.zip](https://github.com/decred/decrediton/files/4439118/politeia_lottie_04_2020.zip)

**Comment by alexlyp** [comment]
We won't be using Lottie animations due to issues we found with performance.  Please include a Gif as well.

**Comment by kyleFirethought** [comment]
@alexlyp Perfect, Will do.

**Comment by kyleFirethought** [comment]
Files:
[politeia_loop_gif_alpha.zip](https://github.com/decred/decrediton/files/4443710/politeia_loop_gif_alpha.zip)

Example:
![politeia_7](https://user-images.githubusercontent.com/7825971/78661419-aa0c1e00-78c6-11ea-9629-0ca5e0a71b30.gif)

@jholdstock @alexlyp @linnutee ,

Okai, so here is the logo_loop in a comprehensive range of sizes with alpha and variants for most of the supported colour schemes.

Obviously, anti-aliasing is non-resistant when it comes to GIFs, the only way to resolve those jaggy edges would be to have background matched with the Ui background.  If the result looks too patchy let me know and I can update the non-alpha version with the correct background hue. 

Let me know how you get on with this pack?

**Comment by kyleFirethought** [comment]
Elements resolving this issue are to be posted here as a part of a broader fix to inconsistencies in animated elements in Decrediton's UI/UX. https://github.com/decred/dcrdesign/issues/209

**Comment by kyleFirethought** [comment]
^Currently working through prior to the colour scheme outlined in the Master Issue: https://github.com/decred/decrediton/issues/2089

**Comment by amassarwi** [comment]
I will be working on governance pages refactoring and I could sneak this one as well.

**Comment by kyleFirethought** [comment]
Nice one @amassarwi , let me know if anything else is required.
