### ISSUE TITLE
[Purchase Tickets] Improve adding new VSP ux

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2396]
When adding a new VSP at decrediton, if clicking at add new VSP, nothing happens. 

Also after pasting and hit `enter`, for example, it should be added.

In the API key input, we are not trimming its inputted value. We should trim it before submitting to avoid silly validation errors. 

![image](https://user-images.githubusercontent.com/15069783/72531985-5a7efe80-3851-11ea-9d84-9dfaa126bfb4.png)

**Comment by guilhermemntt** [comment]
I'm working on it.

**Comment by matheusd** [comment]
As a follow up, it would be nice to have an indicator that decrediton is trying to add the VSP.

Here's one address that takes a while (30+ seconds) to return the appropriate response: http://testnet-split-tickets.matheusd.com:8000.

**Comment by guilhermemntt** [comment]
@matheusd So I'll open another issue and work on it soon
