### ISSUE TITLE
Add a warning to backup redeem scripts

### ISSUE THREAD

**Issue by sumiflow** [decred/decrediton#2401]
If a VSP goes offline, it could result in permanently locked funds for some users that did not backup their redeem script.

The warning could be similar to the one in the docs.
https://docs.decred.org/wallets/decrediton/using-decrediton/#backup-redeem-script
Warning: Backup your redeem script
If your VSP goes down, you’ll need this script to vote or revoke tickets.

Perhaps add it to the "Configured VSP" box:
![image](https://user-images.githubusercontent.com/5420838/72915883-aaa10980-3d06-11ea-86c2-ae875e4a6cf3.png)

**Comment by matheusd** [comment]
Probably best to:

1- Show the script with a reminder to back it up immediately after importing via api (maybe via modal?)

2- Add a warning button asking to backup the data and upon clicking show the scripts for all configured VSPs. Once the user dismisses that we can hide the button.

**Comment by vctt94** [comment]
I believe we can also import the script to the wallet after the user imports its API key.

This way, even if the user fails backing up the script, we can still retrieve its script by the `listscript` method.

**Comment by sumiflow** [comment]
> I believe we can also import the script to the wallet after the user imports its API key.
> 
> This way, even if the user fails backing up the script, we can still retrieve its script by the `listscript` method.
You could do this as well but there's still a potential problem if the user's wallet gets deleted or lost or corrupted and the VSP goes offline.
I raised this issue after I saw a user in support chat that lost access to his funds when he wiped his old files before upgrading to a new version of Decrediton and the pool was no longer available.  That DCR is probably locked forever even though he still has his seed.

**Comment by vctt94** [comment]
Yeah, I agree with you, as right now the script contains info you can't derive from the seed. 

But having the script into the wallet db (despite the fact it can be corrupted, lost, etc..), still better than not having, as there is little we can do about users not backing up their redeem script, but looking at the code now, I noticed we already add the imported script, after adding a new VSP.

Also we need to make sure the user back it up with the same robust methods of backing up their seed, as it may cause permanent fund loss, if the script has never voted.

**Comment by sumiflow** [comment]
> Also we need to make sure the user back it up with the same robust methods of backing up their seed, as it may cause permanent fund loss, if the script has never voted.

Spot on. It might be a somewhat rare case but still a possibility. I doubt that most users are doing this or that they even realize they should.

**Comment by vctt94** [comment]
From @jrick at matrix: 

![image](https://user-images.githubusercontent.com/15069783/73615780-c7ccb680-45e9-11ea-8cc7-927d979c9681.png)

**Comment by matheusd** [comment]
FYI, the relevant dcrwallet issue is this: https://github.com/decred/dcrwallet/issues/1613
