### ISSUE TITLE
Incorrect display of active tickets number

### ISSUE THREAD

**Issue by d146t** [decred/decrediton#2404]
In the ticket section of the overview tab, the number of active tickets shown is 0, even when you have active tickets. Occurs on Mac OS and Linux.
<img width="1435" alt="20200123_ticket_number_display" src="https://user-images.githubusercontent.com/46449825/73078744-1e881100-3ec3-11ea-9bbf-0d9151b3dd12.png">

**Comment by zubairzia0** [comment]
working fine here, is this still occurring? (if you had immature tickets they would have become live tickets by now)

**Comment by matheusd** [comment]
The issue might have been fixed by this: https://github.com/decred/decrediton/pull/2389
