### ISSUE TITLE
Exporting display error on tab switch.

### ISSUE THREAD

**Issue by davecgh** [decred/decrediton#2405]
Whenever performing a lengthy export via `Transactions -> Export`, changing to a separate sub tab results in the filename to export being cleared.  When the export finishes, the result is a toast displaying without the proper filename as seen in this screenshot:

![image](https://user-images.githubusercontent.com/2115102/73131454-d525e780-3fd0-11ea-8d89-f8594484fabe.png)

Reproduction steps:

1. Create a testnet wallet with a lot of transactions if necessary so the export process takes a while
1. Go to `Transactions` -> `Export`
1. Choose a destination and hit `Export`
1. Click on `History` to change the sub tab within the overall `Transactions` section.
1. Return to the `Export` sub tab by clicking on it
1. Wait for the export to complete and observe the improper toast

**Comment by vctt94** [comment]
This was fixed by https://github.com/decred/decrediton/pull/2395, so I am closing this issue.

**Comment by davecgh** [comment]
Cool.  Thanks.  FWIW, I searched before creating this issue and missed that somehow.
