### ISSUE TITLE
[discussion] Functional components & hooks

### ISSUE THREAD

**Issue by amassarwi** [decred/decrediton#2438]
I've discussed privately with @vctt94 on matrix, and we thought opening a discussion issue would be the best way to go here, to get more opinions about it.

We would like to use functional components & hooks in decrediton to improve maintainability - many class components life-cycle hooks will be deprecated soon and functional components is the way in modern react apps.

Of course such change will lead a huge *refactor* but of course if can be done incrementally (e.g page by page).

If we get green light to implement this I'd love to contribute to the efforts to make it happen.

**Comment by vctt94** [comment]
I believe it is a good step updating our code basis towards react last updates. As we can see react is clearly going through this direction and each time working less with classes. 

The good part is that we don't need a rush to update everything at once, so I believe we can start updating some small components and we can see how it goes. 

But I'd rather wait and see @alexlyp and @matheusd 's opinions, before starting any work

**Comment by matheusd** [comment]
Seems reasonable. A quick spot check shows that most class-based components use it just to handle internal state changes, so it shouldn't be too bad.
