### ISSUE TITLE
Ixd: Receive View, minor improvements

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#2450]
Specs/Preview: https://xd.adobe.com/view/dca43feb-3e5a-4ce4-5d73-e1fcdf05946d-aa95/

Made a separate issue for this, as this is slightly different matter than previously brought up on: https://github.com/decred/decrediton/issues/1943

Listing a some minor improvements on the Receive view: 
- Instead of always displaying the QR code, i've replaced that area with three actionable buttons: Copy, View QR and Share. 
- Copy button is the same as before - copies present address to clipboard. 
- View QR firstly background blurs the entire viewport and displays: 1) the present address, 2) QR 3) Decred logo and 4) message `This is My Decred (DCR) Address` inside a modal. Reason for this is to provide an obfuscated way to present the QR code to whoever may scan it. This way the rest of the Wallets details are hidden (ie. sales situation, when one party has a laptop / tablet, other a phone). Also presenting it in a clean and isolated manner provides a better context for screenshotting the QR, with a clear instruction and DCR branding next to it. 
- Share: this should use the Mac or Windows OS level sharing option. Ie. share via email, messenger etc. Default sharing could be in text format, ie.  `This is my Decred (DCR) address: DsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxH`, but if possible the same modal could be rendered as a small png or pdf as that would allow to copy-paste address text or properly print the QR without much loss of quality.
- The spacing and layout is slightly tweaked to best fit the buttons. 
- Buttons have similar styling as elsewhere, with the exception of using `#E9F8FF` as hover color in order to fit with the icons.
- The address component is made slightly smaller, both in size and type. 
- The address components outline should trigger when a new address is generated, or when the address is copied or on mouse hover. 
- A tooltip should be displayed for 3 sec when address is copied to clipboard or a new address is generated. The last two points should ensure there's very clear feedback when interacting with the address component.

**Comment by guilhermemntt** [comment]
According to https://github.com/electron/electron/issues/6330, it seems like Electron applications are not accepting sharing API in Desktop yet. Some applications like Spotify allow this by opening the default user browser at the specific chosen social media page to share. The other option is to implement native code interfaces to background OS, but I think it is not the goal here.
