### ISSUE TITLE
[1.5.1] Blank voted/earned stats on ticket page

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2462]
On the "Overview" tab whilst displaying the "Tickets" chart. To the left of the chart, and under where the total balance is displayed, I am seeing:

> X active tickets
> With a total value of Y DCR
> 
> voted tickets
> Earned

The number of voted tickets and earned DCR are not populated.

**Comment by vctt94** [comment]
This page you mean?

![image](https://user-images.githubusercontent.com/15069783/79752393-9ca15b80-82ea-11ea-9e8e-704faa0c6625.png)


I am not able to reproduce that

**Comment by jholdstock** [comment]
Discussing with @vctt94 on Matrix, seems like it could be a localization issue, missing messages for the en-GB locale. Screenshot shows just two of the missing messages being logged - the ones I think are relevant to the issue described above. There are many more.

![Screenshot from 2020-04-20 16-24-11](https://user-images.githubusercontent.com/6762864/79768961-69c78980-8323-11ea-9cad-a02063b4d2fa.png)

**Comment by jholdstock** [comment]
Fixed by #2782
