### ISSUE TITLE
Layout and rendering issues on Windows

### ISSUE THREAD

**Issue by jrick** [decred/decrediton#247]
![image](https://cloud.githubusercontent.com/assets/1420313/22786681/8ca81078-eea7-11e6-808c-03d07a1ac105.png)
(need to click for the full size image)

There are some layout and rendering issues here.  The most obvious being that the logo does not fit inside the application window.  Compared to the application running on Linux, it seems to be clipped all around the application (notice that there is less margin between the seed word box and the right side of the application).

If you expand the full size image and view it on a non-high-DPI screen you can also notice that fonts are rendering extremely poorly.  There is no subpixel font smoothing that is typical of non-Metro/Modern Windows UIs, and the "Please write down this seed..." message is extremely blurry.  It actually gives me a headache to try and read this.

**Comment by sndurkin** [comment]
The layout as it is now looks okay for me on Windows 10:

![image](https://user-images.githubusercontent.com/1452379/28717811-44d8c982-7371-11e7-80da-0010a956163b.png)

There are a couple minor issues with the logo and the seed word box, but I can fix those with some quick CSS changes. For the logo element, I changed `padding-top: 20px` to `margin-top: 20px` and removed the `width: 100%` rule on the seed word box element:

![image](https://user-images.githubusercontent.com/1452379/28717863-77565014-7371-11e7-9180-c32eec93232e.png)

I can open a PR for these changes if you have time to test them on Linux/OSX. The font is definitely still a problem, though.
