### ISSUE TITLE
Create Decrediton AppImage for Linux

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#2472]
To get around users having to open a terminal in order to launch Decrediton under Gnome (#2277) we could distribute it as an AppImage (https://docs.appimage.org/).
This would greatly enhance UX as there would only be one file which they would set as executable and run by clicking (no extracting archives and clicking the correct file).

Other popular crypto wallets seem to be using this format for distributing on Linux (Ledger Live, Electrum BTC).

I believe we're already using electron-builder so producing an AppImage should be fairly straight forward.
https://www.electron.build/configuration/appimage.html

**Comment by jzbz** [comment]
Done via https://github.com/decred/decrediton/pull/2864.

**Comment by xaur** [comment]
@jzbz Is it the only way to make Decrediton executable via GNOME UI? Did you try creating a `.desktop` file? They basically look like this

```
[Desktop Entry]
Name=Decrediton
Exec={ command line to launch the app }
Type=Application
Icon={ icon path }
```

and must be placed in `~/.local/share/applications`. Full spec describing each key is [here](https://developer.gnome.org/desktop-entry-spec/).

P.S. Having AppImage builds is good in any case (and they can be made _reproducible_ as shown by Electron and others).

**Comment by jzbz** [comment]
Desktop file would work but the user would need to place it in the appropriate location and edit the path to match where they extracted the Decrediton archive, which seems just as convoluted as running it from the CLI.

In the case of the AppImage they still need to mark it as executable either via UI or with `chmod +x`, my understanding is there's no way around that even if it's referenced by a `.desktop` file.

The good news is more and more things are distributed in that format so the work flow is unlikely to be foreign to most users.

**Comment by xaur** [comment]
Agreed, dealing with paths is always a problem for users. This is why a process of "installing" is helpful, it asks you for necessary info and places everything correctly.

For Linux users, the ultimate solution would be to package our software as deb/rpm/etc packages and serve from our package repository server. This would also automate the step of verifying signatures.
