### ISSUE TITLE
Pass extra args to wallet

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#248]
For debug purposes it would be very helpful to pass extra args to wallet from the command line.  Suggested by @jrick based on Paymetheus.

**Comment by jrick** [comment]
![image](https://cloud.githubusercontent.com/assets/1420313/22791339/088edfdc-eeb7-11e6-92af-335b5b530f0d.png)

Other than the fact that visual studio gives me only a small text box for all those args, this works great for development. :)
