### ISSUE TITLE
[Purchase Tickets] Make sure vsp is not down

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2484]
When buying tickets from a VSP, we should make a call before purchasing it, to make sure the vsp is live. 

Right now if a vsp is down, we will purchase the ticket anyway, which will probably, be missed, as the vsp can be not live anymore.

**Comment by guilhermemntt** [comment]
I'm working on this issue now.

**Comment by matheusd** [comment]
Doing a quick check is fine, but do note:

1. We'll change how VSPs work in the near future, moving to accountless, per-ticket VSPs which will require an interaction between the user and the VSP by default (thus making this check redundant)

2. Having an online front-facing web server (which responds to API requests) is no guarantee the VSP is watching over the ticket with their backend wallets

**Comment by jholdstock** [comment]
dcrstakepool already exposes PoolStatus: "Closed" , as seen on chappjcs pool https://dcr.blue/api/v2/stats
