### ISSUE TITLE
Send issue on Transactions tab

### ISSUE THREAD

**Issue by zubairzia0** [decred/decrediton#2495]
When "Send funds to another account" is selected and the "To" account is automatically selected, the send button does not function. Only when an account is selected/reselected does it start working. 
![Sendto account](https://user-images.githubusercontent.com/23157945/82742230-5d22c080-9d29-11ea-9999-8ffc88b3c1db.png)

**Comment by guilhermemntt** [comment]
Right, I've reproduced this behaviour. Even if someone had insufficient funds, a warning should appear just above the "Send" button. I'll take a look closer to fix it.
