### ISSUE TITLE
Windows unclean shutdown

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#250]
On windows, dcrd and dcrwallet do not shutdown cleanly.

**Comment by alexlyp** [comment]
@sndurkin can you comment on this issue from what you have seen recently?

**Comment by sndurkin** [comment]
From the code, it looks to me like there's not really any logic for doing a clean shutdown of dcrd/wallet on any platform. As far as I can tell, it sends SIGINT to both processes (`closeDCRW()` and `closeDCRD()` in `main.development.js`), so I think when logic is added to close them via pipes, it will need to be tested on all platforms.

**Comment by jcvernaleo** [comment]
Both dcrd and dcrwallet do clean shutdowns when they recieve SIGINT (same reason you can safely use ctrl-c to shutdown safely.

Windows however lacks signals (unlike proper OSes :) ) so that whole thing needs to be replaced with pipes for things to be the same on UNIX and other OSes.

**Comment by alexlyp** [comment]
fixed with #636
