### ISSUE TITLE
Use non-bundled dcrd

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#251]
It would be helpful for some users to be able to set there own dcrd (so it can run on a different machine).  Exactly how to set this needs some thinking.  At the very least, this has to wait until #204 gets done since there is little point in this if the settings cannot be saved.

**Comment by jrick** [comment]
Without tooting my own horn too much, I like how Paymetheus does this, although on PM's side, the case when using the bundled dcrd could be made simpler (by running it with a flag that causes it to skip the dialog).

**Comment by peterzen** [comment]
+1 - please also add a `dcrwallet` host option.

**Comment by oktapodia** [comment]
This issue looks already resolved by https://github.com/decred/decrediton#using-existing-dcrd-and-dcrwallet-daemons

**Comment by alexlyp** [comment]
@oktapodia I would say this is partially solved by that.  I'll do some further testing but I think there are few other blocking issues to fully allow non-bunlded dcrd/dcrwallets to work

**Comment by peterzen** [comment]
@alexlyp Could you point me at those issues please?  If it's something that can be solved in Decrediton itself I'd look into finding a solution.

**Comment by matheusd** [comment]
You can currently manually go into `~/.config/decrediton/config.json` and set `daemon_start_advanced` as `true`. Restart decrediton and you'll be able to specify which dcrd you want to connect to.
