### ISSUE TITLE
Change react-select dependency

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2517]
Right now our react-select dependency is at version `1.0.0`, while their repo is at `3.1.0`.

Talking at matrix and @amassarwi suggested we change it to use pi-ui's select input.

So after https://github.com/decred/pi-ui/issues/264 is closed, we can make this change, as it may end with some breaking change and duplicated work, if done before it.

**Comment by amassarwi** [comment]
Can be prefixed with [pi-ui]
