### ISSUE TITLE
My Tickets loading indefinitely

### ISSUE THREAD

**Issue by guilhermemntt** [decred/decrediton#2524]
It seems like Decrediton is trying to load tickets indefinitely when there are no purchased ones. By the way, no indicator is shown in this case.

![Peek 11-06-2020 06-48](https://user-images.githubusercontent.com/39631429/84373051-6a0d3400-abb2-11ea-81f3-0eaf72e5554f.gif)

![Peek 11-06-2020 06-51](https://user-images.githubusercontent.com/39631429/84373075-72656f00-abb2-11ea-9464-d400c1225453.gif)

**Comment by vctt94** [comment]
I also noticed a similar behavior when GETTRANSACTIONS fails. It loads infinitelly, but needs to investigate
