### ISSUE TITLE
Creating new LN account throws error

### ISSUE THREAD

**Issue by guilhermemntt** [decred/decrediton#2529]
Creating a new wallet account to use for LN operations is throwing error due to unknown function.

![image](https://user-images.githubusercontent.com/39631429/84692315-08cfc280-af1c-11ea-9a3a-58e111b600cf.png)

![image](https://user-images.githubusercontent.com/39631429/84692339-12f1c100-af1c-11ea-930a-dcbfb0f72b40.png)

**Comment by matheusd** [comment]
Fixed by #2535
