### ISSUE TITLE
Security section: functional components refactor

### ISSUE THREAD

**Issue by thi4go** [decred/decrediton#2530]
This is a sub-issue from #2438 & #2439, meant to refactor components from the `Security` section of decrediton towards a more functional approach.

**Comment by amassarwi** [comment]
🚀 🎸

**Comment by thi4go** [comment]
On this!

**Comment by amassarwi** [comment]
Great thanks, please keep an eye on components which can be used from pi-ui, and open a separated issue if you find some parts that we could refactor in that regard as well.

**Comment by thi4go** [comment]
Will do mate! :)
