### ISSUE TITLE
[LN] Add padding on channels list

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2538]
the titles look too close, have some padding between them would be good.

![image](https://user-images.githubusercontent.com/15069783/84830994-e6fc3b80-b000-11ea-88d5-e5e9b64f1e1b.png)

**Comment by HlloWrld** [comment]
I will try and work on this

**Comment by fguisso** [comment]
This issue has resolved in #2641

**Comment by johncodesit** [comment]
Hi, I'm a new front end dev workin on decred, here looking for some Good first Issues, I believe as @fguisso stated, this problem is already solved and merged, shouldn' it be closed @vctt94  ?

**Comment by vctt94** [comment]
Sure, thanks for noticing.
