### ISSUE TITLE
Consensus Changes Tab does not appear to be updating.

### ISSUE THREAD

**Issue by hermanlim** [decred/decrediton#2546]
decrediton1.5.1, ubuntu 20.04

![Screenshot_20200625_123435](https://user-images.githubusercontent.com/16378892/85646872-79c36700-b6e0-11ea-93e5-5873bcc95d3e.jpg)

Status remains 'stuck' saying "In progress"
Not fixed by rescanning or restarting
Is correctly displayed on VPS.

**Comment by vctt94** [comment]
This was fixed on https://github.com/decred/decrediton/pull/2442 and should be good for the next release, so I am closing this for now.
