### ISSUE TITLE
"Shutting down decredtion", advanced startup & settings ui issues

### ISSUE THREAD

**Issue by amassarwi** [decred/decrediton#2552]
Currently animation & message aren't centered properly.
I guess this was introduced with #2537.

**Comment by amassarwi** [comment]
Also related to #2537 and reported by @vctt94 on matrix - advanced startup layout is broken:
![image](https://user-images.githubusercontent.com/10324528/86132343-0b6b1400-bae7-11ea-890c-cfd8f60aff5e.png)

**Comment by amassarwi** [comment]
![image](https://user-images.githubusercontent.com/10324528/86479680-e4ae1700-bd4c-11ea-9cdb-0d28eec7eb22.png)

**Comment by amassarwi** [comment]
@vctt94 reported another small ui issue on matrix:

> Choosing wallets is not with cursor pointer

**Comment by vctt94** [comment]
@matheusd reported when decrediton starting going to tutorial page, decrediton crashes

**Comment by amassarwi** [comment]
> @matheusd reported when decrediton starting going to tutorial page, decrediton crashes

on it

**Comment by vctt94** [comment]
On small widths, when there is a error to start, the error goes to the bottom of the page.

![image](https://user-images.githubusercontent.com/15069783/88580886-b3aac480-d022-11ea-96cd-f8449de0883a.png)

**Comment by amassarwi** [comment]
@vctt94 i think we can close this issue, as we fixed most of the listed issues and the remaining alignment issue
is being addressed by @guilhermemntt in #2639

**Comment by vctt94** [comment]
yeah, sure
