### ISSUE TITLE
[vsp] Trim api key 

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2555]
When adding a vsp if the api key as blankets ` `, it will fail to add with wrong key. We should trim it, before trying to add. 

I'd prefer that to be done after https://github.com/decred/decrediton/pull/2516 is merged

![image](https://user-images.githubusercontent.com/15069783/86365648-29a05380-bc50-11ea-9521-427b36f1f4ea.png)

**Comment by mikennaji** [comment]
@vctt94 where can I find the API Key input?

**Comment by francov99** [comment]
Does this still need to be fixed?

**Comment by vctt94** [comment]
Yes, it does.

**Comment by johncodesit** [comment]
@vctt94  is this still open? It could be my first ever contribution to Decred

**Comment by vctt94** [comment]
Hey johncodesit, 

I belive this has been fixed, also we changed the vsp system on our new release. So I am closing this issue for now
