### ISSUE TITLE
Trezor: Letters in Pin entry are odd

### ISSUE THREAD

**Issue by RichardRed0x** [decred/decrediton#2562]
![image](https://user-images.githubusercontent.com/37707106/86542503-128e8980-bf0e-11ea-9c86-11eb7c584883.png)

I haven't seen this kind of display before with letters, usually it is boxes with a . or - or something in them. Using letters makes it slightly more difficult to enter the pin because they cause a mild [Stroop](https://en.wikipedia.org/wiki/Stroop_effect) type interference as the user searches for the right number on their device and corresponding location.

**Comment by JoeGruffins** [comment]
Very similar to #1932
