### ISSUE TITLE
[txHistory] vote info is showing enter timestamp

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2566]
Right now at our overview or my tickets page, we are showing the enter timestamp (which is the date the ticket was purchased). We should show the leave timestamp (the date the vote was voted) 

example: (this ticket was voted today and it is showing may 20:

![image](https://user-images.githubusercontent.com/15069783/86651624-0f50d780-bfba-11ea-94a5-21e43ba006c5.png)

**Comment by guilhermemntt** [comment]
On it.
