### ISSUE TITLE
[LN] Add a copy action to LN node pubkey

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2573]
Right now it is not possible to select or to copy the node pubkey. We can add a copy icon which copies it to clipboard, as it is a public and important information

![image](https://user-images.githubusercontent.com/15069783/87159871-64316e00-c298-11ea-95e5-c7863dca6c0f.png)

**Comment by matheusd** [comment]
I think most of the _data_ should be copyable in general, but that change to make stuff unselectable is now tricky due to the move to css modules (the selectors don't work globally anymore) so I'm not sure the best solution here.

**Comment by amassarwi** [comment]
we wanted to main.css and use normal classes it should work

**Comment by amassarwi** [comment]
Also, Ilike the idea of using pi-ui component which add the nice copy icon here.

**Comment by matheusd** [comment]
closed by #2641
