### ISSUE TITLE
[myTickets] cancel searching tickets is broken

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2582]
When changing ticket's filter, for example to live, it will start looking into transactions and we have an option to cancel:

![image](https://user-images.githubusercontent.com/15069783/87705669-a533f180-c774-11ea-90e6-00ae014a79ee.png)

But when canceling, decrediton is crashing: 

![image](https://user-images.githubusercontent.com/15069783/87705590-82a1d880-c774-11ea-9417-87ce3b818b15.png)

**Comment by guilhermemntt** [comment]
On it.
