### ISSUE TITLE
Double negative tx values

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2590]
Seeing this in a few different places:

![Screenshot from 2020-07-21 11-34-25](https://user-images.githubusercontent.com/6762864/88044968-307eff80-cb46-11ea-8ac7-5bdc137382b1.png)
![Screenshot from 2020-07-21 11-34-16](https://user-images.githubusercontent.com/6762864/88045008-32e15980-cb46-11ea-93f9-f00a40b86382.png)

**Comment by vctt94** [comment]
I am not really sure what the problem here is, can you clarify it?

**Comment by jholdstock** [comment]
I would expect either `0.002 DCR` or `-0.002 DCR`. The value should have either one or zero minus symbols, `--0.002 DCR` is not correct

**Comment by vctt94** [comment]
Oh, I see. Haven't noticed
