### ISSUE TITLE
[overview] warning when new pending tx

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2595]
When there is a pending tx at the overview page, a warning shows:

![image](https://user-images.githubusercontent.com/15069783/88184528-312c9a00-cc09-11ea-9a8c-0e8b16822141.png)

**Comment by amassarwi** [comment]
As discussed on matrix this is a fix on pi-ui we should accept react node besides plain text for tooltip content.

**Comment by vctt94** [comment]
fixed
