### ISSUE TITLE
Create launcher for decrediton

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#26]
Aim is to have a similar launcher to paymetheus.  
Spawn dcrd and dcrwallet child processes so decrediton works straight off the bat.

First iteration can just be a simple process spawner, but in the end dcrd/dcrwallet should be fully functional but practically invisible to the user for ease of use.

**Comment by jcvernaleo** [comment]
Should this one maybe get split up into OS specific tasks?  There may be osx/linux differences and almost certainly windows differences.  Or do we want to just assume Linux for now and worry about tracking the others when we actually start building/testing on them?

**Comment by alexlyp** [comment]
Good point.  

Right, I think linux/mac should be the aims of decrediton since windows is already mostly covered by PM

**Comment by jrick** [comment]
I'm guessing the only differences between the platforms will be file paths.  Get it implemented on one and it "should" be trivial to port elsewhere.

**Comment by jcvernaleo** [comment]
As mentioned in #37, this should start dcrd and dcrwallet listening on non-standard ports like paymetheus does so as not to interfere with other copies.
