### ISSUE TITLE
[css modules] Add global style modules

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2608]
In decrediton we may have some styles which are the same for the whole application, for example, the class `is-row` which is used to describe a flex row around the code. 

Rigth now if we need it with modules, we are adding `isRow` to many css modules, with the same code, which could be avoided if we have a shared global css modules, which are the same for many applications places.

**Comment by amassarwi** [comment]
Make total sense, we need a `main.css` to replace `main.less` which can be used as plain classes without module hashing, and as @vctt94 mentioned can be used globally from any part of the app using string classes.

Usage would look something like:

`className={classNames(styles.somthing, "classFromMainCss")}`

**Comment by amassarwi** [comment]
https://github.com/decred/decrediton/pull/3324 introduces `main.css` file for global styling.
