### ISSUE TITLE
[governance] proposal not yet voting showing eligible tickets

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2610]
Right now we are showing eligible tickets for a proposal not yet on voting staging, example:

![image](https://user-images.githubusercontent.com/15069783/88654372-aaae0780-d0a3-11ea-9963-e24d11f8491f.png)

So as it is not on voting stage, it does not have eligible tickets, so we should not show this info on proposals on that stage.

**Comment by amassarwi** [comment]
Good point 👍

**Comment by amassarwi** [comment]
On it
