### ISSUE TITLE
[governance] voting proposals looks weird

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2611]
The area to vote on a proposal looks weird: 

![image](https://user-images.githubusercontent.com/15069783/88657592-8c96d600-d0a8-11ea-8cbc-c27d3507a84a.png)

**Comment by amassarwi** [comment]
hrmmm that's new & strange, will try track it down

**Comment by amassarwi** [comment]
on it

**Comment by amassarwi** [comment]
Seems like a general issue with the radio button, as it currently also broken in eligible tickets component.
