### ISSUE TITLE
Add more lint rules for react

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#262]
Need to add to .eslintrc.js
```
-  "extends": "eslint:recommended",
+  "extends": ["eslint:recommended", "plugin:react/recommended"],
```

That finds a whole bunch of places where we don't follow the rule:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md
which is a nice type checking rule which we should follow.

**Comment by jcvernaleo** [comment]
And just to save searching, here are the docs for that react type stuff:
https://facebook.github.io/react/docs/typechecking-with-proptypes.html

**Comment by jcvernaleo** [comment]
@alexlyp might want to confer with other js devs to see if we are missing anything useful beyond the one I linked to.

**Comment by alexlyp** [comment]
we're good for now on eslint rules
