### ISSUE TITLE
[tickets]  Cancel button in Configure VSP page no working

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#2625]
Clicked on the "advanced settings" gear on the Purchase Tickets page then the little circle button.  

There are no VSPs listed and nothing happens when I click cancel of Add VSP

**Comment by guilhermemntt** [comment]
It'll probably be fixed by https://github.com/decred/decrediton/pull/2604.

**Comment by vctt94** [comment]
I am closing this as #2604 got merged
