### ISSUE TITLE
Multiple CSS misalignment bugs

### ISSUE THREAD

**Issue by guilhermemntt** [decred/decrediton#2639]
As we're close to the next release version of Decrediton, it's important to fix the various CSS issues generated during past implementations. Feel free to add other bugs to this issue.
Items found so far:

- **Transactions**

  - Misaligment in send DCR page.

  ![transaction-misaligment](https://user-images.githubusercontent.com/39631429/91337067-3b622b00-e7a9-11ea-9971-05aa1a580126.png)

  - Misaligment in export transactions page.

  ![export-transactions-misaligment](https://user-images.githubusercontent.com/39631429/91338447-56359f00-e7ab-11ea-9c22-7b3ece99e116.png)

  - Misaligment in transaction history page.

  ![image](https://user-images.githubusercontent.com/39631429/91369190-8dbf3e00-e7e1-11ea-91cb-96809e8fa037.png)

  - Receive page has no responsiveness.

- **Governance**

  - Voting progress overflows it's list container.

  ![image](https://user-images.githubusercontent.com/39631429/91369339-eb538a80-e7e1-11ea-8723-6932e46fe9cc.png)

- **Overview**

  - Scrollbar does not scroll till the end of page.

![image](https://user-images.githubusercontent.com/39631429/91370723-76824f80-e7e5-11ea-83db-55cb346faf8f.png)

- **Tickets**

  - Tickets list columns intersecting each other.
  
  ![tickets-list-misaligment](https://user-images.githubusercontent.com/39631429/91337609-04404980-e7aa-11ea-9293-14be3fab0dba.png)

  - Broken title responsiveness.

- **About modal:** there's a scrollbar when minimizing the window.

- **Accounts** 

  - Broken title responsiveness.

  - Broken list item responsiveness.

- **Settings:** misaligment when considering high resolutions - observed in https://github.com/decred/decrediton/issues/2552#issuecomment-653581460.

  ![settings](https://user-images.githubusercontent.com/39631429/91338659-a7de2980-e7ab-11ea-9859-c3ba24382400.png)

**Comment by guilhermemntt** [comment]
On it.

**Comment by guilhermemntt** [comment]
"Transaction History" page and "My Tickets" page require some visual design attention, as its columns tends to invade each other in small dimensions. Have you got suggestion here, @linnutee?

**Comment by linnutee** [comment]
Pretty sure these had some examples with specs. Will dig out.

**Comment by linnutee** [comment]
This should be one of the recent versions that includes most of the responsive views, as well work that was done for wider widths. What to keep in mind on some of the smallest views and components is the adaptive changes. Ie. on that example since the columns can't fit horizontally on that width, they are positioned then on two rows instead. 

https://xd.adobe.com/view/7c4f3f55-4ded-446b-9c5d-a22d1a670c1e-291c/screen/520defe2-8399-4fb2-8780-f7ca541bdc5a/specs/

**Comment by guilhermemntt** [comment]
Thank you @linnutee ! I'll work on this.
