### ISSUE TITLE
[My Tickets] Header looks weird with sidebar reduced

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2670]
When the sidebar is reduced, the headers of the table looks weird: 

![image](https://user-images.githubusercontent.com/15069783/93337992-3b7da580-f800-11ea-9307-5a0813d21f3e.png)

**Comment by victorgcramos** [comment]
On it!

**Comment by victorgcramos** [comment]
I'll take the opportunity to refactor MyTickets component to use functional components + hooks
