### ISSUE TITLE
[responsiveness] overview looks weird in small widths: 

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2679]
The icon which shows the menu active looks weird and we should put the tables in the same column, so we can see them

![image](https://user-images.githubusercontent.com/15069783/94269472-16cab180-ff15-11ea-94e8-f46bb8a2b151.png)

**Comment by victorgcramos** [comment]
I think #2673 fixes it.

**Comment by victorgcramos** [comment]
Nop, it doesn't. My branch was outdated, and when I did a rebase, I got those errors.

**Comment by victorgcramos** [comment]
On this!
