### ISSUE TITLE
[dcrInput] DcrInput with inputs smaller than 1 is buggy

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2682]
It is possible that when the amount on dcrInput is smaller than 1 it shows as 0.

I think that maybe it can also be a good oportunity to refactor it to a functional component

**Comment by matheusd** [comment]
Initial amounts < 1 DCR also don't seem to be correctly handled (for example `<DcrInput amount={1} />` doesn't seem to correctly fill the initial input value as `0.00000001`.
