### ISSUE TITLE
[trezor] Init device fails

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2686]
When initing a trezor device, although everything goes fine with the device, decrediton fails: 

![image](https://user-images.githubusercontent.com/15069783/95202314-895e4b80-07b7-11eb-9c6c-c50739862694.png)

**Comment by JoeGruffins** [comment]
@vctt94 Working since #2705 is in?

**Comment by vctt94** [comment]
No, that's fixed. Thanks
