### ISSUE TITLE
Missing filename on .csv export

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2691]
Popup toast notification says `{filename}` instead of the actual filename

![Screenshot from 2020-10-07 10-36-26](https://user-images.githubusercontent.com/6762864/95314276-00afe000-0889-11eb-9ba0-fc48e27718f9.png)

**Comment by amassarwi** [comment]
On it

**Comment by amassarwi** [comment]
Can't reproduce on macos.

**Comment by jholdstock** [comment]
Possibly because I am running british english language, not american english

**Comment by jholdstock** [comment]
Fixed by #2782
