### ISSUE TITLE
Tickets csv export includes "Time" column

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2693]
The first column of the Tickets .csv export is "Time", but this isn't listed in the description:

```
"time","spenderTimestamp","status","ticketHash","spenderHash","sentAmount","returnedAmount"
"2019-09-10T16:29:25.000+0100","2019-09-12T09:10:50.000+0100","revoked",,"78812ab542649090b40b0a456ca033c4f370bf378da345c2386f2e7c54ced167",24.44004763,24.40934749
```

![Screenshot from 2020-10-07 10-55-23](https://user-images.githubusercontent.com/6762864/95316368-9f3d4080-088b-11eb-8b16-e51c9d75712c.png)

**Comment by thi4go** [comment]
On this. Also on #2692 since they are related
