### ISSUE TITLE
Dark mode: white panel on transaction history page

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2696]
White panel stands out against everything else, I assume it was something which was missed whilst implementing dark mode.
"Amount Range" in black is difficult to read on dark blue background.

As a seperate thing - why is this panel closable with an x icon? It doesnt seem necessary, and its also impossible to restore the panel after it has been closed which is inconvenient.

![Screenshot from 2020-10-07 12-23-01](https://user-images.githubusercontent.com/6762864/95324604-e5989c80-0897-11eb-98c4-cf9f3c0a3659.png)

**Comment by amassarwi** [comment]
On it
