### ISSUE TITLE
Verify Message shows two results at once

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2699]
I verified one message with correct signature, green "Valid signature" result was displayed as expected.

I modified the signature and pressed "verify message" button again. An "invalid signature" result was displayed, as expected, but the old "Valid" response was not cleared.

 Some sample data to recreate the issue:
> Address: `TsganSasmr8t9z6yRWX6hw8RyGKxHGgfGwP`
> Signature: `IAGp3L2F1uIZQCnggTqicLXCyuw8t4kEFZl0hsGUq1QSImSQTrYKirNIzcZ5toTv4A/hIlC/DfXxELkkmSOYqUQ=`
> Message: `message`

![Peek 2020-10-07 14-29](https://user-images.githubusercontent.com/6762864/95337250-8fccf000-08a9-11eb-90dc-8a7e811c88f1.gif)

**Comment by amassarwi** [comment]
On it
