### ISSUE TITLE
Sign Message validation triggering on Validate address field

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2700]
- Enter a valid address into the Validate Address field. "Owned address" result appears - expected.
- Modify the Address field in the sign message form - the Validate Address result below changes to "Invalid address", even though the field value has not changed

![Peek 2020-10-07 14-31](https://user-images.githubusercontent.com/6762864/95337568-e1757a80-08a9-11eb-886a-722cdeaa9281.gif)

**Comment by victorgcramos** [comment]
On this!
