### ISSUE TITLE
Comma seperate atom values

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2701]
Decred values are comma separated, but atom values are not. This is problematic because atom values are usually longer and thus need comma separation even more than Decred values.

![Screenshot from 2020-10-07 12-51-32](https://user-images.githubusercontent.com/6762864/95327424-ed5a4000-089b-11eb-9033-3fddcf936bbc.png)

**Comment by bgptr** [comment]
on this

**Comment by xaur** [comment]
FYI thousand separator varies by language (can be `,` or `.` or ` `). Some locales even use [groups](https://en.wikipedia.org/wiki/Decimal_separator#Digit_grouping) other than 3 digits.
