### ISSUE TITLE
Cannot change consensus vote choices

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2702]
Each of the agendas on the "Consensus Changes" tab has a three dots icon to open a menu, but none of them can actually be clicked. As a result, it is not possible to change vote preferences

![Screenshot from 2020-10-07 12-55-50](https://user-images.githubusercontent.com/6762864/95327870-9d2fad80-089c-11eb-9400-96224b4f7556.png)

**Comment by victorgcramos** [comment]
on this!

**Comment by amassarwi** [comment]
Actually does make sense to be able to change the vote choices even though the vote was finished ?
Can we maybe just ditch the `You may still toggle ...` part?

**Comment by victorgcramos** [comment]
I agree @amassarwi, but I found out that the component is still not working properly, and needs some love. I'm on it! Thanks for the feedback!
