### ISSUE TITLE
Tx History: Pending tx ellipsis drawn over tx type menu 

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2708]
The animated ellipsis shown next to an unmined transaction in the transaction history list is rendered over the dropdown transaction type selection menu - I would expect the menu to be drawn on top

![Peek 2020-10-12 09-42](https://user-images.githubusercontent.com/6762864/95725417-89ef5a00-0c6f-11eb-8570-5d3a17cfbb22.gif)

**Comment by bgptr** [comment]
on this
