### ISSUE TITLE
"Tickets eligible for voting" alignment

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2723]
- `default` account name is not centered in its borders - This also affects the "Tickets tab" > "My Tickets" table.
- Little/no padding between transcation ID and account name
- Date is not aligned under the "Purchased heading", too far left

![Screenshot from 2020-10-15 10-09-55](https://user-images.githubusercontent.com/6762864/96103757-fe283880-0ecf-11eb-9f0c-24609306b6b9.png)

**Comment by bgptr** [comment]
on this
