### ISSUE TITLE
[testnet] Create wallet needs seed input

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2740]
When creating a wallet on testnet, only adding password and its confirmation should be enough for creating the wallet, but right now the seed is being required

**Comment by bgptr** [comment]
on this

**Comment by matheusd** [comment]
Weird, I just tested it and worked fine on latest master (created a testnet wallet without confirming the seed, only by entering the passphrase)

**Comment by alexlyp** [comment]
Same @matheusd seems to work fine

**Comment by bgptr** [comment]
@alexlyp @matheusd i could only reproduce it by going back and forth to the previus `copy` view.
