### ISSUE TITLE
Cannot verify messages

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2750]
I generated a message, signature and address on the sign message panel, and copied them straight into the verify message panel. I'm getting both `Invalid Signature` validation error, and a toast notification indicating a coding error (`TypeError: Cannot read property 'verifyMessage' of undefined`), even though the data is all valid.

```
Address: Tsia9KpKCGyxkLNFo2QdHrdXfkBU7MQccHP
Message: 12345
Signature: H4O80vrzDfjwZ43LGrbbW2ArjLU+dhYv391vqRt03lh4BjVs7k2ygubBGbxBwXqdDUzrc6VhYPbopUvN0HXpYJ8=
```

![Screenshot from 2020-10-20 09-41-41](https://user-images.githubusercontent.com/6762864/96562496-bd0d9b00-12b8-11eb-9703-b573cefdf8b7.png)

**Comment by victorgcramos** [comment]
on this! 😅
