### ISSUE TITLE
Peer count is incorrect

### ISSUE THREAD

**Issue by jrick** [decred/decrediton#2759]
This is in RPC mode.

![Screen Shot 2020-10-21 at 5 18 54 PM](https://user-images.githubusercontent.com/1420313/96788712-ecf49580-13c1-11eb-9c74-f4c414904084.png)

As you can see from the dcrd log, I currently have 8 outbound peers, yet decrediton reports two.

There isn't any notifications for new or lost peers, so I guess this is just polling?

**Comment by vctt94** [comment]
Correct. It is polling every minute, so that's probably the reason of that. 

Do you think we should decrease this time?
