### ISSUE TITLE
Voted tickets show purchase time, not vote time

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2760]
In the Overview tab, under the "Staking Activity" heading, voted tickets used to display their vote timestamp, but they now display the purchase timestamp which is not so useful. 

This is odd because it causes the dates in the list to be out of order, for example:

```
Staking Activity

Live    22 October
Voted   13 July     -> should be 21 October (vote time)
Live    20 October
Live    19 October
Voted   10 April    -> should be 18 October (vote time)
Live    18 October 
```

Apologies for not sharing a real screenshot of this - I observed it on mainnet and didnt want to share real info about my staking :stuck_out_tongue:

**Comment by amassarwi** [comment]
Reproduced here, I see also some voted tickets having _Purchased_ status.

**Comment by vctt94** [comment]
duplicated: https://github.com/decred/decrediton/issues/2566
