### ISSUE TITLE
VSP-fee wallets aren't loading

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#2769]
By "VSP-fee wallets" I mean wallets that are used to receive the ticket fees from the legacy VSP mechanism. Trying to load a wallet with such transactions triggers a "cannot read property getHash of undefined"

**Comment by matheusd** [comment]
I can provide an xpub key for a testnet wallet that has such transactions.

**Comment by jholdstock** [comment]
I am also hitting this. Whilst creating a watch-only wallet with the master pubkey defined in the dcrstakepool test harness:

`tpubVpksTuUYrAgbfwZvU3h9gPLPemf6WCisSrEtYS7gKWqRdPKeqd9t8wPxX99ubvm82N18JeFhhK357q5PuJsVj1qnC7MFVjS37dMjzH7SD34`

**Comment by amassarwi** [comment]
will investigate 👀
