### ISSUE TITLE
Is Legacy should be checked by default

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2785]
The new and legacy VSP forms are very similar, and when you open the Tickets tab its not immediately obvious which one you are looking at.

In order to keep a smooth UX for users of legacys VSPs (ie. everybody right now) - the legacy VSP form should be the default, and switching to the new VSP form should be a conscious choice.

As a bonus - decrediton should remember which one you had open most recently. Eg. If I buy legacy tickets, next time I open decrediton it should open the legacy form.

**Comment by bgptr** [comment]
on this
