### ISSUE TITLE
"Finished Voting" proposals ordering

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2786]
Proposals in the "Finished Voting" list are ordered by their status - all of the "Passed" proposals come first, and then all of the "Declined/Quorum not met" proposals. I would expect this list to be time ordered. To provide an example, if I want to check the status of the D.R.E.A.M proposal, which finished voting only a few days ago, I need to scroll past every "Passed" proposal to find it, which is a long way down. The proposals are loaded in small batches, so scrolling down a long way is slow.

**Comment by victorgcramos** [comment]
Good one! On it!
