### ISSUE TITLE
LN Warning style

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2798]
This page stands out as not conforming to the Decrediton style. Eg:

- Colours are wrong - for a good example of correct colour/style for a markdown document, check "Help" > "Constitution"
- Links are barely visible in dark mode
- Left padding is insufficient when window is slightly shrunk horizontally
- Button needs more top padding
- Capitalizing every word on the button is odd. Would be better as  "I understand and accept the risks"

In addition, a bit of padding between each bullet will make the page look less like an imposing wall of text, and more like easily digestible chunks. This should increase the chance of people actually reading it.

![Screenshot from 2020-10-27 08-41-49](https://user-images.githubusercontent.com/6762864/97277731-c1920080-1830-11eb-8a25-f2481f7ad757.png)
![Screenshot from 2020-10-27 08-42-45](https://user-images.githubusercontent.com/6762864/97277732-c1920080-1830-11eb-8fcc-b12c1b7256f4.png)

**Comment by bgptr** [comment]
on this
