### ISSUE TITLE
"Send all funds" button does not activate Send button

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2799]
- Open Transactions tab
- Enter a valid recipient address
- Click "Send all funds"
- Send button does not activate, even though the form is filled with valid data.

![Peek 2020-10-27 09-01](https://user-images.githubusercontent.com/6762864/97279583-15054e00-1833-11eb-9fdd-12013595aec7.gif)

**Comment by bgptr** [comment]
on this
