### ISSUE TITLE
Dark mode: Wallet sync progress bar difficult to read

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2800]
In the first screenshot, "Syncing RPC connection" is difficult to read. Light blue/gray on a blue background.

The background colour for this text does not change when dark mode is enabled, so I would suggest the colour of the text should not change either, it should remain white. This also applies to the icons (see screenshots 2 & 3)

![Screenshot from 2020-10-27 09-13-33](https://user-images.githubusercontent.com/6762864/97281019-e7b99f80-1834-11eb-87d6-6c803c888364.png)

![Screenshot from 2020-10-27 09-17-01](https://user-images.githubusercontent.com/6762864/97281294-36ffd000-1835-11eb-9995-4b73ddaca2ed.png)
![Screenshot from 2020-10-27 09-17-09](https://user-images.githubusercontent.com/6762864/97281295-37986680-1835-11eb-9514-c83280c2987f.png)

**Comment by bgptr** [comment]
on this
