### ISSUE TITLE
Peer count is ugly

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2801]
The peer count is really ugly, the circle border does not match any other style in Decrediton. Large text, always visible at the top of the navbar is just not right for this.

I would suggest to put this at the bottom of the navbar, similar to the Latest block label.

![Screenshot from 2020-10-27 09-18-37](https://user-images.githubusercontent.com/6762864/97281454-73333080-1835-11eb-87e4-d8795aa9cae5.png)

**Comment by amassarwi** [comment]
On it
