### ISSUE TITLE
LN: Button with invisible icon

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2804]
A magnifying glass is shown when you hover on this button, but nothing is shown by default

![Screenshot from 2020-10-27 09-57-46](https://user-images.githubusercontent.com/6762864/97286129-0884f380-183b-11eb-89cc-03917c21797a.png)

**Comment by guilhermemntt** [comment]
I'll solve it in https://github.com/decred/decrediton/issues/2811 fix.
