### ISSUE TITLE
Decrediton doesn't display dcrd logs when using remote daemon

### ISSUE THREAD

**Issue by guilhermemntt** [decred/decrediton#2828]
When starting Decrediton with ``daemon_start_advanced`` flag setted to ``true`` and using a remote dcrd instance, "Help" -> "Logs" -> "dcrd" pane remains blank and does not show dcrd logs.

**Comment by vctt94** [comment]
That's correct, if decrediton did not spawn dcrd it is not possible to read logs from it. 

Closing this issue.
