### ISSUE TITLE
watching only wallet: Asked for password to discover accounts.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/decrediton#2842]
This must be due to something recent. When creating a watching only wallet I am asked to provide a passphrase which does not exist to discover accounts that can't be discovered. Afterwards I am unable to open the wallet at all with the error: 
```
react_devtools_backend.js:6 Error: 12 UNIMPLEMENTED: wallet.Unlock: watching only wallet: watching wallets can not be unlocked
```

![discoveraccounts](https://user-images.githubusercontent.com/34998433/97861647-718ece80-1d47-11eb-947b-c92992ab42d1.png)

**Comment by JoeGruffins** [comment]
After restarting decrediton, I am unable to open the wallet and continue as normal.

**Comment by matheusd** [comment]
Probably side effect from #2815 

I'll check it out.
