### ISSUE TITLE
SPV enable shows double log message

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2849]
- Open Decrediton
- Open a wallet with SPV disabled
- Go to the settings tab, disable SPV, hit save
- Accept the prompt to restart decrediton
- "Shutdown complete" message is shown, and when a new wallet is loaded, a duplicate log message is show. 

I guess "Shutdown complete" should be removed before the new log messages are displayed.

![Screenshot from 2020-11-03 10-24-51](https://user-images.githubusercontent.com/6762864/97974074-fe28a380-1dbe-11eb-8c42-196fb64b46a3.png)

**Comment by amassarwi** [comment]
on it
