### ISSUE TITLE
Legacy autobuyer issues

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2852]
On the legacy VSP page, teststakepool.decred.org is configured to purchase tickets, however it cannot be selected for automatic ticket purchases. "No results found"  is shown instead

As well as the above, it is also possible to click on the "Turn on" button without setting a VSP or a purchase account.

![Screenshot from 2020-11-03 12-13-35](https://user-images.githubusercontent.com/6762864/97984021-0fc57780-1dce-11eb-8401-299caf9edfaf.png)

**Comment by bgptr** [comment]
on this
