### ISSUE TITLE
[Governance] Longer height screens not loading more proposals

### ISSUE THREAD

**Issue by victorgcramos** [decred/decrediton#2861]
I noticed that if you have a screen's height > 20 proposals list height, the component won't load more proposals.

After investigating it a bit, I figured it out that the `InfiniteScroller` component does not trigger the `loadMore` action, since it considers the list complete.

<img width="2437" alt="Screen Shot 2020-11-04 at 12 18 20 PM" src="https://user-images.githubusercontent.com/22639213/98130833-72377a00-1e99-11eb-9d3f-44f7e479d387.png">

**Comment by bgptr** [comment]
on this
