### ISSUE TITLE
[1.6.0-rc2] Live tickets are not shown in ticket summary

### ISSUE THREAD

**Issue by darthcrypto87** [decred/decrediton#2868]
I have some tickets live but they don't show up in the ticket summary.
They were bought before I ran 1.6.0, SPV mode is deactivated.

![image](https://user-images.githubusercontent.com/26526304/98327730-893eaf00-1ff4-11eb-96bf-44dce8252e01.png)

![image](https://user-images.githubusercontent.com/26526304/98327622-42e95000-1ff4-11eb-9731-bd0b5d52fa8b.png)

**Comment by darthcrypto87** [comment]
Addition: The live tickets also don't show up when I have no filter active
![grafik](https://user-images.githubusercontent.com/26526304/98338415-733be900-200a-11eb-94b9-9fdfb4f893ed.png)

**Comment by matheusd** [comment]
Try setting the "Is Legacy" checkbox in the Purchase tab and see if they show up.

**Comment by vctt94** [comment]
I think this will not solve it @matheusd 

Right now live old vsp tickets are not being showed, which is wrong. Maybe we should show them at ticket status, as well?

**Comment by darthcrypto87** [comment]
Sorry, but that didn't do the trick.
I have restarted the wallet after checking "Legacy" but the live tickets still won't appear.
