### ISSUE TITLE
[1.6.0-rc2] Transactions History Range Filter from 0-100

### ISSUE THREAD

**Issue by karamble** [decred/decrediton#2874]
When opening the transactions history the range filter for the dcr amount is set to 0-100 per default.

Once the min amount is moved to a minimum of 1dcr to filter out all dust mix transactions the range filter is not able to be put back to 0 to see all transactions again.
![image](https://user-images.githubusercontent.com/25404928/98406791-7f559400-2066-11eb-985e-11767a1f2d48.png)

**Comment by guilhermemntt** [comment]
Please, check the slider's min/max limits:

![image](https://user-images.githubusercontent.com/39631429/98413484-7362d580-2058-11eb-933f-e4b1dd24edc9.png)

Anyway, I'm going to take a look at that. The purpose of the right three-point menu is unclear and I think we can improve this feature with a tooltip. Also, the slider is disappearing during some renderings and we should have a left margin before the min/ max inputs.

Thanks for your report!
