### ISSUE TITLE
[1.6.0-rc2] Purchasing single tickets from mixed account resulting in error

### ISSUE THREAD

**Issue by karamble** [decred/decrediton#2875]
Purchase from mixed account resulting in error: 

`[ERR] GRPC: Unary method /walletrpc.WalletService/PurchaseTickets invoked by 127.0.0.1:45544 errored: wallet.PurchaseTicketsWithResponse: insufficient balance:: txauthor.NewUnsignedTransaction`

![image](https://user-images.githubusercontent.com/25404928/98407556-c7c18180-2067-11eb-9a60-abef675dad14.png)

**Comment by alexlyp** [comment]
So this isn't totally unexpected.  Due to the way ticket purchasing works with the new VSPs there needs to be a certain number of utxos available.  I'm guessing this is what caused this error for you.

**Comment by karamble** [comment]
same behaviour with purchases from accounts where incoming funds are still in mempool.

**Comment by RichardRed0x** [comment]
I got the same kind of error buying a second ticket from an unmixed account, the first one went through alright but when I went back for a second ticket I got an error like this one.

**Comment by orangegelato** [comment]
Getting the same error here, exacly as mentioned by RichardRed0x.
