### ISSUE TITLE
[1.6.0-rc2] sending funds is only possible from mixed account

### ISSUE THREAD

**Issue by karamble** [decred/decrediton#2877]
The user is not able to access any funds that are spread over his different accounts. This will ultimately lead the user beeing forced to multiple mix and transact in order to manage his own accounts, makes the usability of transactions with the wallet depending on cssp epochs unuseable for a lot of use cases. User should have the opportunity to operate mixing, not constantly required to do so.

Please let the user decide from which account they want to send funds from. I can understand the way it is implemented strict right now, but at least give a section in the settings to enable the selection of accounts again. Grey out account selection for the other users, as it obviously would 'not be required' when sending funds only from mixed account per default.

**Comment by RichardRed0x** [comment]
It seems possible to transfer between accounts but not to send to an (external) address from any account except "mixed". For people with 0 balance in their mixed account, upon upgrading to 1.6 they have no way to spend any of their DCR without first mixing it.

**Comment by xaur** [comment]
> For people with 0 balance in their mixed account, upon upgrading to 1.6 they have no way to spend any of their DCR without first mixing it.

Is it only the case in Privacy mode or regardless of it?

**Comment by jholdstock** [comment]
This only affected wallets with privacy enabled
