### ISSUE TITLE
[1.6.0-rc2] mixing autobuyer button giving "Account balance too small" error on incorrect passphrase

### ISSUE THREAD

**Issue by RichardRed0x** [decred/decrediton#2878]
When I click to turn on autobuyer I get a message about account balance too small if I enter incorrect passphrase

**Comment by amassarwi** [comment]
On it

**Comment by amassarwi** [comment]
I'm trying to reproduce on master, i clicked the mixing toggle and tried wrong password and got an error `...incorrect passphrase` not the error mentioned in title.

I found another issue with the toggle which was still on after an error, which shouldn't be the case, I can fix that tho.
