### ISSUE TITLE
typo in the Start Mixer popup text

### ISSUE THREAD

**Issue by RichardRed0x** [decred/decrediton#2879]
![image](https://user-images.githubusercontent.com/37707106/98484449-6f28ea80-2207-11eb-8c12-1753aa76baeb.png)

Decrediton must remain running for *the* mixer to properly mix inputs.

This could be a bit more informative too perhaps, with some idea of how long Decrediton might have to remain open for or when the user knows it is safe to close.

**Comment by jholdstock** [comment]
I will take this one
