### ISSUE TITLE
Copy for the "Enable Privacy-preserving mode" button

### ISSUE THREAD

**Issue by RichardRed0x** [decred/decrediton#2880]
![create-mixing-accounts](https://user-images.githubusercontent.com/37707106/98489645-cb4f3700-2226-11eb-8e9f-090a3d317580.png)

As "creating the default accounts" changes how Decrediton operates, I suggest using language like "switch to privacy-preserving mode".

Here's some draft copy that could be used to further explain what's happening to the user:

Create Default Accounts and enable Privacy-preserving mode

Do you wish to create default mixing accounts mixed and unmixed? **This action can not be undone**

Once you Create Default Accounts, you will only be able to send DCR from your Mixed account. This is because DCR in other accounts which has not been mixed can be easily tracked. 

After creating the mixing accounts, you must mix the DCR in your default account and any other accounts you are using, so that it moves to the Mixed account, before you can spend it. You can do this either by mixing the DCR directly in the Privacy tab (you must move the DCR you wish to mix to the "unmixed" account), or by using it to buy mixed tickets in the Tickets tab. **It is important that you do not close Decrediton while the mixing is taking place.**

**Comment by jholdstock** [comment]
I will take this along with #2879
