### ISSUE TITLE
button to add more outputs looks ugly on dark mode

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2883]
When clicking to send funds to another account, the add output button is disabled and looks like this:

![image](https://user-images.githubusercontent.com/15069783/98546197-548d5a80-2275-11eb-951f-ef89d23220f0.png)

It barely can see the `+` and it doesn't give the idea of a disabled button on dark mode

**Comment by amassarwi** [comment]
hrmm i think this is good place to consider pi-ui as we do have a very similar button in pigui for user credits somewhere :thinking:

**Comment by amassarwi** [comment]
and on it
