### ISSUE TITLE
[1.6.0 rc2] Perpetually mixing and unhelpful error

### ISSUE THREAD

**Issue by RichardRed0x** [decred/decrediton#2892]
I have the mixing animation and message going for several days now, the balance has been 0 in the unmixed account and no transactions for >24 hrs.

Not sure if related but when I eventually turned off the autobuyer it gave a not helpful error.

![image](https://user-images.githubusercontent.com/37707106/98655062-f759dd80-2336-11eb-8148-a70474725bb8.png)

**Comment by amassarwi** [comment]
on it
