### ISSUE TITLE
Replace grpc with @grpc/grpc-js

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#2900]
We should investigate replacing the grpc package.  

https://www.npmjs.com/package/@grpc/grpc-js#migrating-from-grpc 

The instructions look pretty straightforward, but I can't seem to get the regen.sh to take the grpc_js or generate_package_definitions arguments.  Maybe I'm missing something from here:
 https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools

**Comment by bgptr** [comment]
on this

**Comment by amassarwi** [comment]
done in https://github.com/decred/decrediton/pull/2936
