### ISSUE TITLE
Incorrect dot colours on Proposals

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2905]
The colours of the dots above the "Passed/Declined/Quorum" status should be green if passed, red if declined, gray if quorum not met. At the moment they almost seem to be random.

![Screenshot from 2020-11-11 12-40-21](https://user-images.githubusercontent.com/6762864/98812827-192c9080-241b-11eb-964d-3c31c5cbc792.png)

**Comment by amassarwi** [comment]
On it
