### ISSUE TITLE
Typo in SPV configuration (Wizard step)

### ISSUE THREAD

**Issue by ordtrogen** [decred/decrediton#2906]
Just installed and started Decrediton for the first time on a machine and during the configuration steps you get to this point. There's a typo although I'm not sure what it should say. What was intended was probably

"Select how Decrediton wallets should connect [...]" (presumes you can have several wallet in the application)

other possibilities
"Select how the Decrediton wallet should connect [...]"
"Select how Decrediton's wallet should connect [...]"
"Select how Decrediton's wallets should connect [...]"

![image](https://user-images.githubusercontent.com/15184875/98814730-62361200-2426-11eb-8a57-e60c08022a42.png)

**Comment by jholdstock** [comment]
Thanks for the report. #2916 takes care of this. I actually just removed the word wallet completely:

> Select how Decrediton should connect to the Decred network.
