### ISSUE TITLE
Politeia CSRF error when switching network

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2914]
- Open Decrediton
- Visit the Governance tab, proposals from Politeia are loaded.
- Settings tab - switch network - Save - Confirm
- Open a wallet on the new network
- Visit the Governance tab, 403 errors from Politeia. Decrediton log shows CSRF errors.

I would guess Decrediton has cached and reused the CSRF token from the previous network which is not valid on the new network. Restarting Decrediton fixes the problem.

```
{
    "data":"Forbidden - CSRF token invalid\n",
    "status":403,
    "statusText":"",
    ...
}
```

**Comment by amassarwi** [comment]
On it
