### ISSUE TITLE
"Options not defined" when VSP listing is disabled

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2921]
When "VSP Listing" is disabled on the Settings tab, the VSP form looks like the screenshot below. Ideally we should inform the user they need to change their settings, and maybe provide a button which changes it, similar to the governance tab when the politeia integration is disabled.

![Screenshot from 2020-11-12 15-19-07](https://user-images.githubusercontent.com/6762864/98958714-78ad9d80-24fa-11eb-9ca9-6174e62568b4.png)

**Comment by victorgcramos** [comment]
On it!
