### ISSUE TITLE
[Privacy] Check balance before requesting passphrase

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2944]
When the mixer is activated with an unmixed balance of zero, decrediton requests the user to enter their passphrase before displaying a zero balance error. Can this error be shown without requesting the passphrase? 

Seems like if decrediton already knows the balance is zero, we are asking the user to enter the passphrase for no reason.

**Comment by amassarwi** [comment]
Good point!

**Comment by amassarwi** [comment]
Will do
