### ISSUE TITLE
Sending DCR in Transactions Tab is consistently incorrect 1.6RC3

### ISSUE THREAD

**Issue by exitus1** [decred/decrediton#2950]
![image](https://user-images.githubusercontent.com/46197055/99338317-f9013500-2851-11eb-8102-efed821917c8.png)
![image](https://user-images.githubusercontent.com/46197055/99338349-04546080-2852-11eb-8a7f-50930acebb2a.png)

See images. I input 200 DCR and it thinks I want to send 20. I've tested this a few times and found it to be oddly consistent with getting the amount I want to send incorrect.

**Comment by thi4go** [comment]
Are you running latest master? Tried to reproduce this but no success, seems to be working here.

**Comment by exitus1** [comment]
Yes, I believe so.

The same thing was happening to me in rc2. I did a short video:

https://youtu.be/OoCcGB2us8s

**Comment by bgptr** [comment]
on this
