### ISSUE TITLE
Privacy UI/UX improvements

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#2965]
Posting an updated version of the design concept for using privacy. 

Bg:
The goal for users is to create anonymity to their coins, as easily as possible. This should happen in a single view, esp. if we have a dedicated view for Privacy. If I understood correctly, to do this, we should only need a way to turn on the mixer, and a transaction to self component, to send funds to unmixed account as a bare bones solution. How these components make up the interaction flow is what to solve.

Ver 1: https://xd.adobe.com/view/58d3e580-9348-4ee6-b132-2adb97a8ac90-0d80/
Mixer is activated by the large toggle as it is now. Unmixed and Mixed Account Balances are shown for feedback and additional context to explain whats happening. Send-to-self contains a locked setting "To: Unmixed" account. Settings are tucked away in info icon/modal. Dev access to change these?

Cons from basic testing: the positioning logic of the items could be better based on some of the feedback. If the user needs to send funds to Unmixed first, this creates an odd backward movement, going from bottom right back to top left. It was noted that a toggle that requires password entry as a follow-up feels odd. The toggle gives no feedback if it can be started or not (in case unmixed has no funds).

Ver 2: https://xd.adobe.com/view/260c88d6-8b96-4cf3-abcb-cb803eaf631e-735f/
To make this more like a step by step action, and address the positioning issue, i've created to isolated components for each interaction. Both have buttons rather than having a toggle for the mixer. 

If the Unmixed account has too low funds, the button should be disabled. If the user clicks the disabled button, a snackbar warning is displayed. Along side that we can use the animated alert icon, which can pop over the right corner of the unmixed account icon. https://lottiefiles.com/20274-alert-open (color red).

If the mixer is running, we can also use a pre-existing animation of this decentralized loop for the time being: https://lottiefiles.com/20387-decentralized-loop (colors: #2970FF #70CBFF)

Please post any feedback here, also whether this could be worked into 1.6 or should be further iterated.

**Comment by exitus1** [comment]
Great work. Both mockups look good. Personally I preffered Ver 2.

I highly agree that it all needs to be in one tab.

Ideally users won't have to seek external sources to understand how to Mix their coins. I look forward to seeing this fleshed out.

**Comment by bgptr** [comment]
I'd like to work on this. I prefer Ver 2.

**Comment by jholdstock** [comment]
Yep I prefer version 2 as well. Nice job @linnutee
