### ISSUE TITLE
can't see rejected proposals

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2969]
How to reproduce:
 - go to governance page;
 - click on finished voting;
 - click on rejected without loading more proposals

Now you will see and the only way to see proposals again is leaving going back the governance page:

![image](https://user-images.githubusercontent.com/15069783/99591219-3e963d00-29cd-11eb-8f9c-ecc883a5bb0f.png)

**Comment by guilhermemntt** [comment]
On it.
