### ISSUE TITLE
(1.6 RC3) Request: Add vspd Stakepool Fee % When Purchasing Ticket

### ISSUE THREAD

**Issue by exitus1** [decred/decrediton#2971]
The Legacy VSP system displayed the fee right in the wallet: 
![image](https://user-images.githubusercontent.com/46197055/99623487-269dd800-2a24-11eb-8919-3740cb537215.png)

Currently there is no fee mentioned or shown when purchasing with vspd.

**Comment by jholdstock** [comment]
`/vspinfo` includes the fee percentage so this should be doable https://github.com/decred/vspd/blob/master/docs/api.md#get-vsp-info

Decrediton should check the fee regularly as it is liable to change.

**Comment by guilhermemntt** [comment]
On it. Well observed. I'll try to find a nice place to position the same icon, but I'm accepting suggestions too.

**Comment by exitus1** [comment]
> 
> 
> On it. Well observed. I'll try to find a nice place to position the same icon, but I'm accepting suggestions too.

I'm not sure if this is possible, but maybe have the fee % next to the VSP's name?

![image](https://user-images.githubusercontent.com/46197055/99750118-b51f6180-2ad7-11eb-9e5a-eaadb460c73c.png)

**Comment by guilhermemntt** [comment]
Yes, maybe something like a tooltip.

**Comment by jholdstock** [comment]
@guilhermemntt  My comment above can be ignored - the fee percentage is actually available from dcrwebapi on `/?c=vsp`, so there is no need to hit each VSP API directly.
