### ISSUE TITLE
Enable PI Integration loading never stops

### ISSUE THREAD

**Issue by sumiflow** [decred/decrediton#2975]
When I set up a new wallet, go to governance, and click "Enable Politeia Integration" the PI loading animation never stops spinning (waited 5 minutes) until I click on a different tab or page and then come back.  When I switch pages and come back it comes up immediately.  I'm using v.1.6.0-rc3 on Windows but I think I've seen it on earlier versions also.  I don't see any errors after the button was clicked in the console window or decrediton log.  I can repeat this by unchecking "Politeia" on the settings page, saving, going back to the governance page, and clicking "Enable Politeia Integration" again.  It's not critical since it's rare and easy to work around but also not a great impression for new users.

**Comment by bgptr** [comment]
on this
