### ISSUE TITLE
Send from unmixed accounts checkbox reset

### ISSUE THREAD

**Issue by sumiflow** [decred/decrediton#2976]
If I check the "Send from unmixed accounts" checkbox I get the warning popup about sending from unmixed accounts.  If I click "cancel" on the warning popup the checkbox should revert to unchecked but it doesn't.  It stays checked.  It does this on Windows. I haven't tested this on Linux.  If I then "uncheck" the box I get the popup warning again.

![image](https://user-images.githubusercontent.com/5420838/99726878-c1c29c00-2a7c-11eb-8a38-962317c902c9.png)

**Comment by alexlyp** [comment]
Just tried to replicate this on master and seems like it's fixed.

**Comment by sumiflow** [comment]
You're probably right.  I didn't build from source.  I downloaded the rc3 binary exe.

**Comment by alexlyp** [comment]
I'll leave this open until you can test on rc4, then we can close

**Comment by sumiflow** [comment]
This is working correctly now with the rc4 binary.
