### ISSUE TITLE
Consolidate styles

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#298]
Currently each page has a section with things like:
```
const styles = {
  body: {
    position: 'fixed',
    left: '0px',
```
to keep all the inline css.

We can probably organize and reuse these pieces a bit better.  Not sure exactly what yet, but worth keeping in mind.

**Comment by alexlyp** [comment]
So now we have 1 consolidated file (ViewStyles.js) as our main spot for various styles for views.  For now I'm going to keep reused component styles in their own file (ToggleButton, KeyBlueButton, etc)

Next step is to see where we have overlap so we can use one main reused const for body, view etc

**Comment by alexlyp** [comment]
Closing in lieu of @go1dfish's #528
