### ISSUE TITLE
Get transactions pertinent to wallet without downloading whole chain

### ISSUE THREAD

**Issue by cinjon** [decred/decrediton#2982]
Hi, I am trying to send DCR from one account to another but no longer have the entire chain on my local device. Is there a way to do this without downloading the entire chain again? The estimated ending on Decredition is ... 2 months -_-.

**Comment by jholdstock** [comment]
Hi @cinjon. You can enable [SPV mode](https://docs.decred.org/wallets/spv/) in the settings.
