### ISSUE TITLE
Warning on ticket statistics

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2989]
When going to the ticket statistics page, it is possible to see the following warning:

![image](https://user-images.githubusercontent.com/15069783/100139849-d7fe9c80-2e6e-11eb-99c5-1f1e32498cf7.png)

**Comment by amassarwi** [comment]
looking 👀

**Comment by amassarwi** [comment]
I had a look, this error is thrown when a child component sets the state of a parent component on render(see https://stackoverflow.com/a/60526905/8148239)


I actually found which component causes the error: `views/TicketsPage/StatisticsTab/StatisticsTab.jsx` this is still a class component which need to be changed to a functional component, we should then wrap the parent's state change logic in `useEffect` as suggesting the linked stackoverflow answer above.
