### ISSUE TITLE
transactions info is not being cleaned

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#2990]
How to reproduce:

 - go to transactions page
 - sucesufully construct a transaction, without sending it
 - now it will possible see the tx info on transaction details
 - go to other view and back to transactions
 
now the info will still show, even though the data was cleaned:

![image](https://user-images.githubusercontent.com/15069783/100140327-928e9f00-2e6f-11eb-82d2-c732d3f8fd0c.png)

**Comment by amassarwi** [comment]
On it
