### ISSUE TITLE
Mixer balance error doesnt clear when balance changes

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2992]
I added funds to my mixed account and the low balance error didn't disappear and the mixer button did not activate.

It only updated after I changed to a different tab and re-opened the mixer tab.

![Peek 2020-11-25 09-12](https://user-images.githubusercontent.com/6762864/100206695-9584a080-2efe-11eb-9b4c-4cfbff602bf5.gif)

**Comment by amassarwi** [comment]
on it

**Comment by victorgcramos** [comment]
This "Insufficient unmixed account balance" appears to be linked to the **Send To Unmixed Account** area, not mixing area. What do you guys think?

**Comment by jholdstock** [comment]
The error message was moved in #2991
