### ISSUE TITLE
Mixer: Sending from unmixed to unmixed

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#2993]
The "Send To Unmixed Account" account form allows sending from unmixed, to unmixed. This doesnt make much sense. I suggest  listing all accounts **apart from** unmixed in this dropdown.

![Screenshot from 2020-11-25 09-14-47](https://user-images.githubusercontent.com/6762864/100206922-e0061d00-2efe-11eb-93dd-ba53b4fabc13.png)

**Comment by bgptr** [comment]
on this
