### ISSUE TITLE
async/await instead of callback`

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#30]
Appears to be able to use the promise/async/await babel needs to have some special tweaks to get it building.

**Comment by Thoughtscript** [comment]
I believe support for async/await in Babel is now provided by : https://github.com/babel/babel-preset-env if that helps to guide others on this issue. https://medium.com/@zwacky/add-es7-async-await-support-into-your-non-bleeding-edge-build-process-ad0dded0d002 - it's now also supported naively in Node 7+.

**Comment by Thoughtscript** [comment]
natively** - damn autospellchecker
