### ISSUE TITLE
Cant buy unmixed tickets when privacy is enabled

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#3004]
I have enabled privacy, and checked "Allow sending from unmixed accounts". This allows me to spend from unmixed accounts in the on-chain transactions tab, but I cannot buy tickets from unmixed accounts. This effects both legacy and new VSP tickets.

**Comment by amassarwi** [comment]
will fix that

**Comment by alexlyp** [comment]
After looking into it and @bgptr making a diff, we've realized that it's not as simple as it seems.  Due to that complexity we don't think it's worth the effort to implement something that we don't think is the best idea.
