### ISSUE TITLE
Layout with fixed height on governance tab

### ISSUE THREAD

**Issue by karamble** [decred/decrediton#3015]
When using decrediton in a different language the length of text elements can vary. On the governance tab the top section has a fixed height which leads to a cut off navigation:
![screen_015](https://user-images.githubusercontent.com/25404928/100556758-6c686500-329c-11eb-9fc2-fd91413b826e.png)

**Comment by guilhermemntt** [comment]
On it.

**Comment by guilhermemntt** [comment]
Hey @karamble, thanks for opening this issue. I'm perceiving the same problem with some buttons and labels in other languages (mainly those not using the Latin alphabet).  So, depending on how disruptive the GUI break is, I think we should consider an alternative translation, if possible.
