### ISSUE TITLE
Improve Restore Wallet page messaging

### ISSUE THREAD

**Issue by victorgcramos** [decred/decrediton#3020]
Got some UX reports from an average user, not much familiar with the crypto universe:

<img width="871" alt="Screen Shot 2020-11-30 at 11 26 19 AM" src="https://user-images.githubusercontent.com/22639213/100622720-f1d13100-32ff-11eb-817b-d3e582e53585.png">

1. The *wallet* on  "Restore Existing **Wallet**" is different from the one on "**Wallet** name", which caused an user to ask me if this Wallet Name should be the same as the wallet you are trying to recover.

2. The same user asked me what "Watch Only", "Trezor" and "Privacy" mean.

    a. Although those terms are self-descriptive, I think we should display some tooltip telling the user if the config can be changed further, what does the config do, etc.
    b. We can tell the user that they are all disabled by default. Maybe collapse all those options into an "Advanced Config" accordion.

**Comment by jholdstock** [comment]
The "Privacy" toggle should actually be removed in #2907.

Watch only and Trezor could definitely use tooltips
