### ISSUE TITLE
Tooltip for ticket fee transactions

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#3024]
Ticket fee transactions seem to have their own icon - yellow. However they have a generic tooltip message "Transaction".

![Peek 2020-12-01 10-42](https://user-images.githubusercontent.com/6762864/100730455-fb22d200-33c1-11eb-9652-687e62f67804.gif)

Can we properly identify these as ticket fees and indicate that in the tooltip?

**Comment by amassarwi** [comment]
sure will do
