### ISSUE TITLE
[1.6-RC4] Font on the Overview Tab appears to be different.

### ISSUE THREAD

**Issue by exitus1** [decred/decrediton#3039]
I have no idea if it was intended for the font to change, but it looks a bit off on my end, especially the "Total Current Balance" number.

![image](https://user-images.githubusercontent.com/46197055/100959377-23a6eb00-34ec-11eb-843c-173b5fe84351.png)

Did anyone else notice?

**Comment by jholdstock** [comment]
This is a deliberate change. Decrediton was the only place using Inconsolata for monospace font. Design guidelines specified moving from Inconsolata to Source Code Pro a very long time ago (I think 2ish years), but Decrediton has only just caught up to that.
