### ISSUE TITLE
[1.6-RC4] Add "Send max" button in Privacy tab

### ISSUE THREAD

**Issue by darthcrypto87** [decred/decrediton#3040]
The new privacy tab is awesome!
I would wish for a "send max" button as in the regular Transaction tab. I think most of the time people will just want to mix everything and having to type it in just doesn't feels right. It feels like this button is missing.
When people only want to mix a portion they still can.

![image](https://user-images.githubusercontent.com/26526304/101007730-ccdbf880-3561-11eb-8a43-1e083b7323be.png)

**Comment by jholdstock** [comment]
Completely agree with this.

**Comment by bgptr** [comment]
on this
