### ISSUE TITLE
Slight misalignment in sidebar menu icons

### ISSUE THREAD

**Issue by guilhermemntt** [decred/decrediton#3055]
There's a slight misalignment in sidebar menu icons tending to the right.

![image](https://user-images.githubusercontent.com/39631429/101431133-166f6f00-38e5-11eb-9515-6a674487eb5f.png)

![image](https://user-images.githubusercontent.com/39631429/101431096-05bef900-38e5-11eb-9c5d-e1b3648aff59.png)

**Comment by bgptr** [comment]
on this
