### ISSUE TITLE
[1.6.0-rc4] VSP Fee not shown for custom VSP

### ISSUE THREAD

**Issue by smartwojak** [decred/decrediton#3056]
In https://github.com/decred/decrediton/pull/2985, rc4 added fee display for the selected VSP. 

However, the fee is not shown when a custom VSP added through "Type to add new VSP".

![image](https://user-images.githubusercontent.com/75653456/101437130-7f3d0280-394a-11eb-878f-c5fae18f1efe.png)

From [PurchaseTickets.jsx](https://github.com/decred/decrediton/blob/v1.6.0-rc4.1/app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseTickets.jsx#L65-L67), it looks like the fee is retrieved from the VSP listing API, so there is no `vspFee` set for custom VSP in [PurchaseForm.jsx](https://github.com/decred/decrediton/blob/v1.6.0-rc4.1/app/components/views/TicketsPage/PurchaseTab/PurchaseTickets/PurchaseForm.jsx#L68) 

Ideally, as we have already made a `vspinfo` API call to vspd on selection, it could simply use the provided `feepercentage` field to display the fee.

**Comment by bgptr** [comment]
#3071 should fix this

**Comment by smartwojak** [comment]
fixed
