### ISSUE TITLE
[1.6-rc4] going to settings from menu keeps menu selected

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#3058]
When going to settings page from a menu, the menu keeps selected as it still being shown, which is not the case

example: 

![image](https://user-images.githubusercontent.com/15069783/101484549-8eb35000-3938-11eb-8ac9-8e6f09126b72.png)

**Comment by bgptr** [comment]
on this

**Comment by amassarwi** [comment]
I would suggest we consider using pi-ui's `Tabs` component, it can be used vertically and it has the active tab animation built in, we might also then get red of the animation logic ans dep!

**Comment by bgptr** [comment]
It sounds like a good idea, @amassarwi. I'll check out the `Tabs` component, but I did a quick fix until then: #3060

**Comment by jholdstock** [comment]
> I would suggest we consider using pi-ui's `Tabs` component, it can be used vertically and it has the active tab animation built in, we might also then get red of the animation logic & dep!

This sounds like a neat idea, perhaps a new issue for 1.7 dev?

**Comment by amassarwi** [comment]
@bgptr I like your fix, I opened another issue for pi-ui Tabs migration. 

#3061

**Comment by bgptr** [comment]
@amassarwi Thank you!
