### ISSUE TITLE
[pi-ui][sidebar] Consider using Tabs component in sidebar

### ISSUE THREAD

**Issue by amassarwi** [decred/decrediton#3061]
Currently we have some logic to show caret for active tabs in sidebar, we have built `Tabs` component which has 
the animation built in and can be used horizontally and vertically, we should consider using it in sidebar.

Note: I think we should replace all tabs in tabbed pages as well but this can be done later with separate issue/task
for each page.  Ideally we shouldn't have any tabs related logic in decrediton.

**Comment by bgptr** [comment]
On this
