### ISSUE TITLE
Wrong mouse cursor on navmenu rescan icon

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#3065]
When rescanning the blockchain, the icon changes to an animated icon. On mouse hover, cursor displays a "pointer" even though it cannot be clicked.

![Screenshot from 2020-12-09 12-05-35](https://user-images.githubusercontent.com/6762864/101628145-47e85780-3a17-11eb-83bd-b7688cb802d7.png)

**Comment by bgptr** [comment]
on this
