### ISSUE TITLE
purchasing more than one ticket at a time fails

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#3076]
Tried purchasing 2 tickets at once, but it only purchased 1 ticket

**Comment by dre-tech** [comment]
The other day we were chatting on the Discord support channel about a couple of tickets that I have that somehow don't have a VSP attached to them and don't show up under ticket status. Now I'm seeing this ticket. It's worth mentioning, that my troublesome tickets were both purchased at the same time.
