### ISSUE TITLE
Unclickable menu items on seed copy/entry 

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#3079]
`About Decrediton`, `Settings` and `Logs` are displayed during the wallet creation pages - see top right in the screenshots. These were not displayed in 1.5.
`About Decrediton` is clickable, but the other two are not. I suggest these should be hidden, as they were previously.

![seed-entered](https://user-images.githubusercontent.com/6762864/102098937-a8b0cf00-3e1f-11eb-8089-b79ada883626.png)
![wallet-seed](https://user-images.githubusercontent.com/6762864/102098940-a8b0cf00-3e1f-11eb-96a2-addf1d821a6b.png)

**Comment by amassarwi** [comment]
on it
