### ISSUE TITLE
Improve vsp fee tx visability

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#3083]
Right now it is not possible to know which vsp fee tx is related to each ticket, so it is pretty hard to know if a ticket tx already got published, for example.

This needs to be improved. 

We will probably need a new grpc command for this, as right now decrediton does not get this information from dcrwallet

**Comment by dre-tech** [comment]
Seems like this is related to #3010.

**Comment by dre-tech** [comment]
Still trying to figure out the new ticket buying process.... I just bought one ticket and it created a transaction with a yellow icon in my transaction history. Immediately below is a red icon transaction. Would this likely be my VSP fee transaction? 

Ticket status in one instance of Decredition shows this immature ticket as 'paid'. My other instance of Decredition set to the same seed never listed this immature ticket in ticket status, but it does show it as a 'solo' ticket in history tickets. The red icon transaction that I presume is my VSP fee took an additional 20 minutes to get mined. Perhaps this contributes to why the second instance of Decredition thinks the ticket is solo? Is it normal for the confirmation of a VSP fee to take much longer than the ticket it relates to?

**Comment by dre-tech** [comment]
@vctt94 One of my tickets that was marked as 'solo' has voted. Is there a way to check to see if there was a VSP attached?

**Comment by vctt94** [comment]
Good to know. So probably the fee registration has worked. 

And no, right now it is not possible to know which vsp is attached to each ticket. We are working on a solution. 

Thanks for the feedback
