### ISSUE TITLE
Overview tab: Dates using different fonts

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#3085]
Recent Transactions are using normal font for dates, Staking Activity is using monospace. The alignment is different as well, Recent Transactions seem to have a large margin-right

![Screenshot from 2020-12-15 10-04-21](https://user-images.githubusercontent.com/6762864/102200605-f92a3a00-3ebc-11eb-9b8a-efb7835b5cc8.png)

**Comment by amassarwi** [comment]
on
