### ISSUE TITLE
[1.6.0-rc4] No info message is shown when Decrediton can't be closed due to activated auto ticket-buyer

### ISSUE THREAD

**Issue by darthcrypto87** [decred/decrediton#3094]
In some occastions there is a message shown why Decrediton can't be shut down.
When the auto ticket-buyer is active Decrediton can't be closed, but no info message about the reason is shown.

(I use the AppImage)

**Comment by bgptr** [comment]
#3037 fixes this. It has been merged after 1.6.0-rc4 released

**Comment by darthcrypto87** [comment]
Fixed by #3037
