### ISSUE TITLE
Quit/Close buttons does not work after GUI being open for more than a day (v1.6 RC4)

### ISSUE THREAD

**Issue by xsanchezz** [decred/decrediton#3096]
<img width="506" alt="Screen Shot 2020-12-16 at 8 38 42 PM" src="https://user-images.githubusercontent.com/4775731/102423570-b745e480-3fdf-11eb-9ced-64a70b109674.png">

I can only close the wallet via Activity Monitor

**Comment by alexlyp** [comment]
Can you check decrediton logs next time this occurs?

**Comment by xsanchezz** [comment]
> Can you check decrediton logs next time this occurs?

Where I can find the logs? Sorry, I am new here

**Comment by xsanchezz** [comment]
Found it, in Application Support folder.

I will be sending it here as soon as the issue happens again.

<img width="118" alt="Screen Shot 2020-12-17 at 1 03 50 PM" src="https://user-images.githubusercontent.com/4775731/102519037-60d0b880-4068-11eb-9bb4-621b810a524a.png">

**Comment by xsanchezz** [comment]
Hi, I have the log file, but it is roughly 60MB. How I can send it?

**Comment by xsanchezz** [comment]
I think I discovered what's going on here. While the Mixer or Auto ticket buyer are active and running, you can't close Decrediton.

After I turned off the mixer and auto ticket buyer, I was able to close the wallet.


This issue is not an issue at all, please just add a message to let the user know that he/she needs to shut down the services (auto ticket buyer and/or mixer) in order to close the wallet.
