### ISSUE TITLE
What's New in v1.6.0 is showing information for v1.5

### ISSUE THREAD

**Issue by xsanchezz** [decred/decrediton#3097]
<img width="672" alt="Screen Shot 2020-12-16 at 8 37 26 PM" src="https://user-images.githubusercontent.com/4775731/102424243-1eb06400-3fe1-11eb-889e-06491da99161.png">
<img width="688" alt="Screen Shot 2020-12-16 at 8 37 43 PM" src="https://user-images.githubusercontent.com/4775731/102424247-207a2780-3fe1-11eb-82d8-64cc648978dd.png">

**Comment by alexlyp** [comment]
Yes, we don't typically update that until we are nearing 1.6.0 final release.   It's been updated now and will be included in the upcoming release candidate.
