### ISSUE TITLE
Staking tab leads to blank screen on v1.6 RC4

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#3111]
I think this is similar to what @karamble described in https://github.com/decred/decrediton/issues/3109.
Except I hit it by going into the privacy settings and disabling all external requests.

I'd expect it to load so you could provide your own VSP not pulled via the API if desired.

![decrediton](https://user-images.githubusercontent.com/4731927/103430504-d4a7b080-4b92-11eb-98c0-1952cde2f9f7.png)

**Comment by degeri** [comment]
this has been fixed https://github.com/decred/decrediton/pull/2946
