### ISSUE TITLE
Remove politeia CSRF tokens

### ISSUE THREAD

**Issue by lukebp** [decred/decrediton#3117]
decred/politeia#1356 removed CSRF protection on public routes due to privacy issues with attaching a CSRF token to a request that casts votes.  This has been deployed to production as a patch.

The existing behavior of including CSRF tokens will not cause any errors, the tokens are now just ignored.  Decrediton can remove all code for handling politeia CSRF tokens since Decrediton only uses public routes.  It should be verified that neither cookie nor header CSRF tokens are included in requests that cast votes.

**Comment by amassarwi** [comment]
can do
