### ISSUE TITLE
loading more tickets never misses

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#3148]
It already finishede to look for live tickets but still shows `loading more tickets`

![image](https://user-images.githubusercontent.com/15069783/104601169-aaf18d80-5658-11eb-8d2f-afaf21236b65.png)

**Comment by sumiflow** [comment]
I have the same issue with rc5 on windows.  In a brand new wallet with no tickets purchased yet it shows "Loading more tickets..." and doesn't stop.  I know there aren't any tickets to show in my case but this makes it seem like it is doing something even though I don't think that it is.
