### ISSUE TITLE
Links aren't displayed as selected when sidebar is on bottom

### ISSUE THREAD

**Issue by guilhermemntt** [decred/decrediton#3186]
When sidebar is on bottom, links placed in its second row can be usually selected, but aren't displayed as selected. The tooltip still appears and sometimes they have ``cursor: default`` instead of ``cursor: pointer``.

![image](https://user-images.githubusercontent.com/39631429/105910662-04b66800-6008-11eb-8a7c-270b1cae7496.png)

**Comment by bgptr** [comment]
#3077 solves this issue

**Comment by amassarwi** [comment]
@alexlyp this can be closed, as it was fixed in #3077.
