### ISSUE TITLE
Network error in Governance tab when there are 2 wallets in Decrediton

### ISSUE THREAD

**Issue by xsanchezz** [decred/decrediton#3198]
The tab was working fine until I created a second wallet in Decrediton (Now I have an old wallet and the new wallet).

<img width="1188" alt="Screen Shot 2021-02-03 at 9 23 26 AM" src="https://user-images.githubusercontent.com/4775731/106754725-b276d780-6603-11eb-8bfa-fc515c75690d.png">

**Comment by alexlyp** [comment]
Openning another issue that will cover this issue.

**Comment by alexlyp** [comment]
I've opened another issue #3202 

Can you check your dev console (turn on Toggle Dev Tools under View above) for any errors?  Please post them on that issue.  @xsanchezz
