### ISSUE TITLE
[governance] Reports of Proposals page not loading 

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#3202]
Various users are reporting the following error: 
The governance page is not showing up and they are Shown a Network Error instead.  Some reported that they were previously able to see it, but now can't.

A user reported seeing:
 "GET https://proposals.decred.org/v1/proposals/tokeninventory net::ERR_BLOCKED_BY_CLIENT" in the dev console.

This is interesting since it's not the correct URL and that would cause it to be caught by the external request restrictions.

I looked around the code and have no idea how that URL could possibly be used instead of the proper POLITEIA_URL_MAINNET

**Comment by amassarwi** [comment]
Might be because they blocked external Pi requess with privacy features ?

**Comment by alexlyp** [comment]
They've all reported pi requests are allowed afaik.  Whenever I toggle the politeia comms off it shows the Enable Politeia page.

**Comment by alexlyp** [comment]
![tokeninventory](https://user-images.githubusercontent.com/4388501/107070402-4b972100-67b1-11eb-8f2a-8c854b635537.png)

**Comment by alexlyp** [comment]
Maybe something wacky with leftover cookies from when we had csrf still going?

**Comment by alexlyp** [comment]
i got it working now. In the same network tab at the top there's a checkbox to 'disable cache'. I checked it then went to the governance page and clicked 'retry' and then the proposals popped up

**Comment by xsanchezz** [comment]
> Can you check your dev console (turn on Toggle Dev Tools under View above) for any errors?

I don't see Toggle Dev Tools under View

> In the same network tab at the top there's a checkbox to 'disable cache'. 

Where is that network tab in Decrediton?

<img width="951" alt="Screen Shot 2021-02-05 at 8 12 55 PM" src="https://user-images.githubusercontent.com/4775731/107101713-971bf000-67ee-11eb-8e9c-602c3e640cdd.png">

**Comment by xsanchezz** [comment]
Alex,

I can confirm that deleting the files inside the Cache folder fixed the issue of Network Error in the Governance screen.
 
<img width="560" alt="Screen Shot 2021-02-07 at 9 51 08 PM" src="https://user-images.githubusercontent.com/4775731/107167362-19dbb100-698f-11eb-8bbd-67cf500bf618.png">
