### ISSUE TITLE
[launcher] Setup Incomplete Wallets are unable to be loaded

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#3203]
Steps to reproduce:

Create a new wallet and name it.
Proceed to the Seed display page, then close Decrediton.
Restart Decrediton and attempt to load the Setup Incomplete Wallet

It shows various errors underneath, but also stops any other wallet from being loaded.

I'm not sure what we should be able to recover in that situation.  But at the very least we should be able to open another wallet.

**Comment by amassarwi** [comment]
Duplicate of #2920

**Comment by alexlyp** [comment]
:+1:
