### ISSUE TITLE
Privacy UX improvement: easier mix with one click

### ISSUE THREAD

**Issue by xsanchezz** [decred/decrediton#3206]
I don't know if posting this here is the best way to submit feedback. If not, please bear with me.

Right now, to start the mix process, is required to send funds to an unmixed address. It would be more user friendly if we can just mix directly from the balance in the default account. That will create a one-click-mix in decrediton.

If there is a specific reason of why the unmixed address exist, please let me know and close this ticket.

<img width="878" alt="Screen Shot 2021-02-05 at 8 22 54 PM" src="https://user-images.githubusercontent.com/4775731/107102804-f8918e00-67f1-11eb-94bb-7cf46dadef09.png">

**Comment by alexlyp** [comment]
Yes this is all necessary since mixing requires a separate account to place unmixed funds.  This needs to be appart from the default account.

**Comment by xsanchezz** [comment]
Thanks for letting me know. I will close this issue.
