### ISSUE TITLE
Can't delete empty accounts in decrediton 

### ISSUE THREAD

**Issue by xsanchezz** [decred/decrediton#3207]
Is only possible to hide accounts, but can't delete them.

Right now I have like 3 -5 accounts with zero balance. How I we can get rid of them?

<img width="770" alt="Screen Shot 2021-02-05 at 8 34 48 PM" src="https://user-images.githubusercontent.com/4775731/107103178-0b589280-67f3-11eb-8795-01474eacbf76.png">

**Comment by alexlyp** [comment]
Yes, once an account is created there is no way to "delete" any account.  There is no mechanism to handle this in dcrwallet and we have no plans on implementing such a mechanism.

**Comment by xsanchezz** [comment]
Okay, is not an issue then. Will be closing this.
