### ISSUE TITLE
Ticket auto buyer default values enhancement

### ISSUE THREAD

**Issue by sumiflow** [decred/decrediton#3211]
May I please have these values default to whatever I set them to last time?  I often have to fill them in with the same values again whenever I close and re-open Decrediton.

![image](https://user-images.githubusercontent.com/5420838/107553187-123c2800-6b9a-11eb-864a-0ccba4de440f.png)

**Comment by guilhermemntt** [comment]
If we proceed with that train of thought, nothing precludes us from automatically starting automatic ticket purchase as soon as Decrediton loads, since the user has flagged this option the last time he used it. It'd be great to see other opinions about this.

**Comment by sumiflow** [comment]
I slightly lean towards not auto-starting the ticket buyer.  In the case where you haven't opened Decrediton for a long time it could be frustrating if it buys a ticket immediately and inadvertently locks your funds.  I can see arguments made for it both ways  though and I would be fine with either.

I definitely would definitely default the other fields though.  They're not as controversial since they wouldn't immediately do anything until you turned it on.
