### ISSUE TITLE
Staking Tab - "History Tickets" and "Tickets Status" name change

### ISSUE THREAD

**Issue by dezryth** [decred/decrediton#3218]
Currently the tab to view Ticket History is named "History Tickets", which does not sound like proper English.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/5300356/107870027-7a209600-6e5a-11eb-8b7c-142f39b8ab4c.png">

I believe it would be more appropriate to rename these tabs to "Ticket Status" and "Ticket History".

**Comment by davecgh** [comment]
Yes, those would be better.
