### ISSUE TITLE
Replace TabbedPage component with pi-ui Tabs

### ISSUE THREAD

**Issue by guilhermemntt** [decred/decrediton#3222]
We can replace our current ``layout/TabbedPage.js`` with the Tabs implementation in ``pi-ui`` dependency since this is going to promote a better integration with ``pi-ui`` and something very close already has been tested with the sidebar component.

**Comment by guilhermemntt** [comment]
On it.

**Comment by amassarwi** [comment]
Yo @guilhermemntt, how is going with this one ?
I'm refactoring the components/layout and replacing the TabbedPage with the pi-ui's makes a lot of sense at this stage.

**Comment by guilhermemntt** [comment]
No problem. You can go on and solve this issue if you want.

**Comment by amassarwi** [comment]
If you didn't start maybe it would make sense to keep this for later, and start with when the `components/layout/*` dir have been migrated.

**Comment by guilhermemntt** [comment]
Ok, it makes sense. I totally agree. Let's postpone this.
