### ISSUE TITLE
Add copy/instructions to various pages

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#323]
Look at Paymetheus to determine at least bare minimum in terms of instructions that should be shown to user

**Comment by jcvernaleo** [comment]
Help page should have some text, probably just next to the header word help (even just 'Go to these resources for more info' or something similar.)

**Comment by jcvernaleo** [comment]
Recieve could use an info page (probably just with the little use each address once warning).

**Comment by jcvernaleo** [comment]
Accounts probably could use some info although I have no idea what it should say.

**Comment by jcvernaleo** [comment]
I like the way the other pages are.  I see nothing useful to add for settings or overview.   I could imagine someone wanting an info page on History to say what the different tx types are but I'm not sure how I feel there.
