### ISSUE TITLE
Bug - Attempting to stake, get "Not enough UTXO" error

### ISSUE THREAD

**Issue by sashafklein** [decred/decrediton#3253]
I think this is a bug. I'm trying to buy a ticket to stake. I have more DCR than the ticket price, and I choose a VSP, etc. When I click "Purchase", however, I get this error:

"Not enough utxo. Need to break the input so one can be reserved for paying the fee."

I've tried restarting the app, and it doesn't fix the bug.

**Comment by amassarwi** [comment]
see https://www.reddit.com/r/decred/comments/lebx71/error_when_trying_to_purchase_tickets_with/
