### ISSUE TITLE
Staking issue following upgrade  to v1.6

### ISSUE THREAD

**Issue by purplezoo** [decred/decrediton#3255]
Hi.  I've upgraded to v1.6.  I tried to buy a ticket.  Despite having sufficient funds, I got an error message (Error: 2 Unknown: wallet.purchaseticketswithresponse:insufficientbalance: individualsplit::txauthor.newunsignedtransaction) Please could someone advise what I'm doing wrong?

**Comment by alexlyp** [comment]
https://www.reddit.com/r/decred/comments/lebx71/error_when_trying_to_purchase_tickets_with/

this will be fixed in 1.6.1 as well
