### ISSUE TITLE
[css modules] Coordination issue.

### ISSUE THREAD

**Issue by amassarwi** [decred/decrediton#3259]
This issue will be used to coordinate `.less` files migration work - original issue: #2439.

Following the list of all `.less` files existed before the migration - checked checkbox indicates that `.less` was migrated:

 - [x] AccountRow.less
 - [x] AccountPage.less
 - [x] AgendaCard.less
 - [x] AgendaOverview.less
 - [x] Balance.less
 - [ ] ConnectPage.less
 - [x] Chart.less
 - [x] CreateWalletForm.less
 - [x] Documentation.less
 - [x] ExportPage.less
 - [x] EyeFilterMenu.less
 - [x] Fonts.less
 - [x] GetStarted.less
 - [x] Governance.less
 - [x] Header.less
 - [x] Heatmap.less
 - [x] Help.less
 - [x] HistoryPage.less
 - [x] HomePage.less
 - [x] Icons.less
 - [x] Input.less
 - [ ] LN.less
 - [x] LanguageSelect.less
 - [x] Layout.less
 - [x] Loading.less
 - [x] Logs.less
 - [x] MiscComponents.less
 - [x] Modals.less
 - [x] MyTickets.less
 - [x] Paginator.less
 - [x] PurchaseTickets.less
 - [x] ReceivePage.less
 - [x] ReleaseNotes.less
 - [x] SecurityCenterMssagePage.less
 - [x] SendPage.less
 - [x] Settings.less
 - [x] SideBar.less
 - [x] SimpleLoading.less
 - [x] Snackbar.less
 - [x] StakePool.less
 - [x] Stakey.less
 - [x] TextToggle.less
 - [x] Themes.less
 - [x] Tooltip.less
 - [x] Trezor.less
 - [x] Tutorial.less
 - [x] TxDetails.less
 - [x] TxHistory.less
 - [x] main.less

**Comment by amassarwi** [comment]
Ditching `MyTickets.less`.

**Comment by bgptr** [comment]
Ditching `MiscComponents.less`
