### ISSUE TITLE
class => functional components & hooks migration coordination. 

### ISSUE THREAD

**Issue by amassarwi** [decred/decrediton#3260]
All unchecked class components in the following list weren't migrated yet from class components to a functional component
with hooks & connectors :

- [x] `components/ErrorScreen`
- [x] `components/shared/Balance`
- [x] `components/buttons/*`
- [x] `components/Header`
- [x] `components/Paginator`
- [x] `components/inputs/*`
- [x] `components/inputs/AccountSelector.js`
- [x] `test/unit/components/inputs/DcrInput.spec.js`
- [x] `components/layout/*`
- [x] `components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfo.jsx` 
- [x] `components/modals/trezor/*`
- [x] `components/views/TrezorPage/*`
- [x] `components/indicators/LoaderBarBottom.js`
- [ ] `components/views/LNPage/*` - **WIP**
- [x] `containers/App.js`
- [x] `components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_PurchaseTickets/index.js`
- [x] `components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_TicketAutoBuyer/index.j`

Original issue: #2438

**Comment by bgptr** [comment]
@amassarwi `components/inputs/SettingsInput.js` was refactored in #3176.
I'm planning to start working on `components/buttons/*`

**Comment by amassarwi** [comment]
Seeet updating the list in a bit

**Comment by amassarwi** [comment]
working on `components/ErrorScreen`.

**Comment by amassarwi** [comment]
`components/inputs/AccountSelector.js` is still a class component.

**Comment by amassarwi** [comment]
I will be migrating `container/App.js` next.

**Comment by guilhermemntt** [comment]
All ``components/modals/trezor`` components have been refactored in ``https://github.com/decred/decrediton/pull/2956`` and should be marked as **WIP**.  I can perform ``components/views/TrezorPage/`` refactoring as well.

**Comment by amassarwi** [comment]
@guilhermemntt Thanks, updated ✅

**Comment by bgptr** [comment]
working on ` components/views/TicketsPage/PurchaseTab/StakeInfo/StakeInfo.jsx`

**Comment by bgptr** [comment]
working on `components/inputs/AccountSelector.js`

**Comment by amassarwi** [comment]
@bgptr sweet, wanna also migrate `test/unit/components/inputs/DcrInput.spec.js` which seems to use a class component ?

**Comment by amassarwi** [comment]
will be working on `components/layout/*` dir.

**Comment by guilhermemntt** [comment]
I'll be glad to finish ``components/views/LNPage/*`` refactoring.

**Comment by amassarwi** [comment]
looking at `components/indicators/LoaderBarBottom.js`

**Comment by bgptr** [comment]
`app/components/inputs/LEGACY_StakePoolSelect.js` is missing from the list. I'm working on it.

**Comment by bgptr** [comment]
`components/views/TicketsPage/PurchaseTab/LEGACY_PurchasePage/LEGACY_TicketAutoBuyer/index.js` is missing from the list. On it.
