### ISSUE TITLE
v1.6.1: Peers should not be plural when there is only a single peer.

### ISSUE THREAD

**Issue by davecgh** [decred/decrediton#3264]
As can be seen in the screenshot, when Decrediton is in SPV mode and only a single peer is connected, the text at the bottom says `Connected to 1 peers` instead of `Connected to 1 peer`.

Note that this screenshot is from v1.6.0, but I confirmed it's still incorrect in v1.6.1 as well.

![image](https://user-images.githubusercontent.com/2115102/109178561-98d23700-774e-11eb-919e-535847723b6c.png)

**Comment by amassarwi** [comment]
can fix

**Comment by davecgh** [comment]
Yeah, the icon isn't there.  If I mouse over where it should be I see the tooltip that says `SPV mode`.

The console in developer tools is throwing an error on mouse over too:

```
GET file:///.../resources/app.asar/dist/style/icons/menuSpvOn.svg net::ERR_FILE_NOT_FOUND
```

**Comment by amassarwi** [comment]
hrmm actually that's known issue https://github.com/decred/decrediton/issues/3036 
but now we see it for the second time, pretty sure it has to do with windows.

**Comment by davecgh** [comment]
Yeah, I'm running it on Windows 10.
