### ISSUE TITLE
Overview Balances

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#3271]
@davecgh idea from matrix:
I think it might make sense to just show to cateogries on the overview which consist of Available (spendable) and Locked (unspendable).  The reason why the funds are locked might be because unconfirmed, immature, locked by tickets, has a time lock, etc.

So available can remain as is.  Locked would now be the combination of anything "unspendable" currently. 

Then we can add a tooltip to show the various categories when Locked is hovered.  

In this case unconfirmed can be removed.

**Comment by bgptr** [comment]
on this
