### ISSUE TITLE
Hidden tooltips for proposals filter buttons.

### ISSUE THREAD

**Issue by amassarwi** [decred/decrediton#3274]
![image](https://user-images.githubusercontent.com/10324528/109416733-b6aad080-79c8-11eb-9037-2e1d3098d8e7.png)

**Comment by bgptr** [comment]
<img width="197" alt="DeepinScreenshot_select-area_20210316143945" src="https://user-images.githubusercontent.com/52497040/111318607-80767d80-8665-11eb-99e7-7441e00971ea.png">

I think these tooltips here not so necessary. It doesn't add any plus information. They could be ditched. What do you think?

**Comment by amassarwi** [comment]
Totally agree, I guess these are for the mobile icons, but they don't add much info, especially becuase tooltips
show on mobile on click instead of on hover.
