### ISSUE TITLE
List UTXO’s view / modal update

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#3281]
You can find all updated layouts, components sheet, colors palette, basically everything in Figma https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred-piui-master?node-id=12%3A0

Basically we left the link at the same place as before. Just changed the way of displaying the list. Now it is within a modal.
![image](https://user-images.githubusercontent.com/8841018/110218379-97310d80-7eca-11eb-9d8e-3178983368d4.png)

**An implementation right now:**
![image](https://user-images.githubusercontent.com/8841018/109772801-7e490380-7c0f-11eb-964c-8126140831bf.png)

**An updated design:**
![image](https://user-images.githubusercontent.com/8841018/110218395-add76480-7eca-11eb-985f-776f40b019da.png)

**An example with scroll bar and maximum practical height for the modal, in case there's more than fits the view:**
![image](https://user-images.githubusercontent.com/8841018/110218396-b465dc00-7eca-11eb-87f4-a6c022d1a732.png)

**Comment by bgptr** [comment]
on this
