### ISSUE TITLE
 Receive view update

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#3282]
You can find all updated layouts, components sheet, colors palette, basically everything in Figma https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred-piui-master?node-id=12%3A0

Reorganized space in the section a bit. Changed the view of fields (now we use the common component from piui library) and put them in a row.
Removed the titles of Copy and View QR buttons.

**Right now in implementation:**
![image](https://user-images.githubusercontent.com/8841018/109773341-23fc7280-7c10-11eb-888a-6b44cac21c88.png)

**An updated design:**
![image](https://user-images.githubusercontent.com/8841018/110218433-d5c6c800-7eca-11eb-891e-ff0b791f2702.png)

**Comment by bgptr** [comment]
on this
