### ISSUE TITLE
 Export view update

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#3283]
You can find all updated layouts, components sheet, colors palette, basically everything in Figma https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred-piui-master?node-id=12%3A0

Changed the view of fields, now we use the common component from piui library. Also more detailed information that previously were in the dropdown is now under information icon above right up corner (so removed dropdown feature in information at all)

**In implementation right now:**
![image](https://user-images.githubusercontent.com/8841018/109773773-a38a4180-7c10-11eb-929f-f6811598f734.png)

**New design:**
![image](https://user-images.githubusercontent.com/8841018/110218466-fabb3b00-7eca-11eb-9c93-f3fad5908878.png)

The modal with detailed information appears, as soon as you clicked on this info icon.
![image](https://user-images.githubusercontent.com/8841018/110218482-0b6bb100-7ecb-11eb-8f2e-ec4ed5377adf.png)

**Comment by bgptr** [comment]
on this
