### ISSUE TITLE
Update Pi Loader on "Governance"

### ISSUE THREAD

**Issue by kyleFirethought** [decred/decrediton#3284]
![cee3902dc296f289bc4580d7c9975d6b](https://user-images.githubusercontent.com/7825971/109879298-512b3e00-7c6d-11eb-8806-896fb3856884.png)

Just flagging the need for an update in the Pi Loader animation currently present in the Governance Page.

You can find the latest version of the Pi Logo (animated) on [Lottie Files](https://lottiefiles.com/search?q=politeia&category=animations).

There is a guide on getting a clean export from Lottie for use in Decrediton here: https://github.com/decred/dcrdesign/tree/master/Contractors/kyleFirethought/242

Let me know if you need any assistance?

- Kyle

**Comment by amassarwi** [comment]
Can do
