### ISSUE TITLE
Purchase tickets view update

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#3286]
You can find all updated layouts, components sheet, colors palette, basically everything in Figma https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred-piui-master?node-id=12%3A0

**How it's already implemented:**
![image](https://user-images.githubusercontent.com/8841018/110007265-8b5b1500-7d2b-11eb-9973-b1506390218d.png)

**New design:**
![image](https://user-images.githubusercontent.com/8841018/110218501-2dfdca00-7ecb-11eb-86f2-265c9f0488ca.png)

**_Staking Overview section_**
- Changed the alignment (from left to center)
- Changed dropdown arrow orientation. Now it points down when the section is collapsed, and up (and getting blue) when expanded

-  Changed a bit the expanded view: now there are 3 items in each row

**How implemented:**
![image](https://user-images.githubusercontent.com/8841018/109838975-b70ccb00-7c57-11eb-8e66-0e0f6e091d41.png)

**New design:**
![image](https://user-images.githubusercontent.com/8841018/109839026-c4c25080-7c57-11eb-8e29-956f43b5e1f2.png)

**_Purchase Tickets section_**
- Use Legacy VSP checkbox is now inside the section and closer to VSP field, right under it
- Changed input fields to the appropriate components from piui library
- Generally tidied up the whole section
- VSP Fee was moved to the “checkout” area above “Total” and “Remaining” amount, a fee icon was changed to the title “VSP Fee”. It should always be displayed and the fee is 0% by default.
- Changed Revoke button style from сontainedButton - Blue to the outlineButton one (white with blue stroke), so now when Purchase button is active they differ from each other

**How implemented:**
![image](https://user-images.githubusercontent.com/8841018/109839149-e28fb580-7c57-11eb-8c8e-23da9dbd5d4d.png)

**New design:**
![image](https://user-images.githubusercontent.com/8841018/110218527-4cfc5c00-7ecb-11eb-8073-f7858d4149fb.png)

After selecting VSP, new checkbox “Always use this vsp” appears and if the fee for this VSP is more than 0%, the number of % has to be colored in Orange (#ED6D47), so users can easily notice it.
![image](https://user-images.githubusercontent.com/8841018/110218556-6b625780-7ecb-11eb-930c-803f1c867e53.png)

When Use Legacy VSP checkbox is checked, an additional gray area appears under the section + info icon above right up corner also appears (the same as it is implemented right now) 
![image](https://user-images.githubusercontent.com/8841018/110218579-88972600-7ecb-11eb-80b9-98b458a04a74.png)

**_Automatic Ticket Purchases section_**
- Now it has only a toggle button and the Settings icon on the right. All those fields as VSP, From, Balance can be reached when we click on this Settings icon.
When we click on it, a modal with these fields appears.
- If you click on the toggle button to turn automatic purchase on without clicking on the Settings icon before, the modal (that I mentioned above) appears, because this automatic purchase can’t be turned on without information from those fields.

**How implemented:**
![image](https://user-images.githubusercontent.com/8841018/109839591-4d40f100-7c58-11eb-9cdc-7995ede72c0f.png)

**New design:**
![image](https://user-images.githubusercontent.com/8841018/109839634-5c27a380-7c58-11eb-8804-6e6c8353dab7.png)

**The Settings modal**
![image](https://user-images.githubusercontent.com/8841018/109839686-6a75bf80-7c58-11eb-949d-9aebd5422d70.png)

**Comment by bgptr** [comment]
on this
