### ISSUE TITLE
Governance-Proposals update

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#3287]
You can find all updated layouts, components sheet, colors palette, basically everything in Figma https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred-piui-master?node-id=12%3A0

**How it's implemented:**
![image](https://user-images.githubusercontent.com/8841018/110609390-38a3b200-819e-11eb-9956-a43682cdf627.png)

**New design:**
![image](https://user-images.githubusercontent.com/8841018/110609460-48bb9180-819e-11eb-9a2e-c29f21428a8a.png)

-Changed primary tab (Proposals / Consensus Changes) to the component from the component library.

_**Description section**_
- Changed the color of description text, now it’s our main dark blue one instead of dark gray and stretched it to full width.
- The link “proposal.decred.org” is now our accent blue color (`#2970FF`) 
- Changed the style of “Create a Proposal” button from “smallButton - Gray” to “smallButton - Blue” and moved it under the description.
- Changed secondary tabs design (In discussion, Voting, etc.) to the one from components library (active line color from Gray7 (`#3D5873`) to Green2(`#2ED8A3`)
- Changed "Refresh Proposals" button design and positioning.
An updated view (hover effect):
![image](https://user-images.githubusercontent.com/8841018/110609859-b5369080-819e-11eb-94b4-44f03f5fcb46.png)

_**In Discussion cards**_

**Implemented:**
![image](https://user-images.githubusercontent.com/8841018/110009124-9fa01180-7d2d-11eb-8994-101234da1b66.png)

**New design:**
![image](https://user-images.githubusercontent.com/8841018/110009774-8481d180-7d2e-11eb-9468-9e8e11c02648.png)

- Added “Filter by name” field and a sorting option to the right up corner.
- Changed card styles to the ones similar to Politeia.
- On the middle card (in the designs) you can see how a card looks like when the mouse is over it ( gray rectangle with an arrow gets darker (from Gray3 to Gray4), previously dark blue arrow gets white and a shadow appears).When you click on a card, new page with its full proposal text will be opened.

_**Voting cards**_
- Same here, similar to Politeia card design.

**New design:**
![image](https://user-images.githubusercontent.com/8841018/110009291-de35cc00-7d2d-11eb-8f2c-4bae994b84ba.png)

_**Finished Voting cards**_

**Implemented:**
![image](https://user-images.githubusercontent.com/8841018/110009359-f1e13280-7d2d-11eb-89e0-65dc3a588ebc.png)

**New design:**
![image](https://user-images.githubusercontent.com/8841018/110009382-fd345e00-7d2d-11eb-9ae2-15f85d0635cf.png)

- For Finished Voting cards there is one more filtering option next to sorting one and filter by name.
- And also as voting for these proposals is finished, there are final results (yes/no), so we added a thin stroke to the left side of each card showing green or red color according to the voting result.

_**Abandoned cards**_
Same.

**Implemented:**
![image](https://user-images.githubusercontent.com/8841018/110010477-65d00a80-7d2f-11eb-8feb-6ba2eab80a95.png)

**New design:**
![image](https://user-images.githubusercontent.com/8841018/110010510-6c5e8200-7d2f-11eb-8094-0b15f7a42f76.png)

**Comment by amassarwi** [comment]
I would like to implement these nice specs!
