### ISSUE TITLE
Governance Proposals Cards update

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#3288]
You can find all updated layouts, components sheet, colors palette, basically everything in Figma https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred-piui-master?node-id=12%3A0

There are 2 types of a proposal description card: when we can vote or we can’t.

When we can vote: _**Voting tab**_.

The structure: 3 sections
1st -  a card design repeats, but the arrow that has been on the right were moved to the left and it means “Go back to the list of proposals”.
2nd - voting section. When you click on a preferable radio button, a sign “Voted” and a checkmark appears. Previously you had to vote manually by clicking on a Vote button, but now your vote can be accepted right after clicking on the right radio button. After clicking on it "Voted" text and a checkmark displays for a few seconds. Same for Governance Changes cards.
3rd - proposal description.
And “See Proposal Comments on Politeia” button.

**How it's implemented:(it's "finished voting", but the concept is the same)**
![image](https://user-images.githubusercontent.com/8841018/110011098-1c33ef80-7d30-11eb-9ca2-4e85f196a97b.png)

**New designs:**
![image](https://user-images.githubusercontent.com/8841018/110011123-21913a00-7d30-11eb-8220-ecba1eb134ba.png)

**Voted**
![image](https://user-images.githubusercontent.com/8841018/110011159-2b1aa200-7d30-11eb-84cb-b00be9383633.png)

You can click on the name of a proposal and be redirected to it on the Politeia website.
![image](https://user-images.githubusercontent.com/8841018/110012046-273b4f80-7d31-11eb-8874-343cb814f217.png)

When we can’t vote: **_In Discussion, Finished voting, Abandoned_** tabs.

The structure is the same as for Voting tab, but there is no voting section.
To go back to the list of proposals you have to click on the arrow within the 1st section.

**Implemented:**
![image](https://user-images.githubusercontent.com/8841018/110011578-a8dead80-7d30-11eb-819e-439be14bdb7e.png)

**New designs:**
![image](https://user-images.githubusercontent.com/8841018/110011792-e0e5f080-7d30-11eb-8d1d-768ff53eb4b1.png)

**Comment by amassarwi** [comment]
On this as well
