### ISSUE TITLE
Governance-Consensus Changes update

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#3289]
You can find all updated layouts, components sheet, colors palette, basically everything in Figma https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred-piui-master?node-id=12%3A0

**How it's implemented:**
![image](https://user-images.githubusercontent.com/8841018/110113468-34ede500-7dc4-11eb-9f08-8db349ff69d5.png)

**New design:**
![image](https://user-images.githubusercontent.com/8841018/110113500-40d9a700-7dc4-11eb-8bcd-a841c827cf7a.png)

_**Description section**_
The same changes here as for Proposals tab:
- Changed the color of the description text (now it’s our main dark blue one instead of dark gray) and stretched it to full width.
- Adde one more sentence with the link to “proposal.decred.org”.
- Changed the style of “Voting Dashboard” button from “smallButton - Gray” to “smallButton - Blue”, changed the text inside to “Go to Voting Dashboard”, moved it under the description and removed the Info icon.

_**Cards**_
- Added “Filter by name” field and a sorting option to the right up corner.
- The cards are now stretched to full width and look similar to Politeia ones. 
- Previously when you clicked on a card, full card description was opened on the same page, but now we use the same concept as for Proposals cards within Proposals tab and open the selected card as a new page. 
- On this new page we don’t show the gray Consensus Changes description section, but only the sections belonging to the selected card. Generally this page use totally the same concept (same visual effects and logic of actions) as the one with a card from the Voting tab (#3288 ).
- To go back to the list of cards you have to click on the arrow within the 1st section (also the same as in proposal cards).

**How it's implemented:**
![image](https://user-images.githubusercontent.com/8841018/110113701-86966f80-7dc4-11eb-92fb-f319bcae7b4d.png)

**New design:**
![image](https://user-images.githubusercontent.com/8841018/110113728-8eeeaa80-7dc4-11eb-994f-e3524157593e.png)

**Comment by amassarwi** [comment]
will do this one as well
