### ISSUE TITLE
Tokens showing as unconfirmed in 1.6.1

### ISSUE THREAD

**Issue by purplezoo** [decred/decrediton#3300]
I’ve just upgraded to 1.6.1. 

On the overview tab it’s showing a number of Decred as unconfirmed:

xx Available
Yy locked
Zz unconfirmed

A rescan doesn’t seem to do anything, and the unconfirmed tokens aren’t available to stake.

How do I resolve / reconcile them so I can stake?
Many thanks

**Comment by alexlyp** [comment]
Unconfirmed transactions are pending fee transactions that will be broadcast by the VSP 6 blocks after ticket purchase.  If they have been around for more than 6 blocks, click on the transactions to see if dcrdata has any information about them, if not then you can abandon them which will remove the funds from unconfirmed.
