### ISSUE TITLE
Incorrect balance when recovering wallet from seed

### ISSUE THREAD

**Issue by xsanchezz** [decred/decrediton#3302]
I decided to download Decrediton in the Windows PC and restored my existing wallet, immediately saw that the balance is lower than my wallet in my Macbook. Now I am wondering if I delete the wallet from my Macbook and restore it produce the same issue.

After investigating and looking for why the different balances, here is what I found.

**Note: Rescanning the entire wallet balance does not solve the incorrect balance in the Windows wallet.**

1) Overview tab -> Available balance

Problem: Available balance is different in the Mixed accounts. There is more balance in the Macbook wallet (mixed account) than in the recovered Windows wallet (mixed account). 

Solution: I went to my Macbook wallet and resend all the amount in the mixed account to the unmixed account. Now the Unmixed balance in both wallets (Windows and Mac) are equal. _**Total balance of coins went up in Windows wallet, but still lower total balance than in my Mac wallet.**_

2) Overview tab -> Locked balance

**Problem: Amount of locked balance is lower in my Windows wallet compared to my Mac wallet.**
    

3) Staking tab --> Purchase Tickets

Total live tickets are correct in both wallets.

4) Staking tab --> Ticket Status

In Windows PC, there are less live tickets visible in Ticket Status than in the Macbook wallet.

Summary: 

Looks like there is an issue recognizing all the locked balance from mixed account (tickets and coins) when recovering the wallet from seed.

**Comment by xsanchezz** [comment]
Total Balance does not match. 

Because the locked balance is lower when I recovered the wallet in the Windows PC. In the Macbook the locked balance is higher.

**Comment by alexlyp** [comment]
On the recovered wallet, go to settings and change Gap Limit to 100 and then restart and rescan.

**Comment by alexlyp** [comment]
did you rescan as well?

**Comment by xsanchezz** [comment]
Yes, I rescanned the entire wallet.

**Comment by xsanchezz** [comment]
Hi Alex, problem solved!

Using a Gap with value 1000 fixed the total balance and locked ticket balance.
 
![Capture](https://user-images.githubusercontent.com/4775731/110536519-f162e600-80f7-11eb-83ed-02896975f36b.PNG)

**Comment by xsanchezz** [comment]
Changed Gap back to 20 as specified. Thank you!
