### ISSUE TITLE
Warning on wallet startup

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#3304]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.   react-dom.development.js:89 
Right above that warning is another that talks about the use of deprecated componentWillReceiveProps in Bar, BarChart so maybe that's where it's coming from.

**Comment by amassarwi** [comment]
On it
