### ISSUE TITLE
[dex integration] Define strict layout breakpoints.

### ISSUE THREAD

**Issue by amassarwi** [decred/decrediton#3309]
As part of integrating dcrdex into decrediton we will need to match both gui's layout breakpoints.

Currently on the dex side we are using bootstrap's famous breakpoints - as mentioned on https://github.com/decred/dcrdex/issues/997#issuecomment-796681860.
I found out that we use way too many layout breakpoints which might it make harder to integrate dex's gui in decrediton:
 - 1919
 -  1680<x<1919
 -  1440<x<1679
 -  1679
 -  1539
 -  1180
 -  1179
 -  1140
 -  1106
 -  978
 -  955
 -  916
 -  890
 -  800
 -  768
 -  765
 -  746
 -  710
 -  676
 -  670
 -  600
 -  588
 -  541
 -  540
 -  511
 -  500
 -  430
 -  420 :)
 -  409
 -  375
 -  299

Many of these are used 1-2 times and very close to other breakpoints so we have to improve these and define stricter set of breakpoints and ensure we use the same values all over the place.

**Comment by bgptr** [comment]
on this

**Comment by amassarwi** [comment]
it would be great, if we follow pi-ui & pigui breakpoints here, as we use it as our ui components lib.
