### ISSUE TITLE
Some minor problems - issues (versions 1.6.0 and mostly 1.6.1)

### ISSUE THREAD

**Issue by blockchain-zero** [decred/decrediton#3310]
- [Little minor issue] On Decrediton v1.6.0 I’ve had chosen Dark Tonality but when I upgraded to v1.6.1, Decrediton opened with Dark tonality but the Tonality Option value was blank.

- [Possible Issue] While manually buying tickets if I change tab and then go back to staking tab sometimes the values given on Purchase Tickets are resetting.

- [Issue] While Automatic Ticket Purchases is running if I change tab and then go back to staking tab the value given before on “Balance to Maintain” goes blank. I hope that doesn't mean that it changes to 0 while Automatic Ticket Purchases is still running. I think it would be better and less confusing if that value is persistent at least until someone stops the Automatic Ticket Purchases.

- [Minor issue] Sometimes paid tickets on Staking -> Ticket History and ticket view in Overview tab are mistakenly showed as solo although they are paid. This is fixed if I open Staking -> Ticket Status and then go back to Ticket History or Overview.

- [Minor issue] In Governance -> Consensus Changes when I set a different value than the default abstain in a consensus change Preference (currently treasury) if I then change tab and go back to Governance -> Consensus the preference given before is resetting back to the default abstain. I thought that was a problem but after I closed and re-opened Decrediton and wallet and go to Governance -> Consensus the preference given was kept as the given one (different than abstain).

- [Possible minor issue] When I hover mouse on a transaction icon of a transaction made to buy a ticket a pop-up message appears that says “Mix”. I think this is confusing and it should better pop-up something like ticket fee or mixed ticket purchase instead.

OS: Windows 10 x64

**Comment by alexlyp** [comment]
Otherwise split up each request/issue that you have into individual issues.  And before opening anything further make sure there are no existing issues that already cover that topic.

**Comment by blockchain-zero** [comment]
I've removed questions, requests and some mixer problems I've had. I've only left some minor possible problems I've come across.
