### ISSUE TITLE
In Governance I get error "Something went wrong, please reload"

### ISSUE THREAD

**Issue by redmac68** [decred/decrediton#3333]
In the Governance tab of Decrediton 1.6.1, I am getting this message:

![image](https://user-images.githubusercontent.com/48153702/112220445-2d309c00-8c1e-11eb-88a9-b2b62d6d8441.png)

when I reload, nothing changes - the issue remains.

This seems to be the case when I open proposals after a certain date. Old proposals seem to be OK. I have tried restarting and re-scanning, but no change.

**Comment by alexlyp** [comment]
https://github.com/decred/decrediton/issues/3202

**Comment by redmac68** [comment]
Thanks
