### ISSUE TITLE
[bug] specific special characters as wallet names cause decrediton errors

### ISSUE THREAD

**Issue by degeri** [decred/decrediton#3359]
Naming a wallet 

`#something` or `$something` seems to cause decrediton to bug out and refuse to load any wallets. 

Also odd that it creates two wallets when `#` is used.
```
\#test
#test
```

![image](https://user-images.githubusercontent.com/41839293/113499044-f22e4280-9512-11eb-9a08-bfe5a0aedb0d.png)

Need to review the usage of special chars in wallet names.

**Comment by JoeGruffins** [comment]
I would like to investigate this.
