### ISSUE TITLE
[staking] Blur on screen when purchasing ticket

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#3368]
When purchasing a ticket, the view gets bluered, while showing the modal, but after typing the passphrase and submiting, the modal gets dismissed, but the bluered keeps showing:

![image](https://user-images.githubusercontent.com/15069783/114077475-3bb5bf00-987e-11eb-974b-363edac58593.png)

**Comment by amassarwi** [comment]
Noticed that as well, it goes away after 1-2 seconds.
Seems to be related to some sync operation happening in the background.

**Comment by bgptr** [comment]
on this
