### ISSUE TITLE
Error refreshing stakepool data from https://dcr.stakepool.net: Error: Network Error

### ISSUE THREAD

**Issue by odrano** [decred/decrediton#3372]
When I open Decrediton (v.1.6.2, MacOS 11.2.3), I'm getting this error:
Error refreshing stakepool data from https://dcr.stakepool.net: Error: Network Error

<img width="1205" alt="Screenshot at Apr 09 09-34-36" src="https://user-images.githubusercontent.com/82175486/114139015-2476e000-9917-11eb-8b09-9ec984089737.png">

How do I fix this issue?

**Comment by matheusd** [comment]
dcr.stakepool.net is offline, so if you had it configured as a VSP, decrediton will attempt to connect to it and won't be able to (thus the error).

It's safe to ignore this error, but you shouldn't purchase any tickets from this VSP (if you were previously doing so).

**Comment by bgdnr** [comment]
I have purchased tickets from dcr.stakepool.net in the pass, however now I have not active tickets from there.
The error keeps appearing when opening Decrediton even if it's not configured as a VSP; it doesn't show up in the VSP dropdown, should I look somewhere else?.

**Comment by matheusd** [comment]
It's going to be configured in one of decrediton's config files. Either `~/.config/decrediton/config.json` or `~/.config/decrediton/wallets/mainnet/[wallet-name]/config.json`.

Another thing you can try is switch to legacy mode in the staking tab, then click on the little gear icon on the right side (to expand the config options), then on the icon on the right side of the VSP name. You'll see your list of configured VSPs and you can remove ones you're not using anymore (and for which you don't have any live tickets).
