### ISSUE TITLE
Spelling error in Decrediton GUI

### ISSUE THREAD

**Issue by TheDoctor503** [decred/decrediton#3382]
On the 'staking' page, then under the 'purchase tickets' tab, under the 'Staking Overview' section, the third column reads 'Last Ticked Voted'

This should read 'Last Ticket Voted'.

**Comment by bgptr** [comment]
@TheDoctor503 Thanks for the report. The typo was fixed in #3277.

**Comment by amassarwi** [comment]
@alexlyp this one can be closed
