### ISSUE TITLE
Purchase Tickets info panel does not update after ticket purchase

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#3384]
After purchasing a ticket, it seems the ticket purchase info (in the purchase tickets page) does not update to account for the new maximum number of possible purchases.

In the screenshot below, I've just purchased some tickets and thus my balance has lowered but the "Amount" field hasn't updated to show the warning that I can't purchase this new number of tickets and the "Purchase" button is still enabled (notice how my balance is 354 DCR while 5 tickets would cost 438 DCR).

Also, the "DCR" label for the "Total" field is spilling over into the "Remaining" field.

![image](https://user-images.githubusercontent.com/1752493/114552782-5485f200-9c3b-11eb-9f72-0c89ecd0eb05.png)

**Comment by bgptr** [comment]
on this
