### ISSUE TITLE
Cast vote errors not displayed

### ISSUE THREAD

**Issue by lukebp** [decred/decrediton#3385]
If an error occurs while attempting to cast an individual proposal vote the error will be returned in the `CastVoteReply`.  The http response code will still be 200.  Decrediton does not currently display the individual `CastVoteReply` errors, which gives the appearance of votes being cast successfully even if they failed.  The `CastVoteReply` errors sould be displayed to the user.

```
// CastVoteReply contains the receipt for the cast vote.
type CastVoteReply struct {
	Ticket  string `json:"ticket"`  // Ticket ID
	Receipt string `json:"receipt"` // Server signature of client signature

	// The follwing fields will only be present if an error occurred
	// while attempting to cast the vote.
	ErrorCode    VoteErrorT `json:"errorcode,omitempty"`
	ErrorContext string     `json:"errorcontext,omitempty"`
}
```

**Comment by victorgcramos** [comment]
On it!
