### ISSUE TITLE
Migrate to new politeia API

### ISSUE THREAD

**Issue by lukebp** [decred/decrediton#3391]
The following politeiawww `www/v1` routes are currently used by decrediton:
- RouteTokenInventory
- RouteBatchProposals
- RouteBatchVoteSummary
- RouteProposalDetails
- RouteVoteResults
- RouteCastVotes

These endpoints have been deprecated in the recent politeia [release](https://github.com/decred/politeia/releases/tag/v1.0.0).

Listed below are the routes that should be used instead.  dcrdata currently pulls the politeia git repos manually in order to build the vote graphs.  This is not required anymore.  All data that dcrdata needs should be available through the politeia API.  

The release also includes a politeiawww client to make interacting with the API easier.
[politeiawww client](https://github.com/decred/politeia/blob/master/politeiawww/client/client.go#L164)

The new API uses generic record routes.  A record is application agnostic.  It can be a proposal, a cms invoice, a cms DCC, or any other type of record.  
[Record structure](https://github.com/decred/politeia/blob/master/politeiawww/api/records/v1/v1.go#L219-L230)

**RouteTokenInventory**

Replaced by the record inventory route.

[req/reply payloads](https://github.com/decred/politeia/blob/master/politeiawww/api/records/v1/v1.go#L398-L427)
[client method](https://github.com/decred/politeia/blob/master/politeiawww/client/records.go#L131)
[pictl reference command](https://github.com/decred/politeia/blob/master/politeiawww/cmd/pictl/cmdproposalinv.go)

**RouteBatchProposals**

Replaced by the records route.

[req/reply payloads](https://github.com/decred/politeia/blob/master/politeiawww/api/records/v1/v1.go#L367-L396)
[client method](https://github.com/decred/politeia/blob/master/politeiawww/client/records.go#L114)
[pictl reference command](https://github.com/decred/politeia/blob/master/politeiawww/cmd/pictl/cmdproposals.go)

**RouteBatchVoteSummary**

Replaced by the ticket vote summaries route.

[req/reply payloads](https://github.com/decred/politeia/blob/master/politeiawww/api/ticketvote/v1/v1.go#L515-L534)
[client method](https://github.com/decred/politeia/blob/master/politeiawww/client/ticketvote.go#L126)
[pictl reference cmd](https://github.com/decred/politeia/blob/master/politeiawww/cmd/pictl/cmdvotesummaries.go)

**RouteProposalDetails**

Replaced by the record details route. 

[req/reply payloads](https://github.com/decred/politeia/blob/master/politeiawww/api/records/v1/v1.go#L306-L316)
[client method](https://github.com/decred/politeia/blob/master/politeiawww/client/records.go#L80)
[pictl reference cmd](https://github.com/decred/politeia/blob/master/politeiawww/cmd/pictl/cmdproposaldetails.go)

Here's a function that converts a record to a proposal from the legacy `www/v1` API.  This shows how proposal data is formatted in the generic record structure.
https://github.com/decred/politeia/blob/master/politeiawww/proposals.go#L863

**RouteVoteResults**

Replaced by the ticket vote results route.

[req/reply payloads](https://github.com/decred/politeia/blob/master/politeiawww/api/ticketvote/v1/v1.go#L453-L476)
[client method](https://github.com/decred/politeia/blob/master/politeiawww/client/ticketvote.go#L109)
[pictl reference cmd](https://github.com/decred/politeia/blob/master/politeiawww/cmd/pictl/cmdvoteresults.go)

**RouteCastVotes**

Replaced by the ticket vote cast ballot route.

[req/reply payloads](https://github.com/decred/politeia/blob/master/politeiawww/api/ticketvote/v1/v1.go#L400-L409)
[client method](https://github.com/decred/politeia/blob/master/politeiawww/client/ticketvote.go#L75)
[pictl reference cmd](https://github.com/decred/politeia/blob/master/politeiawww/cmd/pictl/cmdcastballot.go)

Feel free to ping me if you have any questions.

**Comment by victorgcramos** [comment]
On this!

**Comment by victorgcramos** [comment]
holding this while working on updating https://github.com/decred/politeia/pull/1309. Meanwhile, anyone may feel free to pick this issue up!

**Comment by amassarwi** [comment]
can do
