### ISSUE TITLE
[minor-ui] ticket css row breaks when ticket is processing a vote

### ISSUE THREAD

**Issue by thi4go** [decred/decrediton#3392]
This is pretty minor. Had my wallet opened and a ticket voted, and the css collapsed a bit while no date information was being displayed.

![image](https://user-images.githubusercontent.com/2729122/115449252-fa63ce80-a1f0-11eb-8d9d-cfc7261efaf3.png)

**Comment by alexlyp** [comment]
Believe this is fixed.
