### ISSUE TITLE
tooltip to send to account is wrong

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#3401]
![image](https://user-images.githubusercontent.com/15069783/115611517-914b8c00-a2c0-11eb-9091-870de7646c5f.png)

It should be account as we are not sending to a different wallet

**Comment by amassarwi** [comment]
On it

**Comment by amassarwi** [comment]
hrmmm looks like it's correct when sending to another wallet:
![Screenshot 2021-04-21 at 23 13 12](https://user-images.githubusercontent.com/10324528/115615100-2e291c00-a2f7-11eb-915c-e3a7388d9ae7.png)

if you click on the icon on the first screenshot you get `x` cancel icon to got back to send funds to another wallet:
![image](https://user-images.githubusercontent.com/10324528/115615204-57e24300-a2f7-11eb-9af0-c5cd38493263.png)

**Comment by vctt94** [comment]
Oh I see. mb then
