### ISSUE TITLE
Some bugs in 1.6.2 release

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#3403]
Posting a list of bugs that I noticed during testing the 1.6.2 release:

1. Buttons alignment is a bit off in the launcher view. We decided to use the right-alignment in the wallet, so let's change it here as well. Also, please, swap the buttons, it should be Cancel-Continue if reading from left to right.
![image](https://user-images.githubusercontent.com/8841018/115709511-fadba100-a379-11eb-8d8b-dd05fc9ba15c.png)
![image](https://user-images.githubusercontent.com/8841018/115722565-cb339580-a387-11eb-92d5-04934dfe1781.png)

2. Arrow within dropdowns has to be turned up when clicked
![image](https://user-images.githubusercontent.com/8841018/115709983-83f2d800-a37a-11eb-88c8-a81ed63c23ff.png)
![image](https://user-images.githubusercontent.com/8841018/115710239-cc11fa80-a37a-11eb-81a9-2688bcc17fd4.png)

3. Same issue with buttons alignment(move and swap):
![image](https://user-images.githubusercontent.com/8841018/115710423-024f7a00-a37b-11eb-8b06-d3690299d97c.png)

4. Swap the buttons (for all pop ups that have buttons):
![image](https://user-images.githubusercontent.com/8841018/115719088-6fb3d880-a384-11eb-997a-2d2fa3833e95.png)
![image](https://user-images.githubusercontent.com/8841018/115719111-74788c80-a384-11eb-96f1-be10ed61b4df.png)
![image](https://user-images.githubusercontent.com/8841018/115719253-983bd280-a384-11eb-8481-8b6b797f3598.png)
![image](https://user-images.githubusercontent.com/8841018/115719400-b9042800-a384-11eb-8a9a-d1789d78cd3c.png)
![image](https://user-images.githubusercontent.com/8841018/115719484-ccaf8e80-a384-11eb-9a24-82d2b94007ff.png)

5. Add a spacing here:
![image](https://user-images.githubusercontent.com/8841018/115719698-05e7fe80-a385-11eb-8844-37a3ccd59bda.png)

6. Move the button to the right:
![image](https://user-images.githubusercontent.com/8841018/115719806-1d26ec00-a385-11eb-9648-ec92f88b3c1d.png)

Also @linnutee you mentioned something about icons and gifs on loader. I didn't notice anything weird, so could you explain here? Thanks.

**Comment by bgptr** [comment]
on this

**Comment by xaur** [comment]
Thanks for testing!
