### ISSUE TITLE
ticket buyer config should populate its info

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#3410]
There is a config button on the right side of the buyer which shows a modal for inputing the information:

![image](https://user-images.githubusercontent.com/15069783/115881713-69743980-a422-11eb-82a3-f2a4f69a9d95.png)

![image](https://user-images.githubusercontent.com/15069783/115881992-b1935c00-a422-11eb-87ab-74ff488157d9.png)

This same modal is shown when turning on the autobuyer, but with the data not populated so it needs to be filled again.

**Comment by bgptr** [comment]
on this
