### ISSUE TITLE
[transactions] Tooltip showing mixer is running on send is malformed

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#3417]
When the mixer is running we don't allow users to send transactions.  A tooltip is shown when the button is disabled due to this situation.  Currently the tooltip is malformed (tall and skinny) making the information hard to read.

**Comment by alexlyp** [comment]
Same malformed tooltip is seen on the Purchase ticket page when hovering the Purchase button.  Also looks like the font color for the Dark mode is incorrect for the Send tooltip

**Comment by bgptr** [comment]
on this
