### ISSUE TITLE
Replace `react-paginator` with our own component.

### ISSUE THREAD

**Issue by amass01** [decred/decrediton#3450]
The tickets QR code export modal uses `react-paginator` instead of using our own Paginator.
We should create our own and it might make sense to add one to `pi-ui` and use it in decrediton and in all
other react apps if needed.

**Comment by amass01** [comment]
hey @bgptr kudos on your work lately on `decrediton` 🥇 
i would suggest we add this component to `pi-ui` to to able 
to use it cross out react apps

**Comment by bgptr** [comment]
Thanks 🙂. Yeah, I planned to add it to `pi-ui`

**Comment by amass01** [comment]
awesome, thank you
