### ISSUE TITLE
[dex] parsing bitcoin.conf should support rpcconnect parameter for remote nodes

### ISSUE THREAD

**Issue by karamble** [decred/decrediton#3462]
Decrediton is ignoring the rpcconnect=IPADDRESS parameter and only reads the rpcport=

A user that has configured his bitcoin.conf to connect his rpc requests to a remote node will not be able to issue rpc commands to a remote IP / bitcoin node because rpc commands will only be issued to 127.0.0.1 hardcoded.
![Auswahl_025](https://user-images.githubusercontent.com/25404928/118044899-86dc5980-b377-11eb-89bc-90f3e483141e.png)

rpcbind parameter is for binding the server=1 listener
rpcconnect parameter is used by bitcoin-cli to issue calls to the remote rpc-server

**Comment by alexlyp** [comment]
Decrediton is no longer dealing with any bitcoin configs so closing this issue.
