### ISSUE TITLE
windows package: bitcoin directory uses "Roaming"

### ISSUE THREAD

**Issue by chappjc** [decred/decrediton#3464]
https://github.com/decred/decrediton/blob/703fd98402f7f4f57cbaa9c3c665adb320385cf2/app/main_dev/paths.js#L291

On Windows, Bitcoin Core uses the "Roaming" option, not "Local". See https://github.com/decred/decred-release/blob/fbc37974ead611113ee704bb68259f2bedfcdb56/cmd/dcrinstall/bitcoin.go#L341

**Comment by alexlyp** [comment]
Resolved
