### ISSUE TITLE
Unable to `yarn` on clean system with `binding.gyp not found` (node `v16.2.0`).

### ISSUE THREAD

**Issue by JoeGruffins** [decred/decrediton#3478]
On a completely new installation, these commands end in error.

<details closed>
<summary>yarn</summary>

```
...
make: *** [binding.target.mk:129: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/joe/.cache/yarn/v6/.tmp/93e6f4a8a994a2e2f13ca2d8029dfde9.47c72cef09fd55af183f2e134f5277f472ee28b5.prepare/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/joe/.cache/yarn/v6/.tmp/93e6f4a8a994a2e2f13ca2d8029dfde9.47c72cef09fd55af183f2e134f5277f472ee28b5.prepare/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.12.6-arch1-1
gyp ERR! command "/usr/bin/node" "/home/joe/.cache/yarn/v6/.tmp/93e6f4a8a994a2e2f13ca2d8029dfde9.47c72cef09fd55af183f2e134f5277f472ee28b5.prepare/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/joe/.cache/yarn/v6/.tmp/93e6f4a8a994a2e2f13ca2d8029dfde9.47c72cef09fd55af183f2e134f5277f472ee28b5.prepare/node_modules/node-sass
gyp ERR! node -v v16.2.0
```
</details>

<details closed>
<summary>"/usr/bin/node" "/home/joe/.cache/yarn/v6/.tmp/93e6f4a8a994a2e2f13ca2d8029dfde9.47c72cef09fd55af183f2e134f5277f472ee28b5.prepare/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="</summary>

```
...
gyp: binding.gyp not found (cwd: /home/joe/git/decrediton) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/joe/.cache/yarn/v6/.tmp/93e6f4a8a994a2e2f13ca2d8029dfde9.47c72cef09fd55af183f2e134f5277f472ee28b5.prepare/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.12.6-arch1-1
gyp ERR! command "/usr/bin/node" "/home/joe/.cache/yarn/v6/.tmp/93e6f4a8a994a2e2f13ca2d8029dfde9.47c72cef09fd55af183f2e134f5277f472ee28b5.prepare/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/joe/git/decrediton
gyp ERR! node -v v16.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```
</details>

Copying the contents of `.cache/yarn` from an older installation solves the problem, but obviously not everyone has those files.

**Comment by JoeGruffins** [comment]
Works on node version 14.16.0. Attempting to make that the recommended node version with the linked pr. At some point this issue may solve itself, but for now, for me, I am unable to run `yarn install` on a new install with node version 16.2.0.

**Comment by matheusd** [comment]
In general, you want to be running the same node version that is used as the basis for the electron version of the project. So, for example, for electron v12 you want to be running all commands on a node v14.16.x instance.

I believe one of my refactor PRs changes the `engine` entry in package.json to the correct (current) version so that any commands warn if you're not running a compatible node version.

I won't close this issue because it's likely the next major electron version will bump the node version (probably to node v16) so we'll need to revisit this, but the correct action for the moment as you note is to just use node v14.16.
