### ISSUE TITLE
[launcher] Add advanced options to Restore wallet

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#3482]
We should give the user the ability to add the following options to the restoring of wallets:

disablecointtypeupgrades and gaplimit

These 2 options should be shown during naming (before wallet is opened).  Possibly use an advanced options dropdown/opener to expose these options since typically won't be used. 

Then depending on how the user responds add these to the launcher.js options for dcrwallet spawn.

**Comment by bgptr** [comment]
on this
