### ISSUE TITLE
[trezor] wallet initialization and migration to per account passphrase wizard

### ISSUE THREAD

**Issue by karamble** [decred/decrediton#3508]
when setting up a wallet with trezor and starting it for the first time the wizard for per account passphrase shows up. you can not input any pw with the device. when you launch the wallet for a second time it skips the wizard.

**Comment by LasTshaMAN** [comment]
I observe the same behavior with Trezor T emulator.

Also it seems to not allow one to omit entering passphrase (i.e. use the empty one),

**Comment by alexlyp** [comment]
This has been fixed and will be included in the upcoming release.
