### ISSUE TITLE
"error refreshing stakepool data" bug

### ISSUE THREAD

**Issue by degeri** [decred/decrediton#3514]
If a user had earlier configured legacypool which has since shutdown eg stakey.net or dcr.farm . Even if they are using the new vspd system Decrediton gives  an error eg: "Error refreshing stakepool data from https://DCR.farm: Error: Network Error" 

Although it does not have any impact. Seen two insistence's of people in support panicking over this. 

We should handle this such that it not give an error if the user is not using the legacymode.

**Comment by bgptr** [comment]
on this
