### ISSUE TITLE
Fix error flows in create wallet

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#3524]
#3521 surfaced this

When an error occurs during the final stages of wallet creation / seed restore, the wallet is partially created and started but the app can't proceed with any operations.

There needs to be some rollback operation to return the app to a usable state.

**Comment by LasTshaMAN** [comment]
Can confirm that "as a new user" it is pretty easy with Decrediton to arrive at the state where you can't return on the previous screen, and you can't go any further (due to some error),

so improving this would be nice!

**Comment by bgptr** [comment]
on this
