### ISSUE TITLE
Decrediton 1.6.3 - Unmixed and Unconfirmed coins

### ISSUE THREAD

**Issue by nbenci** [decred/decrediton#3527]
Basically this has been going for a while now, i have some coins sitting in a "Unmixed" wallet in "Unconfirmed" state. No pending transactions, can't see which coins are unconfirmed nor why.

All balances are 0 on wallets, except Unmixed, but spendable there is 0 as they are in 'unconfirmed' state, this has been going for more than a month now.

Any clues on how to approach to this problem ?

**Comment by alexlyp** [comment]
Rescan and then abandon any pending transactions.

**Comment by nbenci** [comment]
resolved, i'm an idiot sandwich...

**Comment by alexlyp** [comment]
What was it?  Always looking for input to improve UI/UX.

**Comment by nbenci** [comment]
For some reason, in the past, unmixed coins where shown as unmixed, while in fact they probably went thru mixer.

i've ignored these pending transactions as they all had 0.0x DCR amount listed in the Decrediton, but that was not the amount sent.

Now after i went to each one of them i saw that amounts are much higher, and abandoned these pending transactions.

Did a rescan afterwards and all coins appeared in Mixed account and ready to be sent ( confirmed ).
