### ISSUE TITLE
Inconsistence amount of active tickets among tabs

### ISSUE THREAD

**Issue by xsanchezz** [decred/decrediton#3531]
Currently, the amount of live tickets is incorrectly displayed in Decrediton 1.6.3

In the overview tab, is correctly displayed, in this example the correct amount of active tickets is 2. In the staking tab, it shows 0 active tickets. See below screenshots.

<img width="1034" alt="Screen Shot 2021-07-11 at 9 01 17 PM" src="https://user-images.githubusercontent.com/4775731/125216589-a109b980-e28c-11eb-83a9-3624b3f2b2b7.png">
<img width="846" alt="Screen Shot 2021-07-11 at 8 57 44 PM" src="https://user-images.githubusercontent.com/4775731/125216592-a2d37d00-e28c-11eb-8f74-e93fe2040a73.png">
<img width="870" alt="Screen Shot 2021-07-11 at 8 58 07 PM" src="https://user-images.githubusercontent.com/4775731/125216594-a404aa00-e28c-11eb-9798-9dd1ba48ebcf.png">

**Comment by alexlyp** [comment]
I see it shows 2 'unspent' tickets there.  From what I can tell you have 2 unrevoked tickets that were missed or expired.  Those aren't considered live, but they are 'active and locked'.  We could probably improve the wording there.  But I see no major inconsistency.

**Comment by xsanchezz** [comment]
Okay, sounds good. Do you want me to close this issue or let it open until the wording is improved?
