### ISSUE TITLE
Change amount from mixed account to DEX

### ISSUE THREAD

**Issue by SovereignNode** [decred/decrediton#3541]
When you go through CoinShuffle and you send funds from 'mixed' to 'dex', the change amount gets sent to the 'dex' account too. Wouldn't it make more sense to send the change back to 'unmixed'?

More generally, shouldn't all doxic change be sent back to the unmixed wallet?

**Comment by alexlyp** [comment]
Yes, any change from mixed transactions should be going back to unmixed.  

Which form did you use within Decrediton did you use to send funds from mixed to dex?

**Comment by SovereignNode** [comment]
Tab 'On-chain transactions'

Select 'Send funds to another wallet'

I chose dex wallet and entered in amount manually. Change ended up in dex wallet too

**Comment by alexlyp** [comment]
I have been unable to replicate this issue.  I have repeatedly sent funds from mixed account to external addresses and other accounts, and the change is always sent to the unmixed account.

**Comment by SovereignNode** [comment]
Here's a picture of my last transfer back to DEX
![2021-09-10](https://user-images.githubusercontent.com/49792942/132815995-ad3eef13-053f-46ff-a34f-2ef23b8b83d3.png)

**Comment by alexlyp** [comment]
You should verify this by going to dcrdata to see the addresses and then use the validate address tool to see which account owns the 2.5640 output.  I believe this could just be a transaction details visual bug

**Comment by alexlyp** [comment]
Hrm I believe I've been able to replicate this issue.  Are the addresses for the amount and the change the same?

**Comment by SovereignNode** [comment]
Yes everything sent from 'mixed' to 'dex' is sent to the same address and nothing goes to unmixed.
