### ISSUE TITLE
i18n: Translator upgrades

### ISSUE THREAD

**Issue by xaur** [decred/decrediton#3583]
Below are ideas how to further improve [translator.html](https://github.com/decred/decrediton/blob/dc00928008d37072146ad4141eb9d81436cc7771/app/i18n/translator.html) collected while fixing issues listed in #3575.

Since it is a small single-file tool I'm putting it all into one issue to not spam the issue tracker with small stuff.

**User-facing changes**

- [ ] Always show all input fields
  - previous string is hidden if it is empty or equal to original string
  - this causes frequent changes to form's structure, confusing the eye and making the buttons jump up and down
  - instead, always show all fields but gray out the previous string if it is equal to new string

- [ ] Add label showing the current string key
  - sometimes I found myself asking "what key I'm looking at?" and the only way to know it is to find which item is selected in the left-hand list
  - put the label above Previous Original String input

- [ ] Add label for the translated string input
  - previous and original inputs have labels but not the translated input
  - an extra label will help to get familiar a bit faster

- [ ] Fix scroll position getting carried from one list to another
  - if I scroll down on one list and switch to another, it gets scrolled by the same %
  - ideally, make the lists scrollable independently

- [ ] Move "copy original" button (`V`) before "save & next" (`>`)
  - to match the order in which they are used

- [ ] Rename `>` and `V` to `save & next` and `copy original`
   - helps to learn the UI faster
   - increases the click area
   - alternatively, add tooltips to explain what these buttons do

- [ ] Jump to first item after `save & next` on last item
   - looping over the list sounds more fun than current behavior

- [ ] Add button to jump to previous string
  - sometimes I missed it after doing a mistake and hitting `save & next`

- [ ] Place Deleted Entries as another radio button + list
  - currently it looks out of place at the bottom
  - moving it along the other lists streamlines the layout, to expose what string was deleted
  - maybe also populate previous string input (read-only) on click
  - after this change it will be easier to make the left-hand list area span all visible vertical space (currently it is hardcoded to `34em`)

- [ ] Navigate to item selected by `save & next` action
  - switch to the list where the "next" item was selected (All/Untranslated/Changed), even if the user changed to a different list before hitting `save & next`
  - scroll the list to make the newly selected item visible

- [ ] Show app versions of previous and original strings
  - change string labels from "Previous Original String" and "Original String" to e.g. "String in v1.6.3" and "String in v1.7.0-pre"
  - this requires getting these versions somewhere, e.g. add a meta `_version` key to `previous_original.json` and `original.json`
  - the idea is to increase translator's awareness of what is being compared

- [ ] Investigate if diff highlighting is easy to do
  - highlight the diff between the "previous original" and "original" strings
  - for instance, it is not easy to detect changes when there is a new whitespace/eol that has been added/removed somewhere or when long Strings are compared
  - originally [suggested](https://github.com/decred/decrediton/issues/3575#issuecomment-949547398) by @JaseurPattu
  - I guess it will add a lot of complexity and take time to implement, but there could be a quick hack to help with the described use case

**Internal**

- [ ] Do not re-prepare file until download is requested

- [ ] Do not `saveTranslation()` on a mere select (click in the list), only save on `save & next` action

- [ ] Use strict comparison (`===` and `!==`) everywhere, verify nothing breaks

- [ ] Optimize finding next key
  - find a way to not re-scan all keys from 0 in `nextKey()`
  - e.g. maybe store an integer index in `state` so that figuring out next key becomes a simple `current_list[state.index + 1]` or something like that (mind edge cases ofc)

- [ ] Wrap code to whatever line length is adopted in this repo

**Comment by xaur** [comment]
I guess an ack from @matheusd wouldn't hurt, to make sure this is going in the right direction.

**Comment by matheusd** [comment]
Seems fair
