### ISSUE TITLE
Stuck on "syncing RPC connection"

### ISSUE THREAD

**Issue by jwt27** [decred/decrediton#3589]
[ Windows 7, amd64, decrediton 1.6.3 ]

For a couple days now I've been unable to launch decrediton.  The daemon starts and syncs but when I open my wallet it gets stuck on "Syncing RPC connection...".  The log file shows a long list of `DCTN: Validate Address`, and then nothing happens.  I could post it here if that helps, but there are no error messages that I can see.

I tried SPV on/off and reloading the wallet from seed, but it gets stuck at the same point.  I'd try `dcrwallet` directly but I don't know how to open the Decrediton wallet file with it.

**Comment by alexlyp** [comment]
Have you recently received a transaction from a PoW mining payout?  There is a bug in 1.6.3 that has caused large transactions like that to not be able to be processed and crash the application.  

It has been patched for the upcoming release.  In the meantime you can use CLI if you need to access those funds.

**Comment by jwt27** [comment]
Haven't done any mining so this might not be related to that.  Just the other day I was still able to access my wallet when I checked if my tickets had voted already.  The next day I went to get more tickets, and that's when this issue first occurred.

**Comment by alexlyp** [comment]
Well same issue applies to having any transaction that has tons of inputs that you may not control.  PoW mining payouts is simply a common transaction that has 100s of inputs.  Not sure on the limit that will cause decrediton to freeze on Validating Addresses.  

You could attempt to roll back to any of the 1.6.0 releases and give those a try before trying out CLI.  But unfortunately I have no 'fixes' to offer than those, or waiting for 1.7.0

**Comment by jwt27** [comment]
Okay thanks, v1.6.2 loads the wallet, so it is the same issue you mentioned.  I see I do have one tx with ~300 inputs.

However when I buy tickets now I get "Error: 2 UNKNOWN: insufficient balance", which is clearly wrong.  Guess I'll be missing out on this price dip :(

**Comment by alexlyp** [comment]
That insufficient balance error was fixed in 1.6.3, but basically you need more outputs to purchase the tickets (to pay for the vsp fee).  You can solve this by either mixing more (if you are using privacy), or sending yourself a few small amounts (1-2 DCR).

**Comment by jwt27** [comment]
Thanks.  I'll assume that works, but will wait for the price to drop before I try it...
