### ISSUE TITLE
[tickets]  Ticket History listing 'duplicates'

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#3590]
On the Staking > Ticket History page, there appear to be duplicated listings.  From what I can tell they correspond to Ticket/Vote or Ticket/Revoke Pairs.  The Votes and Revokes are labeled correctly, but the Tickets transactions themselves are also getting the same labeling.  

Something that may be related to this is warnings about children with duplicated keys in the console. 

We should be able to roughly keep the same listing, but we should figure out a way to label the tickets vs votes/revokes.  Maybe add Voted Ticket/Missed Ticket/Revoked Ticket for the tickets (Depending on their status), and then simple Vote or Revocation for those transactions.

**Comment by bgptr** [comment]
On this
