### ISSUE TITLE
Seed verification view updates

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#3593]
Seed Verification step updates based on [#2345 (Enhance Decrediton seed confirmation) ](https://github.com/decred/decrediton/issues/2345#issue-528505906)  and [#232 (Make seed verification less painful)](https://github.com/planetdecred/dcrandroid/issues/232#issue-381933869).

You can find the updated designs here https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred---piui---decrediton?node-id=363%3A0 (Decrediton - Latest page)

In the current desktop version users have to type in the first few letters of every missing word in the seed and select the right one, which is pretty long and painful process from a ux perspective. @jzbz suggested to use similar concept that is already implemented for the mobile clients and that's a good idea as this can simplify user interaction with this step a lot. 

So, the new process of confirming the seed will be like this (there should be all 33 rows as on mobile, but used only some of them on the layout just to show the concept. Though any smaller amount would be more convenient, but I guess using all 33 is more safe) :
![image](https://user-images.githubusercontent.com/8841018/140893814-e60eadde-55c0-4a7f-a43e-84cab8a3cabe.png)

Here users just have to choose and click on the right word within each of the 33 rows.

As the whole page doesn't fit the screen height, there is a bar stuck to the bottom that shows "Create Wallet" and "Back" buttons. 
![image](https://user-images.githubusercontent.com/8841018/140895376-4a22d3c0-4960-41a1-a919-19dd413c3e4d.png)

When scrolled till the end of the page the bar disappears and transforms into static buttons under the Private Passphrase fields. When starting to scroll up, the bar on the bottom appears again
![image](https://user-images.githubusercontent.com/8841018/140896801-7c5abeff-213d-4483-839f-27428d205485.png)

**Comment by bgptr** [comment]
This looks awesome. On it.
