### ISSUE TITLE
Custom cspp server configuration ability

### ISSUE THREAD

**Issue by monsa00** [decred/decrediton#3599]
Currently there is no way to configure a custom cspp server in Decrediton. It would be ideal to allow this functionality for flexibility and to promote decentralization.

**Comment by alexlyp** [comment]
After thinking about it for a bit, I don't think we'll be allowing for custom cspp servers in decrediton.  It's currently able to be switched in dcrwallet via CLI options.  Overall it isn't something that any basic user would really need to change and would lead to less privacy overall for the general user.  

If dev's or advanced users would like to change it for whatever reason, it's available to them in dcrwallet.

**Comment by xaur** [comment]
It should be up to the user, but with warnings explaining how exactly it will degrade privacy (e.g. reduced anonymity set).

There's more to privacy than the mixing anonymity set though. Everyone using one central server also works against privacy. Especially if same people admin other services (VSP API, dcrdata, DCRDEX, seeders, etc) that may provide additional user data.

But even bigger reason to allow configurable CSPP server, at least for me, is availability and resilience. Imagine what all mixing Decrediton users will do if the server goes down for a long time (not an ordinary crash). It would be a big disruption if they couldn't quickly switch to a fallback server. I would not expect them to suddenly learn dcrwallet (and shoot feet by misuse).
