### ISSUE TITLE
Rescan can't get past 70-80%

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/decrediton#360]
On macOS 10.12.4.

Tested this by restoring my wallet from seed 10 times. Didn't grab the exact block interval for the first 3 times. Decrediton got stuck rescanning at these block heights:

89999
93999
85999
93999
93999
91999
93999

During the last two, I watched Activity Monitor, dcrd went from 150+% CPU usage to 0 when the problem interval was encountered.

Closing Decrediton and reopening results in an incorrect balance being displayed.

Tried rescanning in dcrwallet (this is with a locked wallet, it works fine when unlocked), results here: https://gist.github.com/gratefulcheddar/bdc1f9dcca15c888514549c2ee6e4bb7

The rescan starts to run into a very large amount of "failed to attempt script importation of incoming tx script ... because addrmgr was locked" near the problem intervals for Decrediton. I'm guessing Decrediton, even though unlocked, isn't handling all of those script importations very well.

**Comment by gratefulcheddar** [comment]
Starting from command line with the `--debug` flag is the immediate solution for this. (e.g. `/Applications/decrediton.app/Contents/MacOS/decrediton --debug`).

According to @alexlyp in #dev, this is caused by how decrediton is handling logs, and there's a simple fix!

**Comment by jcvernaleo** [comment]
Yeah, this is next on my list of things to hit.

**Comment by jcvernaleo** [comment]
This is the same as #365, isn't it?

**Comment by gratefulcheddar** [comment]
Looks like it

**Comment by jcvernaleo** [comment]
Going to close this as a duplicate then (the other issue will have a link to this anyway so the info here will still be visible).

**Comment by alexlyp** [comment]
Well partially jcv, actually this also has something to do with an upcoming change to dcrwallet.  Which I'll link here. https://github.com/decred/dcrwallet/issues/539

**Comment by jcvernaleo** [comment]
Okay, then I'll reopen.

**Comment by alexlyp** [comment]
This has been resolved. Closing
