### ISSUE TITLE
Enter key vs. Button click bugs?

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/decrediton#361]
macOS 10.12.4

I noticed and tested this multiple times. There are a few places where pressing Enter instead of clicking a button has abnormal results.

When restoring from seed, if you press Enter after confirming the passphrase instead of the "Create Wallet" button, it will reload the "Create a Wallet" screen. Screenshot for reference:
![screen shot 2017-04-27 at 3 46 09 pm](https://cloud.githubusercontent.com/assets/12915233/25503748/034bdc64-2b61-11e7-8251-10216f91cb78.png)

When restoring from seed, if you press Enter after filling the "Scan for used accounts" field with your passphrase on the "Opening Wallet" page, the wallet loads without prompting the user to rescan. Screenshot for reference:
![screen shot 2017-04-27 at 3 46 45 pm](https://cloud.githubusercontent.com/assets/12915233/25503747/034aa5b0-2b61-11e7-9e62-7e5225ad5a6e.png)

Also, I noticed that when entering a block to rescan from during the initial restore from seed, you have to press Enter. The button will not work. At least not with "0" entered. Screenshot for reference:
![screen shot 2017-04-27 at 3 48 30 pm](https://cloud.githubusercontent.com/assets/12915233/25503744/033a1bb4-2b61-11e7-85b6-02f3651e996e.png)

**Comment by alexlyp** [comment]
Interesting I'll look into this, i think it's some goofy thing with electron recognizing button presses

**Comment by jcvernaleo** [comment]
I've actually hit this on linux too.

**Comment by karamble** [comment]
https://discuss.atom.io/t/why-doesnt-pressing-enter-submit-form/29132

Hope this helps

**Comment by alexlyp** [comment]
Fixed by @sndurkin #677
