### ISSUE TITLE
Settings views updates

### ISSUE THREAD

**Issue by MariaPleshkova** [decred/decrediton#3613]
In the current release (1.6.3) all sections of Settings are on one page and, thus, a bit out of our components library (had to use subtitles within sections there, bit it's not the way we show them). So we reorganized the view a bit.
We split a view into 3 main parts (Connectivity, General, Privacy and Security) and reworked them into a tab view.
Here is an example from the Settings in Launcher:
![image](https://user-images.githubusercontent.com/8841018/146071677-8f6a02fe-89c9-4dba-9163-e8f953ebc380.png)
Basically there are just 3 separate pages now, so all information is broken down into 3 categories(tabs). This way it's more clear where needed info is located.

For Settings in the Launcher we use two-columns grid for showing subitems on the page, because there's enough space for that:
![image](https://user-images.githubusercontent.com/8841018/146072945-ab471507-71ba-4e7a-a837-fe57cd68720d.png)

What concerns Settings within an existing wallet, we mostly have to use one-column grid there (big left part of the screen is taken by the menu). But if there are short sections such as Timezone and Misc, then we can place both of them in one row.
![image](https://user-images.githubusercontent.com/8841018/146073071-f1f08175-47a3-430d-b475-c31c8bae2186.png)
![image](https://user-images.githubusercontent.com/8841018/147104084-b5d95d65-54e2-4c33-8115-dcb2095e1446.png)

For wider screens we can still always place 2 sections in a row:
![image](https://user-images.githubusercontent.com/8841018/147106360-acdfb5f2-2c58-4c27-b7d5-bd3249e7e74e.png)

And as there are already some tabs (Settings, Sources, Tutorials and Logs), we just split Settings tab into 3 new ones (Connectivity, General, Privacy and Security). So now there are 6 tab items in total.

Also we added the title ( Address Usage) above the Discover Address Usage button. This way it's more clear that this button is the separate option within Misc.

What concerns Privacy and Security tab, Private Passphrase updating is now out of the section, and the section with checkboxes is renamed to Outbound Connections.
![image](https://user-images.githubusercontent.com/8841018/147105075-aa7f0cfc-d18b-4e2a-9d10-fa07ccb68cbe.png)

Please, notice that we also added a new section with Launcher option ticker to the General tab. Describing what is this for in #3614 (point 4, when the wallet is launched)
![image](https://user-images.githubusercontent.com/8841018/146241988-59b091b5-6253-4505-b4cf-15b3ab687f98.png)

_P.S.There is a question to think about though. It is a save feature. Now the Save button is always out of the visible area (I need to scroll to see it). So initially I as a user have no idea that I have to click on it to save the changes.
So I see 2 options here:_
_1. Add an autosave feature after every change (that would be the best one in my opinion)
2. Add Save button below each section_

Launcher Settings can be found within Concepting-Launcher page in Figma (see also 2 more pages to the right): https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred---piui---decrediton?node-id=2978%3A11507

In-wallet settings design is within the Decrediton-Latest page:  
https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred---piui---decrediton?node-id=3103%3A12223

**Comment by bgptr** [comment]
on this

**Comment by MariaPleshkova** [comment]
@bgptr added the latest discussed screenshots and description to the issue text
