### ISSUE TITLE
Missing dark mode on Sign Transaction confirmation

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#3623]
![Screenshot from 2021-12-30 12-33-30](https://user-images.githubusercontent.com/6762864/147752377-c82884dc-e3a3-4819-b0f8-15f99923681e.png)

**Comment by matheusd** [comment]
Do you still get this on 1.7.0-rc2 jholdstock? Otherwise, this is can be closed.

**Comment by jholdstock** [comment]
Sorry for the delay. This is fixed in 1.7 release.
