### ISSUE TITLE
Governance "In Discussion" proposals not showing

### ISSUE THREAD

**Issue by sumiflow** [decred/decrediton#3639]
On Windows 1.7.0-rc1, every time I click to the Governance page under "In Discussion" it shows "No Proposals Available" even though I know there should be 1 in discussion currently.
If I click any other tab like "Abandoned" and then click back to "In Discussion" then it shows correctly.  The issue returns every time I leave the governance page and come back.
![image](https://user-images.githubusercontent.com/5420838/148276403-b4b0a236-f742-4dc8-b9b6-e3f9c57c7d56.png)
![image](https://user-images.githubusercontent.com/5420838/148276414-285a3094-24d5-4744-ba25-e43d82218f3f.png)

**Comment by bgptr** [comment]
On this. Thanks for the report
