### ISSUE TITLE
DEX Tab UI Suggestion: Remove "Send to Self" when paying Registration Fee

### ISSUE THREAD

**Issue by exitus1** [decred/decrediton#3647]
![dex11](https://user-images.githubusercontent.com/46197055/148305450-bad8de2f-0a0a-44cf-b3cc-45ed36532d64.png)

I tried paying the fee by hitting "Send to Self" out of habit and it didn't do anything. Later went back and realized I had to actually press "Register" specifically. In order to not confuse users, I suggest replacing the Send to Self button with Register.

**Comment by alexlyp** [comment]
This step has been removed to we can close this issue.
