### ISSUE TITLE
[dex] Dex Window not launching after Reload UI

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#3649]
If you reload the UI then attempt to launch the Dex Window, nothing is spawned.  It flashes and does nothing.

**Comment by alexlyp** [comment]
Apparently https://github.com/decred/decrediton/blob/master/app/main.development.js#L429-L431 isn't firing for whatever reason after mainWindow.reload()

I've looked through https://www.electronjs.org/docs/latest/api/browser-window/ for any insight as to why it isn't working, but no luck or reports of a similar issue.

**Comment by xsanchezz** [comment]
Hi Alex,

Just did the initial process to create a DEX account, after finishing the last step, the windows went in blank. I needed to force close Decrediton, and after reopening, the DEX screen was fine and ready to use.

<img width="1295" alt="Screen Shot 2022-01-12 at 8 29 38 PM" src="https://user-images.githubusercontent.com/4775731/149245452-8c3c853d-3dc4-4771-bd45-b71b864f004f.png">

<img width="896" alt="Screen Shot 2022-01-12 at 8 43 14 PM" src="https://user-images.githubusercontent.com/4775731/149245631-26406634-adc3-4581-949c-e3467771788d.png">
