### ISSUE TITLE
Connect Wallets to DEX button descriptions enhancement

### ISSUE THREAD

**Issue by sumiflow** [decred/decrediton#3662]
Just a proposed slight DEX setup UI text/spacing change to make it easier for users to know which option to select.

Before:
![image](https://user-images.githubusercontent.com/5420838/149389430-123b6404-d3c6-4a6c-b790-e64277f1f96d.png)

After:
![image](https://user-images.githubusercontent.com/5420838/149389458-a1df16c1-9356-4363-84aa-03d2817d8c4f.png)

**Comment by alexlyp** [comment]
Yah that makes sense.  @bgptr care to handle this and try to spruce up some of those steps' css/style?

**Comment by bgptr** [comment]
Sure, on it.
