### ISSUE TITLE
incorrect treasury balance

### ISSUE THREAD

**Issue by sumiflow** [decred/decrediton#3675]
It's not a big deal but the treasury balance on the governance page is only showing the balance of the legacy treasury.  Perhaps it should be the legacy and new decentralized treasury combined.

![image](https://user-images.githubusercontent.com/5420838/150273767-867b5a6f-d533-4dc9-a7f1-1319d2b07b80.png)

**Comment by alexlyp** [comment]
Ha good point, total oversight. On it

**Comment by alexlyp** [comment]
So I looked into this and it's totally fixable in full-node mode.  But I'm not really sure on a way to get this information while in SPV.  I think I'll have to chat with @chappjc to see if we can add it to an existing dcrdata request.

**Comment by chappjc** [comment]
Last week deployed with
https://dcrdata.decred.org/api/treasury/balance

Need the data in an endpoint you're already hitting though?

**Comment by alexlyp** [comment]
Ah no that will do perfectly!
