### ISSUE TITLE
Incorrect balance shown and cant spend from wallet

### ISSUE THREAD

**Issue by freedomprivacy** [decred/decrediton#368]
Following a successful send of 0.5 DCR from my decrediton wallet to an exchange, my balance shortly after increased by 20 DCR - no-one had sent me any DCR and it hasnt shown in the transaction history. When i went to send another 0.5 DCR from the same wallet to the same exchange after this, i was unable to send any DCR due to the following error.
<img width="752" alt="screen shot 2017-04-24 at 5 38 50 pm" src="https://cloud.githubusercontent.com/assets/28222804/25564759/66d62872-2dfd-11e7-81dc-c3bdd819e1f6.png">
I do not have my seed as I cannot find it anywhere. I do have a backup of my wallet. 
Please would you help in finding a solution to this issue.
BTW I am using the latest version of the wallet 1.0.1
thanks

**Comment by alexlyp** [comment]
This is an issue that comes from dcrwallet i'll be leaving this open until we have that fix in place and can confirm it is no longer an issue in decrediton

**Comment by jrick** [comment]
It's actually decred/dcrd#618

**Comment by freedomprivacy** [comment]
so, what do I do from here guys? Have to wait for a bug fix to be released?

**Comment by jrick** [comment]
If i understood the issue correctly...

Your balance jumped up probably because it is using a spendable balance with some number of block confirmations rather than the total balance.  The issue linked above is a bug that manifests when you try to spend anything that was mined in the latest block.  By waiting another block, those outputs are no longer in the latest block and the mempool will allow you to spend them again.

Try creating the transaction again and see if the same error occurs.

**Comment by freedomprivacy** [comment]
I waited for many blocks to go by, tried the transaction (in fact many different transaction), and it always came up with the same error. Anything I can try at my end to aid further analysis?

**Comment by jrick** [comment]
Ok, that sounds more like an issue with dcrwallet then.

Some questions:

* What version of decrediton are you running?
* What version of decrediton did you use to create the wallet?
* Has this wallet been used to send other transactions?
* Do you see transaction [879af9e1163a9c3ec183df647a348ba076755c0562ba3e2761d2121d63decf6e](https://mainnet.decred.org/tx/879af9e1163a9c3ec183df647a348ba076755c0562ba3e2761d2121d63decf6e) in your wallet?  Did you create this transaction? (This is the transaction that spent that output you see in the error message)

**Comment by freedomprivacy** [comment]
I will get back to you on those questions when I wake up (off to bed as late here in Oz). thanks again

**Comment by freedomprivacy** [comment]
Ok, latest on this:
1) I restored from my backup /Library folder (and all subdirectories) - all on my Mac.
2) I started the 1.0.1 Decrediton app and it caught up the relevant blocks, and then gave me my correct balance !! Whoo hooo
3) I sent a small transaction (0.1 DCR) to another DCR wallet(Web wallet) on a different computer.
It came up as an unconfirmed balance almost immediately. So all looking good.
4) The next block is processed, and my balance doubles on the Decrediton wallet...
The Web Wallet shows a confirmed transaction for 0.1 DCR (134dbd4a4fa30362466154602c3199c0925f3a8a8f20620c88b5af17f5198b7f) 
The Decrediton wallet shows the same transaction #, but for 0.0 DCR
5) three blocks later and the balance is still showing double.
6) So I have tried restarting the wallet and now all i get is the following screenshot
![image](https://cloud.githubusercontent.com/assets/28222804/25650182/95a42622-301e-11e7-87f8-d591c6d5a4ca.png)
7) I've tried following the same procedure (restoring the /library folder from backup) but can't now get past the RPC error

To answer your other questions:
I created the wallet in version 0.8.2
I do not see the TXN ID you stated in my wallet.

thanks

**Comment by freedomprivacy** [comment]
Following the last set of updates, I have now also sent a small amount of DCR (0.06) from my web wallet to the Decrediton wallet. After the block was updated/the transaction confirmed it showed up correctly in the wallet (TXN ID 488568038aa58b16e77fc56dffbcb70b364579cd6bfe315cfedb53fb763e9e7b)

So I am still left with the balance being double what it should be, and not able to send any DCR to anywhere...

**Comment by freedomprivacy** [comment]
just downloaded version 1.0.2 of decrediton and rescanned the blockchain (great option to add) and its restored my correct balance. Thanks guys for all your help

**Comment by xaur** [comment]
> I do not have my seed as I cannot find it anywhere.

@freedomprivacy you can create a new wallet with a new seed and send funds from the old one. It is risky to not have the seed.
