### ISSUE TITLE
Ticket auto-buyer isn't buying tickets

### ISSUE THREAD

**Issue by sumiflow** [decred/decrediton#3684]
I've been running Decrediton 1.7 on Linux for a few days and restarted a few times now but I don't think that the ticket auto-buyer has ever purchased a ticket for me since the 1.7 upgrade.

I have enough balance in my mixed account and I haven't found any errors being generated in the dcrd, dcrwallet, or decrediton logs yet.  Fortunately, I am able to purchase tickets manually through the purchase button, just not through the auto-buyer.

**Comment by alexlyp** [comment]
Can you look at your dcrwallet during the period of time after you have turned on the autobuyer.  Is it attempting to mix transactions or do anything?
