### ISSUE TITLE
Overview type styling: sizes & grey values 

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#3692]
1) Overview layout has a few mismatching type styling for "Recent Transactions" and "Staking Activity" as well the "See all" links and "current total balance, available, locked" subtexts. These should be with the 18px and 13px sizes. 

<img width="1401" alt="Screenshot 2022-02-03 at 14 09 30" src="https://user-images.githubusercontent.com/17774057/152340175-71955cb9-1eed-499e-82b2-995fd3af72e2.png">

<img width="819" alt="Screenshot 2022-02-03 at 14 09 20" src="https://user-images.githubusercontent.com/17774057/152340204-67b637da-b65c-4452-84a0-35964f6cd61f.png">

2) Dates and numbers on Overview graph have out-of-scheme grey value, should be #596D81

<img width="434" alt="Screenshot 2022-02-03 at 14 20 24" src="https://user-images.githubusercontent.com/17774057/152341694-31f327c6-e3bc-4c5a-8ae3-1871b46375bc.png">

3) Lightmode: to improve viewing contrast on small type sizes, both #C4CBD2 and #8997A5 can be replaced with → #596D81 in all instances where it's used as a subtext for tx's. (Overview, Transaction History, LN views containing TX rows).

<img width="2267" alt="Screenshot 2022-02-03 at 14 19 21" src="https://user-images.githubusercontent.com/17774057/152341559-76e6b77a-0a63-4cf7-ae98-e836301e92fe.png">

4) Non-selected (state) navigation items: #8997A5 → #3D5873

<img width="2114" alt="Screenshot 2022-02-03 at 15 26 36" src="https://user-images.githubusercontent.com/17774057/152351692-df08d171-d086-45b8-83a5-abcf6a247a7b.png">

https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred---piui---decrediton?node-id=3210%3A11609

**Comment by bgptr** [comment]
On this
