### ISSUE TITLE
Start wallet in decrediton specific directory

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#37]
Much like paymetheus, decrediton should start dcrwallet in a directory of its own rather than in $HOME/.dcrwallet (or whatever the os specific one is) so it doesn't interfere with existing wallets.

**Comment by jrick** [comment]
Related to this, paymetheus also runs dcrwallet (and the launcher runs dcrd) with nonstandard RPC ports so both a normal cli install and paymetheus can both be running without conflicting listen addresses.

**Comment by jrick** [comment]
https://github.com/decred/Paymetheus/blob/0112908050fb2da8cbafe97c679b2ee60f410a6c/Paymetheus.Rpc/WalletProcess.cs#L58

**Comment by jcvernaleo** [comment]
@jrick since starting wallet and dcrd is a seperate issue #28 I think the port issue should be handled there.
