### ISSUE TITLE
orphan transaction references outputs of unknown or fully-spent transaction

### ISSUE THREAD

**Issue by lolandhold** [decred/decrediton#3701]
Sending coins with Decrediton 1.7.0 gives this error.
```
Error: 2 UNKNOWN: wallet.PublishTransaction(3917fb):: dcrd.PublishTransactions: rejected transaction 3917fb: orphan transaction 3917fb references outputs of unknown or fully-spent transaction 92f8b7
```
Rebroadcasting the transaction didn't fix it.
Restarting Decrediton didn't fix it.

This happened [many times](https://github.com/decred/decrediton/search?q=orphan+transaction&type=issues) before.
In 2018 [1](https://github.com/decred/decrediton/issues/1247) [2](https://github.com/decred/decrediton/issues/1209)
In 2017 [3](https://github.com/decred/decrediton/issues/934) [4](https://github.com/decred/decrediton/issues/420)

**Comment by alexlyp** [comment]
Rescan

**Comment by alexlyp** [comment]
There's various explanations for why one would get this error from dcrwallet.  But in my opinion, most are not a bug.

You are attempting to spend outputs that the network doesn't know about.  This can happen a few different ways, but typically if you create a transaction while not connected to any peers.  Your local wallet will think something is spent, but the network doesn't.

**Comment by lolandhold** [comment]
Rescan how?

Starting Decrediton should restore to a stable state.  Right now it doesn't.  In my opinion, this is a bug.

I'm connected to many peers.

**Comment by alexlyp** [comment]
Rescan button is on the lower left.  

Review if you have pending transactions.  That is not a bug if you have pending transactions.  Your wallet believes the outputs of that transactions are available to spend, but the network does not.  It's not a bug.

**Comment by lolandhold** [comment]
There were no pending transactions.
