### ISSUE TITLE
Cannot connect to DCRDEX in Decrediton 1.7.0 -- Account not Found

### ISSUE THREAD

**Issue by walliams** [decred/decrediton#3705]
Since updating to 1.7.0 from 1.6.3 the app is returning this error when I try to login to the DEX:

`Connecting to DCR wallet Failed: Error: UpdateWallet error: dcr Wallet.Address error: -11: account not found`

I am certain that my passwords are correct. When I restore my DEX seed to a new wallet I am able to login properly, but I would prefer not to have to incur a transaction fee just to send my funds over to a new wallet.

**Comment by alexlyp** [comment]
You had a working 1.6.3 DEX set up but then you hit this error when using 1.7.0 ?

**Comment by walliams** [comment]
> You had a working 1.6.3 DEX set up but then you hit this error when using 1.7.0 ?

yep. and i have no clue what the issue is or how to diagnose it

**Comment by alexlyp** [comment]
If you have already been set up to use the DEX in a previous version, you can try to just bypass the stuff in decrediton and just open a browser and go to https://127.0.0.1:5760 

That should open the same DEX window as you would see inside of decrediton

**Comment by alexlyp** [comment]
So to confirm, you get this error simply by trying to Login with your dex passphrase?

**Comment by alexlyp** [comment]
Please try 1.7.1 and see if the same problem persists.

**Comment by xsanchezz** [comment]
@alexlyp @walliams  I had this issue before and I solved it by uninstalling Decrediton and reinstalling again. Make sure to delete all files.

**Comment by walliams** [comment]
> So to confirm, you get this error simply by trying to Login with your dex passphrase?

 It happens on the second password prompt when I am linking my DCR wallet (BTC links automatically)

> Please try 1.7.1 and see if the same problem persists.

Same issue on 1.7.1

> @alexlyp @walliams I had this issue before and I solved it by uninstalling Decrediton and reinstalling (the latest version) again. Make sure to delete all files.

Interesting. Glad I'm not alone at least. I will try this, but... when you say delete all files, what do you mean? I'm on linux, and there's a bunch of decred related folders. When I "installed" 1.7.1 all i really did was download the .tar and unzip to my home directory and then run ./decrediton from terminal. So reinstalling just that folder won't change anything...
Do you mean delete and resync the whole blockchain too?

**Comment by walliams** [comment]
@alexlyp THANK YOU! You are exactly right-- I had it set to default and then I added new accounts to the wallet and renamed them all.
Might be good to have a fix for this built into the GUI, perhaps a drop-down menu where you select what account to link to the DEX, and have it refresh that menu when the wallet is opened.
Very much appreciate your support.
