### ISSUE TITLE
Available Balance very far from correct value.

### ISSUE THREAD

**Issue by lbiazao** [decred/decrediton#371]
<img width="763" alt="captura de tela 2017-05-02 as 10 51 00" src="https://cloud.githubusercontent.com/assets/5401274/25620666/891c35c4-2f25-11e7-8168-6c0ad3a6ceb4.png">
My balance is very far from the correct balance, it should appear something around DCR 46.00 but to be honest I don't know the correct balance.
https://mainnet.decred.org/address/DsVntNXuAjp7QkMhCo7GPT3weP7sd1j9btZ

**Comment by petravis** [comment]
I had the same issue - rescanning the blockchain with version 1.0.2 took care of the issue.

**Comment by lbiazao** [comment]
Yes, you are right. It did work with the rescan. Why this version is not listed as the new version in the website?

**Comment by alexlyp** [comment]
@lbiazao hrm which link do you mean?  we might have missed one

**Comment by lbiazao** [comment]
I tryed to donwload from the decred.org / The wallets, now it's showing 1.0.2 in the morning wasn't.

**Comment by alexlyp** [comment]
great.  closing
