### ISSUE TITLE
[governance] update voting preference takes too much time

### ISSUE THREAD

**Issue by bgptr** [decred/decrediton#3717]
On the consensus changes details page, clicking on the "Update Preference" button, Decrediton fetches public keys from all VSP one by one, and it could take a large amount of time on the mainnet. 
The votes should be run parallel, like in https://github.com/decred/decrediton/pull/3633

Also, if a fetch request fails, we should inform the user, that there was an error and not all of the VSPs have been updated.

**Comment by amass01** [comment]
I would like to address this one
