### ISSUE TITLE
[ux] Notify user of votes

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#3721]
When new consensus agendas or Pi votes go live for voting users should receive a visual notification both on the overview screen in Decrediton as well as in the sidebar where the governance tab is.

- On the overview page it could be a small box showing there a N new consensus or Pi votes live and linking the user to the governance tab if clicked.
- The governance tab in the sidebar could have an icon (exclamation mark or something that draws the eye) appear when there are new items requiring the user's attention.

**Comment by alexlyp** [comment]
Yah I like the sound of that.  

The consensus vote part should be decently easy to check and notify since we can get vote choices easily.  If any are abstain then alert user.  

The Pi proposal vote one is a little more complicated, but I believe we should be able to figure something out for that.

**Comment by bgptr** [comment]
on this
