### ISSUE TITLE
Restore existing wallet on Decrediton

### ISSUE THREAD

**Issue by Fegor-Clinton** [decred/decrediton#3742]
I tried to restore a wallet using the 33 seed words, I input them correctly and cross-checked 3 times but I kept getting the error:
"*please paste a valid 33-word seed"
I continued with the process still and typed in a passphrase and clicked continue.
Surprisingly, it worked and continued fetching blocks.
Although, when it was done, I got another screen saying migrate to per account passphrase, I clicked on continue and put in my passphrase, but it keeps telling me incorrect passphrase.
![image](https://user-images.githubusercontent.com/81264478/164720348-fcf06c05-a7d0-4b6c-85df-a45cbb434b63.png)
![image](https://user-images.githubusercontent.com/81264478/164740386-baf26d0b-34df-42ea-8262-759beaf3b9ca.png)
![image](https://user-images.githubusercontent.com/81264478/164740761-64c14e8d-f70b-4de7-982c-3c55e0cc5912.png)

**Comment by alexlyp** [comment]
You must have not entered your password correctly then.

**Comment by Fegor-Clinton** [comment]
Thanks for your response.
Although, the password I created when restoring my wallet is the one I used
there.
Did I make a mistake there?

Hope to get your reply soon.
Thank you.
