### ISSUE TITLE
Can't scroll in Staking/Governance tabs.

### ISSUE THREAD

**Issue by exitus1** [decred/decrediton#3759]
![image](https://user-images.githubusercontent.com/46197055/167948891-c27e216c-bb05-4d1c-925a-cc2c03cdd44b.png)

**Comment by exitus1** [comment]
I noticed this was still a problem in 1.7.3, so I dug a bit deeper.

Enabling UI animations **allows** for scrolling, but disabling UI animations doesn't allow me to scroll in staking, governance, transactions tabs etc.

Hopes this helps.

**Comment by bgptr** [comment]
Thanks, @exitus1 This definitely helps, i'm able to reproduce it now.
On this.
