### ISSUE TITLE
[treasury spending] Changing Voting for preference to Yes give error

### ISSUE THREAD

**Issue by xsanchezz** [decred/decrediton#3763]
Here is the message error I get when trying to choose yes in the voting preference.

<img width="573" alt="Screen Shot 2022-05-15 at 5 26 41 PM" src="https://user-images.githubusercontent.com/4775731/168494800-81e11f5d-9dd2-4a82-ade5-14930a2adce1.png">

**Comment by alexlyp** [comment]
Ah looks like it's due to a missing commit on dcrwallet.  We'll add it for the upcoming release (v1.7.3). Should be out soon

**Comment by xsanchezz** [comment]
Just downloaded 1.7.3 from the binaries repo. @alexlyp 

The first try to update the preferences to Yes, I got this error message:

<img width="397" alt="Screen Shot 2022-05-19 at 9 50 08 AM" src="https://user-images.githubusercontent.com/4775731/169309519-8e303888-a838-4e54-a965-f903b4c0b75d.png">

In the second attempt to select Yes, it went in a loading state infinitely (this time the yes option looks like it was accepted):

<img width="393" alt="Screen Shot 2022-05-19 at 9 47 48 AM" src="https://user-images.githubusercontent.com/4775731/169309118-beb23d9d-25e6-496e-9b8c-a16103e373d5.png">

I closed Decrediton and opened it again, and the setting is now on Yes.

<img width="430" alt="Screen Shot 2022-05-19 at 9 49 44 AM" src="https://user-images.githubusercontent.com/4775731/169309788-700821f3-abf5-42fd-9530-8682e276d7fe.png">

**Comment by alexlyp** [comment]
Dunno about the first one, but the 2nd attempt you probably entered an incorrect password.  There is a pull request currently up to fix that issue.

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/

**Comment by bgptr** [comment]
Could reproduce the second one on the mainnet. On it.
