### ISSUE TITLE
remove all BTC wallet type selection steps

### ISSUE THREAD

**Issue by chappjc** [decred/decrediton#3793]
With DEX including a native BTC wallet since 0.4 (January 2022), the Decrediton selection dialogs and buttons regarding Bitcoin should be removed.

A related question from Matrix that I did not know the answer to is, if the DEX user changes BTC wallet type from bitcoindRPC to native *in DEX*, what if anything needs to happen back in Decrediton?

See also the dcrinstall issue to remove the Bitcoin related downloads and config: https://github.com/decred/decred-release/issues/227

**Comment by bgptr** [comment]
on this
