### ISSUE TITLE
Warnings present after recent react update

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#381]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by matheusd** [comment]
Needs to update react-router to 3.0.4 and material-ui to 0.17.4.

I read through the changes of the packages and there doesn't seem to be any incompatibilities (we're not using anything very fancy from them).

I'll provide a PR later on.
