### ISSUE TITLE
[UX] To addresses instead of to address for txn with multiple outs

### ISSUE THREAD

**Issue by norwnd** [decred/decrediton#3817]
Hi, I've been playing around with Decrediton and this one thing caught my eye,

transaction could be targeting multiple recipients, yet when inspecting a particular transaction it always says "To address" in the UI (regardless of how many outputs it has).

I think it would be a bit nicer to show "To addresses" in case of multiple outputs, like on screenshot below:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/112318969/196055813-196f21ed-406c-4fff-ae9b-346ebb902fa9.png">

**Comment by bgptr** [comment]
Solved in #3789
Thanks @norwnd

**Comment by norwnd** [comment]
Ah, okay thanks :)
