### ISSUE TITLE
[dex] -14: invalid passphrase (DEX isn't aware of password change in Decrediton)

### ISSUE THREAD

**Issue by norwnd** [decred/decrediton#3820]
Reproducible with Decrediton 1.7.5, assuming I already have a working DEX setup in Decrediton (I've imported my DEX-seed),

- update password (Private Passphrase) in Decrediton (under Settings -> Privacy and Security tab)
- launch DEX window
- go to Wallets tab and try to unlock Decred wallet
it will ask for DEX app password, when I enter it I get `-14: invalid passphrase` error (and if I try to enter old or new Decred wallet password in DEX app password field I get `incorrect password` - this part works correctly I think)

There is also the following log line in `dexc`:
```
-14: invalid passphrase` error on front-end
and `2022-10-19 16:46:40.749 [ERR] SRVR: error unlocking dcr wallet: failed to unlock dcr wallet: -14: invalid passphrase
```
As a work-around, I was able to manually update wallet password via `set a new wallet password` form (in Reconfigure Decred Wallet section), however it's not an obvious step to do (definitely not very smooth user experience). **Update:** this work-around stops working as soon as I quit from Decrediton app (when closing and re-opening DEX window without closing whole Decrediton app I'm able to lock/unlock wallet successfully, so only full restart of Decrediton seems to result in reverting to "broken state").

I think this step can be easily automated - when I change password (Private Passphrase) in Decrediton something should be done to propagate these changes to `dexc` as well. And if for some reason it can't, better error message (with some instructions on what to do) would be useful.

**Comment by bgptr** [comment]
On this
