### ISSUE TITLE
ui: send amount could be wrong

### ISSUE THREAD

**Issue by norwnd** [decred/decrediton#3854]
Running 1.7.6, I'm filling in send form in Decrediton, setting amount to 20. Occasionally it displays total as 2 and 2 is used on confirm form and sent afterwards too (it became harder to impossible to reproduce after couple of tries, if I don't restart my wallet). I'm using my own address to demonstrate, but it happened with not owned address too for me (both testnet and mainnet).

[1st.webm](https://user-images.githubusercontent.com/112318969/224299992-b017be30-988f-4a84-a66d-63ac0c2f1503.webm)
[2nd.webm](https://user-images.githubusercontent.com/112318969/224300036-c7cd0f4d-e62c-4f29-8cc9-25f1fc76c41f.webm)

**Comment by lolandhold** [comment]
I have the same problem with 1.7.6.

I set the amount to 50 (fifty), when I enter the password to send it shows 5 (five), and the transaction receipt pop-up shows 5 (five), it sends 5 (five).

Another time I set the amount to 50 (fifty), when I enter the password to send it shows 50 (fifty), the transaction receipt pop-up shows 5 (five), it sends 50 (fifty).

**Comment by alexlyp** [comment]
I've been trying to replicate this, but so far haven't been able to.  I'll keep trying, but so far these videos examples I can't seem to recreate.  It always properly updates for me.

**Comment by bgptr** [comment]
I was able to reproduce the issue. To solve it, I added a debounce to the input value. I will open a pull request shortly. Thanks for the report, guys.
