### ISSUE TITLE
Add hardware wallet button on main screen

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#3859]
When Decrediton starts up the user is presented with the options to open an existing wallet, create a new wallet, or restore a wallet. I propose we have a fourth option to pair a hardware wallet.

Currently adding a hardware wallet is pretty unintuative as the user must select "restore" and then click on the advanced options in order to set up their hardware wallet. Users would be forgiven for not knowing that Decrediton supports this functionality.

We currently have a [proposal up for discussion](https://proposals.decred.org/record/609db9e) to add basic Ledger functionality in addition to the existing Trezor functionality and I think it would be good to highlight this feature by giving hardware wallets a dedicated icon.

**Comment by bgptr** [comment]
@jzbz On the redesigned launcher view (#3690), there is a dedicated Trezor button. Is that what you had in mind?

**Comment by jzbz** [comment]
That looks fantastic. Only thing that needs to be decided is whether to give Ledger a button too or consolidate them both under one generic hardware wallet button, as it's possible in the future we may support additional hw wallets to those two.

**Comment by bgptr** [comment]
Yeah, we could add a dedicated "Ledger" button or replace the "Trezor" button with a generic "Hardware Wallet" button. The hardware type could then be automatically detected on the connect page (https://user-images.githubusercontent.com/52497040/137967347-4ed984f8-4e0b-465b-b851-30b2d7b2953d.png), or the user could be given a manual option to choose.

**Comment by jzbz** [comment]
I think a manual option after they click a generic hardware wallet button is best as there are a lot of hw wallets out there and we only support 2 for now. Or if it's happening automatically have a message like the one in your example image showing which devices are supported and being looked for.

**Comment by amass01** [comment]
this is related to https://github.com/decred/decrediton/issues/3865, i think what @JoeGruffins had in mind is
two icons in the main screen one for each. I agree that there should be a page for hardware wallets which
has for now two icon buttons one for ledger and one for trezor

**Comment by amass01** [comment]
i have created a new issue in pi-ui to add a new ledger icon https://github.com/decred/pi-ui/issues/478
