### ISSUE TITLE
Decredition not downloading blocks

### ISSUE THREAD

**Issue by repsah** [decred/decrediton#386]
I recently downloaded decredition and run it on a Ubuntu laptop (17.04) but apparently it's not downloading blocks. Stuck at 0. I have it installed on another laptop and everything works fine.

**Comment by alexlyp** [comment]
can you check your logs in ~/.dcrd/logs/mainnet.log ?

It should show you if you are receiving blocks from peers.

**Comment by jcvernaleo** [comment]
I just recently updated a laptop to ubuntu 17.04 so I'll see if I hit this.

**Comment by jcvernaleo** [comment]
I just tried the decrediton-1.0.2 binaries on Ubuntu 17.04 (a fresh machine) and it seems to be downloading blocks just fine.

@repsah along with the logs @alexlyp asked for could you run it with the `--debug` flag and show us some of the output from there?

**Comment by repsah** [comment]
Looks like a problem with DNS, which is weird, everything else works fine:
21:24:11 2017-05-21 [INF] DCRD: Version 1.0.1+release (Go version go1.7.5)
21:24:11 2017-05-21 [INF] DCRW: Version 1.0.1+release (Go version go1.7.5)
21:24:11 2017-05-21 [INF] DCRW: Generating TLS certificates...
21:24:11 2017-05-21 [INF] DCRW: Done generating TLS certificates
21:24:11 2017-05-21 [INF] DCRD: Home dir: /home/repsah/.dcrd
21:24:11 2017-05-21 [INF] DCRD: Loading block database from '/home/repsah/.dcrd/data/mainnet/blocks_ffldb'
21:24:11 2017-05-21 [INF] DCRD: Block database loaded
21:24:11 2017-05-21 [INF] DCRW: Experimental RPC server listening on 127.0.0.1:9112
21:24:11 2017-05-21 [INF] INDX: Exists address index is enabled
21:24:11 2017-05-21 [INF] STKE: Stake database version 1 loaded
21:24:11 2017-05-21 [INF] CHAN: Blockchain database version 2 loaded
21:24:11 2017-05-21 [INF] CHAN: Chain state: height 0, hash 298e5cc3d985bfe7f81dc135f360abe089edd4396b86d2de66b0cef42b21d980, total transactions 1, work 140738562105344, stake version 0
21:24:11 2017-05-21 [INF] RPCS: RPC server listening on 127.0.0.1:9109
21:24:11 2017-05-21 [INF] AMGR: Loaded 3 addresses from file '/home/repsah/.dcrd/data/mainnet/peers.json'
21:24:11 2017-05-21 [INF] CMGR: Server listening on 0.0.0.0:9108
21:24:11 2017-05-21 [INF] CMGR: Server listening on [::]:9108
21:24:11 2017-05-21 [INF] CMGR: 3 addresses found from DNS seed mainnet.decredseed.org
21:24:11 2017-05-21 [INF] CMGR: DNS discovery failed on seed mainnet-seed.decred.org: lookup mainnet-seed.decred.org: Temporary failure in name resolution
21:24:11 2017-05-21 [INF] CMGR: DNS discovery failed on seed mainnet-seed.decred.netpurgatory.com: lookup mainnet-seed.decred.netpurgatory.com: Temporary failure in name resolution
21:24:14 2017-05-21 [INF] GRPC: Unary method /walletrpc.VersionService/Version invoked by 127.0.0.1:38066
21:24:15 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletLoaderService/WalletExists invoked by 127.0.0.1:38070
21:24:15 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletLoaderService/OpenWallet invoked by 127.0.0.1:38070
21:24:20 2017-05-21 [INF] WLLT: Opened wallet
21:24:20 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletLoaderService/StartConsensusRpc invoked by 127.0.0.1:38070
21:24:21 2017-05-21 [INF] RPCS: New websocket client 127.0.0.1:59964
21:24:21 2017-05-21 [INF] CHNS: Established connection to RPC server 127.0.0.1:9109
21:24:21 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletLoaderService/SubscribeToBlockNotifications invoked by 127.0.0.1:38070
21:24:21 2017-05-21 [INF] WLLT: The client has successfully connected to dcrd and is now handling websocket notifications
21:24:21 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletLoaderService/DiscoverAddresses invoked by 127.0.0.1:38070
21:24:21 2017-05-21 [INF] WLLT: Discovering used addresses for 1 account(s)
21:24:21 2017-05-21 [INF] WLLT: Synchronized account 0 branch 0 to next child index 0
21:24:22 2017-05-21 [INF] WLLT: Synchronized account 0 branch 1 to next child index 0
21:24:22 2017-05-21 [INF] WLLT: Finished address discovery
21:24:22 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletLoaderService/FetchHeaders invoked by 127.0.0.1:38070
21:24:22 2017-05-21 [INF] WLLT: Fetching headers
21:24:22 2017-05-21 [INF] WLLT: Fetched 0 new header(s)
21:24:22 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletService/Accounts invoked by 127.0.0.1:38398
21:24:22 2017-05-21 [INF] GRPC: Unary method /walletrpc.TicketBuyerService/TicketBuyerConfig invoked by 127.0.0.1:38400
21:24:22 2017-05-21 [ERR] GRPC: Unary method /walletrpc.TicketBuyerService/TicketBuyerConfig invoked by 127.0.0.1:38400 errored: rpc error: code = 9 desc = ticket buyer is not running
21:24:22 2017-05-21 [INF] GRPC: Unary method /walletrpc.AgendaService/Agendas invoked by 127.0.0.1:38404
21:24:23 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletService/LoadActiveDataFilters invoked by 127.0.0.1:38398
21:24:23 2017-05-21 [INF] WLLT: Loading active addresses and unspent outputs...
21:24:23 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletService/NextAddress invoked by 127.0.0.1:38398
21:24:23 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletService/Balance invoked by 127.0.0.1:38398
21:24:23 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletService/StakeInfo invoked by 127.0.0.1:38398
21:24:23 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletService/TicketPrice invoked by 127.0.0.1:38398
21:24:23 2017-05-21 [INF] GRPC: Streaming method /walletrpc.WalletService/TransactionNotifications invoked by 127.0.0.1:38398
21:24:23 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletService/Ping invoked by 127.0.0.1:38398
21:24:23 2017-05-21 [INF] GRPC: Unary method /walletrpc.WalletService/Network invoked by 127.0.0.1:38398
21:24:23 2017-05-21 [INF] WLLT: Registering for transaction notifications for 40 address(es) and 0 output(s)
21:24:23 2017-05-21 [INF] GRPC: Streaming method /walletrpc.WalletService/GetTransactions invoked by 127.0.0.1:38398
21:24:31 2017-05-21 [INF] CMGR: DNS discovery failed on seed mainnet-seed.decred.mindcry.org: lookup mainnet-seed.decred.mindcry.org: Temporary failure in name resolution

**Comment by alexlyp** [comment]
appears to not be a problem related to decrediton.  closing
