### ISSUE TITLE
Dialog Enter Password to Buy Tickets Doesn't disappear

### ISSUE THREAD

**Issue by magnus-staberg** [decred/decrediton#387]
The dialog with title "Enter Passphrase to Purchase Tickets" doesn't disappear after successfully entered correct password and clicked on 'OK' button.

**Comment by alexlyp** [comment]
Strange I've never encountered this.  Are you on OSX or linux?  did the transaction successfully send?

**Comment by magnus-staberg** [comment]
OSX. The transaction succeeded. It has occurred every time. Can't remember but I might have bought more than one ticket.

**Comment by alexlyp** [comment]
ok i'll try replicate, thanks for the report

**Comment by africanalex** [comment]
I get this too on macOS

**Comment by jcvernaleo** [comment]
So I was able to confirm this issue on the release 1.0.2 (on osx 10.11.6, el Capitan) but it is no longer present in master.  I haven't gone back to figure out which commit fixed it, but it does appear fixed.

**Comment by alexlyp** [comment]
Ah just checked the logs and this is in fact fixed on master.  

https://github.com/decred/decrediton/commit/4fcab75dbe12be741dd898af9802dfedcb06b47e#diff-b34abae158072a43b7818e035145baceR175

Thanks for the report
