### ISSUE TITLE
Decrediton 1.8.0: No feedback when purchasing ticket with wrong password

### ISSUE THREAD

**Issue by DaanWillemsen** [decred/decrediton#3897]
Steps to reproduce:

1. Go to staking tab
2. Select a vsp and purchase a ticket
3. Submit a wrong password in the prompt. 
4. The prompt dissapears with no feedback that the password was wrong.

Earlier versions of Decredition did let me know whether the password is wrong.

**Comment by alexlyp** [comment]
Thanks for the report, will check this out.

**Comment by amass01** [comment]
@alexlyp did you have a look ? if not i can
