### ISSUE TITLE
Trezor fixes (bundle bridge + udev rules)

### ISSUE THREAD

**Issue by jzbz** [decred/decrediton#3901]
As of this moment Decrediton relies on the user manually installing the [Trezor Bridge](https://data.trezor.io/bridge/latest/index.html) software before they can use their device.

- Decrediton should make use of whatever mechanism Trezor Suite uses to access the device, which likely means bundling all the necessary tools for Trezor to just work without the user needing to hunt down additional tools.
- It should also prompt the user and offer to automatically install the [Trezor udev rules](https://data.trezor.io/udev/51-trezor.rules).
- We may want to take inspiration from how [Trezor solved this](https://github.com/trezor/trezor-suite/pull/4133) for Trezor Suite.

Relevant Matrix discussions:

https://matrix.to/#/!MYLcxlwzxwViTaFPGo:decred.org/$dqHvqW7IXOhrxvJzViTFboXncwvgpd7qEKli_Q6ZE3M?via=decred.org&via=matrix.org

https://matrix.to/#/!xUNvyzkFgiMjhvPbIi:decred.org/$IIiIaoprWFJa_wm1vrMzClLWTJMTbT8Ab7kAdYsuTPc?via=decred.org&via=matrix.org&via=t2bot.io

**Comment by JoeGruffins** [comment]
@jzbz 

Automatic application of the udev rules in problematic because it needs admin permissions to copy which is not great and does not work out of the box on some distros, like mine. Would instructions in case we suspect the udev rules to be missing be enough? More comments on #3950

**Comment by jzbz** [comment]
> @jzbz
> 
> Automatic application of the udev rules is problematic because it needs admin permissions to copy which is not great and does not work out of the box on some distros, like mine. Would instructions in case we suspect the udev rules to be missing be enough? More comments on #3950

Yes I think that's a fair compromise, prompt the user with the instructions on how to do it themselves if they seem missing.
