### ISSUE TITLE
Trezor: Webpack build broken on master.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/decrediton#3920]
master is currently 391d8a54e73b543eb8570705c0ff56d62aeca89c

A minor trezor-connect version bump moved a file that was needed by Trezor. @matheusd figured this out and here is the diff to make current master move the correct files, also from @matheusd : 

```
diff --git a/webpack/trezor.js b/webpack/trezor.js
index 3fa4713f5..fe0545e28 100644
--- a/webpack/trezor.js
+++ b/webpack/trezor.js
@@ -53,7 +53,8 @@ module.exports = {
 
         new CopyWebpackPlugin({
             patterns: [
-                { from: "./node_modules/trezor-connect/data", to: "data" }
+                { from: "./node_modules/trezor-connect/data", to: "data" },
+                { from: "./node_modules/@trezor/transport/messages.json", to: "data/messages" }
             ]
         }),
```

Staying on version 8 will however show this warning:
```
index.js:172 trezor-connect version 8 has been deprecated. Please start using @trezor/connect version 9 https://www.npmjs.com/package/@trezor/connect
```

 #3911 also closes this issue by bumping the version and placing the correct files in the correct place, albeit without webpack at the moment.

**Comment by matheusd** [comment]
I think we should go with the immediate fix right now, so that any new versions released support trezor again, then we can work on the proper v9 webpack magic.
