### ISSUE TITLE
Ledger: Broken on master.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/decrediton#3921]
master is currently 391d8a54e73b543eb8570705c0ff56d62aeca89c

Ledger needs WebUSB in order to work which is not supported by the current electron version. Please see the discussions in #3884

**Comment by JoeGruffins** [comment]
Can be closed by #3918

**Comment by xaur** [comment]
> Can be closed by #3918

WebUSB is announced in [Electron 23](https://www.electronjs.org/blog/electron-23-0). Neither the [blog](https://www.electronjs.org/blog/electron-22-0) nor the more detailed [release notes](https://releases.electronjs.org/releases/stable?version=23&page=13&limit=2) mention WebUSB for Electron 22. Maybe it was added but not announced until v23? If WebUSB works in v22, that release is notable for being the last to support Windows 7.

**Comment by JoeGruffins** [comment]
@xaur oh yeah I think you are correct. My mistake, we need 23+

**Comment by xaur** [comment]
Damn :) Ok we'll need to say Windows 7 is no longer supported too I think.

**Comment by JoeGruffins** [comment]
closed by #3928
