### ISSUE TITLE
Wallet splash page tutorial "Block Creation" still has placeholder text

### ISSUE THREAD

**Issue by exitus1** [decred/decrediton#3924]
![image](https://github.com/decred/decrediton/assets/46197055/3e416ffa-84af-41e4-a4bc-7d92428a6f92)

**Comment by xaur** [comment]
I think it was missed in #3881. Should be a one line fix:

https://github.com/decred/decrediton/blob/release-v1.8.1/app/components/views/GetStartedPage/WalletSelection/Form/Form.jsx#L305

Also it may be worth to deduplicate some of these lists of tutorials:

- https://github.com/decred/decrediton/blob/release-v1.8.1/app/components/views/SettingsPage/TutorialsTab/TutorialsTab.jsx#L44
- https://github.com/decred/decrediton/blob/release-v1.8.1/app/components/views/GetStartedPage/LoadingPage/LoadingPage.jsx#L22
- https://github.com/decred/decrediton/blob/release-v1.8.1/app/components/views/GetStartedPage/WalletSelection/Form/Form.jsx#L305
