### ISSUE TITLE
Chinese version is missing DEX Launcher

### ISSUE THREAD

**Issue by exitus1** [decred/decrediton#3936]
Poking through the translations I discovered this:

<img width="434" alt="chinese dex" src="https://github.com/decred/decrediton/assets/46197055/a0180932-e18a-4654-a3f9-011a373d987b">

![signal-2024-02-06-153742_002](https://github.com/decred/decrediton/assets/46197055/466f446c-77e9-4cf0-8947-b09e7a31018e)

**Comment by artikozel** [comment]
@DominicTing

**Comment by DominicTing** [comment]
I did not find these untranslated entries, please point out which line it is. Thanks.

**Comment by DominicTing** [comment]
[exitus1](https://github.com/exitus1) I did not find these untranslated entries, please point out which line it is. Thanks.

**Comment by DominicTing** [comment]
@exitus1 I did not find these untranslated entries, please point out which line it is. Thanks.

**Comment by exitus1** [comment]
I just retested it and the launcher is there now. Strange. Maybe DEX devs know why that could happen.

Sorry for the bother.

**Comment by DominicTing** [comment]
i see, it doesn't matter.
