### ISSUE TITLE
Decrediton AppImage does not run out of the box on Ubuntu 24.04.1 LTS

### ISSUE THREAD

**Issue by dev-warrior777** [decred/decrediton#3973]
```sh
dev@dev-Thin-15-B12UCX ~/decrediton $ ./decrediton-linux-amd64-v2.0.4.AppImage 
[102263:1019/020448.703653:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_decredEYmeC3/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

This is _after_ installing libfuse2
Info: 
- Ubuntu 24.04 cannot run AppImage out of the box. It needs libfuse**2** (libfuse3 installed by default and removing will break the system) [app image wiki](https://github.com/AppImage/AppImageKit/wiki/FUSE) 
- For 24.04.**1** I had no need to add the universe repository.

**Comment by dev-warrior777** [comment]
workaround

```sh
$ ./decrediton-linux-amd64-v2.0.4.AppImage --appimage-extract 
...
$ cd squashfs-root/
$ sudo chown root:root chrome-sandbox 
$ sudo chmod 4755 chrome-sandbox
$ ./decrediton
```

**Comment by jholdstock** [comment]
I get this too on 24.04. Seen it on a few decrediton releases, not just the latest. My workaround is to start with the `--no-sandbox` flag which allows it to run without having to extract.

**Comment by dev-warrior777** [comment]
That is a better workaround, thanks!

**Comment by dev-warrior777** [comment]
Since we have workarounds let's close this as documented, thanks.
