### ISSUE TITLE
Import of the Seed is not working

### ISSUE THREAD

**Issue by Dyrk** [decred/decrediton#40]
I've tried to import standard 33 words seed (without new lines: words and spaces only) of existing wallet and it failed. In the console, I see "Error: seed length must be between 128 and 512 bits" and, actually, the correct seed is printed in the console.

**Comment by alexlyp** [comment]
Yah it's looking for the seed hex.  Not the seed phrase.

But that being said, this is all still in a very raw state, so I wouldn't go around looking for issues until we release properly with 0.7.0 (12/20)

**Comment by jrick** [comment]
It's bytes, actually.  The client sends the binary data without any extra hex encoding (which was needed to efficiently encode it in JSON, but it's silly for protobufs).  At the moment there is no support for handling the seed mnemonic from the gRPC server, but we were thinking about adding a SeedService or similar that can handle those tasks.
