### ISSUE TITLE
I can't send from the office of the coin. the window restarts and has to do it all again.

### ISSUE THREAD

**Issue by anastasiia26** [decred/decrediton#403]
the window restarts and has to do it all again.

**Comment by jcvernaleo** [comment]
@anastasiia26 Not sure I understand what you mean.  Could you describe what you are doing a little better (and is this on osx or linux)?

Are you trying to use the send page to send decred to an address?

**Comment by jcvernaleo** [comment]
This almost sounds like #361 but I need a little more info to say for sure.

**Comment by jcvernaleo** [comment]
Since I never heard back after 3 weeks, I'm going to close this as a dup of #361.  If I'm wrong, feel free to reopen.
