### ISSUE TITLE
Enhancement proposal present a clear picture of you Tickets.

### ISSUE THREAD

**Issue by lbiazao** [decred/decrediton#419]
For the stand point of PoS users presente a clear picture of:
- What are the tickets I own, 
- How much did I pay for each of them
- How long they are in the mature state
- Presente the total value of the tickets
- Present the amount of Decreds I own.
- Present Graph of the investment and return monthly
- Present the average ticket fee for the last cycle, present a way to recommend the proper fee without needing to goo to the pool indication for taking this decision. Presente the expected return based on price and fee.

**Comment by alexlyp** [comment]
We will be working on adding this functionality over the next few weeks.

**Comment by alexlyp** [comment]
We have begun work on the ticket information page this issue is being considered in terms of how to parse that information.  More about that in the 2 following issues: 
#478  and https://github.com/decred/dcrwallet/issues/833
