### ISSUE TITLE
Bug to send a transaction

### ISSUE THREAD

**Issue by lbiazao** [decred/decrediton#420]
This weekend I have tried to send transation to another Wallet and something went wrong. Without any confirmation, I tried to reload the history by deleting data directory and downloading everything again:
The history shows I have 148 Decreds but I can't send them:
This is from my Decrediton wallet of Mac OS:
Present the error:
Error: -32603: orphan transaction 105028f7fe9762aa8265d5076328af77436cd19047b1c7bc003ef766fc1fb75a references outputs of unknown or fully-spent transaction 7c6feff866fcc352d9f4a27861ed5b1b252916f1e92cb64e055441d375ea33a8 Please try again

<img width="1177" alt="captura de tela 2017-06-03 as 22 26 46" src="https://cloud.githubusercontent.com/assets/5401274/26758138/fafca83c-48ab-11e7-8362-131fad5abeb9.png">

**Comment by lbiazao** [comment]
What's the matter with this error, i still can't send my Decreds to any other wallet.
The balance is reflecting a value I don't know if it's truth.

**Comment by lbiazao** [comment]
Following some help from Emilio Man I have recreated the wallet from the seed and the wallet started working properly again. Maybe the error is trying to create a transaction in the end of the PoS windows. Not sure what happened.

**Comment by alexlyp** [comment]
This is a dcrwallet bug, I will leave this issue open until we have confirmation that we no longer hit it elsewhere

**Comment by alexlyp** [comment]
This bug has been resolved in dcrwallet in 1.0.7 release
