### ISSUE TITLE
Validate v1.0.3

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#427]
Basic testing should be done on:

- [x] Linux
- [x] OSX

If possible, clean install, and upgrade.  Multiple linuxes are welcome.  Place comment with what you test.

**Comment by alexlyp** [comment]
Tested on Linux and everything looks good to go

**Comment by jolan** [comment]
Tested upgrade and clean install on Linux and encountered no issues either.

**Comment by jcvernaleo** [comment]
Clean install worked on OSX.  Going to test upgrade now.

**Comment by jcvernaleo** [comment]
Upgrade looks good too.
