### ISSUE TITLE
Creating a Wallet from an existing Seed on first launch does not work

### ISSUE THREAD

**Issue by consti** [decred/decrediton#431]
I'm using version 1.0.3 of decredition and try to import my existing seed.
I launch the app, enter the seed, enter a passphrase and verify the passphrase.
The `Create Wallet` button does not respond. I don't see anything in the console, nor in the logs.

* Version of the app: 1.0.3 
* OS: MacOS High Sierra (17A264c)

**Comment by jcvernaleo** [comment]
Just to be sure, are you clicking `Create Wallet` with the mouse or pressing enter?  Currently, you must click, enter doesn't work.

I just tested with decrediton 1.0.3 and OSX El Capitan and as long as I click the button all seems to work.

**Comment by alexlyp** [comment]
Was able to reproduce by causing the Confirm Seed box to error with a bad seed or something.  Click away then click back and fix the error.  Create Wallet button no longer works.

**Comment by consti** [comment]
Thanks! Sorry for the late feedback; totally forgot to get back.
👍
