### ISSUE TITLE
Cannot Open Detailed Transaction View in Overview Tab and Recent Transactions List

### ISSUE THREAD

**Issue by magnus-staberg** [decred/decrediton#434]
Clicking on transactions in History view opens a transaction detail view.
Nothing is opened when clicking on transactions in "Overview", recent transactions list.
When hoovering over transactions they are highlighted so both list seems to be clickable.

Decrediton 1.0.3 on latest Mac OS.

**Comment by alexlyp** [comment]
Yah it is intended not to be able to click on them on the overview, was debating about removing the hovering capabilities there to avoid this confusion.  I'll take a look at our options and report back
