### ISSUE TITLE
Detailed ticket transaction info view has misaligned components

### ISSUE THREAD

**Issue by magnus-staberg** [decred/decrediton#435]
See attached image
<img width="867" alt="transaction info" src="https://user-images.githubusercontent.com/921390/27101385-d8cdc772-5081-11e7-8b88-f5cc07139c2f.png">
"Received at" and "Properties" need to be replaced.

**Comment by alexlyp** [comment]
There are plans for a more detailed report of transaction information, I'll fix this issue when that stuff lands as well.
