### ISSUE TITLE
Mouse Cursor When Hovering over Buttons

### ISSUE THREAD

**Issue by magnus-staberg** [decred/decrediton#436]
When hovering over a button with text then the mouse cursor acts like it's hover over some text and not a button. 

The mouse cursor should look like
<img width="268" alt="screen shot 2017-06-13 at 21 56 07" src="https://user-images.githubusercontent.com/921390/27101725-2af8fbba-5083-11e7-8216-f8509369d173.png">
and not
<img width="102" alt="screen shot 2017-06-13 at 21 56 13" src="https://user-images.githubusercontent.com/921390/27101728-2c750204-5083-11e7-907f-6cb36efb9a7e.png">
when placed on a button, even when the button has text inside itself.

**Comment by alexlyp** [comment]
Gotcha, will fix.  Current OS i'm using doesn't change the cursor type so hard for me to see these issues.  Thanks for the report.
