### ISSUE TITLE
Wallet doesn't work on openSUSE fails with "Error: Failed to connect before the deadline Please try again"

### ISSUE THREAD

**Issue by WuCris** [decred/decrediton#437]
Decredition can't be opened on openSUSE. On every attempt it says "Error: Failed to connect before the deadline Please try again"

**Comment by jrick** [comment]
leap? tumbleweed?

**Comment by WuCris** [comment]
Leap 42.2

**Comment by jcvernaleo** [comment]
@WuCris could you try `ps aux | grep dcr*` after starting decrediton?  I tried SUSE in a VM and I see the same issue and it seems that dcrwallet just isn't starting up for me.  I have not seen that elsewhere but would like to confirm that it is the same thing you are hitting.

**Comment by WuCris** [comment]
`decrediton-1.0.3/resources/bin/dcrwallet` and `/home/chris/Downloads/decrediton-1.0.3/resources/bin/dcrd` show up when I run `ps aux | grep dcr*` there's no `dcrctl` process, not sure if that's something that should be running there or not.

If I use `dcrwallet` through the command line it works fine on openSUSE.

**Comment by jcvernaleo** [comment]
dcrctl should not be running.  That is just included as a convenience in case you ever need to directly interact with dcrd or dcrwallet.
Your issue might be a case of #402 which is a work in progress at the moment.

**Comment by WuCris** [comment]
I notice that when I run `ps aux | grep dcr* ` that it's starting `dcrd` with the fallowing command: 
`decrediton-1.0.3/resources/bin/dcrd --configfile=/home/chris/.config/decrediton/dcrd.conf --piperx=3` 

And dcrwallet with: `decrediton-1.0.3/resources/bin/dcrwallet --configfile=/home/chris/.config/decrediton/dcrwallet.conf --piperx=4`


If I run that command in terminal for `dcrd` it starts up perfectly fine. However if I run `dcrwallet` with that then it outputs the fallowing:

```
19:43:21.366 2017-06-15 [INF] DCRW: Version 1.0.3+release (Go version go1.8.3)
19:43:21.366 2017-06-15 [INF] DCRW: Generating TLS certificates...
19:43:21.383 2017-06-15 [INF] DCRW: Done generating TLS certificates
19:43:21.383 2017-06-15 [INF] DCRW: gRPC server listening on 127.0.0.1:9121
19:43:21.383 2017-06-15 [INF] RPCS: Listening on [::1]:9110
19:43:21.383 2017-06-15 [ERR] DCRW: Failed to read from pipe: read |4: transport endpoint is not connected
19:43:21.383 2017-06-15 [INF] DCRW: Shutdown requested.  Shutting down...
19:43:21.383 2017-06-15 [WRN] DCRW: Stopping legacy RPC server...
19:43:21.383 2017-06-15 [INF] RPCS: Listening on 127.0.0.1:9110
19:43:21.383 2017-06-15 [INF] DCRW: Legacy RPC server shutdown
19:43:21.383 2017-06-15 [WRN] DCRW: Stopping RPC server...
19:43:21.383 2017-06-15 [INF] DCRW: RPC server shutdown
19:43:21.383 2017-06-15 [INF] DCRW: Shutdown complete
```

The problem is `--piperx=4`. If I run it without ` --piperx` option it starts up without issue. It should be noted however that if I try several times in rapid succession that after a few tries it does start up properly with `--piperx=4`

**Comment by jcvernaleo** [comment]
That's interesting.  That pipe stuff was a shutdown mechanism we took from Paymetheus.  Unfortunately while it works great there, it never quite worked for us with the nodejs codebase.  Let me test if things work okay for me on suse if I just remove that stuff all together.

**Comment by jrick** [comment]
I'm surprised even the first dcrd command you tried works at all.  Those options require the fd to be both valid and inheritable by the forked process, which will not typically be the case when you are just running stuff interactively in the shell.

**Comment by jcvernaleo** [comment]
@jrick just tested on my Ubuntu box and `dcrd --testnet --piperx=3` runs fine.  `--piperx=4` however fails with `Failed to read from pipe: read |4: bad file descriptor`.

**Comment by jrick** [comment]
I bet `lsof -p $$` shows that you have an fd 3 open but not 4.  Should be coincidence that that succeeds at all.

**Comment by jcvernaleo** [comment]
Okay, so along with jrick's point, even if I completely remove the --pipe stuff I still can't get decrediton to start on suse.  Not sure what the actual problem is.

Interestingly, the electron dev tools don't really seem to work there for me either.

**Comment by WuCris** [comment]
After having updated to openSUSE 42.3 and having installed the latest version of Decredition the problem no longer persists. 42.2 will soon reach end of life status so nothing to worry about here. 

It should be noted that Decredition still doesn't appear to work on openSUSE as after it loads it presents and the wallet sync the interface changes to be an all white window. However this is likely an error unrelated to this issue and running it through terminal does not output any error. As such I've closed the issue.
