### ISSUE TITLE
Design implementation feedback

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#446]
Listed out the front-end that's not yet been implemented and few other fixes based on Version 1.0.3 (1.0.3). 

Front-end files, visual and interaction design references:
https://www.notion.so/eeter/Decredition-UI-UX-02-17-29901d48b7b54d6b97d090bfa8423740
https://www.notion.so/eeter/Decrediton-UI-UX-04-17-ca88d67833e24bc1a00779bfecabe98b

## 01. Opening launching views
- [x] **a)** The notification (error) dialog needs padding from top. Should appear on top of all other elements (if covering anything). Appropriate position and spacing for notifications can be seen at **/send.html**

- [x] **b)** Header section Title (Starting RPC and…) default positioning is a bit lower. (won't be covered by notifications then either).  (Also see nr. 10 at bottom of the list) 

- [x] **c)** Start RPC connection… – all the changing information should be displayed at the header section (e.g. below title). If this is an exception then let's align it horizontally left as the other elements are and add more leading between the text rows. 

- [ ] **d)** Nav section is missing the background color #09182d 

![01](https://user-images.githubusercontent.com/17774057/27244371-e58ae192-52ee-11e7-8419-4b09d51fe13c.png)

(Still need to check the wallet setup and creation views.)
**wallet-decrypt-loading.html
wallet-decrypt-public-data.html
wallet-decrypt.html
wallet-existing-seed.html
wallet-new-seed-input.html
wallet-new-seed.html**

## 02. Overview
Overall seems good, so leave this as last or lower priority.

- [x] **a)** Smaller bits:
- The smaller decimal spots should be even smaller in the all places. 
-  Some of the fonts look like they're in Light style, while should be Regular (this could be a render issue on my end as well). 
- Title (available balance) is vertically mispositioned. 
- The whole header section is slightly smaller in height (seems to be a case through-out the app)

**/overview.html**

- [x] **b)** First transaction displays an extra space below it. 

- [x] **c)** On hovering a transaction, it should be clickable and take the user to the transaction details view **(/overview-transaction-details.html)**

- [x] **d)** Will the search feature be added? The search values can be: 
- Transaction hash
- Date (numeral+text)
- Amount
**(/overview-search-activated.html)**

- [x] **e*)** I didn't include "Rescan" feature in the initial design. Listed it to be improved with a future update. Only thing i'd recommend atm is a minor update for how the "Rescanning the blockchain…" displays. Could it perhaps be as a notification dialog with a background color #8997a5 and only show it on hovering the Rescan button (see draft on right)?

![02](https://user-images.githubusercontent.com/17774057/27244392-f3fdd554-52ee-11e7-92d5-994b667aa113.png)

## 03. Accounts
- [x] Not yet implemented. 

A little extra idea was to use different color coding for wallets. There's a few examples under /images but depending how this is implemented let me know and I can provide more. 

**/accounts-add-new.html
/accounts.html**

![03](https://user-images.githubusercontent.com/17774057/27244406-04e8f1c8-52ef-11e7-8e16-78e9173bbd57.png)

## 04. Send
- [x] **a)** Header section, sub title uses wrong font. 

- [x] **b)** Content section not yet implemented. 
**/send.html**

![04](https://user-images.githubusercontent.com/17774057/27244434-2a605f68-52ef-11e7-83be-d3ced62a71f8.png)

## 05. Confirm send

- [x] **a)** (!!!) This one did not have a designed view, added to work list now. The current one has a critical UX issue as the password entry is optically lost. I drafted a temporary example using existing views, but feel free to update it however quicker. The password entry should have a top position in the hierarchy. Other data can be displayed on the card as it currently is, but update type style as on: **/overview-transaction-details.html**

- [x] **b)** No spacing between buttons.

![05](https://user-images.githubusercontent.com/17774057/27244440-30999a16-52ef-11e7-98e8-cc9525f7a3a2.png)

## 06. Send completed
- [x] Displays weird stuff – probably only should display a success notification (with relevant info).

![06](https://user-images.githubusercontent.com/17774057/27244447-36c41d94-52ef-11e7-9ff6-e84c7baaeaa1.png)

## 07. Receive
- [x] Not not yet implemented. 
**/recieve.html**

![07](https://user-images.githubusercontent.com/17774057/27244469-5348b7f4-52ef-11e7-9dc9-ab232f38db0a.png)

## 08. History
- [x] **a)** - The header section content (and size like in the other views) is wrong. 
- [x] **b)** Is there plans to add the account selection and option to display unspent outputs? If the unspent outputs stays out, i'll rework the view to accomodate Tx Types better.

- [x] **b and c)** I'm working on another way to display the votes – coming with next design update. But meanwhile to add a bit of clarity, perhaps the page selection can be displayed below the list and have TX Type take its position.

**/history.html**
**history-unspent-outputs.html**

![08](https://user-images.githubusercontent.com/17774057/27244490-673eec06-52ef-11e7-9720-9d5cb74d851e.png)

## 09. Tickets
- [x] Not yet implemented.
 If there's any questions regarding the interaction design, message on slack.

https://www.notion.so/eeter/Decrediton-UI-UX-04-17-ca88d67833e24bc1a00779bfecabe98b
/decrediton - tickets - v002/
tickets-voting-preferences-agenda-cards.html
tickets-voting-preferences-agenda-details.html
tickets-voting-purchase-automatic-section.html
tickets-voting-purchase-info-modal.html
tickets-voting-purchase-initial-view.html
tickets-voting-purchase-manage-pools-modal.html
tickets-voting-purchase-manual-and-automatic-settings-closed.html
tickets-voting-purchase-passphrase-modal.html
tickets-voting-purchase-stakepool-manual-entry.html**

![09](https://user-images.githubusercontent.com/17774057/27244493-6dcdf454-52ef-11e7-89a2-872ac287eae5.png)

## 10. Misc, throughout app
- [x] Header section has a lower height throughout the application (hence problems with notifications, etc)

![10](https://user-images.githubusercontent.com/17774057/27245011-e8961674-52f1-11e7-8f0b-27d72a4ebd70.png)

- [ ] Also throughout the app, upon focusing on a text field – a blue box appears around it. This can be removed.

<img width="368" alt="screen shot 2017-06-16 at 23 59 32" src="https://user-images.githubusercontent.com/17774057/27244659-35320b98-52f0-11e7-9e70-b64f3ffe3ff1.png">

**Comment by alexlyp** [comment]
@linnutee I've been able to update a lot of your notes here.  We will be releasing 1.0.5 tomorrow.  So feel free to drop any notes here

**Comment by alexlyp** [comment]
Receive, send and accounts page have mostly addressed the concerns you provided

**Comment by linnutee** [comment]
Nice! 

Few additional bits about Receive and Accounts views:

- [ ] Receive page: upon selecting the address, the account name also gets highlighted which may cause confusion for the users. Ideally the address area should be both clickable and selectable. When clicked on automatically copies the address to clipboard and provides a notification (e.g. how selecting a color works on http://decred.org/brand/). 
![receive](https://user-images.githubusercontent.com/17774057/27459502-3d38d558-57b7-11e7-9a4b-d115d08e0fca.png)

- [ ] Accounts page: on expanding the account information we should display the horizontal lines on the top and bottom. Those create the connection that the opened account is still part of the group, elsewise a sort of hard visual change takes place. Also would interacting with the account details be clearer if only one account at a time can be expanded? 
![accounts](https://user-images.githubusercontent.com/17774057/27459629-1187f32a-57b8-11e7-9f65-15ac452d467f.png)

**Comment by alexlyp** [comment]
Gotcha I'll address these soon.

**Comment by alexlyp** [comment]
The copy-to-clipboard needs to be rigged in, but totally doable.  If I do that should I disable user-select css everywhere?
