### ISSUE TITLE
Transaction fee per kB

### ISSUE THREAD

**Issue by magnus-staberg** [decred/decrediton#447]
Give a more explicit explanatory label to the transaction fee input. State that it's per kB.

**Comment by magnus-staberg** [comment]
Maybe a popover or something :)

**Comment by alexlyp** [comment]
Which area are you talking about?  the Confirm transaction page after sending?

**Comment by magnus-staberg** [comment]
When buying a ticket.

**Comment by alexlyp** [comment]
i see it pretty clearly as DCR/kB next to the field

**Comment by magnus-staberg** [comment]
You are correct. I guess it's been improved in latest design changes. Thanks for responding.
