### ISSUE TITLE
transaction not showing address accounts

### ISSUE THREAD

**Issue by bowsfixer** [decred/decrediton#448]
I tried sending some DCR (running OSX) from Wallet Decretion v. 1.0.3  The recipient still has not received the amount. It says confirmed and the amount in my wallet has decreased but the recipient has not received it.  I'm worried the amount has been sent to the wrong address ...

Is it normal to not see the accounts numbers next to the amount transaction ? 

I also have this error message at startup : 

Error: Connection to RPC server failed: dial tcp [::1]:9119: getsockopt: connection refused. You may need to edit /Users/XXmbp13/Library/Application Support/decrediton/config.json and try again

**Comment by alexlyp** [comment]
Do you have a transaction ID?

**Comment by alexlyp** [comment]
We are addressing the RPC connection error now, simply a race between dcrwallet and dcrd startup

**Comment by bowsfixer** [comment]
Transaction:0ce0b4434625aea267d63360e5bd7719858d64fb426544142c0d48b6150e9621

**Comment by alexlyp** [comment]
https://mainnet.decred.org/tx/0ce0b4434625aea267d63360e5bd7719858d64fb426544142c0d48b6150e9621

It's been long since confirmed. Dsf78mfFMr3B7Coz56QDbiQ1eWoe2gj1EVi received 90 and you got about 7.76 in change back.

**Comment by bowsfixer** [comment]
so i can be certain the 90 has been received by the other party , I need to solve this with them then!  Thank you for taking the times to answer me. good day to you
