### ISSUE TITLE
Allow for app settings to perpetuate after app close

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#45]
The rough idea is to have a app settings screen that would set certain values in a flat file or something that is loaded on start.

**Comment by jcvernaleo** [comment]
Just to fill in the info here, #58 does allow setting to persist across restarts so this issue is really about the setting screen to change the settings, not the persistent settings themselves.

**Comment by alexlyp** [comment]
So we have a branch from @dajohi that accomplishes this.  https://github.com/dajohi/decrediton/tree/dhill_settings
Though we have yet to add actual settings knobs.  We will close this issue and open another one for a future release that will add them
