### ISSUE TITLE
validate v1.0.5

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#455]
- [x] osx
- [x] linux

**Comment by jcvernaleo** [comment]
OSX seems good in clean install and upgrade (at least in terms of install, startup, and getting to the normal pages, did not do exhaustive functionality test).

**Comment by jcvernaleo** [comment]
Basic install/startup works for me on Ubuntu as well in clean and upgrade situations.  Going to do some more serious testing though.

**Comment by alexlyp** [comment]
OK on linux64 debian8

**Comment by jcvernaleo** [comment]
Looks like that's all the testing for this round so closing.
