### ISSUE TITLE
Option to delete accounts ?

### ISSUE THREAD

**Issue by pdlckr** [decred/decrediton#465]
I seem to have made one too many accounts, it would be great to see an option to delete an account with zero balance. 

I have also thought it would good to be able to transfer from one account to the other without having to grab the address for the other account and a section to see our voting rewards.

Thanks :)

**Comment by alexlyp** [comment]
deleting accounts is a simple for the front-end, but some care needs to be taken in the actual dcrwallet infrastructure.  Definitely interested to see what we could come up with to fix this issue.

And I like the idea of a simple transfer button as well.

**Comment by jrick** [comment]
I wouldn't implement deleting, but being able to hide accounts would be a worthwhile feature.

Accounts are deterministically created, so you can't really ever delete them, and you wouldn't necessarily want to create the same old account by accident when creating a new account.

**Comment by pdlckr** [comment]
Yeah can understand the difficulty as its tied to the actual wallet. Hide feature sounds cool though.
Thanks

**Comment by jcvernaleo** [comment]
What do people think hide should do in the case where the account has a balance?  Refuse to hide it (or not offer the option).  Hide it but leave balance in total?  Hide it but remove balance from total?
Also would we need a way to unhide a balance?  Or is it sufficient to say if you need to unhide, the restore from seed.

Finally, what happens if new funds are sent to a hidden account.

I do like the idea, but I want it thought through before we go coding something.  Opinions from any of you on those questions would be great.

**Comment by jrick** [comment]
I'd only hide it if it has a zero balance.  If anything more is received, it should be unhidden.

**Comment by pdlckr** [comment]
Agree with jrick, an optional tick box in settings could be implemented to automatically hide if there is zero balance. Show if balance arrives.

**Comment by linnutee** [comment]
Yes, the hiding feature is actually present in the current design, but not yet implemented. 
The interaction model is as following: a user can hide every account under the account details. When doing so, the account (and it's balance) is no longer displayed or accessible anywhere else (drop-down fields, quick balance section, etc) besides the Accounts page where it can be revealed.

Hide / reveal account:
https://giphy.com/gifs/l4FGFu3EKIgttskXm

**Comment by linnutee** [comment]
Regarding funds being sent to a hidden account, I think this needs to be worked out in Decreditons notification system (how new funds are displayed is another similar matter). 

I wouldn't recommend to force revealing an account but rather have the choice to either display notifications about hidden accounts or not.

**Comment by jcvernaleo** [comment]
I really do not like the idea of hiding an account with a balance in it (and then showing a balance that is no longer correct).  I think that will cause nothing but confusion.  @jrick's suggestion sounds significantly better for users than that.

**Comment by linnutee** [comment]
What about the case if the balance is extremely small? Or can an account even have a too low balance for emptying it out (e.g. not enough for transaction fee)?

**Comment by jcvernaleo** [comment]
I forget what the actual value is but we do have an `isDust` function is dcrd for values that are basically too low for anything.

**Comment by jrick** [comment]
There isn't a single constant.  the dust limit is a function of the output script size and the min relay fee.

https://godoc.org/github.com/decred/dcrwallet/wallet/txrules#IsDustAmount

**Comment by alexlyp** [comment]
Implemented
