### ISSUE TITLE
validate v1.0.6

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#474]
Normal testing should be done on v1.0.6
- [x] osx
- [x] linux

Please comment on linux version tested.

**Comment by jcvernaleo** [comment]
I did quick tests (fresh install/upgrade) on OSX and Ubuntu 16.04 and fresh install only (Fedora 25).  All seemed fine.  Did slightly more thorough testing on Ubnutu16.04 and that seems good too.

**Comment by alexlyp** [comment]
looks good to me
