### ISSUE TITLE
Can't Receive Crypto's (Invalid Address)

### ISSUE THREAD

**Issue by FrencisAlreadyInUse** [decred/decrediton#480]
I can't receive any coins on my decred wallet.

I tryed both sending from the coinbase app and webplatform. I got both 'Please enter a valid email or Bitcoin address'.

I both copied and scanned (qr-code) the generated address but failed every single time.

http://i66.tinypic.com/imuu53.jpg (Coinbase App, scanned the Generated Decred QR-code)

http://i64.tinypic.com/107q1a8.jpg (Coinbase Webplatform, copied the Decred Generated Address)

**Comment by jcvernaleo** [comment]
As @jrick said in your dcrwallet issue, those errors are correct.  Decrediton only works with decred (addresses start with a `D`).  You cannot send bitcoin to a decred address.  You can only send decred to one.  The coinbase app or webpage is for using bitcoin so you need to give it a bitcoin address which you get from a bitcoin wallet, not a decred one.

**Comment by FrencisAlreadyInUse** [comment]
Oké great, thanks you very much
