### ISSUE TITLE
Connecting to stakepool.eu from osx

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#492]
A user reported that they cannot connect to stakepool.eu with multiple versions of decrediton on osx.  Error is on the response, not a bad api key.

Can ping stakepool,eu and visit in browser.

@alexlyp and I have not been able to reproduce locally.

**Comment by alexlyp** [comment]
Appeared to be a local situation and the user was able to connect to another stakepool completely fine.  Closing
