### ISSUE TITLE
Can't find backup/seed option

### ISSUE THREAD

**Issue by thiago17** [decred/decrediton#508]
Hello, I want to backup my wallet by writing down the seed but I can't find the option to open and visualize it. Is that possible with decredition?
Also, I can't import my old wallets since I already started a new one. All I want is to have the option to: restore a wallet by seed and see the seed of the current loaded wallet.
Thanks in advance, decredition is great and all my previous issues I solved by reading here.

**Comment by jcvernaleo** [comment]
For security purposes, the seed is only shown when you first create a wallet and is not stored anywhere (and therefore cannot be shown).  All the decred wallets share this feature.  If you did not save the seed, you should create a new wallet, save the seed, and then transfer all funds to that wallet.

Decrediton only supports having a single wallet, so if you to create a new wallet, you must delete (or rename) the old files (which are in `~/.config/decrediton` on Linux and `~/Library/Application Support/decrediton` on OSX.

**Comment by thiago17** [comment]
Thank you!
