### ISSUE TITLE
Disable user-select on divs that have copy-to-clipboard

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#523]
Or instead of disabling, fix divs so they at least dont overflow on double click

**Comment by sndurkin** [comment]
@alexlyp Can you identify other divs with this issue? I will fix them and include them in PR #525.

**Comment by alexlyp** [comment]
from the looks of it, pretty much every div with text has this same issue.  so definitely not a small fix

we can audit and figure out the best course of action

**Comment by alexlyp** [comment]
done
