### ISSUE TITLE
I have problems with the replenishment of the purse DECRED

### ISSUE THREAD

**Issue by Pechakur** [decred/decrediton#529]

**Comment by sndurkin** [comment]
You can see the transaction is on the blockchain here: https://mainnet.decred.org/tx/56e97d7080cfdd263b816fedd9881b4f783c333114b0cfa36ccbb8d7c1c0eb41


Is your wallet fully synced? You won't see your funds in your wallet until the sync has reached the block that includes your transaction.

**Comment by Pechakur** [comment]
Thank you!

2017-07-31 20:52 GMT+08:00 Sean Durkin <notifications@github.com>:

**Comment by alexlyp** [comment]
wallet was not synced, closing
