### ISSUE TITLE
Cannot enter fractional (decimal point) amounts for sending

### ISSUE THREAD

**Issue by eboltz** [decred/decrediton#533]
Title says it. Want to send 0.57 DCR but decimal point won't register in send field.

**Comment by alexlyp** [comment]
Which version are you on? I believe that was fixed for 1.0.6

**Comment by eboltz** [comment]
1.0.5...downloaded and installed only a couple days ago it seems. Will DL the latest and retry, thanks!

**Comment by eboltz** [comment]
Confirm problem fixed in 1.0.6. Thanks again.
