### ISSUE TITLE
Prompt for wallet unlocking passphrase using native dialog rather than DOM

### ISSUE THREAD

**Issue by go1dfish** [decred/decrediton#558]
It is worth exploring prompting for passwords using native UI elements rather than the DOM to improve security.

dnldd on slack points out that this is a pattern other Electron apps such as Authy use.

Tradeoff is that the designers will have very little control over the password prompt.

Benefit is that the UX code won't have to consider passwords in memory and they will never touch the DOM at all other than the case of wallet creation and passphrase changing.

The tradeoffs are worth it for the case of unlocking the wallet for actions, but not for creation/changing passphrase.

**Comment by vctt94** [comment]
This has been done.
