### ISSUE TITLE
Address use

### ISSUE THREAD

**Issue by jcvernaleo** [decred/decrediton#57]
Currently, on startup decrediton gets a new address from the wallet.  That way when you go to the recieve page it already has an address ready.  That's nice, but if you do not go to the recieve page the next time you start up it will get an new address to have ready.  We can go through a lot of addresses this way.

Probably it should either not ask for an address until it needs it (as in you load the wallet page) or internally keep track of the last used address.

**Comment by jrick** [comment]
Deriving addresses should be very quick already, I don't think you need to optimize this by pregenerating any.

**Comment by alexlyp** [comment]
I think with jrick's updated address management (20 lookahead this is no longer an issue)
