### ISSUE TITLE
Decoupling requests on successful block connect

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#574]
By issuing requests when a new block notifiication hits, instances where wallet gets tons of new block connected notifications  (after a restart after a while or some other down time) and will lead to a lot of unnecessary requests being issued.

**Comment by Thoughtscript** [comment]
@alexlyp - I'd enjoy taking this ticket as well if that's OK. Thanks!

**Comment by Thoughtscript** [comment]
Am taking a look at this per our conversation! Thanks!

**Comment by alexlyp** [comment]
So this should be improved vastily with the new "synced" block pull from insight-api.  Wallet's should only be opened after that block is received by daemon.  Though this should still be looked into after that PR is merged.

**Comment by Thoughtscript** [comment]
@alexlyp - great thanks ... holding off just a bit since I know some major changes are forthcoming. Will dive in again after the PR.
