### ISSUE TITLE
Ticket buying fails without feedback if old api key in config data after generating new wallet

### ISSUE THREAD

**Issue by go1dfish** [decred/decrediton#580]
Steps to reproduce:

1.  Generate a testnet wallet
2. Sign up on testnet stakepool with wallet
3. Enter pool API token into decrediton
4. Close decrediton, wipe wallet.db
5. Create new testnet wallet
6. Attempt to buy ticket

(alternately putting the wrong api token in your config manually and trying to purchase a ticket will probably accomplish the same thing)

We need to show an error here, right now things just get stuck.

**Comment by alexlyp** [comment]
Right, ok so first it should fail properly instead of getting stuck.

But also I was going to add a config clear function when a new wallet.db is created to avoid old apikeys to be associated with the new wallet.

**Comment by alexlyp** [comment]
I believe this was fixed in #589
