### ISSUE TITLE
Clean up ticket buyer configuration fields

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#594]
- Make sure each field is checked for errors before entry and fix ways in which it currently works.
- Add text to make it clear what type of entry is expected (atoms, DCR, % etc)
- Add back in instructions for fields to explain what each does.

**Comment by go1dfish** [comment]
We want to add a generic DCR Input component for this.

Like how Balance works but for DCR inputs.

have it take 2 extra params, 1 for “required”

and 1 for “showErrors”

There are a lot of cases in the UI where we don’t want to show validation errors until some attempt is made

i.e. required fields shouldn’t show as an error until the person tried to submit a form, so the field could always validate and only show errors when showErrors is true

and the form would set showErrors true when an attempt had been made


It may make sense to make a similar component for non-dcr numeric inputs as well

**Comment by vctt94** [comment]
".Make sure each field is checked for errors before entry and fix ways in which it currently works."

Right now I am checking for errors on onChange and if it found any error, I change the state of the app/Components/PurchaseTickets/index.js. Would that work for making sure the field is checked? 

And By adding instructions for fields, you mean like a tooltip? 

Is this FeeInput I created for showing fees a good idea? Or should I let just the Decred and Numeric Inputs? 

Thanks
