### ISSUE TITLE
Add a transfer feature for easily moving DCR between accounts

### ISSUE THREAD

**Issue by sndurkin** [decred/decrediton#595]
We should add a feature that allows users to easily transfer DCR between accounts, without having to manually generate the address for the target account, copy and paste it into field on the Send page. We could either create a new Transfer page or (IMO the better option would be to) add this functionality into the existing Send page. Behind the scenes it would just generate a new address for the target account and proceed with the regular send funds flow.

**Comment by peterzen** [comment]
It would be a nice sub-feature to weave the `consolidate` call into this UI, perhaps through a **Send all** button or somesuch (like some online wallets and exchange UIs do).
