### ISSUE TITLE
Page Title "Ticket price:"

### ISSUE THREAD

**Issue by magnus-staberg** [decred/decrediton#610]
All pages except "Tickets" have a nice design of the title and the title is same as the text on the menu to the left, except the "Ticket" page. The menu button's title is "Tickets" but that page displayed's title is "Ticket price:".

Solution: The title of the page should be "Tickets" and the text "ticket price:" should be moved below the title.

<img width="745" alt="screen shot 2017-08-22 at 20 45 30" src="https://user-images.githubusercontent.com/921390/29603005-b8cf817a-87e2-11e7-85cf-d1e0b298b089.png">

**Comment by alexlyp** [comment]
This is going to be completely redone in an upcoming design overhaul.

**Comment by alexlyp** [comment]
Completed
