### ISSUE TITLE
Improve UI for Rescan button

### ISSUE THREAD

**Issue by mmquimby** [decred/decrediton#627]
Please add an "Are you sure?" with description of function, or something similar, to the Rescan button in the wallet.

I'm a new user and just waited overnight for blockchain to load up. Then I did a test transfer into the wallet. Waited a moment, and then saw this juicy button labeled "Rescan". I thought it might scan for current transactions so I clicked it. Horrified that it started full blockchain scan again. Wish it had warned me or been clearer. Even just renaming button "Rescan Entire Blockchain" would be an improvement, though overly long.

**Comment by alexlyp** [comment]
Well starting a new rescan isn't a horrible thing really, what are you worried about?

**Comment by mmquimby** [comment]
Even though the rescan only took 15 minutes, 

1. it was not what I wanted so it was a bad experience for me. I assumed that it was going to take hours like the first scan.

2. I believe I was unable to transfer funds out that had just arrived until after rescan had completed. Also not great.

Moreover, I'm not thrilled with the question you're asking. As an investor, I'd like to know that the UI team wants to listen to users and create delightful UI's. Your question doesn't have the empathy I'm looking for.

**Comment by sndurkin** [comment]
@mmquimby I agree the UX isn't great. To clarify, though, the button doesn't re-download the whole blockchain, it just rescans relevant transactions from the dcrd process, so the worst thing that will happen is it will use your CPU unnecessarily.

I think the best long-term fix for this is to add a way to abort the rescan and, ideally, some additional information on when to use it within the tooltip or some other contextual help. What do you think?

Adding an abort rescan feature isn't that easy so for now, I've changed the button text to "Rescan Blockchain" and added a better warning within the tooltip in #628.

![image](https://user-images.githubusercontent.com/1452379/29790360-98915630-8c07-11e7-90e6-920ce4ebfadf.png)

**Comment by mmquimby** [comment]
@sndurkin Great solution for now, thanks for super speedy implementation! Glad to know what it's doing. Would be slightly clearer to say "This scans the entire blockchain for transactions, but does not re-download the whole blockchain."

Longer term, ability to cancel would be very nice.

**Comment by sndurkin** [comment]
That's a good point, thanks, added in #629. If you have more UX recommendations, they are very welcome, but know that they may not be implemented as quickly!

**Comment by matheusd** [comment]
https://github.com/decred/dcrwallet/issues/939 implemented cancelable rescans on dcrwallet. This could be ported to Decrediton.
