### ISSUE TITLE
Change the success notification to be a snackbar

### ISSUE THREAD

**Issue by sndurkin** [decred/decrediton#632]
The success notification I'm referring to is the little green alert that pops up in the top-middle of the header with an X icon. It (and any other notifications) should be changed to be a self-dismissing snackbar.

We can also use this as an opportunity to rewrite the snackbar component from scratch instead of utilizing Material UI's snackbar, so that we can have more flexibility for customization.

**Comment by alexlyp** [comment]
I believe this was done for the success/error notifications on the Transactions page, but still needs to be done else where.

**Comment by Jascha-Sundaresan** [comment]
I can look into writing this from scratch using react-motion to get us off material UI's snackbar.
