### ISSUE TITLE
Change passphrase modal needs to clear values on cancel/attempt etc

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#637]

**Comment by matheusd** [comment]
See if #558 will be done (may make this irrelevant). Maybe do as part of #639.

**Comment by alexlyp** [comment]
Just confirmed that this is still broken.

**Comment by lustrousgorilla** [comment]
This issue doesn't have the `good first issue` label, but it seems pretty straightforward - I'd like to give it a shot.

**Comment by alexlyp** [comment]
This issue will be closed shortly with a PR I recently submitted.

**Comment by matheusd** [comment]
Fixed on #967
