### ISSUE TITLE
Move password prompting logic to app container or otherwise centralize

### ISSUE THREAD

**Issue by go1dfish** [decred/decrediton#639]
As I'm working in the tickets page and the rest of the app it occurs to me that we should manage the password prompting modal at the app level rather than for each individual page.

There are a few places where the logic of managing showing a password dialog and setting up a callback are duplicated.

We should be able to pass down a requestPassphrase function that accepts some parameters for display/labeling and a callback function to receive the passphrase.

Better yet we can probably expose it as a function that returns a promise that resolves with the password and rejects on user cancel.

**Comment by Jascha-Sundaresan** [comment]
I'll jump on this.
