### ISSUE TITLE
When receiving a payment and it is pending, it shows up in overview but not history.

### ISSUE THREAD

**Issue by jpz** [decred/decrediton#640]
I just received my first payment, I checked the history tab to see it, nothing was there.  Other parts of the application however reflected that a pending payment had arrived.

I would say it might be a small usability issue, but one for UX people if we have them to think about.  You can see in this example, I have a balance of 2.69 DCR, but no history of transactions.

![image](https://user-images.githubusercontent.com/934340/30070330-75c6ecf0-92a6-11e7-81f9-939403f3d27f.png)

**Comment by alexlyp** [comment]
Yah this has been noted from @go1dfish and @linnutee, we are currently refactoring various parts and this will be updated and fixed when the tx details/history has been changes a bit.

**Comment by jpz** [comment]
👍
