### ISSUE TITLE
Implement keylogger resistant passphrase entry UI

### ISSUE THREAD

**Issue by peterzen** [decred/decrediton#646]
In order to protect the user from keyloggers stealing their passphrase, implement a virtual keyboard in addition to the default input field.  By default, the input field should be active and the user should have the ability to select **I use an untrusted computer** to activate the virtual keyboard.

![image](https://user-images.githubusercontent.com/5878500/30178314-c472a5de-9408-11e7-8e57-73a1fdee5093.png)

The virtual keyboard might be implemented using [react-screen-keyboard](https://www.npmjs.com/package/react-screen-keyboard)

Related to #639

**Comment by alexlyp** [comment]
Great issue, should be totally doable

**Comment by alexlyp** [comment]
This was discussed thoroughly and we've determined that this will not protect users from vulnerabilities and may give some a false sense of security.
