### ISSUE TITLE
Decrediton breaks when trying to access the ticket screen

### ISSUE THREAD

**Issue by sndurkin** [decred/decrediton#653]
Steps I used to reproduce:

1. Build Decrediton using `npm run package`.
2. Launch `release/win-unpacked/Decrediton.exe`.
3. After Decrediton loads, click the Tickets menu item.

It throws a JS error and clicking elsewhere on the UI is now broken.

Here is my `config.json`:

    {
      "network": "mainnet",
      "wallet_port_testnet": "19121",
      "wallet_port": "9121",
      "cert_path": "",
      "daemon_port": "9109",
      "daemon_port_testnet": "19119",
      "daemon_cert_path": "",
      "daemon_rpc_host": "127.0.0.1",
      "daemon_rpc_host_testnet": "127.0.0.1",
      "wallet_rpc_host": "127.0.0.1",
      "rpc_user": "USER",
      "rpc_pass": "PASSWORD",
      "enableticketbuyer": "0",
      "balancetomaintain": "0",
      "maxfee": "0.1",
      "maxpricerelative": "1.25",
      "maxpriceabsolute": "0",
      "maxperblock": "5",
      "currency_display": "DCR",
      "hiddenaccounts": [],
      "stakepools": [
        {
          "Host": "https://ultrapool.eu",
          "Network": "mainnet",
          "APIVersionsSupported": [
            1,
            2
          ]
        },
        {
          "Host": "https://dcr.stakepool.net",
          "Network": "mainnet",
          "APIVersionsSupported": [
            1,
            2
          ]
        },
        {
          "Host": "https://stakepool.eu",
          "Network": "mainnet",
          "APIVersionsSupported": [
            1,
            2
          ]
        },
        {
          "Host": "https://stake.decredbrasil.com",
          "Network": "mainnet",
          "APIVersionsSupported": [
            1,
            2
          ]
        },
        {
          "Host": "https://pool.d3c.red",
          "Network": "mainnet",
          "APIVersionsSupported": [
            1,
            2
          ]
        },
        {
          "Host": "https://teststakepool.decred.org",
          "Network": "testnet",
          "APIVersionsSupported": [
            1,
            2
          ]
        },
        {
          "Host": "https://dcr.ubiqsmart.com",
          "Network": "mainnet",
          "APIVersionsSupported": [
            1,
            2
          ]
        },
        {
          "Host": "https://stakepool.dcrstats.com",
          "Network": "mainnet",
          "APIVersionsSupported": [
            1,
            2
          ]
        },
        {
          "Host": "https://dcr.stakeminer.com",
          "Network": "mainnet",
          "APIVersionsSupported": [
            1,
            2
          ]
        }
      ]
    }

**Comment by alexlyp** [comment]
This has been resolved by @go1dfish in #659
