### ISSUE TITLE
Electron window contents flicker when resizing

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#656]
All webcontents, menubar (and dev console) flicker when resizing the electron BrowserWindow.

Tried to upgrade to most recent version of electron but the issue remained.

**Comment by matheusd** [comment]
Confirming this is not solved by electron 1.7.6. Everything I've researched seems to point that this is a chrome/chromium/hardware bug.

https://github.com/electron/electron/issues/8127

https://github.com/electron/electron/issues/8127

https://bugs.chromium.org/p/chromium/issues/detail?id=606152
