### ISSUE TITLE
Different color scheme for testnet

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#666]
Having just the testnet under the logo may not be sufficient for people to realize they are using mainnet or testnet

**Comment by matheusd** [comment]
Thoughts on full background color replacement or just the sidebar itself? @linnutee?

Full background
![full background ](https://user-images.githubusercontent.com/1752493/30593415-d8cbdf34-9d20-11e7-8b0e-6c8b5ec746c6.png)

Just sidebar
![just sidebar](https://user-images.githubusercontent.com/1752493/30593417-d8f951c6-9d20-11e7-9572-66bb92f90119.png)

**Comment by alexlyp** [comment]
I think for the testnet difference we can just do a different sidebar color
