### ISSUE TITLE
Add features/design to About(version) popup window

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#669]
The first iteration of the About window currently just shows hard coded html to display the versions of the various software.  This should be done dynamically in 2 ways: 

1) Pull the version numer from package.json some how and then use that for decrediton versions.
2) Query dcrd and dcrwallet --version to get actual binary version and use there.

We should also try and spruce up the design.

**Comment by alexlyp** [comment]
Version numbers are now properly pulled, Still would like someone to spruce up the design a little bit.

**Comment by alexlyp** [comment]
I believe everything we want is currently available in the design, but I'll bump this to the future milestone since this is completely acceptable for release.  I'll wait until @linutee has a chance to do a mockup.

**Comment by matheusd** [comment]
Done via #1528
