### ISSUE TITLE
Give an alert when trying to ctrl+v the seed

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#673]
Just an idea I had (leaving here for future research/debate). If the app detects a ctrl+v (clipboard paste) attempt when entering the seed, notify the user why that is not allowed, with a link for further explanation.

**Comment by alexlyp** [comment]
Yah seems like a great idea to add something like this.  Should be pretty easy to add once we add overarching keyboard event capturing.  I believe it would be relatively simple to add this when we get the proper fix for #635

**Comment by peterzen** [comment]
I haven't followed the discussion on this closely, so the question may be naive – but how does this improve the user's security?  I mean, if the seed is on the clipboard then the damage is already done  and disabling the paste function doesn't really solve anything.  The education aspect is understandable but it seems more productive to prevent the seed from being **copied onto** the clipboard when it's displayed.

**Comment by matheusd** [comment]
Nothing can prevent the seed being stolen if the computer is already compromised during wallet creation. 

This is meant to protect against seed **loss** by a first time user that just copies & pastes the seed without knowing the consequences of the loss. Which is especially important in decrediton which doesn't have a way to show the seed again after creation.

If this issue is addressed (on ctrl+v display a message informing **why** you can't/shouldn't paste) then at the end of this message we could add a box to the effect of: "type 'I understand the risks' if you really want to paste" and allow the paste to proceed if the user so chooses.

**Comment by vctt94** [comment]
What warning message can it be?
