### ISSUE TITLE
Inform users about initial blockchain sync

### ISSUE THREAD

**Issue by jholdstock** [decred/decrediton#675]
When Decrediton is opened on a PC with an already sync'd blockchain in `~/,drcd` the UI displays a loading screen while it waits for `dcrd` RPC to become ready. The loading screen states "Preparing background process". 

This screen could explain to the user what is going on and why things may take a long time. It may also be useful to know if Decrediton can be killed safely during this loading screen.

**Comment by alexlyp** [comment]
That already is the case. 

What is happening is that your daemon is taking a while for the RPC to become ready.  You have not yet even started downloading the chain.

**Comment by alexlyp** [comment]
But sure I will add a small note that this may take a bit depending on power of computer etc.

**Comment by jholdstock** [comment]
I've updated the issue in light of the conversation on slack.

My particular case was loading an already downloaded chain out of `~/.dcrd` and not an initial blockchain download
