### ISSUE TITLE
Show voting info on ticket details

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#683]
Similar to the online block explorer, show details on what were the agenda choices of the vote and what was the ticket the vote originated from.

**Comment by alexlyp** [comment]
https://github.com/decred/insight-api/blob/master/lib/Rpc.js#L73-L80

Here are the pertinent lines that we added to insight to parse the vote choices with help from @davecgh

**Comment by matheusd** [comment]
Ok, that put me on the right track but there is a problem. dcrwallet gRPC currently returns only the outputs of the wallet's owner, not all outputs which filters the information of the vote.

Offending block is this: https://github.com/decred/dcrwallet/blob/master/wallet/notifications.go#L142-L158

Don't know what is the rationale for that or if modifying it will break something else...

**Comment by matheusd** [comment]
Just to expand upon last answer, possible alternatives to fix it:

- Append to the outputs the other txOuts that are not credits
- Return all txOut on a different attribute of TransactionSummary
- Add a new gRPC call to the voting details of a given transaction
- Decode and return the voting information as a new attribute of TransactionSummary

@alexlyp, what do you think?

**Comment by matheusd** [comment]
This can now be closed as well
