### ISSUE TITLE
White blank screen Windows 10 - dev environment.

### ISSUE THREAD

**Issue by rjmacarthy** [decred/decrediton#685]
Hey, Ive tried to run Decrediton `npm run dev` on a windows environment.  But once rpc connection is established the electron window just throws a blank white screen.  Anyone else experienced the same thing?  I'm yet to try it on my linux env to see if the same thing happens.

No errors in the console either.  The chrome dev tools does crash, but I tried disabling that in the code but still crashing.

![image](https://user-images.githubusercontent.com/5537428/30691235-0a3df1e8-9ebf-11e7-9c63-c9cc35835f8e.png)

![image](https://user-images.githubusercontent.com/5537428/30691269-20690c14-9ebf-11e7-8467-1eee961431b0.png)

Any help appreciated.

Thanks.

**Comment by lukebp** [comment]
I ran into a slightly different issue when first trying to get decrediton to run in dev mode.  Here are some of the steps I took to get everything running properly:
- make sure that you are using node v6.9.5
- make sure that you have up-to-date binaries for dcrd, dcrctl, and dcrwallet in `app/bin/`
- delete the node_modules folders and re-install (one is located in the root directory of the project and one is located in `app/`)

**Comment by alexlyp** [comment]
This has been fixed in master and was related to a build issue of grpc on windows.

**Comment by rjmacarthy** [comment]
Cool will give it another shot.  Thanks guys.
