### ISSUE TITLE
Errors about duplicated Keys sometimes when showing All tx in history

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#689]
Also can occuring on overview.  Unclear what the cause is, but appears 2 different txs are being given the same tx.Hash possibly which makes it so they won't be show, this results in irregularties with pagination and other things.

**Comment by alexlyp** [comment]
Appears to be a possible race or corner case, sometimes hitting the error, sometimes now on load.

Looks like somehow duplicate txHashes are being added to the transactions list.

**Comment by matheusd** [comment]
We could add a "smoke test" to detect and filter duplicate transactions in the meantime, but that's not an elegant solution...
