### ISSUE TITLE
Disabled buttons still work

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#709]
Clicking any disabled buttons still make them call the onClick() handler. 

I'll fix this together with issue #706.

**Comment by linnutee** [comment]
Similar case with Send button, i'll just mention it here. 
- Send is currently visually disabled until information is entered and user clicks elsewhere (e.g. outside amount field). 
- Instead it should change to enabled state once the information is entered (w/o having to click elsewhere).

**Comment by Thoughtscript** [comment]
I believe this ticket got closed per: https://github.com/decred/decrediton/pull/710/commits/6fcecb9f8aeb63be0c8715758b7b9cab8c5f4a1f
