### ISSUE TITLE
Cannot add a second stakepool

### ISSUE THREAD

**Issue by girino** [decred/decrediton#715]
After having added my first stakepool, when trying to add a second one, the button "add stakepool" does not work.

Steps to reproduce:
1- register to any stakepool and add it.
2- go to the "Configured Stake Pools:" and click on "add stakepool" button.

expected: screen for adding the API key should open.
What happens: nothing.

Edit: Version 1.1.0 (1.1.0), on OSX (Sierra v. 10.12.6)

**Comment by matheusd** [comment]
Fixed by #721

**Comment by jolan** [comment]
Closed via #721.
