### ISSUE TITLE
Cannot start decrediton twice

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#727]
Bug report from user willywoo on slack. Running two instances of decrediton thrown an error due to already running daemons. It should report a better error.

Maybe it can be worked with #723.

**Comment by alexlyp** [comment]
Yah I'm hoping to start work on proper daemon selection and fall back in situations like this.

**Comment by matheusd** [comment]
WIP for this and #723 
https://github.com/decred/decrediton/compare/master...matheusd:startup-improvements?expand=1

Still missing an edge case when decrediton is closed while dcrd hasn't finished loading yet.
