### ISSUE TITLE
Dropdowns for type selection restyling

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#730]
Update all dropdowns for various type selection to match designers prototype.

**Comment by matheusd** [comment]
See also PR #728 and issue #663.

**Comment by linnutee** [comment]
<img width="876" alt="screen shot 2017-10-04 at 17 39 43" src="https://user-images.githubusercontent.com/17774057/31181932-368011a2-a92b-11e7-94ec-2369143bcd17.png">

I've called it Context Menu - Eye Filter, to make it a bit clearer as there's different dropdowns. 

This one like the pagination also goes to History and My Tickets views.
[decrediton ui v012 - transactions and history - history](https://xd.adobe.com/view/5ca79364-9459-4017-b0b1-7e26f90059fd/)
[decrediton ui v01 - tickets - my tickets](https://xd.adobe.com/view/7707b586-62f0-4c93-afaf-1c5b9432b8eb/screen/97287f68-fc56-4c15-a903-f60a29722595/My-Tickets-2)

See [UI components](https://xd.adobe.com/view/82325302-2eb8-4684-9b46-7ef1bc6b227a/ ) and specs: [UI components specs 031017.pdf](https://github.com/decred/decrediton/files/1356155/UI.components.specs.031017.pdf)
Icons: [decrediton - context button - eye.zip](https://github.com/decred/decrediton/files/1356184/decrediton.-.context.button.-.eye.zip)

-------------------------------------------------
Past releases and references: https://www.notion.so/eeter/Decrediton-UI-knowledge-base-5cc97bc87cc74e80bb4ef42e996fab2d

**Comment by matheusd** [comment]
Preview.
![eye-context-menu mp4](https://user-images.githubusercontent.com/1752493/31246991-93537418-a9e5-11e7-9412-e7c3ca6bd1aa.gif)

**Comment by alexlyp** [comment]
looks really good, just looks like font sizing and should be gtg

**Comment by matheusd** [comment]
I believe I applied all relevant styles as specified in the docs, but it looks a bit off (the shadow of the menu seems a bit too light, doesn't seem to give enough distinction from the background).

I could return to the shadow from the gif (it's a different one). That one seems to leave the menu more visible.

@linnutee Remarks?

![screenshot_2017-10-06_08-36-20](https://user-images.githubusercontent.com/1752493/31276443-3659a84e-aa72-11e7-9b53-8549744be40b.png)

**Comment by linnutee** [comment]
Overall looks great! Only bit missing is the dialogs small arrow:

<img width="644" alt="screen shot 2017-10-12 at 02 38 50" src="https://user-images.githubusercontent.com/17774057/31472297-8a48a95e-aef6-11e7-89b0-762dcbf73b88.png">


Don't mind the shadows getting a bit harder, so for example:
```
Y: 3 px
Blur: 8 px
Alpha: 21% #000000
```
