### ISSUE TITLE
Dropdowns for account selection restyling

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#731]
Update css to match designer's suggested style.

**Comment by matheusd** [comment]
See also PR #728 and issue #663.

**Comment by alexlyp** [comment]
Sorry I should have been more explicit.  The @linnutee has come up with some new designs for various current assets.  This is a placeholder issue for that work.  I'll try and link with images to be more clear.

**Comment by linnutee** [comment]
<img width="873" alt="screen shot 2017-10-04 at 18 00 56" src="https://user-images.githubusercontent.com/17774057/31182986-fe2624ba-a92d-11e7-9741-dcedc8c60172.png">

[UI components](https://xd.adobe.com/view/82325302-2eb8-4684-9b46-7ef1bc6b227a/ ) and specs: [UI components specs 031017.pdf](https://github.com/decred/decrediton/files/1356155/UI.components.specs.031017.pdf)

Ok i've gathered the different fields and dropdowns together and fine tuned them a little bit. 
These are based on the initial release assets, the updates are primarily in small details of how each states interactions works – what gets highlighted etc.

Summary:
- Default states should either include a description of content for normal fields or
 type of amount (if it's DCR, DCR/Kb, Blocks, Tickets…). 
- On hover there's a color change to slightly darker 
- On activation/click the stroke changes to blue in most cases and in dropdowns the dropdown field includes a blue stroke in the bottom of it. Text color remains the same `#0c1e3e` as on hover.
- After entering the data, the stroke color changes back to "default" and text color remains the same `#0c1e3e`.
- Inactive/disabled = greyed out. 

Here is the previous version from February 2017, just for a reference.
[decrediton - v004 - 0217.zip](https://github.com/decred/decrediton/files/1356274/decrediton.-.v004.-.0217.zip)

-------------------------------------------------
Past releases and references: https://www.notion.so/eeter/Decrediton-UI-knowledge-base-5cc97bc87cc74e80bb4ef42e996fab2d

**Comment by matheusd** [comment]
Preview for new select and accounts select styles. 

@linnutee, could you please double check if the colors look right? I'm having a bit of trouble following some of the specs (eg: on the latest answer you mentioned the text color as #0c1e3e but on the specs, text color is specified as #091440 in the input, #dadfe2 in the select items; stroke on the select items is listed as #596d81 but that seems a bit dark on my end, etc).

![accounts-select mp4](https://user-images.githubusercontent.com/1752493/31341611-69414eae-ace0-11e7-835f-a5d2926c0fd1.gif)

**Comment by linnutee** [comment]
It's a bit hard to tell from the gif but they look about right. 

Two notices though: 
- The text field dropdowns should have square corners when opened (keep the corners only for the context menu - eye filter) 
- Then accounts dropdown should have account name in default state as #0C1E3E.

Most likely needs to be the same with the basic dropdowns also. I'm now realizing most of them have a selection made already … but if there isn't anything selected from a dropdown it can have the lighter #C4CBD2 same as text fields.

<img width="836" alt="screen shot 2017-10-12 at 02 48 52" src="https://user-images.githubusercontent.com/17774057/31472560-1d8077fa-aef8-11e7-91ec-2f5e983d52a0.png">

**Comment by alexlyp** [comment]
Added in #772
