### ISSUE TITLE
Implement the new header sub menu design

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#733]
This will be used on the (new) Transactions page and the Tickets page.

**Comment by linnutee** [comment]
![dcr - secondary navigation](https://user-images.githubusercontent.com/17774057/31184631-9df81d3c-a932-11e7-88fe-7222bd70b8a1.gif)

Motion design specs:
- Hover state:
130 ms to change the text color/opacity from `#929eac` to `#0d1f3f`

- Pressed
Starting from press, roller moves in X to position under new item - 210 ms
Starting from press, roller scales in width to match with new item size  – 130 ms

Use a quart-type In and Out easing curve.  

Visual design specs:
<img width="822" alt="screen shot 2017-10-04 at 18 07 57" src="https://user-images.githubusercontent.com/17774057/31183349-fbc47680-a92e-11e7-8433-444d857c7a84.png">

**Comment by alexlyp** [comment]
After discussion with @matheusd and @go1dfish a few ideas to include in this issue:

via @matheusd: 
 >Instead of each view defining its own `<Sidear />` and `<Header />`, have a container define `<Sidebar>` and a child view. The child view could be either a `<TabbedChild tabs=[{headerProps=..., content=...}]>` or `<SingleChild headerProps=... content=... >`. `<TabbedChild>` defines the header and content in such a way as to sync them (when changing between tabs the content is appropriately synced).>

Things to do:
- refactor the send/receive into the transactions page, creating a new header and the tabs but still maintaining all other pages the same way they are
- also when doing this we should move to routes for tabs and avoid the component state stuff we are doing for the tickets tabs

**Comment by go1dfish** [comment]
This container component should also handle the if !walletService ErrorPage logic that is duplicated everywhere as well.

**Comment by matheusd** [comment]
Preview.
![tabs mp4](https://user-images.githubusercontent.com/1752493/31445301-24aa1bb4-ae74-11e7-81e5-b9a557b0505f.gif)
