### ISSUE TITLE
Update send all styling

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#734]
Update to use an icon and also refine the look and feel for when it is in "send all" mode.

**Comment by matheusd** [comment]
@linnutee do you have an icon for the send all button?

**Comment by linnutee** [comment]
Not yet, taking this and a few other issues on tomorrow + thu.

**Comment by linnutee** [comment]
Preview:https://xd.adobe.com/view/5ca79364-9459-4017-b0b1-7e26f90059fd/screen/02b7aeb3-2ba4-47e0-9ad4-39edae81af1a/Send-

Icon 20px
[send-all.svg.zip](https://github.com/decred/decrediton/files/1380854/send-all.svg.zip)

**Comment by alexlyp** [comment]
Fixes in #772
