### ISSUE TITLE
Statistics page mockup

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#736]
First pass can include stubbed in data, mostly to choose an appropriate graphing package and get the rough idea for design implementation.

**Comment by linnutee** [comment]
<img width="947" alt="screen shot 2017-10-07 at 01 24 07" src="https://user-images.githubusercontent.com/17774057/31300773-43e6062e-aafe-11e7-9aec-b2b9504343db.png">

[Statistics - specs 041017.pdf](https://github.com/decred/decrediton/files/1364046/Statistics.-.specs.041017.pdf)


[Visual design preview here, slides 6-8](https://xd.adobe.com/view/7707b586-62f0-4c93-afaf-1c5b9432b8eb/screen/eabc4f54-628f-413b-b28d-563557eb0476/Custom-Size-6)

As an initial mockup, the statistics view could include only the "Pool" data group (currently under Purchase Tickets). Keep in mind that there will be more data included and most likely the data groups will go through a period of changes when we get more user input.

The construction of the Statistics view is done in a grouped manner. Each group includes a relevant graph and it's data + a controller if needed. [See wireframes for more details.](https://xd.adobe.com/view/7036661c-7a51-47eb-b79e-3f3125b323c5/)
There will be a need for different [types of graphs](http://datavizproject.com), so keep that in mind when picking a library or developing those.

For the first pass, other data groups aren't included. Instead i've left a placeholder with inactive buttons and the "More coming soon!" copy. Sort of a positive notification that this is being worked on.

**Comment by alexlyp** [comment]
Closing in favor of new updated issues.
