### ISSUE TITLE
Block explorer & decrediton confirmations mismatch

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#739]
Open any transaction detail on decrediton and on the block explorer. Decrediton shows one less confirmation than the block explorer.

Also as soon as it is first accepted, a transaction is shown with indicator "confirmed" but 0 confirmations (in decrediton) and as unconfirmed in the block explorer.

**Comment by alexlyp** [comment]
I would consider this moreso an issue with insight/block explorer rather than dcrwallet/decrediton.   

But yah I believe there is an off-by-1 issue with confirmations still in dcrwallet
