### ISSUE TITLE
How do I start all over again?

### ISSUE THREAD

**Issue by thiago17** [decred/decrediton#747]
I'm using decrediton on linux for a while and I want to get rid of my actual wallet and restore a new one that was created on the webwallet service. I already have the seed saved with me.
Which file does I need to delete and start all over again?

**Comment by alexlyp** [comment]
on linux that file is located at ~/.config/decrediton/mainnet/wallet.db  

delete or rename that file and you will be asked to create a new wallet on the next start of decrediton.

**Comment by thiago17** [comment]
Thanks, it worked.
