### ISSUE TITLE
Use default dcrd.conf

### ISSUE THREAD

**Issue by jrick** [decred/decrediton#749]
Currently decrediton is starting dcrd with a dcrd.conf that it writes.  This does not give users any opportunity to make changes to their dcrd settings that aren't exposed by decrediton (such as the datadir to change the location of the blockchain data).

Paymetheus handled this nicely and I think decrediton will be able to do the same.  In Paymetheus, the launcher application would still start dcrd with nonstandard options, but it would do so using the command line arguments instead of using a config file.  This allowed users to modify the config file, and any flags passed by the launcher would override the user's settings if they conflicted.  Otherwise the user's settings were used.

**Comment by alexlyp** [comment]
So after playing a few different options I settled on, this PR https://github.com/decred/decrediton/pull/752

While I think it mostly fixes our issues, it unfortunately doesn't resolve back and forth to testnet with just a change to config.json

I'm open to other suggested to make the configuration handling as smooth as possible while also not using rpcuser/pass as a commandline arg (which can be seen by `ps`)
