### ISSUE TITLE
Link fields/pages to docs for extended help

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#764]
Idea for discussion: link pages/fields/tooltip/whatever to docs for extended help (possibily to the translated version if available).

Ideally in the docs we could have links to explanation videos.

This is placeholder issue to discuss this and document how it will be done.

**Comment by alexlyp** [comment]
I think once we finish the incoming design changes we can start to have a concrete discussion about help/docs usage.  @linnutee has previously introduced a Stakey helper that will pop up from time to time in areas that users finds particularly confusing. I feel that this idea melded with links to docs could be a good final direction.

**Comment by vctt94** [comment]
done
