### ISSUE TITLE
Button/form streamlining

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#765]
As @oktapodia pointed out in his PR #740 the current buttons are simply `<div>` with onClick handlers.

From the looks of it, it would be a benefit to instead use `<button>` for this purpose, which has the onSubmit handler.  But this may also require doing a full refactor re-introducing `<form>` and using the associated package `redux-form`  

I'm open to discussion and input on ways to easily make the switchover

**Comment by mcdanielU** [comment]
Hello, have you used redux-form ?
