### ISSUE TITLE
Styling of the revoke notification on the HomePage

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#767]
With the newly added feature of the revoke notification on the home page we need to add proper styling for it.  This should include a check for revoke tickets request attempt being true/false to show a loading/feedback fot the user.

**Comment by alexlyp** [comment]
Please do not attempt this issue without explicit input from @linnutee or @sander

**Comment by Jascha-Sundaresan** [comment]
@linnutee, can you chime in here w/ some input?
