### ISSUE TITLE
No error given when dcrwallet version is not appropriate

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#769]
There is a dcrwallet rpc version check on start up to ensure that the expected built api.proto is being used on a valid verison of dcrwallet bin.  When the error is tripped you can see `VERSION_NOT_VALID` on the console, but decrediton just sits at the Check Wallet Loading screen.

**Comment by matheusd** [comment]
Preview of the layout and message.

![screenshot_2017-10-18_13-58-10](https://user-images.githubusercontent.com/1752493/31729141-eebcaa32-b40c-11e7-9423-d7b8cb434b62.png)

**Comment by alexlyp** [comment]
I like it,  Should be enough for anyone running dev to understand the issue
