### ISSUE TITLE
Integrating Votetime in Ticket Overview Tab

### ISSUE THREAD

**Issue by karamble** [decred/decrediton#773]
Would be nice to see the average votetime on the details section of the ticket tab.

Chappjc`s solution for this can be found here:
https://github.com/chappjc/votetime

**Comment by alexlyp** [comment]
We're adding a new grpc command that will be returning information about tickets,  this will lead to a My Tickets page in the very near future.  With that we should be able to calculate this information as well.

**Comment by matheusd** [comment]
Discussion happening in #901
