### ISSUE TITLE
Send to self/others styling

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#776]
<img width="826" alt="screen shot 2017-10-13 at 01 24 00" src="https://user-images.githubusercontent.com/17774057/31522207-594d39fe-afb5-11e7-905a-28a2fd5655fc.png">

<img width="828" alt="screen shot 2017-10-13 at 01 24 33" src="https://user-images.githubusercontent.com/17774057/31522214-5efb36da-afb5-11e7-9e4f-44d13c75813f.png">

Sending to self or others can have an icon toggle. Upon clicking, changes "To:" field to account dropdown and changes icon to send-to-others.svg. When clicking again, changes back to default send view.  

[send-to icons.zip](https://github.com/decred/decrediton/files/1380871/send-to.icons.zip)

**Comment by alexlyp** [comment]
I merged this proposal's implementation from @matheusd and it appears to be working as requested here.  

Though I'm reopening the issue after discussing shortly with @behindtext.  He mentioned that the icons themselves look good, but they would be totally unclear what they do without the additional tooltip hover. 

@linnutee I think we should revisit this in the near future to figure out a more inuitive way to switch between the different modes.
