### ISSUE TITLE
Update input fields styling

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#777]
<img width="873" alt="screen shot 2017-10-13 at 01 32 00" src="https://user-images.githubusercontent.com/17774057/31522431-6d5087ca-afb6-11e7-8168-9e641cf78e10.png">

Just about the same thing as for dropdowns: https://xd.adobe.com/view/82325302-2eb8-4684-9b46-7ef1bc6b227a/

[UI components specs v002.pdf](https://github.com/decred/decrediton/files/1380915/UI.components.specs.v002.pdf)

Since last version I've updated the default states type color to `#C4CBD2`
- Input field A = most basic field with normal bodycopy … e.g destination address, account names, passwords etc. 
- Input field B = large numbers + type size script, this is used for displaying Amounts in DCR. The full numbers and two first decimal spots are with a larger typeface (19px), while all following decimal spots are with smaller (13px). 
- Input field C = has only large numbers, no sizing script. (Not sure atm if this may become obsolete or not, but I included it just in case)
- Input field D = small numbers.

**Comment by matheusd** [comment]
This is being partly worked on #763
