### ISSUE TITLE
Feature Request: Additonal filter type in "History" page.

### ISSUE THREAD

**Issue by gravityz3r0** [decred/decrediton#785]
Would like to request an extension to the current filters, namely "Regular" transaction. This filter should allow user to choose a range of value of the said transactions. For example, I want to be able to see only transactions between 100-200 DCR. 

This is important because as it is, the regular transactions includes a lot of micro transactions involving very small fees and is really not very useful to user end most of the time.

Alternatively, create an extra option to "hide" these micro transactions instead.

**Comment by vctt94** [comment]
can I get this one?
