### ISSUE TITLE
Cant paste in inputs

### ISSUE THREAD

**Issue by go1dfish** [decred/decrediton#794]
On master I am unable to paste into inputs, if I highlight text and paste the highlighted text is removed.

This is happening on macOS High Sierra decred master

**Comment by alexlyp** [comment]
Strange, this could be related to general oddities we've had reported in macOS pasting.  (ie mangling highlight copy/paste for private pass creation and usage later)

How are you pasting?  it seems to work on linux highlight middle clicking, highlight ctl-v, and ctl-c/ctl-v

**Comment by Jascha-Sundaresan** [comment]
@go1dfish can you list the steps to reproduce this bug?

**Comment by Jascha-Sundaresan** [comment]
I can't reproduce this on OSX El Capitan

**Comment by go1dfish** [comment]
The issue appears to happen when launching Decrediton from tmux as also experienced by this user here:

https://github.com/electron/electron/issues/9352#issuecomment-304317313

Closing this for now, and I'll run the app outside of tmux when I need to paste.
