### ISSUE TITLE
Update headers styling

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#797]
Preview: https://xd.adobe.com/view/c09a14cb-4f5d-42fe-9226-a453cb0cbd80/
Icons: [decrediton - header icons - 171017.zip](https://github.com/decred/decrediton/files/1389141/decrediton.-.header.icons.-.171017.zip)

Typesetting and colors on the headers and bodycopy needs to be gone over through-out. Included specs below.

**Overview**
- Update font size for the balance numbers (current one is smaller)
- Update Rescan button position, aligned with the type baseline (32px from bottom)
- Rename button to "Rescan"

**Transactions**
- Add icon
- (?) As far as I remember the last decision was to include History under Transactions? If that's not the case I will also add a History icon here. @alexlyp can you verify? 

**Tickets**
- Add icon
- Re-align/add current ticket price to left. 

**Accounts**
- Add icon
- Add bodycopy

**Security Center**
- Add icon
- Add submenu
- Optional: write a relevant copy to wrap up the function of the page.* 

**Settings**
- Add icon

**Help**
- Add icon
- Add bodycopy

<img width="746" alt="screen shot 2017-10-17 at 00 47 27" src="https://user-images.githubusercontent.com/17774057/31636849-d55ec392-b2d4-11e7-8975-9cfc75830c6e.png">
<img width="880" alt="screen shot 2017-10-17 at 00 22 40" src="https://user-images.githubusercontent.com/17774057/31636850-d57f0b7a-b2d4-11e7-8b05-4b6987154867.png">
<img width="664" alt="screen shot 2017-10-17 at 00 51 07" src="https://user-images.githubusercontent.com/17774057/31636974-51824d22-b2d5-11e7-83f4-871772a0ac9e.png">

**Comment by Jascha-Sundaresan** [comment]
I can jump on this and do it as soon as @sndurkin and @oktapodia sign off on the toolset I'd use to do it in #786

**Comment by Jascha-Sundaresan** [comment]
how do we want the ticket price to look?  like the balance on the overview page or the balance on the history tab?

**Comment by Jascha-Sundaresan** [comment]
also, do we want the ticket price visible on all 4 tabs or just the purchase tickets one?
