### ISSUE TITLE
Update main navigation motion design

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#798]
![decrediton - motion - navigation](https://user-images.githubusercontent.com/17774057/31638925-c6a7245c-b2de-11e7-9c65-08cdbe778424.gif)

Motion design specs:
Hover state on text: 
- Change the text color/opacity from `#c4cbd2` to` #ffffff`(Quart InOut) -> 130 ms

Unhover: 
- Same thing in reverse

Clicked:
- Selection rectangle moves in Y to new position below pressed item -> 210 ms (Expo InOut)
- Text color on previous item changes back to `#c4cbd2` -> 130 ms (Quart InOut)

**Comment by alexlyp** [comment]
Nice looks great.

**Comment by Jascha-Sundaresan** [comment]
I'll look into this.

**Comment by Jascha-Sundaresan** [comment]
I think this issue can be closed now
