### ISSUE TITLE
grpc node_module causing build errs in webpack (or watchify)

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#8]
When attempting to:
`import grpc from 'grpc'` 
in any file in app/ webpack is not able to properly build it and gives crazy parsing errors. 

This may have something to do with webpack config setup or package.json settings.

**Comment by alexlyp** [comment]
So we've successfully been able to import grpc with the current README.md instructions. 

I'll leave this issue open until we've confirmed that we can properly package/build/release the app

**Comment by jcvernaleo** [comment]
@alexlyp npm run package works fine for me on linux and macOS.  I can even run the packages it builds (don't know if they work, but that would be another issue).

So is this issue still valid or can we close it?

**Comment by alexlyp** [comment]
Yah closing now
