### ISSUE TITLE
Switch to encapsulating styles at the component level.

### ISSUE THREAD

**Issue by Jascha-Sundaresan** [decred/decrediton#802]
I propose some consistent design implementation standards that make translating design's work into clean functional code an easy and consistent practice.

Steps: 

1) get a pdf from design w/ a clear image and all spacing explicitly measured in px values.
Get *names* of colors, based on the color palate in the style guide. Do NOT get literal color values.
For components w/ multiple states, get colors, background colors and box shadows for each (hover, disabled, active, active&hover, error, etc.)

2) style *one* component at a time. Style rules that are reused may be imported from elsewhere (or supporting libraries like styled-system). Style rules that are not reused are on the same page as the component export. Rules are always written as either a style object or a function that accepts a single argument of props and returns a style object.

All components have padding to measure _inside_ spacing and margins for _outside_ spacing.

All components should *only* have padding defined in the component export. Margin definitions are to be left to the developer _consuming_ the component and placing it in a view.

All style values to be customized in the consumption of a component are to be exposed as properties of the component, like margin or width.

Responsive values are passed to properties as arrays of values according to breakpoints set in a theme.

Eg:

```
import React from "react";
import PropTypes from "prop-types";
import cxs from "cxs/component";
import { px } from "fp";

const primaryColors = ({ theme: { colors }}) => (
  { backgroundColor: colors.buttonPrimary,
    ":hover": { backgroundColor: colors.buttonPrimaryHover },
    ":active": { backgroundColor: colors.buttonPrimaryActive }
  }
);

const secondaryColors = ({ theme: { colors }}) => (
  { backgroundColor: colors.buttonSecondary,
    ":hover": { backgroundColor: colors.buttonSecondaryHover }
  }
);

const canBeSecondary = props => props.secondary ? secondaryColors(props) : primaryColors(props);

const Button = cxs(({ children, ...props }) => (
  <Text is="button" px={ 20 } py={ 15 } align="center" fontWeight="heavy" f={ 13 } color="white" { ...props }>
    { children }
  </Text>
))(({ theme: { shadows, colors, radii }}) => ({
  cursor: "pointer",
  boxShadow: shadows["button"],
  border: "1px solid transparent",
  borderRadius: px(radii["button"]),
  transition: "all 100ms cubic-bezier(0.86, 0, 0.07, 1) 0s",
  ":active": {
    boxShadow: shadows["buttonPressed"]
  },
  ":disabled": {
    cursor: "default",
    color: colors["disabled"],
    backgroundColor: colors["lightGrey"]
  }
}), canBeSecondary);

Button.propTypes = { secondary: PropTypes.bool };
```

This button is then consumed like so:
```
<Button ml="auto" mb={ -15 } >
 <T id="button.message" m="click me" />
</Button>
```

This allows developers to consume react components and place them in a view to pixel perfect spec as per design's request, while staying idiomatic to react, only working w/ the components' props.

It also allows for quick and easy thematic changes to components. in one centralized place allowing us to spot inconsistencies or irregularities faster.

```
colors: {
    tooltip:              "#337AB7", // these colors need names!
    iconBase:             "#8795A2",
    iconActive:           "#2970FF",
    buttonPrimary:        colors.blue,
    buttonPrimaryHover:   "#1b8ff",
    buttonPrimaryActive:  "#0025cc",
    buttonSecondary:      "#8997a5",
    buttonSecondaryHover: colors.darkGrey,
    messageBannerSuccess: colors.green,
    messageBannerError:   colors.orange,
  },
```

**Comment by Jascha-Sundaresan** [comment]
At a glance, this allows me easily see we're missing a color definition for buttonSecondaryActive, and our buttons don't have unique values for when they're disabled. This is something I can then turn around and confirm w/ design is intentional.

Unsurprisingly, most of the time, it isn't.

**Comment by Jascha-Sundaresan** [comment]
this allows us to clean up our layout components and have expressive jsx markup.
eg
```
    <Box bg="white" px={80}>
      <Heading><T id="accounts.title" m="Accounts" /></Heading>
      <MessageBanner justify="center" />
      <Button ml="auto" mb={ -15 } onClick={ toggleShowAddAccount }>
        <T id="accounts.addNewButton" m="Add New" />
      </Button>
    </Box>
```

**Comment by Jascha-Sundaresan** [comment]
doing something like this requires only changing the components at the view level, no styling rules need to be written at all

<img width="707" alt="screen shot 2017-10-17 at 11 55 41" src="https://user-images.githubusercontent.com/8117045/31689150-6142bc60-b343-11e7-865c-b72b2e223974.png">

It can be done as
```
<Box px={ 60 } py={ 45 }>
  <Icon i="accounts" s={ 30 } mr={ 10 } />
  <Heading><T id="accounts.title" m="Accounts" /></Heading>
  <Flex align="flex-end" justify="space-apart">
    <Text><T id="accounts.subtitle" m="Accounts allow you to keep separate..." /></Text>
    <Button mb={ -15 } />
  </Flex>
</Box>
```

**Comment by Jascha-Sundaresan** [comment]
If you wanted to abstract and reuse the header logic in every view, you can now simply do
```
<Header
  icon="accounts"
  heading="accounts.title"
  text="accounts.subtitle"
/>
```

**Comment by Jascha-Sundaresan** [comment]
here's the generalized header:

```
import React from "react";
import { FormattedMessage as T } from "react-intl";
import {
  Box,
  Button,
  Flex,
  Heading,
  Icon,
  MessageBanner,
  SubHeading,
} from "shared";

const PageHeader = ({ page }) => {
  const title = page + ".title";
  const subtitle = page + ".subtitle";
  const button = page + ".button";
  return (
    <Box px={ 60 } py={ 45 }>
      <MessageBanner justify="center" />
      <Flex align="center">
        <Icon i={ page } s={ 30 } mr={ 10 } />
        <Heading mb={ 14 }><T id={ title } /></Heading>
      </Flex>
      <Flex ml={ 40 } align="flex-end" justify="space-between">
        <SubHeading><T id={ subtitle } /></SubHeading>
        <Button mb={ -15 }>
          <T id= { button } />
        </Button>
      </Flex>
    </Box>
  );
};

export default PageHeader;

```

**Comment by vctt94** [comment]
Are we going further with this discussion? 

Now that most design has been done at stylesheets file, I am not sure the benefits of refactoring all of them in order to add them to the components itself.

**Comment by vctt94** [comment]
Closing this issue because of #2439
