### ISSUE TITLE
Invalid prop `getNextAccountError` of type `string` supplied to `AccountsList`, expected `object`.

### ISSUE THREAD

**Issue by Jascha-Sundaresan** [decred/decrediton#803]
the property that's currently being passed into the message banner is being checked by "prop-types" to be an object.

at app/index.js the initial state values are inconsistently labeled `null` and `""`

Are response errors and successes always strings?

**Comment by alexlyp** [comment]
Successes are always constructed as strings.   Errors are objects that have toString handlers iirc
