### ISSUE TITLE
Remove Skip Sync button

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#812]
Due to incoming changes to wallet we need to ensure that the connected dcrd is fully synced before doing address discovery in wallet.  This means we need to remove the skip sync button until a more graceful flow is developed that could possibly delay the address discovery request until synced, but still allow the user to proceed to get addresses etc.

**Comment by jrick** [comment]
You won't be able to get addresses, because they would be always derived by the old coin type.  If that was a seed restored wallet with activity on the new coin type, the wallet will never upgrade to the new coin type because addresses derived by the old coin type were returned.

**Comment by Jascha-Sundaresan** [comment]
>a more graceful flow

Maybe having the sync progress bar over to the right in the sidebar over where the balance is ...and on the accounts overview page when on it?

We could disable some of the menubar items. maybe navigate to the page, but the whole page-view is blurred and unclickable w/ an overlay that says "wait until sync finished"

that would make sense on virtually every page except receive/settings/about and then have a full sized progress on the home page if they choose to navigate there just to watch the progress.

**Comment by alexlyp** [comment]
I should have been more clear with what I was referring to in terms of a graceful flow.  But essentially decrediton issues a series of requests to dcrwallet (loader actions essentially).  The issue here is we can't request certain commands until we know the daemon is synced (ie address discovery on wallets from existing seeds.

So not really a UI issue rather UX.  I'll open another issue that discusses these hurdles and we can think about fixes after release.
