### ISSUE TITLE
Remove voting screen from requiring API Key entry to be shown

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#814]
Currently the voting/governance view requires that users have entered at least 1 apikey for the contents to be accessible.  But this page should be shown to any user regardless of stakepool usage.  

So the page should always be accessible and then only the vote choice toggling should be disabled for the user.

**Comment by Jascha-Sundaresan** [comment]
How do you use Decrediton to vote without a stakepool?

**Comment by alexlyp** [comment]
You can't.  This is merely for users to be able to see what the votes are and to see the benefits of purchasing tickets.
