### ISSUE TITLE
Pagination refactor/rewrite for GetTransactions/GetTickets

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#815]
Currently the GetTransactions and GetTickets are requested on start-up for the entire set of transactions and tickets.  This is obviously not ideal, though it appears that it still runs without much noticeable slowdown on large wallets we should be requesting the transactions on a page by page basis.  

With the current method of providing start/end block for GetTransactions/TicketsRequests it's not trivial to just ask for page M of N.  I'd like to open up discussion here about possible ways to fix this and implement an elegant pagination solution.

**Comment by jrick** [comment]
FYI, the wallet will need some work done to incrementally return these transactions in a stream before this change makes sense in the client.  Currently all of these transactions are being loaded at once before being streamed to the client.

**Comment by matheusd** [comment]
The work jrick mentioned is referenced in this issue:

https://github.com/decred/dcrwallet/issues/768
