### ISSUE TITLE
Passphrase modal on send page chopped 

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#829]
After refactoring in #820, passphrase modal on send confirmation for sign/publish is not shown properly.

**Comment by Jascha-Sundaresan** [comment]
I'll take care of this.

**Comment by Jascha-Sundaresan** [comment]
Please check #828 I believe this is already fixed by that. If further styling adjustments need to be made, please let me know.

![image](https://user-images.githubusercontent.com/8117045/31914597-265e8838-b800-11e7-92ad-bdc14c6c7f04.png)
