### ISSUE TITLE
Implement "Settings" view visual design

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#835]
https://xd.adobe.com/view/15b5fb9d-ebde-4efc-919c-61dba3706e8c/
Visual design + specs

Input fields: #777

[changepasswordDefault.svg.zip](https://github.com/decred/decrediton/files/1412308/changepasswordDefault.svg.zip)

**Comment by sndurkin** [comment]
@linnutee wrong link, this is of the Security Center tab
