### ISSUE TITLE
Implement "Security Center" view visual design

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#836]
https://xd.adobe.com/view/982858aa-7fbf-45d6-a55c-75d3abca5a56/
Visual design + specs

Ignore the header example on #797, this should just have a Description there. 
@alexlyp will provide the copy text, currently as "Lorem ipsum…" placeholder. 

Input fields: #777

**Comment by alexlyp** [comment]
@linnutee do you have the lock+eye header icon?  can't find it in existing impls

**Comment by linnutee** [comment]
Yep it's in #797 header icons zip:
https://github.com/decred/decrediton/files/1389141/decrediton.-.header.icons.-.171017.zip
