### ISSUE TITLE
Implement "Sorting" to Transaction History

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#854]
<img width="777" alt="screen shot 2017-11-04 at 23 29 56" src="https://user-images.githubusercontent.com/17774057/32409640-26f1f412-c1b8-11e7-81f0-c6fad431b918.png">

Preview: https://xd.adobe.com/view/2f6756f6-5479-40af-9db3-9202d5029d36/

This applies for the Transaction History view. Don't think there's much point adding it to My Tickets also?

Sorting button uses the same "Context Menu" as seen in #730 for Display filter (see specs there also). 
- On hover it should display tooltip with message "Sort by". 
- Allows to sort **visible transactions** by "Newest", "Oldest", "Smallest Amount", "Largest Amount". 

Also if needed update the Display filter: 
- On hover displays tooltip with message "Show"
- Allows users to show: "All", "Received", "Sent", "Invalid (yes/no @alexlyp?)"

This partially addresses #785 – but I would not add that complex amount selector feature atm. That should be addressed together with adding a proper Search function, which will should go hand-in-hand with filtering/sorting + possibly needs these to be re-worked also.

Icon: [sort-by.svg.zip](https://github.com/decred/decrediton/files/1442867/sort-by.svg.zip)

**Comment by matheusd** [comment]
FYI, with the changes planned in https://github.com/decred/decrediton/issues/815 decrediton will no longer maintain the full transaction history in memory, so the sorting options "Smallest Amount" and "Largest Amount" won't be immediately available without work on dcrwallet.
