### ISSUE TITLE
Can't Download Decredition Wallet

### ISSUE THREAD

**Issue by JCCoins99** [decred/decrediton#857]
Hi!
I've been trying to download the Decredition Wallet on my MacBook Pro and have been having issues. The first thing that happens, which I'm not sure if is a bug - but after I put in my seed info and click to put in my passcode the seed disappears. Then after I type in my passwords the button I'm supposed to press to continue is greyed out and won't activate. 

I've tried just about everything. 

Would love some help!
Jenny

**Comment by alexlyp** [comment]
When you enter the seed make sure you are pressing Enter or Tab on each selected word, you should see each seed word entered have a little box around it and an X to the left.  And as you properly enter words you will see the "Word remaining" count decrement until 0.

**Comment by JCCoins99** [comment]
Amazing. Thanks so much!!
