### ISSUE TITLE
White Screen of Death

### ISSUE THREAD

**Issue by timmychuk** [decred/decrediton#859]
Mac OS High Sierra 10.13.1

Open Wallet and get a white screen evertime and have to force quit.

**Comment by alexlyp** [comment]
what version/commit are you running?

**Comment by timmychuk** [comment]
The new version 1.1.1

Thanks

Sent from my iPhone

On Nov 7, 2017, at 6:22 AM, Alex Yocom-Piatt <notifications@github.com<mailto:notifications@github.com>> wrote:


what version/commit are you running?

**Comment by alexlyp** [comment]
very strange. 

so to confirm, you see the window open, the background processing etc, then on "Open Wallet" it goes white and there is nothing shown?

**Comment by timmychuk** [comment]
When i launch the decred application instead of the blue interface with wallet i get a totally white screen that freezes. There is sometimes an error message about contracting support.

**Comment by alexlyp** [comment]
what does the error message say?  can you confirm that you dcrd or dcrwallet are not still running in the background.  Appears on macOS that they have periodic issues shutting down.

**Comment by taoteh1221** [comment]
@timmychuk Try --ignore-gpu-blacklist in your startup command. @alexlyp if you just enabled webgl on the latest releases, and a user's machine uses xorg graphics drivers (instead of proprietary graphics drivers) they may get a white screen. Me and quite a few others had similar issues in Meteor on Ethereum's Mist Wallet. I have no clue what MacOS runs for video drivers by default though, I'm an Ubuntu guy.

**Comment by alexlyp** [comment]
don't believe we have ever touched webgl, maybe some electron dep does, but afaik it shouldn't be an issue.

**Comment by timmychuk** [comment]
@alexlyp pretty sure it was the periodic issue of shutting down that triggered the wallet to lock up.

**Comment by alexlyp** [comment]
how are you shutting down decrediton?  are you clicking the icon in the dock and quitting?  i received a similar report to this and trying to gather information about ways to reproduce.  thanks

**Comment by dnldd** [comment]
can confirm this issue on OSX, dcrwallet and dcrd processes don't get killed sometimes when closing decrediton. Manually killing these processes and restarting decrediton does the trick.

**Comment by caseyhelbling** [comment]
I can confirm this issue as well. I killed all the processes and can get it to start back up. 
![2017-11-21 at 1 43 pm](https://user-images.githubusercontent.com/12005/33225203-bdea0f3c-d138-11e7-8fc7-4eede0d8c897.png) This is the error message you receive...

**Comment by timmychuk** [comment]
Yes this is the screen i get if it doesn't turn white and completely freeze

**Comment by Boid-John** [comment]
I have this issue as well. UI is just blank white, have to force quit the app. Sometimes I open it and it works, sometimes I get the above error message. OSX High Sierra 10.13.1

**Comment by alexlyp** [comment]
How are you all shutting down the app?  There appears to be an issue with closing dcrd and dcrwallet in the background if you don't shut down the app cleanly.

**Comment by alexlyp** [comment]
Ok I'lve been able to reproduce this issue by right clicking decrediton in the docker and Quit.  

It appears to shut down cleanly if you always use the red X in the upper left.

If you do hit this error just make sure you kill any running dcrd processes in the background and restart decrediton

**Comment by jrick** [comment]
Sounds like we have shutdown logic attached to the window closed events, but not the application shutdown event.
