### ISSUE TITLE
Use DecodeMessageService to decode transaction details

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#870]
Currently we just use what wallet has provided us to render the transaction details page.  Now we can get the full transaction information decoded on demand to show all the information about a given transaction.

**Comment by matheusd** [comment]
Other than showing all inputs and outputs (not just the ones from the wallet) and the vote choices, what else do we need to show on the transactions page that is currently not shown?

**Comment by alexlyp** [comment]
Hmmm i think that's it.  Should be able to show all the input/output tx fields then that should do it.
