### ISSUE TITLE
Want to delete my wallet and start over.

### ISSUE THREAD

**Issue by JCCoins99** [decred/decrediton#873]
How can delete my wallet? I need to start over.

Thanks!
Jenny

**Comment by JCCoins99** [comment]
To clarify. I need to completely uninstall my decrediton wallet and start over with a new seed sequence.

**Comment by matheusd** [comment]
Hello,

Here is the documentation on how to deleting a wallet. After deleting the wallet file, the next time you run decrediton you will be asked for a seed. If you go ahead with the deletion, **MAKE SURE YOU HAVE THE SEED FOR THE OLD WALLET**, as you won't be able to restore it without it. 

If you want to be extra safe, first rename the old wallet file (to something like `wallet.old`), recreate the wallet, then if everything checks out delete the old wallet file.

https://docs.decred.org/advanced/deleting-your-wallet/
