### ISSUE TITLE
Detect & allow user to change language on first run after install

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#880]
User should be able to select the desired language after install, the first time Decrediton is run (before starting wallet creation). 

Ideally, the app should detect the OS language and suggest that, but allow the user to change. After the first run, the user can change the language in the settings page.

**Comment by alexlyp** [comment]
Yah that's a great idea, I'm thinking we can do this while the blockchain is downloading?  I'm trying to think of other initial startup settings/options we could add during blockchain download, maybe timezone setting?

**Comment by matheusd** [comment]
I guess timezone could be relevant (to see all timestamps in utc/local timezone/custom timezone). I'll try to think of additional options.

Maybe instead of cherry picking which configs to show, we could show the config page (or all relevant options in the config page that don't depend on having the wallet created).
