### ISSUE TITLE
Sidebar menu selected does not change if route switched from Tickets Page

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#882]
If switch route clicking in accounts on Purchase tickets area, the content shows Account Page, but the sidebar menu still Tickets as selected.

**Comment by alexlyp** [comment]
@Jascha-Sundaresan I'd like you to investigate this for when you return.  Basically clicking the "Accounts" button next to the account selection dropdowns doesn't properly trigger the Motion in the SideBar.  Looks like it'll be non-trivial to get this to work correctly.  And tbh if it's not a relatively easy fix I'm willing to just nuke the Accounts buttons altogether

**Comment by Jascha-Sundaresan** [comment]
ack
