### ISSUE TITLE
Create Wallet button not working

### ISSUE THREAD

**Issue by H4ck3d0ff** [decred/decrediton#883]
Hi, brand new here. Trying to setup a wallet as started mining today but the 'Create Wallet' button is greyed out despite confirming the seed and adding a wallet encryption passphrase.

Am i missing something?

Thanks!

**Comment by H4ck3d0ff** [comment]
Ok i missed the fact i couldn't copy/paste and had to type individual words manually...

**Comment by alexlyp** [comment]
In the upcoming release have added an alert/error when a user attempts to Ctrl-V into that area. 

Overall this is our way to enforce good seed handling procedures for people to slow down and take an extra 5 mins to properly secure their wallets.
