### ISSUE TITLE
Research and choose charting package 

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#900]
I'd like to open up discussion for choosing a React based charting package that will be used with the upcoming statistics page.

I'd like whatever we land on to be a relatively widely used package with recent updates.  

After a brief search, https://github.com/recharts/recharts looks to be a very strong candidate

**Comment by linnutee** [comment]
Afaik Sander preferred using d3 ones in the web context. From first glance these got a plenty of different chart types to cover most or all of the statistics items. 

Main questions:
- How easily are these customisable? (visual and motion side)
- What would be the main issues or limitations when implementing these into the statistics views, based on the last wireframes: https://xd.adobe.com/view/7036661c-7a51-47eb-b79e-3f3125b323c5/

**Comment by lustrousgorilla** [comment]
I had a really good experience using https://github.com/FormidableLabs/victory-chart for a client's app.

**Comment by vctt94** [comment]
related #1063

**Comment by alexlyp** [comment]
we settled on recharts
