### ISSUE TITLE
Staking account to replace auto-buyer

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#906]
As first discussed by @go1dfish here: https://github.com/decred/decrediton/issues/588

We'd like to implement staking accounts to further simplify the automatic ticketbuying process.  

This is the general way it would work: On wallet creation the user would be asked if they would like to use a staking account to this wallet.  By enabling this feature and specifying which account they want to use, ticketbuyer would be automatically enabled on every startup and the balance to maintain would be 0 for that account.  This account would not be listed in the normal dropdowns for spending.  It will be able to be seen in the accounts page, but can't be hidden or renamed.

To fund the staking account, we would use a similar send transaction from account to account, but there would only be the staking account selectable.  

To withdrawal from the staking account, first thing would be to set the balance to maintain absolute to the requested amount to withdrawal.  To smooth out this process, I think we should do "pending" withdrawals  which become finalizable once those funds are spendable.  We could probably use the config to "save" pending withdrawal amounts, then those could be checked against the staking account spendable balance on startup.  

And for this mode I'd like to fully remove any of the autobuyer config settings.  They all don't really have any strong use now that the sdiff algo has been changed.  So if you want to buy a ticket and you have enough to purchase a ticket.  Feel free to drop any input about this feature here.

**Comment by go1dfish** [comment]
> And for this mode I'd like to fully remove any of the autobuyer config settings. They all don't really have any strong use now that the sdiff algo has been changed. So if you want to buy a ticket and you have enough to purchase a ticket. Feel free to drop any input about this feature here.

Agree here, and this revelation was the thought that triggered the idea of the staking account to begin with.  There is no benefit or need to micromanage so instead we should focus on the entry and exit point of staking for users.

> To withdrawal from the staking account, first thing would be to set the balance to maintain absolute to the requested amount to withdrawal. To smooth out this process, I think we should do "pending" withdrawals which become finalizable once those funds are spendable. We could probably use the config to "save" pending withdrawal amounts, then those could be checked against the staking account spendable balance on startup.

The withdrawal process has always been the trickiest part of this idea.

As a user, I think I'd want to see the amount I can immediately withdraw, before initiating a withdraw.  Withdrawls below that are immediate.

Then after initiating a withdraw I would have a "pending withdraw" amount shown in the staking account.

Ideally I'd like the client to estimate how long a withdraw might take based on the accounts' average ticket size and display this to the user before the withdraw and for any pending withdraw amounts.

A user should be able to cancel or adjust pending withdraws.

**Comment by vctt94** [comment]
The ticket auto buyer has been improved and I believe we can close this one as now ppl can chosse accounts to stake.

For further discussion on ticket auto buyer improvements we can have a new issue.
