### ISSUE TITLE
I can't confirm my wallet seed

### ISSUE THREAD

**Issue by bigsicret** [decred/decrediton#910]
I am with Ubuntu 16.04, Decrediton 1.1.1 and I can't create my wallet because Decrediton does not accept the wallet seed. Why ?

Thank you

**Comment by alexlyp** [comment]
Are you selecting each word? The word count on the left should go down each time you select a word.  Use tab instead of space.

**Comment by alexlyp** [comment]
Definitely fixed in recent release.
