### ISSUE TITLE
Add transactional data export

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#912]
Add a menu-bar item that allows users to export their transactional data over a given period of time and put it nicely into a csv for use elsewhere.

As a first pass this should be able to export information about tickets and votes that can be used for tax filing purposes.

Please update this issue with information that you'd like to see.

**Comment by matheusd** [comment]
It may be simple enough for a newcomer to export transaction and ticket information, as listing for those is already implemented.

After the statistics work is done, those may be added.
