### ISSUE TITLE
Show "New App Version Available" notification

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#916]
Consensus has been that no auto-update feature will be implemented to the wallet. But Decrediton could show a "New Version Available" dismissable notification or always present notice (to be decided with the design team).

This involves:
- [x] Decide and implement new version detection (either querying the releases on github or some other api endpoint on decred.org)
- [x] Implement notice UI

**Comment by jrick** [comment]
This should be opt-in, since it is a form of phoning home.

**Comment by matheusd** [comment]
Decrediton currently makes some other requests that could also presumably be used for tracking (stakepool listing, latest block height). Do you think we should add a global opt-in to prevent requests for anything other than the wallet? Or add individual opt-ins for the other requests? Or disregard the others and add the opt-in only for the update notification?

**Comment by jrick** [comment]
I'm not sure how/when decrediton is making that request, but i would prefer that to be controllable by the user as well, perhaps a button to load the stakepool list.

But that's just something we should work towards (and I can open a new issue for that) but even without that done, we shouldn't make the situation worse.

**Comment by alexlyp** [comment]
Yah I believe this discussion is partially related to https://github.com/decred/decrediton/issues/908, where we should have some sort of "anonymous" mode where we don't make any outbound calls and if we do we can use a tor proxy or something.

**Comment by matheusd** [comment]
@alexlyp They are related, though sort of orthogonal: I might not want to make *any* outbound connections, even if I use a traditional/tor proxy for my network. Or I may want to disable them while I'm on a trip or something.

@jrick That's why I was asking those questions: get a feel for what you believe is important then open issues to track this. Current outbound calls made are:

- Stakepool listing (called when initializing a config after install and on the stakepool page if no stakepool configs are available).

- Last Block Number (called when initializing the app and every 5 minutes when syncing the blockchain - used to determine the current block height and present a better estimate for the user when the chain has been fully downloaded).

There's also some talk about adding more stuff to the overview page (https://github.com/decred/decrediton/issues/904). And there's also stuff we could eventually add, like usage statistics, ability to send error reports/logs somewhere, etc.

So I guess the best course of action would be to start adding granular opt-ins for this stuff and have a settings tab/division/whatever holding these, with explanations of what exactly they do and where they access and a "master switch" to disable all outbound (non-wallet) connections.

Code-wise, we should restrict all outbound calls to use a custom middleware (encapsulating axios), make sure no new code uses anything other than this middleware and then that can implement the checks for the opt-ins.
