### ISSUE TITLE
Remove network toggle in settings, add to menu bar

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#919]
Overall, I think it's reasonable to remove the mainnet/testnet toggle in settings since it mostly just confuses the user.  

I think we should move it to the menu bar and it would have various things added to gracefully changeover to the other network.  In its current form it doesn't work.  Ideally, it should warn the user what will happen then trigger a restart of the wallet onto the chosen network.

**Comment by matheusd** [comment]
Yeah, this should be *really* thought through, as changing the network is potentially a *very* lengthy operation (imagine a user switch to testnet for the first time and having to download the entire blockchain).

**Comment by alexlyp** [comment]
Yup exactly.  For now I'm ok with just removing and then adding back when we can fully flush out the feature

**Comment by matheusd** [comment]
For the record, removed in #914. To be re-added on the future.

**Comment by matheusd** [comment]
Closing as the new wallet creation interaction covers this.
