### ISSUE TITLE
Add a new loading indicator

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#920]
In some places imagine a bit less invasive of a loading than the spinning DCR logo could be nice.  

I was thinking that we could just add another state to the button for loading.  Another color than enabled or disabled.  Also add some sort of basic animation to indicate that something is processing:  three blinking dots? small spinning DCR logo in the button?

**Comment by linnutee** [comment]
This one is for replacing the large loader (rotating dcr symbol) during setup (and in any places currently within the app). 

Example + specs: https://xd.adobe.com/view/6efed3df-eadb-4b04-aa12-538c00ba2c59/

[decrediton - setup loader - alpha gif.zip](https://github.com/decred/decrediton/files/1545032/decrediton.-.setup.loader.-.alpha.gif.zip)

**Comment by alexlyp** [comment]
Hrm not sure how I would add this gif in place of the css animated decred loading currently.  @matheusd any thoughts?

**Comment by alexlyp** [comment]
https://github.com/decred/decrediton/pull/973

Here's a quick spin of it.  Still needs proper spacing but looks relatively smooth. Just wondering if using a GIF is good for performance etc.

**Comment by matheusd** [comment]
I'll take a look at the PR in a moment. Performance wise, I don't think it will make any noticeable difference (for the case of a single animation playing).

Having it as an svg animation would be better from the pov of display quality and responsiveness but I believe we can roll with this one for now.

**Comment by linnutee** [comment]
This one might be too tricky as an svg due to the 3d. Is there any other output format that's more optimal, spritesheet?

**Comment by alexlyp** [comment]
https://github.com/decred/decrediton/blob/master/app/style/icons/stakeySprites.png

This is what I had Kyle make for the stakey bounce animation, I suppose that would be best for consistency.

**Comment by alexlyp** [comment]
OK the hexagonal loader is in master
