### ISSUE TITLE
Add hide/show motion to other expandable areas

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#933]
Take the motion that was implemented in #915 and apply it to the following areas:
- ~Account row click to show details~
- StakeInfo area expanding
- Purchase Ticket advanced
- Ticket buyer advanced settings

**Comment by vctt94** [comment]
I can work on this

**Comment by alexlyp** [comment]
Great, take a crack at Account details expanding first.  Feel free to refactor things as you deem necessary.
