### ISSUE TITLE
Transaction lost :(

### ISSUE THREAD

**Issue by leon-yum** [decred/decrediton#934]
https://www.reddit.com/r/decred/comments/7hhv0g/please_help_how_to_cancel_transaction/

I tried to send a 50 DCR transaction to `Dsb29tgK8rzy11eAa4ikeUtp79BvaCxgYV4` and it ended up going to `Dsh7QBFy41FjiyZD1FE5xkYToKFYtPbsYB5`. So far still pending with 0 confirmations... what happens if this transaction is never confirmed? Here is the transaction id: https://mainnet.decred.org/tx/5913b687405109077978dac5868a4da80b7971a3a3782fe7a0f8f266403a642a

Now after restarting Decredition I don't even see my transaction of 50 DCR!!

<img width="797" alt="screen shot 2017-12-04 at 9 45 38 am" src="https://user-images.githubusercontent.com/30158970/33561298-e8027ea2-d8d7-11e7-8ae9-6fcd18bbe445.png">

**Comment by alexlyp** [comment]
Looks like the transaction is not in mempool currently.  I'd first shut down decrediton then on restart click Rescan Blockchain.  That should resolve any issues.  

Can you explain what you mean, it went to a different address?  Whenever you construct a transaction, typically the utxo is created that you requested, and 1 is created for change being returned to you.  I'm assuming that is what you saw.

**Comment by leon-yum** [comment]
Yeah so this is the address I was trying to send too here: `Dsb29tgK8rzy11eAa4ikeUtp79BvaCxgYV4`

And in my wallet this is where the transaction was sent too:

<img width="774" alt="screen shot 2017-12-04 at 9 03 36 am" src="https://user-images.githubusercontent.com/30158970/33562831-e1c8a71a-d8db-11e7-9099-f3c3e23ee001.png">

However I no longer see this transaction in my wallet.

I just restarted Decredition and rescanned the blockchain, but my transaction and that `50 DCR` is still missing. I guess I'll try again in a few hours?

**Comment by alexlyp** [comment]
Ok so the way that display works is this:  that 3.18 is the CHANGE back to your wallet.  (hence new wallet output)

It currently doesn't show non-wallet outptus.  It will in the coming release.  

As to why this transaction isn't seen in mempool, not sure.  I'd give it a little time and then it should show up.

**Comment by leon-yum** [comment]
Thanks! I'll check again end of day!

**Comment by leon-yum** [comment]
Hi guys, still nothing :( I'm missing my 50 DCR. Is there anything else I can provide you guys to possible get back this missing DCR?

**Comment by alexlyp** [comment]
It's not missing, since there is/was no transaction sent to the network.  You can re-create your wallet from seed and all will be fine.

What OS are you using?

**Comment by leon-yum** [comment]
OSX, going to rescan 1 more time the reinstall and remake the wallet

**Comment by leon-yum** [comment]
btw I just tried to sent my entire balance to Exodus and got this error message... I was able to send 10 before. 
```
Error: -1: Rejected transaction 79702bca69f5208c99c3f346a80d82737c21bce104ec6dba2d8a472f34ca8ef3: orphan transaction 79702bca69f5208c99c3f346a80d82737c21bce104ec6dba2d8a472f34ca8ef3 references outputs of unknown or fully-spent transaction 5913b687405109077978dac5868a4da80b7971a3a3782fe7a0f8f266403a642a
```

**Comment by leon-yum** [comment]
Yeah I just tried to send another `50` and `20` and they are both stuck
Transaction:3e61da5ef0dcee00a93e1f7e585c0f52e4d8f77fa2b84368962a7b883bf8ed2d

<img width="784" alt="screen shot 2017-12-04 at 10 59 09 pm" src="https://user-images.githubusercontent.com/30158970/33590725-d655960c-d946-11e7-80fe-eb348da157a8.png">

**Comment by leon-yum** [comment]
OK! I restored my wallet and my missing 50 DCR is back! thanks :D btw that is def a bad bug... hopefully it's fixed in the next version.

**Comment by alexlyp** [comment]
Doubtful it will be "fixed" since this is most likely caused by connectivity issues on your end.  Plus this is not a decrediton issue, rather dcrwallet.
