### ISSUE TITLE
Replace change address on sent transactions to just "change"

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#935]
To avoid confusion with users, we should just show "change" instead of the address that it's coming back to.  

Maybe we can have an "advanced" reveal to show the more specific information, but overall it's best to just hide it since it can be seen on the explorer anyways.

**Comment by matheusd** [comment]
Also, maybe change on transfer to show the account name instead of the address (as that is more useful than the address)

**Comment by alexlyp** [comment]
Good point, I'll add that to my PR.  Thanks
