### ISSUE TITLE
Add rescan button to dashboard and trigger rescan on Create

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#94]

**Comment by jrick** [comment]
Rescanning when creating a wallet is only required if you're creating one with a user-provided seed for recovery.  Otherwise there is no reason to rescan as there is no data expected to be found.

**Comment by alexlyp** [comment]
@jrick good point.  I'm currently doing it for every created wallet.  When I implement create "from existing seed" later today I'll make that it only fires on that path.
