### ISSUE TITLE
Support watching only wallets

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#941]
This is likely to require multiple modifications in Decrediton and maybe a few changes to the dcrwallet end of the grpc channel.

This will useful after the statistics work, as it will allow to more easily monitor a cold wallet.

**Comment by matheusd** [comment]
Requires https://github.com/decred/dcrwallet/issues/1092

**Comment by vctt94** [comment]
Can I get this one?

**Comment by vctt94** [comment]
I am thinking on start adding `getmasterpubkey` command to decrediton, after that add the option to create a watching only wallet on launch.

How do you feel about that approach?

**Comment by matheusd** [comment]
Not sure what you mean by "getmasterpubkey command", as what we wanna do is the opposite: the user provides the masterpubkey, then decrediton will call the new rpc endpoint to create a watch only wallet.

**Comment by vctt94** [comment]
Yeah, but would not be possible to get the masterpubkey from decrediton? Right now it is only possible to get masterpubkey from cli, right?

**Comment by matheusd** [comment]
That's true, but that's a separate issue (add ability to obtain the masterpubkey of a given account).

**Comment by vctt94** [comment]
I see, it makes sense.
