### ISSUE TITLE
Transaction issue: I can send 10 DCR out, but not more

### ISSUE THREAD

**Issue by leon-yum** [decred/decrediton#942]
I've been successful at sending out `10` DCR at a time to another wallet. However if I try larger transaction sizes like `20` or `50` they fail. ie: They get stuck pending and never go through.

Here is the transaction ID for another transaction I tried to send `30 DCR`
9e2bb0abb249c569232faacec73c7817494de540afa8c83a39e9b6ab2b2f8f41

![screen shot 2017-12-05 at 9 30 53 am](https://user-images.githubusercontent.com/30158970/33615422-b812a5d2-d99f-11e7-806e-33b54c9ba315.png)

![screen shot 2017-12-05 at 9 30 48 am](https://user-images.githubusercontent.com/30158970/33615428-bb6ed052-d99f-11e7-8f8f-b8011456f844.png)

**Comment by matheusd** [comment]
It's likely your wallet has a transaction it's trying to double spend from. Could you please try and check the log files if there is any warning or error message?

You can find the log files inside the app, in the Advanced Menu. Open the "mainnet" subdir, then the log file.

**Comment by leon-yum** [comment]
Ok, btw I'm at the corporate office, they block a lot of sites, I can't even ping google in the terminal. Wondering if that has anything to do with it? Here is my log

[dcrwallet.log](https://github.com/decred/decrediton/files/1531959/dcrwallet.log)

**Comment by alexlyp** [comment]
This is caused by local networking issues.  We'll be brainstorming about ways to help give more information to the user in these types of situations.
