### ISSUE TITLE
(1.1.1) Visual Design: Transaction Rows updates

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#944]
<img width="836" alt="screen shot 2017-12-06 at 05 00 55" src="https://user-images.githubusercontent.com/17774057/33642386-7a6cb72e-da42-11e7-834e-d493b169d92d.png">

Transactions row modules in both **"Overview"** and **"History"** subpage seem messed. Specifically spacing, positioning and alignments.

Reference: https://xd.adobe.com/view/2f6756f6-5479-40af-9db3-9202d5029d36/
<img width="1006" alt="screen shot 2017-12-06 at 05 12 35" src="https://user-images.githubusercontent.com/17774057/33642766-1c792fe2-da44-11e7-829a-a4f14065e7c8.png">

**Comment by matheusd** [comment]
Preview.
![tx-row](https://user-images.githubusercontent.com/1752493/33665946-9d8dda52-da7f-11e7-95cd-7a28143fbc46.png)
