### ISSUE TITLE
(1.1.1) Visual Design: Main menu updates

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#945]
<img width="613" alt="screen shot 2017-12-06 at 05 36 36" src="https://user-images.githubusercontent.com/17774057/33643394-7682f484-da47-11e7-8cc0-9cbec46ccf4c.png">

1. Menu items are currently off from standard positioning. I've refined the whole positioning logic a bit, see new specs below. Also included a wallets icon, this is mostly for being a hint as well helps to align the elements.

2. Incorporated rescan into the main menu. The Icon should work as a rescan button. Upon click, displays the progress bar and a cancel icon on the right side. 

Visual design + specs: https://xd.adobe.com/view/3f97bc61-1369-42eb-ab9e-d8725178d9f4/ 

New Icons: [decrediton - menu - icons 061217.zip](https://github.com/decred/decrediton/files/1533784/decrediton.-.menu.-.icons.061217.zip)

**Comment by matheusd** [comment]
Previews.
Home screen without rescan button & updated sidebar visuals:
![image](https://user-images.githubusercontent.com/1752493/33678248-63350ae2-daa2-11e7-86cb-e29e4460d06e.png)

Tooltip on rescan button
![image](https://user-images.githubusercontent.com/1752493/33678269-71058822-daa2-11e7-9b5a-1800c9d95fa3.png)

Rescanning
![image](https://user-images.githubusercontent.com/1752493/33678288-7c162550-daa2-11e7-9f84-73d3fa436a94.png)

Mainnet
![image](https://user-images.githubusercontent.com/1752493/33678314-8c8c664c-daa2-11e7-8918-f3ecff4caa52.png)
