### ISSUE TITLE
(1.1.1) Visual Design: Security page updates

### ISSUE THREAD

**Issue by linnutee** [decred/decrediton#947]
<img width="802" alt="screen shot 2017-12-06 at 06 02 40" src="https://user-images.githubusercontent.com/17774057/33644019-1b420886-da4b-11e7-892b-38f06db4d192.png">

I've considered three possible approaches for this view: having both signing and verifing on a single page; subpages or a single page with tabs/transforming elements.

The single page with tabs made the most sense, as the elements are simple and lightweight. Imo dedicating subpages for these adds too much effort vs transforming the element itself calmer. 

If we go with subpages, the design needs to be changed to account for whitespace etc. Otherwise should refer to the visual design mockup: https://xd.adobe.com/view/982858aa-7fbf-45d6-a55c-75d3abca5a56/

**Comment by alexlyp** [comment]
This was changed in the overall header PR.  Since we are nearing release I'm going to pass on updating to use the tabs as shown in the docs since it would require a pretty major change.  I will update the current styling to best fit the design docs for other pages.
