### ISSUE TITLE
Voting preference does not update

### ISSUE THREAD

**Issue by lustrousgorilla** [decred/decrediton#971]
Upon changing the radio button selector from 'Abstain' to 'Yes' for `sdiffalgorithm`, clicking the 'Update Preference' button, and then selecting the other active proposal `Insupport`, it appears that `sdiffalgorithm` still displays a 'Preference: Abstain' badge. Upon reselecting `sdiffalgorithm`, the radio button selector is back to 'Abstain'.

**Comment by matheusd** [comment]
You were probably using an older version, as AFAIK 1.1.1 only show the `lnfeatures` agenda. But this should be kept to be re-checked whenever we have two agendas to vote on.

**Comment by lustrousgorilla** [comment]
Ok, looks like I'm on 1.0.8. How does one update the client from within (i.e. without downloading the new version and reinstalling)?

**Comment by matheusd** [comment]
No way to do that currently. You need to download a new installer.
