### ISSUE TITLE
Show Wallet Addresses or test if address is from wallet

### ISSUE THREAD

**Issue by matheusd** [decred/decrediton#978]
Got a support message on slack, about a transaction not showing up on Decrediton.

I thought it would be helpful if we could either show all used wallet addresses **or** have a way to test if a given address is from the wallet. 

dcrctl has a `getaddressesbyaccount`, but AFAIK a listing like that wasn't implemented on Decrediton due to concerns of address reuse.

Maybe an alternative to listing addresses would be to have a way of inputing an address, and then the app can check this listing whether this address has been generated by it.

**Comment by alexlyp** [comment]
So we already have this ability with ValidateAddress (isMine in response), it was added to dcrwallet a while back, just never implemented on the decrediton side.  Maybe we can add another tab to the security center?

Ideally, if it is an address owned by the wallet then we can query the transaction set and display all of the transactions from this address.
