### ISSUE TITLE
Retry RPC connection button does not give feedback when hitted

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#985]
If click on retry connection button, when fails to connect with rpc, it triggers the action, but does not give any feedback for the user. It should have a spinner or something to know it is triggered.

**Comment by alexlyp** [comment]
Hrm, how did you reach that button?  Afaik that screen is basically obsolete with the new startup procedures.

**Comment by vctt94** [comment]
I started dcrd as testnet and decredtion as mainnet.

**Comment by matheusd** [comment]
We should probably add a check to make sure the three apps are running on the same network. If there is a misconfiguration in dcrd.conf (for example), it will be started but the wallet won't be able to connect to it.

**Comment by vctt94** [comment]
I agree, this should solve this problem

**Comment by vctt94** [comment]
It is also possible get to this page if user and pass mismatch between the conf files
