### ISSUE TITLE
Problem when changing wallet password with copy-paste

### ISSUE THREAD

**Issue by moondood** [decred/decrediton#986]
I have run into an issue with the password change feature in the Windows version of Decredition. When the new password (and confirmation password) are pasted in from a copy (i.e., ctrl-v after ctrl-c), a problem exists. The password will show up as changed, but it won't be changed to the intended new password. I think it has something to do with masking (or whatever you call it when the field turns your characters into asterisks) but I'm not sure. I have replicated it several times.

**Comment by alexlyp** [comment]
We have an impending release v1.1.2, it would be great if you could test this on the new version to see if the issue remains.  If so, I can escalate this and we can work on getting a patch release out asap.

**Comment by moondood** [comment]
Sure. I can do that.

**Comment by matheusd** [comment]
@moondood Have you tried the latest v1.1.2 or v1.1.3 release yet? Did they solve this issue?

**Comment by vctt94** [comment]
fixed
