### ISSUE TITLE
Unmined and Immature counts in: Tickets > My tickets is not updated properly ( v1.1.2 ) ( It updates after few Decrediton restarts )

### ISSUE THREAD

**Issue by nbenci** [decred/decrediton#993]
Decrediton: v1.1.2
host OS: OSX v10.12.6

After ticket purchase thru ticket buyer, in `Purchase tickets` tab, 1st row of stats.
`Own mempool ticket` count updates with +count of tickets purchased.
After they are mined, `Immature tickets` count updates as well with the correct amount.

In `Tickets > My ticket`s - amount of `UNMINED` tickets and `IMMATURE` tickets is not updated properly after purchase. 
Action flow was: purchase tickets, then check `My tickets` tab.

Tried restarting Decrediton to see if that will help, and counts in `Tickets > My tickets` stayed the same as before purchase / restart. 

Action flow:
Starting stats in `Purchase Tickets` tab is:
`Own mempool tickets: 0`
`Immature Tickets: 1`

Starting stats in `My tickets` tab is:
`IMMATURE 1`
`UNMINED 0`

1.) Purchased 1 manually ticket thru ticket buyer.

Stats in `Purchase Tickets` changed to:
`Own mempool tickets: 1`
`Immature Tickets: 1` 

Stats in `My tickets` stayed:
`IMMATURE 1`
`UNMINED 0`

2.) Waited for ticket to be mined.

3.) Stats in `Purchase Tickets` changed to:
`Own mempool tickets: 0`
`Immature Tickets: 2` 

Starting stats in `My tickets` stayed:
`IMMATURE 1`
`UNMINED 0`

4.) Quit Decrediton. ( waited for proper Decrediton shutdown )
5.) Started Decrediton ( waited for proper wallet initialisation )
6.) Checked `Tickets` and stats remained the same as in step 3.)

7.) Restarted Decrediton 2nd time
8.) Starting stats in `My tickets` changed to:
`IMMATURE 2`
`UNMINED 0`

**Comment by Mandragorian** [comment]
I think i run into something related. My tickets have matured and in the `Purchase Tickets` tab the correct number of live tickets is reported. However in the `My Tickets` tab the tickets are reported as being immature.

Also when I got to the `My Tickets` tab and click the `Immature` button the tickets are there. When I click the `Live` button no tickets are shown.

I have not restarted decrediton since the tickets went from being immature to live.

**Comment by matheusd** [comment]
This is a limitation of how tickets tickets are currently being fetched. The ticket list is only obtained during decrediton startup. We changed the transactions to a paginated view, allowing updates of the transactions to occur without needing to refetch the entire set of transactions (https://github.com/decred/decrediton/issues/815). We should do the same for tickets.

In the meantime, we could re-fetch the entire ticket set after a ticket purchase/vote/revocation is detected, but I'm unsure if on big wallets that will have a noticeable slowdown.
