### ISSUE TITLE
User reported issue that was discovered from electron-store via asar

### ISSUE THREAD

**Issue by alexlyp** [decred/decrediton#995]
https://github.com/sindresorhus/electron-store/issues/30

**Comment by alexlyp** [comment]
Hrm I'm trying to rollback electron-store to 1.2.0, but it's still pulling in the newer version of conf whereas the fix would be to lock conf@1.1.2

**Comment by matheusd** [comment]
Can you actually consistently reproduce this on windows or is it a heisenbug?

**Comment by alexlyp** [comment]
I've been unable to hit it on Win10, but appears once a user hits it they can't fix it.
